/* eslint-disable no-console */
import { h3, h4, h5, p, vote, nl, ul, publishZapis, type Block } from "../zapis-lib";

const V9 = "PRO ( 9 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )";

const transcript: Block[] = [
  h3("1) Zahájení ustavujícího zasedání Zastupitelstva obce Krhanice"),
  p("Zasedání Zastupitelstva obce Krhanice (dále jen „zastupitelstvo“) bylo zahájeno v 18:00 hodin dosavadním starostou obce Mgr. Alešem Papouškem („dále jen „předsedající“)."),
  p("Předsedající přivítal přítomné občany a budoucí zastupitele zastupitelstva obce. Členové zastupitelstva obce dostali osvědčení o zvolení členem zastupitelstva obce podle § 53 zákona č. 491/2001 Sb., o volbách do zastupitelstev obcí a o změně některých zákonů, v platném znění."),
  p("Předsedající konstatoval, že zasedání bylo řádně svoláno tak, aby se v souladu s § 91 odst. 1 zákona č. 128/2000 Sb., o obcích (obecní zřízení), v platném znění, konalo do 15 dnů ode dne uplynutí lhůty pro podání návrhů soudu na neplatnost voleb nebo hlasování. Žádný návrh nebyl podán. Informace podle § 93 odst. 1 zákona o obcích byla na úřední desce Obecního úřadu Krhanice zveřejněna v souladu se zákonem po dobu nejméně 7 dní. Současně byla zveřejněna na „elektronické úřední desce“ obce Krhanice."),
  p("Předsedající z prezenční listiny přítomných členů zastupitelstva konstatoval, že přítomno je 9 členů zastupitelstva (z celkového počtu 9 všech členů zastupitelstva), takže zastupitelstvo je usnášeníschopné (§ 92 odst. 3 zákona o obcích)."),

  h4("Složení slibu členy zastupitelstva"),
  p("Předsedající v souladu s § 69 odst. 2 zákona o obcích vyzval přítomné členy zastupitelstva ke složení slibu. Před složením slibu předsedající upozornil přítomné členy zastupitelstva, že odmítnutí složit slib nebo složení slibu s výhradou má za následek zánik mandátu (§ 55 zákona č. 491/2001 Sb., o volbách do zastupitelstev obcí a o změně některých zákonů, v platném znění). Složení slibu proběhlo tak, že předsedající přečetl slib stanovený v § 69 odst. 2 zákona o obcích:"),
  p("Slibuji věrnost České republice. Slibuji na svou čest a svědomí, že svoji funkci budu vykonávat svědomitě, v zájmu obce a jejích občanů a řídit se Ústavou a zákony České republiky."),
  p("a jmenovitě vyzval přítomné členy zastupitelstva ke složení slibu pronesením slova „slibuji“ a podpisem na připraveném archu. Žádný člen zastupitelstva neodmítl složit slib, ani nesložil slib s výhradou."),

  h3("2) Volba zapisovatele, návrhové komise a ověřovatelů zápisu"),
  p("Předsedající navrhl zapisovatelku, ověřovatele zápisu a členy návrhové komise."),
  p("Zapisovatel: Alena Kratochvílová"),
  p("Ověřovatelé zápisu: Tomáš Kratochvíl, Martin Jiřička"),
  p("Návrhová komise: Jaroslav Mixa, Jana Laboutková"),
  vote(V9),

  h3("3) Schválení programu"),
  p("Předsedající seznámil přítomné s návrhem programu:"),
  ...nl([
    "Zahájení",
    "Volba zapisovatele, návrhové komise a ověřovatelů zápisu",
    "Schválení programu",
    "Volba starosty a místostarosty",
    "Zřízení finančního a kontrolního výboru",
    "Diskuse",
    "Usnesení a závěr",
  ]),
  p("Předsedající se zeptal přítomných, zda má někdo návrh na změnu nebo doplnění programu."),
  p("Ivan Dvořák navrhl doplnit program o následující body:"),
  ...ul([
    "Volební řád zastupitelstva",
    "Návrhy pracovněprávních vztahů mezi obcí a členy zastupitelstva",
    "Návrh na odměny za výkon funkce neuvolněných zastupitelů",
    "Návrh peněžitých plnění poskytovaných fyzickým osobám, které nejsou členy zastupitelstva obce, za výkon funkce členů výborů, komisí a zvláštních orgánů obce",
  ]),
  p("Hlasování o doplnění programu:"),
  vote("PRO ( 2 – Maršíková, Dvořák ) – PROTI ( 7 ) – ZDRŽEL SE ( 0 )"),
  h5("Návrh"),
  p("ZO schvaluje vyvěšený program jednání zastupitelstva obce."),
  vote(V9),

  h3("4) Volba starosty a místostarosty"),
  p("Určení počtu místostarostů. Předsedající navrhl, aby zastupitelstvo volilo pouze jednoho místostarostu."),
  p("Předsedající se zeptal zastupitelů, zda někdo navrhuje jiný počet místostarostů."),
  p("Nikdo nenavrhl jiný počet místostarostů."),
  h5("Návrh"),
  p("ZO schvaluje zvolení jednoho místostarosty."),
  vote(V9),

  h4("a) Určení, které funkce budou členové zastupitelstva vykonávat jako dlouhodobě uvolnění"),
  p("Předsedající navrhl, aby funkce starosty obce byla vykonávaná jako uvolněná ve smyslu § 71 zákona o obcích, tzv. uvolněný člen zastupitelstva obce."),
  h5("Návrh"),
  p("ZO schvaluje v souladu s § 84 odst. 2 písm. k) zákona o obcích, že pro výkon funkce starosty obce bude uvolněný člen zastupitelstva obce."),
  vote(V9),

  h4("b) Určení způsobu volby starosty a místostarosty"),
  p("Předsedající konstatoval, že nestanoví-li zastupitelstvo jinak, probíhá volba starosty a místostarosty veřejně hlasováním. Případnou změnu způsobu hlasování by muselo schválit zastupitelstvo. Předsedající vyzval členy zastupitelstva, zda mají návrhy na změnu způsobu hlasování."),
  p("Ivan Dvořák navrhl tajnou volbu starosty a místostarosty."),
  h5("Návrh"),
  p("ZO schvaluje volbu starosty a místostarosty tajným hlasováním."),
  vote("PRO ( 2 – Maršíková, Dvořák ) – PROTI ( 7 ) – ZDRŽEL SE ( 0 )"),
  h5("Návrh"),
  p("ZO schvaluje volbu starosty a místostarosty veřejným hlasováním."),
  vote(V9),

  h4("c) Volba starosty"),
  p("Předsedající vyzval zástupce sdružení nezávislých kandidátů Občané Krhanic a Prosečnice k předložení návrhu zastupitele na funkci starosty obce. Tomáš Kratochvíl navrhl do funkce starosty obce Aleše Papouška. Předsedající vyzval zástupce sdružení nezávislých kandidátů PROUD 22 – SDRUŽENÍ NEZÁVISLÝCH KANDIDÁTŮ k předložení návrhu zastupitele na funkci starosty obce. Ivan Dvořák navrhl do funkce starosty obce Bc. Ivana Dvořáka."),
  p("Vystoupení I. Dvořáka. Vysvětlil přítomným, proč kandiduje na starostu."),
  p("Hlasování o prvním návrhu:"),
  h5("Návrh"),
  p("ZO schvaluje do funkce starosty obce Mgr. Aleše Papouška."),
  vote("PRO ( 6 ) – PROTI ( 2 – Maršíková, Dvořák ) – ZDRŽEL SE ( 1 - Papoušek )"),
  p("Starosta byl zvolen. Další hlasování je bezpředmětné."),
  p("Po zvolení starosty pokračoval nově zvolený starosta ve vedení zasedání zastupitelstva. Promluvil k přítomným, jak by chtěl pracovat v novém volebním období."),

  h4("c) Volba místostarosty"),
  p("Starosta vyzval zástupce sdružení nezávislých kandidátů Občané Krhanic a Prosečnice k předložení návrhu zastupitele na funkci místostarosty obce. Tomáš Kratochvíl navrhl do funkce místostarosty obce Jaroslava Mixu. Starosta vyzval zástupce sdružení nezávislých kandidátů PROUD 22 – SDRUŽENÍ NEZÁVISLÝCH KANDIDÁTŮ k předložení návrhu zastupitele na funkci místostarosty obce. Návrh nebyl vznesen."),
  h5("Návrh"),
  p("ZO schvaluje do funkce místostarosty obce Jaroslava Mixu."),
  vote("PRO ( 8 ) – PROTI ( 0 ) – ZDRŽEL SE ( 1 - Mixa )"),

  h3("5) Zřízení finančního a kontrolního výboru"),
  p("Starosta úvodem tohoto bodu informoval o povinnosti zřídit finanční a kontrolní výbor, neboť funkční období výborů předchozího zastupitelstva zaniklo spolu se zánikem původního zastupitelstva. Zastupitelstvo určuje počet členů výboru, který musí být lichý, přičemž finanční a kontrolní výbor musí mít nejméně tři členy. Členy výboru mohou být členové zastupitelstva i jiné osoby, pouze předsedou výboru může být jen člen zastupitelstva. Členy kontrolního nebo finančního výboru nemůže být starosta, místostarosta. Starosta navrhl, aby zastupitelstvo zřídilo finanční výbor a kontrolní výbor, přičemž každý z nich bude mít pět členů."),
  h5("Návrh"),
  p("ZO schvaluje zřízení finančního výboru a kontrolního výboru. Každý výbor bude pětičlenný."),
  vote(V9),

  h4("a) volba předsedy finančního výboru"),
  p("Starosta vyzval zástupce sdružení nezávislých kandidátů Občané Krhanic a Prosečnice k předložení návrhu zastupitele na funkci předsedy finančního výboru. Tomáš Kratochvíl navrhl do funkce předsedy finančního výboru Bc. Petra Duba. Starosta vyzval zástupce sdružení nezávislých kandidátů PROUD 22 – SDRUŽENÍ NEZÁVISLÝCH KANDIDÁTŮ k předložení návrhu zastupitele na funkci předsedy finančního výboru. I. Dvořák navrhl do funkce předsedy finančního výboru Bc. Ivana Dvořáka."),
  h5("Návrh"),
  p("ZO schvaluje do funkce předsedy finančního výboru Bc. Petra Duba."),
  vote("PRO ( 6 ) – PROTI ( 2 – Maršíková, Dvořák ) – ZDRŽEL SE ( 1 - Dub )"),
  p("Předseda finančního výboru byl zvolen. Další hlasování je bezpředmětné."),

  h4("b) volba předsedy kontrolního výboru"),
  p("Starosta vyzval zástupce sdružení nezávislých kandidátů Občané Krhanic a Prosečnice k předložení návrhu zastupitele na funkci předsedy kontrolního výboru. Tomáš Kratochvíl navrhl do funkce předsedy kontrolního výboru Ing. Martina Jiřičku. Starosta vyzval zástupce sdružení nezávislých kandidátů PROUD 22 – SDRUŽENÍ NEZÁVISLÝCH KANDIDÁTŮ k předložení návrhu zastupitele na funkci předsedy kontrolního výboru. Lucie Maršíková navrhla do funkce předsedy kontrolního výboru Mgr. Lucii Maršíkovou."),
  h5("Návrh"),
  p("ZO schvaluje do funkce předsedy kontrolního výboru Ing. Martina Jiřičku."),
  vote("PRO ( 6 ) – PROTI ( 2 – Maršíková, Dvořák ) – ZDRŽEL SE ( 1 - Jiřička )"),
  p("Předseda kontrolního výboru byl zvolen. Další hlasování je bezpředmětné."),

  h4("c) volba členů finančního výboru"),
  p("Starosta vyzval předsedu finančního výboru Petra Duba k podávání návrhů na členy finančního výboru. Petr Dub podal následující návrhy:"),
  ...nl([
    "člen : Jana Laboutková",
    "člen : Ing. Alena Kratochvílová",
    "člen : Ing. Bohuslav Kadeřábek",
    "člen : Dana Kohoutová",
  ]),
  p("Starosta vyzval zástupce sdružení nezávislých kandidátů PROUD 22 – SDRUŽENÍ NEZÁVISLÝCH KANDIDÁTŮ k předložení návrhu na funkci člen finančního výboru. I. Dvořák navrhl na člena finančního výboru Bc. Ivana Dvořáka."),
  p("Hlasování dle návrhů:"),
  h5("Návrh"),
  p("ZO schvaluje za člena finančního výboru Janu Laboutkovou."),
  vote("PRO ( 6 ) – PROTI ( 0 ) – ZDRŽEL SE ( 3 – Laboutková, Maršíková, Dvořák )"),
  h5("Návrh"),
  p("ZO schvaluje za člena finančního výboru Ing. Alenu Kratochvílovou."),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 2 – Maršíková, Dvořák )"),
  h5("Návrh"),
  p("ZO schvaluje za člena finančního výboru Ing. Bohuslava Kadeřábka."),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 2 – Maršíková, Dvořák )"),
  h5("Návrh"),
  p("ZO schvaluje za člena finančního výboru Danu Kohoutovou."),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 2 – Maršíková, Dvořák )"),
  p("Finanční výbor je z hlediska počtu členů kompletní. Další hlasování je bezpředmětné."),

  h4("d) volba členů kontrolního výboru"),
  p("Starosta vyzval předsedu kontrolního výboru Martina Jiřičku k podávání návrhů na členy kontrolního výboru. Martin Jiřička podal následující návrhy:"),
  ...nl([
    "člen : Ing. Aleš Kozel",
    "člen : Ing. Markéta Fischerová",
    "člen : Ing. Radek Ščotka",
    "člen : Mgr. Lucie Maršíková",
  ]),
  p("Starosta vyzval zástupce sdružení nezávislých kandidátů PROUD 22 – SDRUŽENÍ NEZÁVISLÝCH KANDIDÁTŮ k předložení návrhu na funkci člen kontrolního výboru. Žádný návrh nebyl předložen."),
  p("Hlasování dle návrhů:"),
  h5("Návrh"),
  p("ZO schvaluje za člena kontrolního výboru Ing. Aleše Kozla."),
  vote("PRO ( 8 ) – PROTI ( 0 ) – ZDRŽEL SE ( 1 - Kozel )"),
  h5("Návrh"),
  p("ZO schvaluje za člena kontrolního výboru Ing. Markétu Fischerovou."),
  vote("PRO ( 8 ) – PROTI ( 1 - Maršíková ) – ZDRŽEL SE ( 0 )"),
  h5("Návrh"),
  p("ZO schvaluje za člena kontrolního výboru Ing. Radka Ščotku."),
  vote(V9),
  h5("Návrh"),
  p("ZO schvaluje za člena kontrolního výboru Mgr. Lucii Maršíkovou."),
  vote(V9),

  h3("6) Diskuse"),
  ...ul([
    "I. Dvořák: Dotaz na pracovně právní vztahy zastupitelů s obcí. Starosta: Budeme řešit na dalším zastupitelstvu. Odměny zastupitelů jsou dány tabulkově.",
    "I. Dvořák: Bude návrh na nějaké peněžité odměny pro členy jednotlivých komisí, kteří nejsou členy zastupitelstva? Starosta: Všichni členové komisí chodí dobrovolně, žádné odměny nedostávají.",
    "V. Ditrich: Vyjádřil nespokojenost s tím, že čtvrtina občanů zvolila 2 zastupitele, kteří se nedostali do vedení obce a pouze jeden je členem kontrolního výboru.",
    "Proběhla diskuse dalších přítomných (S. Anfilov, K. Anfilov, Bydžovský, Maršík, Svěrák, Strnad), především na téma proč nebyl do finančního výboru zvolen pan Dvořák, … Diskuse nepřinesla žádné nové závěry.",
  ]),

  h3("7) Usnesení a závěr"),
  p("Starosta se zeptal přítomných na doplnění nebo změnu usnesení z jednání. Nebylo vzneseno žádné doplnění či změna. Proběhlo hlasování."),
  vote(V9),
  p("Závěr: Zastupitelstvo obce bylo ukončeno v 18:50 hod."),

  p("Datum pořízení zápisu: 27.10.2022"),
  p("Ověřovatelé zápisu a starosta obce, podepsáno v listinné podobě."),
  h4("Přílohy"),
  ...nl([
    "Svolání zastupitelstva obce",
    "Prezenční listina zastupitelů",
    "Prezenční listina občanů",
    "Slib člena zastupitelstva",
  ]),
];

async function run() {
  const r = await publishZapis({
    cislo: "5",
    rok: "2022",
    isoDate: "2022-10-19",
    dateLabel: "19. 10. 2022",
    fullDateDot: "19.10.2022",
    pdfPath: "scripts/zapisy-pdf/zapis-2022-5.pdf",
    transcript,
  });
  console.log("OK", r.docId, "blocks", r.blocks);
}
run().catch((e) => { console.error(e); process.exit(1); });
