/* eslint-disable no-console */
// One-off: faithful visual transcript of Zápis č. 4/2021 (13.9.2021), read
// page-by-page from the official PDF. Structure per scripts/build-zapis-2026-1.ts.
import { h3, h4, h5, p, vote, nl, ul, publishZapis, type Block } from "../zapis-lib";

const V6 = "PRO ( 6 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )";

const transcript: Block[] = [
  h4("Přítomni"),
  p("Aleš Papoušek, Jaroslav Mixa, Tomáš Kratochvíl, Petr Dub, Martin Jiřička, Edita Jarošová"),
  h4("Omluveni"),
  p("Václav Zíta, Jana Laboutková, Bohuslav Kadeřábek"),

  h3("1) Zahájení, přivítání přítomných, konstatování přítomnosti"),
  p("Starosta konstatoval, že zasedání bylo svoláno dne 3.9.2021 bylo vyvěšeno na úřední desce obecního úřadu, tj. tedy nejméně 7 dní před zasedáním. Bylo tedy svoláno řádně a včas v souladu se zákonem o obcích v platném znění. Starosta konstatoval, že podle prezenční listiny je přítomno 6 členů zastupitelstva, tedy nadpoloviční většina členů zastupitelstva. K předchozímu zápisu nebyly vzneseny námitky."),
  h5("Určení zapisovatele"),
  p("Zápisem zasedání zastupitelstva obce byla pověřena Ing. Alena Kratochvílová."),
  p("Starosta přečetl program."),
  ...nl([
    "Zahájení",
    "Volba návrhové komise a ověřovatelů zápisu",
    "Zpráva kontrolního výboru",
    "Protokol o kontrole výkonu samostatné působnosti svěřené orgánům obce Krhanice (Ministerstvo vnitra – kontrolní orgán)",
    "Rozpočtové opatření",
    "Koupě, prodej, pronájem",
    "Různé",
    "Diskuse",
    "Usnesení a závěr",
  ]),
  p("Proběhlo hlasování o programu."),
  h5("Návrh"),
  p("ZO schvaluje program zasedání zastupitelstva obce."),
  vote(V6),

  h3("2) Volba návrhové komise a ověřovatelů zápisu"),
  p("Starosta přednesl návrh návrhové komise a ověřovatelů zápisu."),
  h5("Návrh"),
  p("ZO schvaluje návrhovou komisi ve složení Jaroslav Mixa, Petr Dub."),
  h5("Návrh"),
  p("ZO schvaluje ověřovatele zápisu ve složení Martin Jiřička, Edita Jarošová."),
  vote(V6),

  h3("3) Zpráva kontrolního výboru"),
  p("Předseda kontrolního výboru Martin Jiřička seznámil se zprávou kontrolního výboru ze dne 30.8.2021."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí Zprávu kontrolního výboru ze dne 30.8.2021."),

  h3("4) Protokol o kontrole výkonu samostatné působnosti svěřené orgánům obce Krhanice (Ministerstvo vnitra – kontrolní orgán)"),
  p("Informace starosty: Dne 30.7.2021 proběhla kontrola výkonu samostatné působnosti za období 1.6.2020 – 30.7.2021. Protokol ze dne 10.8.2021 byl na úřední desce obce Krhanice vyvěšen dne 16.8.2021. Kontrola se týkala zejména dodržování zákona o obcích a zákona o svobodném přístupu k informacím, a to v těchto oblastech: kontrola fungování orgánů obce, nakládání s nemovitým majetkem obce, vytváření podmínek pro naplňování práv občanů obce, ostatní povinnosti na úseku samostatné působnosti. Starosta nyní přečetl protokol. Dle doporučení Ministerstva vnitra bude v zápisech uváděn datum pořízení zápisu zastupitelstva. Při kontrole nebylo shledáno porušení zákona."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje a bere na vědomí Protokol o kontrole výkonu samostatné působnosti svěřené orgánům obce Krhanice (Ministerstvo vnitra – kontrolní orgán)."),
  vote(V6),

  h3("5) Rozpočtové opatření"),
  h4("Žádost Aktivní Krhanice"),
  p("Informace starosty: Byla předložena žádost spolku Aktivní Krhanice o finanční příspěvek na akci „Zažít Krhanice jinak“ na částku 10.000, - Kč. Příspěvek by byl použit na zajištění hudební složky. Bude sepsána smlouva. Zábor veřejných prostorů na akci byl poskytnut ze strany Obecního úřadu bezúplatně."),
  h5("Návrh"),
  p("ZO schvaluje poskytnutí finančního příspěvku ve výši 10.000,- Kč pro Aktivní Krhanice, IČ 09017429, Krhanice 35, 257 42 Krhanice na akci „Zažít Krhanice jinak“. Se spolkem bude uzavřena veřejnoprávní smlouva."),
  h5("Rozprava"),
  p("T.Kratochvíl: Přednesl protinávrh k usnesení. Jen v případě výročí obec přispívala na hudbu celou částkou."),
  h5("Návrh"),
  p("ZO schvaluje poskytnutí finančního příspěvku ve výši 5.000,- Kč pro Aktivní Krhanice, IČ 09017429, Krhanice 35, 257 42 Krhanice na akci „Zažít Krhanice jinak“. Se spolkem bude uzavřena veřejnoprávní smlouva."),
  vote("PRO ( 5 ) – PROTI ( 1 - Papoušek ) – ZDRŽEL SE ( 0 )"),

  h4("Mateřská škola Krhanice"),
  p("Martin Jiřička přečetl dopis ředitelky mateřské školy s žádostí o navýšení provozního příspěvku o 30 tisíc Kč na nákup notebooku s operačním systémem Windows 10 Pro a kancelářským software Office 2019."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje navýšení provozního příspěvku Mateřské škole Krhanice o 30.000,- Kč na nákup notebooku s operačním systémem Windows 10 Pro a Office 2019."),
  vote(V6),

  h4("Základní škola Krhanice"),
  p("Edita Jarošová přečetla dva dopisy ředitelky Základní školy Krhanice: První dopis s žádostí o poskytnutí návratné finanční výpomoci ve výši 595.979,- Kč na projekt Nákup tabulí s interaktivním systémem do kmenových učeben pro dotaci z Programu rozvoje venkova. Tato částka bude po obdržení dotace školou vrácena obci."),
  p("Druhý dopis s žádostí o navýšení provozního příspěvku na nákup sekačky a křovinořezu o 32.000,- Kč."),
  p("Starosta: Se školou bude uzavřena smlouva o návratné finanční výpomoci – investiční."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje poskytnutí návratné finanční výpomoci ve výši 595.979,- Kč Základní škole Krhanice, okres Benešov pro projekt „Nákup tabulí s interaktivním systémem do kmenových učeben“ v rámci dotace z Programu rozvoje venkova s termínem vrácení do 31.8.2022. Se Základní školou Krhanice, okres Benešov bude uzavřena smlouva o návratné finanční výpomoci."),
  vote(V6),
  h5("Návrh"),
  p("ZO schvaluje navýšení provozního příspěvku Základní škole Krhanice, okres Benešov o částku 32.000,- Kč na nákup sekačky a křovinořezu."),
  vote(V6),

  p("Petr Dub seznámil s rozpočtovým opatřením č. 5/2021. Výdaje budou o 5.000,- Kč nižší."),
  h5("Návrh"),
  p("ZO schvaluje rozpočtové opatření č. 5/2021."),
  vote(V6),
  h5("Rozprava"),
  p("L.Maršíková: Požádala o přehodnocení rozhodnutí o snížení částky na 50%. Kapela bude stát 12.000,- Kč a je to akce, na které se neplatí vstupné. Seznámila přítomné, jakým způsobem bude akce probíhat."),
  p("E.Jarošová: Pokud by v žádosti byl požadavek příspěvku na děti, neměla bych s částkou 10.000,- Kč problém. Proběhla krátká diskuse."),
  p("Starosta přerušil schůzi pro dohadovací řízení."),
  p("Přerušení schůze: 18:21 hod."),
  p("Pokračování schůze: 18:28 hod."),

  h5("Revokace usnesení"),
  h5("Návrh"),
  p("ZO schvaluje zrušení usnesení o poskytnutí finančního příspěvku ve výši 5.000,- Kč pro Aktivní Krhanice, IČ 09017429, Krhanice 35, 257 42 Krhanice na akci „Zažít Krhanice jinak“. Se spolkem bude uzavřena veřejnoprávní smlouva."),
  vote(V6),
  h5("Návrh"),
  p("ZO schvaluje zrušení usnesení rozpočtové opatření č. 5/2021."),
  vote(V6),

  h5("Návrhy nových usnesení"),
  h5("Návrh"),
  p("ZO schvaluje poskytnutí finančního příspěvku ve výši 10.000,- Kč pro Aktivní Krhanice, IČ 09017429, Krhanice 35, 257 42 Krhanice na akci „Zažít Krhanice jinak“. Se spolkem bude uzavřena veřejnoprávní smlouva."),
  vote(V6),
  p("Rozpočtové opatření bude vyrovnané."),
  h5("Návrh"),
  p("ZO schvaluje rozpočtové opatření č. 5/2021."),
  vote(V6),

  h3("6) Koupě, prodej, pronájem"),
  ...ul(["pronajmout část pozemku parc. č. 132/1, 1988 a 128/10 k.ú. Krhanice o výměře 165 m² k dočasnému zřízení zahrádky a umístění movitých věcí za cenu 5 Kč/m²/rok od 1.11.2021 na dobu 4 let."]),
  p("Informace starosty: Jedná se o žádost Davida Kalouska, kterému nájemní smlouva na tyto části pozemků končí 31.10.2021. Jde o pokračování nájmu."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronajmout část pozemku parc. č. 132/1, 1988 a 128/10 k.ú. Krhanice o výměře 165 m² k dočasnému zřízení zahrádky a umístění movitých věcí za cenu 5 Kč/m²/rok od 1.11.2021 na dobu 4 let Davidu Kalouskovi, Krhanice č. ev. 112, 257 42 Krhanice."),
  vote(V6),
  ...ul(["pronajmout část pozemku parc. č. 132/1, 1988 a 128/10 k.ú. Krhanice o výměře 209 m² k dočasnému zřízení zahrádky a umístění movitých věcí za cenu 5 Kč/m²/rok od 1.11.2021 na dobu 4 let."]),
  p("Informace starosty: Jedná se o žádost Moniky Povolné, které nájemní smlouva na tyto části pozemků končí 31.10.2021. Jde o pokračování nájmu."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronajmout část pozemku parc. č. 132/1, 1988 a 128/10 k.ú. Krhanice o výměře 209 m² k dočasnému zřízení zahrádky a umístění movitých věcí za cenu 5 Kč/m²/rok od 1.11.2021 na dobu 4 let Monice Povolné, Krhanice č. ev. 162, 257 42 Krhanice."),
  vote(V6),
  ...ul(["uzavřít Smlouvu o zřízení věcného břemene - služebnosti č. IP-12-6014232/1, Krhanice-kNN-p.č. 509/11 na pozemcích parc. č. 132/10 a 132/11 k.ú. Krhanice s ČEZ Distribuce, a.s., IČ 24729035, DIČ CZ24729035, se sídlem Děčín IV-Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 6.000,- Kč."]),
  p("Informace starosty: Tato smlouva byla již jako budoucí smlouva odsouhlasena na 3 pozemky. Mezitím byl jeden pozemek prodán majiteli nemovitosti, pro kterého se dělala elektrická přípojka. Proto nyní projednáváme znovu a jen 2 pozemky za částku 6.000,- Kč jako platbu za věcné břemeno."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o zřízení věcného břemene - služebnosti č. IP-12-6014232/1, Krhanice-kNN-p.č. 509/11 na pozemcích parc. č. 132/10 a 132/11 k.ú. Krhanice s ČEZ Distribuce, a.s., IČ 24729035, DIČ CZ24729035, se sídlem Děčín IV-Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 6.000,- Kč."),
  vote(V6),
  ...ul(["pronájem části pozemku st. p. 675 k.ú. Krhanice o výměře 18 m² k umístění plechové garáže k podnikání za cenu 20 Kč/m²/rok od 14.9.2021 na dobu 10 let Jiřímu Mlejnkovi, Krhanice 215, 257 42 Krhanice. Záměr byl schválen ZO č. 1/2021 dne 17.3.2021, nyní dochází k úpravě celkové výměry z 17,5 m² na 18 m²."]),
  p("Informace starosty: Záměr byl již schválen na ZO dne 17.3.2021. Při následné demolici havarijních skladů a úpravě st.p. 675 k.ú. Krhanice došlo ke změně výměry na 18 m² podle velikosti garáže pronajímatele."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronájem části pozemku st. p. 675 k.ú. Krhanice o výměře 18 m² k umístění plechové garáže k podnikání za cenu 20 Kč/m²/rok od 14.9.2021 na dobu 10 let Jiřímu Mlejnkovi, Krhanice 215, 257 42 Krhanice. Záměr byl schválen ZO č. 1/2021 dne 17.3.2021, nyní dochází k úpravě celkové výměry z 17,5 m² na 18 m²."),
  vote(V6),

  h3("7) Různé"),
  h4("Smlouva č. 1190901143 o poskytnutí podpory ze Státního fondu životního prostředí České republiky - „Nové stromy na Sokolce v Krhanicích“"),
  p("Informace starosty: Ze strany SFŽP nám byla zaslána smlouva o poskytnutí podpory (dotace). Tento projekt na výsadbu nových stromů na Sokolce v Krhanicích byl ze strany SFŽP akceptován, poté proběhla realizace, pak vyúčtování na SFŽP a nyní se podepisuje smlouva a bude poskytnuta dotace."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy č. 1190901143 o poskytnutí podpory ze Státního fondu životního prostředí České republiky na projekt „Nové stromy na Sokolce v Krhanicích“ a souhlasí s přijetím podpory a s podmínkami této smlouvy na uvedený projekt."),
  vote(V6),
  h5("Návrh"),
  p("ZO pověřuje starostu uzavřením a podpisem Smlouvy č. 1190901143 o poskytnutí podpory ze Státního fondu životního prostředí České republiky na projekt „Nové stromy na Sokolce v Krhanicích“."),
  vote(V6),

  h4("MEMORANDUM O VZÁJEMNÉ SPOLUPRÁCI – ke společnému provozu vodohospodářské infrastruktury"),
  p("Informace starosty: Dne 14.6.2021 Zastupitelstvo obce č. 2/2021 schválilo Memorandum o vzájemné spolupráci – ke společnému provozu vodohospodářské infrastruktury. Z důvodu připojení se dvou obcí k memorandu a z důvodu zapracování některých připomínek od obcí do memoranda, je nutné znovu projednat přepracované memorandum s upraveným počtem obcí. Připojením se k memorandu souhlasíme s budoucím vstupem do Vodohospodářské společnosti Benešov s 50% podílem."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí návrh projektu budoucího zajištění společného provozu vodohospodářské infrastruktury v regionech Benešovska a Vlašimska a okresech Praha-západ a Praha-východ za účasti zastoupení skupiny SUEZ Groupe v České republice a schvaluje uzavření předloženého návrhu memoranda o vzájemné spolupráci jako podkladu pro zahájení realizace projektu."),
  vote(V6),
  h5("Návrh"),
  p("ZO pověřuje starostu obce Mgr. Aleše Papouška k podpisu předloženého návrhu memoranda o vzájemné spolupráci a k provedení všech dalších právních jednání v rámci plnění práv a povinností vyplývajících z memoranda o vzájemné spolupráci."),
  vote(V6),

  h4("Plán inventur na rok 2021"),
  p("Informace starosty: Standardním způsobem provedeme inventarizaci. Schválíme Plán inventur na rok 2021 včetně přílohy č. 1 – Seznamu inventurních soupisů s konkrétním postupem pro provedení inventarizace majetku a závazků obce. Jsou zde uvedeny konkrétní osoby, termíny a úkoly. Pro rok 2021 se zřizuje jedna inventarizační komise pro střediska – Obecní úřad Krhanice, Knihovna, Hasičská zbrojnice ve složení: Aleš Papoušek, Jana Cachová, Lenka Termerová, Jaroslav Mixa a Bohuslav Kadeřábek."),
  p("Stav majetku a závazků bude zjišťován k datu 31.12.2021. Inventurní soupisy bude inventarizační komise vyhotovovat průběžně v měsíci lednu 2022. Inventarizační komise vyhotoví Inventarizační zprávu nejpozději do 8.2.2022."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Plán inventur na rok 2021 včetně přílohy č. 1 – Seznamu inventurních soupisů na rok 2021."),
  vote(V6),

  h4("Komise pro sestavení rozpočtu pro rok 2022"),
  p("Informace starosty: V souladu se směrnicí č. 2/2017 Metodika sestavení rozpočtu obce Krhanice opět odsouhlasíme standardní složení Komise pro sestavení rozpočtu pro rok 2022: Aleš Papoušek, Jana Laboutková, Bohuslav Kadeřábek, Alena Kratochvílová a Jana Cachová. Jednotliví žadatelé – základní škola, mateřská škola, Komise pro obnovu a rozvoj obce, Kulturní, školská a sociální komise, SDH Krhanice, JSDHO Krhanice, TJ Sokol Krhanice, některé spolky a zájmové organizace budou vyzváni k předložení požadavků na rozpočet na rok 2021. Sezení komise bude naplánováno na měsíc listopad 2021."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Komisi pro sestavení rozpočtu pro rok 2022 ve složení: Mgr. Aleš Papoušek, Jana Laboutková, Ing. Bohuslav Kadeřábek, Ing. Alena Kratochvílová, Ing. Jana Cachová."),
  vote(V6),

  h4("Svoz nebezpečného odpadu 20. září 2021"),
  p("Informace místostarosty: Svoz bude v pondělí 20. září 2021. Den předem od 18:00 do 20:00 hod. bude již možné nebezpečný odpad předávat. Ale žádný eternit, pneumatiky, rozebrané spotřebiče a také žádné přístroje od firmy Samsung, která již nemá smlouvu s EKO-KOMem."),

  h4("Dotace na Radary"),
  p("Informace starosty: Dne 11.8.2021 Výbor Státního fondu dopravní infrastruktury naši žádost o dotaci zamítl. Žádost podáme znovu při opětovném vyhlášení dotačního titulu. V úterý 14.9.2021 proběhne instalace radaru s ukazatelem SPZ na silnici směrem k silničnímu viaduktu."),

  h4("ZŠ – navýšení stravného pro cizí strávníky"),
  p("Starosta: Ředitelka školy požádala o navýšení ceny oběda pro cizí strávníky. Ceny potravin výrazně zdražují."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje navýšení ceny oběda pro cizí strávníky na částku 78,- Kč od 1.10.2021."),
  vote(V6),

  h3("8) Diskuse"),
  ...ul([
    "H.Strnadová: Dotaz, zda bude pokračovat oprava cesty na Boroví. Starosta: Ne. Nejprve musíme cestu geodeticky zaměřit, abychom nezasahovali do cizích pozemků.",
    "D.Nováková: Smějí jezdit k Boroví motorová vozidla? Starosta: Ne, pokud nemají průkazku obecního úřadu.",
    "R.Novotný: Nešla by při opravě cesty vybudovat do Týnce cyklotrasa? Starosta: Nejprve musí dojít ke geodetickému zaměření. Cesta pravděpodobně vede mimo stávající cestu.",
    "L.Maršíková: Dotaz na novou budovu u víceúčelového hřiště. Komu bude budova sloužit? Starosta: K jednorázovým akcím spolků a organizací. Bude sloužit i škole jako venkovní třída. Tento týden probíhá testování provozu WC. Musíme rozhodnout o podmínkách pronájmu včetně cen. T.Kratochvíl: Domluvili jsme se, že objekt nebudeme pronajímat na soukromé akce.",
    "L.Maršíková: Dotaz na sklad v Hodkově: Co tam bude obec skladovat? Starosta: Štěpkovač, popelnice, věci týkající se komunálu.",
    "L.Maršíková: Nevyklidíte místnosti na úřadě? Daly by se použít pro zájmové akce. Starosta: S tím se nepočítá. Tyto místnosti slouží zároveň jako archiv.",
    "L.Maršíková: Dotaz na sportovní akce a cvičení dospělých, které probíhaly v tělocvičném sálku, zda by nešly přesunout do budovy víceúčelového hřiště? Starosta: Probíhají práce na rekonstrukci školy, které brání ve využívání tělocvičného sálku. Potom se bude znovu používat.",
    "H.Strnadová: Dotaz k zázemí víceúčelového hřiště, zda někdo řeší chování mládeže. Starosta: Chování mládeže s místostarostou průběžně řešíme. Např. včera jsem vykázal jednotlivce, který ničil popelnici a roh budovy. Pokud mi někdo zavolá, podíváme se na záznam z kamery a potom to řešíme s konkrétním viníkem. Proběhla diskuse.",
    "D.Nováková: Od kdy svítí na ceduli nápis OTEVŘENO a kdy ZAVŘENO? Starosta: Nyní od 8 do 21 je OTEVŘENO.",
    "H.Strnadová: Dotaz zda se počítá s nějakou zelení na cestě k Boroví. Starosta: Počítáme se stromovou alejí. Musíme nejdříve geodeticky vytýčit pozemky.",
  ]),

  h3("9) Usnesení a závěr"),
  p("a. Návrhová komise přečetla usnesení zastupitelstva obce."),
  vote(V6),
  p("b. Závěr: Zastupitelstvo obce bylo ukončeno v 19:00 hod."),

  p("Datum pořízení zápisu: 20.9.2021"),
  h4("Přílohy"),
  ...nl(["Svolání zastupitelstva obce", "Prezenční listina zastupitelů", "Prezenční listina občanů"]),
];

async function run() {
  const r = await publishZapis({
    cislo: "4",
    rok: "2021",
    isoDate: "2021-09-13",
    dateLabel: "13. 9. 2021",
    fullDateDot: "13.9.2021",
    pdfPath: "scripts/zapisy-pdf/zapis-2021-4.pdf",
    transcript,
  });
  console.log("OK", r.docId, "blocks", r.blocks);
}
run().catch((e) => { console.error(e); process.exit(1); });
