/* eslint-disable no-console */
import { h3, h4, h5, p, vote, nl, ul, publishZapis, type Block } from "../zapis-lib";

const V8 = "PRO ( 8 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )";

const transcript: Block[] = [
  h4("Přítomni"),
  p("Aleš Papoušek, Jaroslav Mixa, Tomáš Kratochvíl, Aleš Kozel, Jana Laboutková, Martin Jiřička, Petr Dub, Šárka Dušová"),
  h4("Omluveni"),
  p("Lucie Maršíková"),

  h3("1) Zahájení, přivítání přítomných, konstatování přítomnosti"),
  p("Starosta konstatoval, že zasedání bylo svoláno dne 3.3.2025, bylo vyvěšeno na úřední desce obecního úřadu, tj. tedy nejméně 7 dní před zasedáním. Bylo tedy svoláno řádně a včas v souladu se zákonem o obcích v platném znění. Starosta konstatoval, že podle prezenční listiny je přítomno 8 členů zastupitelstva, tedy nadpoloviční většina členů zastupitelstva. K předchozímu zápisu nebyly vzneseny námitky."),
  h5("Určení zapisovatele"),
  p("Zápisem zasedání zastupitelstva obce byla pověřena Ing. Alena Kratochvílová."),

  h3("2) Volba návrhové komise a ověřovatelů zápisu"),
  p("Starosta přednesl návrh návrhové komise a ověřovatelů zápisu."),
  h5("Návrh"),
  p("ZO schvaluje návrhovou komisi ve složení: Jaroslav Mixa, Jana Laboutková."),
  h5("Návrh"),
  p("ZO schvaluje ověřovatele zápisu ve složení Šárka Dušová, Martin Jiřička."),
  vote(V8),

  h3("3) Schválení programu"),
  p("Starosta přečetl program."),
  ...nl([
    "Zahájení",
    "Volba návrhové komise a ověřovatelů zápisu",
    "Schválení programu",
    "Zpráva Kontrolního výboru",
    "Rozpočtové opatření",
    "Obecně závazná vyhláška obce",
    "Společná voda d.s.o.",
    "Koupě, prodej, pronájem",
    "Různé",
    "Diskuse",
    "Závěr",
  ]),
  p("Starosta: Má někdo návrh na změnu nebo doplnění programu?"),
  h5("Návrh"),
  p("ZO schvaluje program zasedání zastupitelstva obce."),
  vote(V8),

  h3("4) Zpráva kontrolního výboru"),
  p("Předseda kontrolního výboru Martin Jiřička seznámil se zprávou Kontrolního výboru ze dne 16.12.2024."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí Zprávu Kontrolního výboru ze dne 16.12.2024."),

  h3("5) Rozpočtové opatření"),
  h4("Rozpočtové opatření č. 1/2025"),
  h4("ZÁKLADNÍ ŠKOLA KRHANICE"),
  p("Informace starosty: Škola bude pořizovat nový server."),
  p("Základní škola použije Fond investic v roce 2025 pro pořízení nového serveru v částce 197 tisíc Kč. Na základě předloženého odpisového plánu navýšíme provozní příspěvek (na odpisy majetku) o částku 32 890,- Kč."),
  p("Fond investic základní školy : stav k 31.12.2024 je 523 125,55 Kč."),
  p("Zároveň z Fondu investic bude proveden odvod do rozpočtu zřizovatele ve výši 250 tisíc Kč. Tyto prostředky budou použity/zapojeny do rozpočtu obce do investiční akce pro základní školu – zastřešení a výměna oken spojovacího krčku mezi budovou základní školy a budovou školní jídelny."),
  p("V roce 2025 je příděl do Fondu investic pro Základní školu dle schváleného rozpočtu pro rok 2025 ve výši: 171,3 tisíc Kč. Úpravou rozpočtu bude tvorba Fondu investic v roce 2025 ve výši 204,19 tisíc Kč."),
  h5("Návrh"),
  p("ZO schvaluje odvod z Fondu investic Základní školy Krhanice ve výši 250 000,- Kč."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje navýšení provozního příspěvku Základní škole Krhanice ve výši 32 890,- Kč (navýšení odpisů pro nový majetek – server)."),
  vote(V8),

  h4("MATEŘSKÁ ŠKOLA KRHANICE"),
  p("Informace starosty:"),
  p("Ředitelka Mateřské školy Krhanice: V rámci dotace OP JAK II chtějí žádat o školního asistenta a na školení pedagogů – jedná se o částku 350.000,- Kč. Pro žádost je potřeba 5% spoluúčast."),
  h5("Návrh"),
  p("ZO schvaluje navýšení provozního příspěvku Mateřské škole Krhanice ve výši 17 500,- Kč (spoluúčast k dotaci z OP JAK II)."),
  vote(V8),

  p("Předseda finančního výboru Petr Dub seznámil s rozpočtovým opatřením č. 1/2025."),
  h5("Rozprava"),
  p("Š.Dušová: Proč dostanou finanční dar od Kámen Zbraslav jen hasiči. Starosta: Dárce mi řekl, abych sám rozhodl o použití finančního daru."),
  p("Š.Dušová: Dotaz k částce 17.500,- Kč pro mateřskou školu. Už víme, že dotaci mateřská škola dostane? Starosta: Zatím nevíme. Částku schvalujeme pro případ, že dotaci dostanou."),
  p("Š.Dušová: Dotaz na částku 683,76 tisíc Kč. Proč se vyskytuje jak v příjmech, tak i ve výdajích? Starosta: Jde o účetní operaci. Obec platí daň sama sobě."),
  p("Š.Dušová: Dotaz na částku 260 tisíc Kč. Proč budeme sahat do rezerv? Nebylo by lepší počkat a práce dělat později? Starosta: Ne."),
  p("T.Kratochvíl: Ocenil, že je v obci AlzaBox a výši příjmu do obecního rozpočtu."),
  p("T.Kratochvíl: Dovysvětlil použití finančních prostředků z daru na technické zhodnocení nového dopravního automobilu zásahové jednotky hasičů a na ochranné dýchací přístroje."),
  p("P.Daněk: Dotaz na navýšení o 50 tisíc Kč na hřbitov? Starosta: Chceme snížit množství odpadů do kontejneru na hřbitově, tím snížit finanční náklady na uložení odpadu na skládce. Zemina z kompostéru bude využita na zarovnání nerovností na hřbitově."),
  p("J.Daňková: Bude částka případně využita i na opravu studny? Starosta: Ne, je to jiná položka rozpočtu."),
  p("Proběhla diskuse o stavu studny a možnosti zalévání během roku se závěrem, že starosta zjistí u firmy na studny, zda je možné vylepšit její stav, např. výměnou válce."),
  h5("Návrh"),
  p("ZO schvaluje rozpočtové opatření č. 1/2025."),
  vote(V8),

  h3("6) Obecně závazná vyhláška obce Krhanice o nočním klidu"),
  p("Místostarosta obce seznámil s OZV o nočním klidu – dochází k zahrnutí nových kulturních akcí, kdy dojde k omezení nočního klidu."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Obecně závaznou vyhlášku obce Krhanice o nočním klidu."),
  vote(V8),

  h3("7) Společná voda d.s.o."),
  p("Informace starosty:"),
  p("Na zastupitelstvu dne 24.9.2024 zastupitelstvo schválilo záměr vstoupit do Společná voda d.s.o. Byl jsem pověřen zajištovat činnosti vedoucí ke vstupu. V prosinci jsme schválili 2 Dohody vlastníků provozně souvisejících vodovodů. Nyní budeme pokračovat v dalších krocích."),
  ...ul([
    "Seznámení se „Společnou zprávou vysvětlující hospodářské i právní důvody a důsledky fúze svazků Posázavský vodovod – dobrovolný svazek obcí, IČO: 14117223, a Společná voda d.s.o., IČO: 17408288“. JIŽ BYLO V MINULOSTI VYSVĚTLENO.",
    "Seznámení se Smlouvou o fúzi – sloučením svazků: Zanikající svazek: Posázavský vodovod – dobrovolný svazek obcí, IČO: 141 17 223; se sídlem: Masarykovo náměstí 194, 254 01 Jílové u Prahy a Nástupnický svazek: Společná voda d.s.o., IČO: 17408288; se sídlem: Černoleská 1600, 256 01 Benešov",
    "Seznámení se „Smlouvou o poskytnutí vstupního vkladu, příspěvku nad rámec základního vkladu vstupujícího člena dobrovolného svazku obcí“: Svazek: Společná voda d.s.o., IČO: 17408288, se sídlem Černoleská 1600, 256 01 Benešov a Vkladatel: Obec Krhanice, IČO: 00232025, se sídlem Krhanice 46, 257 42 Krhanice",
    "V rámci tohoto bodu projednáme bezúplatný převod z bodu č. 8) Koupě, prodej, pronájem",
  ]),
  ...ul([
    "bezúplatně převést na svazek Společná voda d.s.o., IČO: 17408288, se sídlem: Černoleská 1600, 256 01 Benešov, zapsaný v rejstříku svazků vedeném u Krajského úřadu Středočeského kraje, část vodohospodářského majetku, který prochází katastrálním územím obce Krhanice a který je součástí vodovodního přivaděče Posázavského vodovodu, a to IČME 2101-674362-00232025-1/3, název části: Posázavský vodovod (Prosečnice-Krhanice), k.ú.: Krhanice, IČME: 2101-674362-00232025-1/4, název části: Posázavský vodovod (Kam. Újezdec-Prosečnice), k.ú.: Krhanice. Jedná se o tento vodohospodářský majetek:",
  ]),
  p("Vybrané údaje majetkové evidence za rok 2024, vodovodní řad: 2101-674362-00232025-1/3 – Posázavský vodovod (Prosečnice-Krhanice). Vlastník vodovodu: Obec Krhanice, IČO 00232025, Krhanice 46, 25742 Krhanice, právnická osoba, telefon 317702121,122, e-mail ou.krhanice@seznam.cz, není plátce DPH. Hodnota uvedeného majetku (objektů) v reprodukční pořizovací ceně (tis. Kč s DPH): 24476.637."),
  p("Vybrané údaje majetkové evidence za rok 2024, vodovodní řad: 2101-674362-00232025-1/4 – Posázavský vodovod (Kam.Újezdec-Prosečnice). Vlastník vodovodu: Obec Krhanice, IČO 00232025, Krhanice 46, 25742 Krhanice, právnická osoba, telefon 317702121,122, e-mail ou.krhanice@seznam.cz, není plátce DPH. Hodnota uvedeného majetku (objektů) v reprodukční pořizovací ceně (tis. Kč s DPH): 4469.861."),
  h5("Rozprava"),
  p("Š.Dušová: Dotaz, zda budeme mít lepší pozici ve Společné vodě oproti stávajícímu stavu? Starosta: Staneme se právoplatnými členy. Budeme na roveň s ostatními."),
  p("Proběhla diskuse o vodném, postavení obce, … bez přijetí závěrů."),
  h5("Návrhy usnesení projednávaného bodu č. 7) Společná voda d.s.o."),
  h5("Návrh"),
  p("ZO schvaluje souhlas s fúzí svazku Posázavský vodovod – dobrovolný svazek obcí, IČO: 141 17 223, se sídlem: Masarykovo náměstí 194, 254 01 Jílové u Prahy, sloučením se svazkem Společná voda d.s.o., IČO: 17408288, se sídlem: Černoleská 1600, 256 01 Benešov."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje smlouvu o fúzi svazku Posázavský vodovod – dobrovolný svazek obcí, IČO: 141 17 223, se sídlem: Masarykovo náměstí 194, 254 01 Jílové u Prahy, sloučením se svazkem Společná voda d.s.o., IČO: 17408288, se sídlem: Černoleská 1600, 256 01 Benešov, s rozhodným dnem 1. 7. 2025."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje vstup do dobrovolného svazku Společná voda d.s.o., IČO: 174 08 288, se sídlem Černoleská 1600, 256 01 Benešov, fúzí sloučením k rozhodnému dni 1. 7. 2025."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje souhlas s účastí ve svazku Společná voda d.s.o., IČO: 174 08 288, se sídlem Černoleská 1600, 256 01 Benešov, a s podmínkami smlouvy o vytvoření dobrovolného svazku obcí ze dne 28.07.2022 a se stanovami svazku Společná voda d.s.o., IČO: 174 08 288, se sídlem Černoleská 1600, 256 01 Benešov, a s podmínkami smlouvy o společném zadávání veřejných zakázek včetně koncesí ze dne 30.12.2022 a přistupuje k nim."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje poskytnutí vstupního vkladu, příspěvku nad rámec základního vkladu člena svazku obcí Společná voda d.s.o., jehož je členem, pro Společná voda d.s.o., se sídlem Černoleská 1600, 256 01 Benešov, IČO 174 08 288, ve výši 542.088,- Kč."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje uzavření smlouvy o vstupním vkladu, příspěvku nad rámec základního vkladu člena svazku obcí Společná voda d.s.o., jehož se stane členem, se svazkem obcí Společná voda d.s.o., se sídlem Černoleská 1600, 256 01 Benešov, IČO 174 08 288."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje dohodu o úpravě majetkových poměrů o bezúplatném převodu části Posázavského vodovodu na svazek Společná voda d.s.o., ke dni 1. 7. 2025, a to IČME 2101-674362-00232025-1/3, název části: Posázavský vodovod (Prosečnice-Krhanice), k.ú.: Krhanice, IČME: 2101-674362-00232025-1/4, název části: Posázavský vodovod (Kam. Újezdec-Prosečnice), k.ú.: Krhanice. Tento vodohospodářský majetek je detailně popsán v příloze č. 1 této dohody, která tvoří její nedílnou součást."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje souhlas s tím, že v rámci ukončení účasti obce Krhanice v zanikajícím svazku jeho zánikem k rozhodnému dni, nedojde v souladu se stanovami svazku Posázavský vodovod – dobrovolný svazek obcí, k vypořádání této obce, tj., že ukončením její účasti jí nevzniká nárok na majetkové a finanční vypořádání."),
  vote(V8),
  h5("Návrh"),
  p("ZO pověřuje starostu obce zabezpečit provedení potřebných úkonů vedoucích k realizaci usnesení bodu č.7 Zastupitelstva obce Krhanice pro vstup obce do Společná voda d.s.o., zejména hlasovat na správní radě svazku Posázavský vodovod – dobrovolný svazek obcí, IČO: 14117223, se sídlem: Masarykovo náměstí 194, 254 01 Jílové u Prahy, pro plánovanou fúzi sloučením tohoto svazku se svazkem Společná voda d.s.o., se sídlem Černoleská 1600, 256 01 Benešov, IČO 174 08 288, podepsat všechny potřebné dohody a smlouvy."),
  vote(V8),

  h3("8) Koupě, prodej, pronájem"),
  ...ul(["uzavřít Smlouvu o zřízení věcného břemene – uložení vodovodní přípojky pro pozemek 272/5 k.ú. Krhanice na pozemku parc.č. 1981/1 k.ú. Krhanice dle geometrického plánu č. 1183-56/2024 na dobu neurčitou za cenu 3 000,- Kč."]),
  p("Informace starosty: Jedná se o vodovodní přípojku v komunikaci k lomu."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o zřízení věcného břemene – uložení vodovodní přípojky pro pozemek 272/5 k.ú. Krhanice na pozemku parc.č. 1981/1 k.ú. Krhanice dle geometrického plánu č. 1183-56/2024 na dobu neurčitou za cenu 3 000,- Kč s Janem Součkem, Chrást nad Sázavou 190, 257 41 Týnec nad Sázavou."),
  vote(V8),
  ...ul(["uzavřít Smlouvu o zřízení věcného břemene – uložení vodovodní přípojky pro pozemek 272/4 k.ú. Krhanice na pozemku parc.č. 1981/1 k.ú. Krhanice dle geometrického plánu č. 1184-57/2024 na dobu neurčitou za cenu 3 000,- Kč."]),
  p("Informace starosty: Jedná se o vodovodní přípojku v komunikaci k lomu."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o zřízení věcného břemene – uložení vodovodní přípojky pro pozemek 272/4 k.ú. Krhanice na pozemku parc.č. 1981/1 k.ú. Krhanice dle geometrického plánu č. 1184-57/2024 na dobu neurčitou za cenu 3 000,- Kč s Kristýnou Sládkovou, Hostěradice 63, 252 82 Kamenný Přívoz."),
  vote(V8),

  h3("9) Různé"),
  h4("INVENTARIZAČNÍ ZPRÁVA OBCE KRHANICE ZA ROK 2024"),
  p("Předseda inventarizační komise Aleš Papoušek přečetl inventarizační zprávu o proběhlé inventarizaci za rok 2024."),
  p("Inventarizace proběhla v řádném termínu, informace o stavu na jednotlivých účtech jsou uvedeny v příloze. Zhodnocení hospodaření obce bude projednáno v rámci Závěrečného účtu a schválení účetní závěrky na zastupitelstvu v měsíci červen 2025."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí Inventarizační zprávu obce Krhanice za rok 2024."),

  h4("PROTOKOL O KONTROLE V ZÁKLADNÍ ŠKOLE"),
  p("28.ledna 2025 proběhla neohlášená kontrola zjištění koncentrace CO2 ve třídách základní školy ze strany Krajské hygienické stanice Středočeského kraje se závěrem: Koncentrace CO2 ve vnitřním prostředí byla tedy nižší než doporučená hodnota 1200 ppm."),

  h4("ZAHÁJENÍ SVOZU BIOODPADU"),
  p("Místostarosta informoval o zahájení svozu. V pátek budou rozmístěny hnědé biokontejnery na stanoviště. Velký modrý kontejner je u školy a bude po týdnu přesunut do Prosečnice a potom do Krhanic na náves u křížku."),

  h3("10) Diskuse"),
  p("P.Daněk: Dotaz na kruhový objezd a návaznost chůze po krajnici směrem od Prosečnice k přechodu na kruhovém objezdu – není to ideální, na jedné straně je kačírek, na druhé straně zábradlí. Starosta: Kačírek v projektu nebyl, měla tam být tráva. Je dobře, že je tam alespoň kačírek. Vše jinak odpovídá projektu."),
  p("P.Daněk: Dotaz na hlavní silnici před mojí nemovitostí. Je výš, než byla původně. Pokud bude více pršet, poteče všechna voda k nám do dvora. S kým tuto situaci řešit? Starosta: Není to majetek obce. Je to majetek Středočeského kraje ve správě Krajské údržby silnic Středočeského kraje. Již jsem několikrát řešil věci související s vodou a nikdy se nic nestalo. Je třeba s nimi písemně/elektronicky komunikovat. Je možné mě dát do kopie, obec vás podpoří."),
  p("P.Daněk: Dotaz na zklidnění dopravy v naší lokalitě. Bude to nějak řešeno ze strany obce? Starosta: Uvažujeme o umístění informativního radaru, který v případě překročení rychlosti zobrazí SPZ. V minulosti jsme zařídili namalování plné čáry na silnici v dané lokalitě v celé délce."),
  p("P.Daněk: Dotaz na klidovou vyhlášku. Kontroluje někdo, zda je dodržována? Starosta: Je potřeba při jejím porušení volat mně, nebo panu místostarostovi. Porušení řešíme buď domluvou, nebo je to na přestupkovou komisi."),
  p("P.Bydžovský: Co nového ve věci věcného břemene (elektrická přípojka) u nádraží? Starosta: Obec nesouhlasí s umístěním kabelu. Při rekonstrukci kabelu v dané lokalitě měl být kabel natažen podél celého kamenictví až dozadu aby se daly udělat všechny přípojky. P.Bydžovský: Takže když majitelka nechtěla mít kabel na svém pozemku, obec nesouhlasí šel kabel přes obecní pozemek? Starosta: Nechápu, když mi někdo natáhne zadarmo kabel k domu, tak to odmítnu?! P.Bydžovský: Kabel měl být natažen „za desetikorunu“. Starosta: Budeme řešit jenom geodetické vytýčení obecního pozemku. Z diskuse nevyplynuly žádné závěry."),
  p("P.Bydžovský: Poděkoval všem, kteří se zúčastnili masopustu a všem, kteří se zapojili do jeho organizace."),

  h3("11) Usnesení a závěr"),
  p("Zastupitelstvo obce bylo ukončeno v 19:12 hod."),

  p("Datum pořízení zápisu: 21.3.2025"),
  p("Ověřovatelé zápisu a starosta obce, podepsáno v listinné podobě."),
  h4("Přílohy"),
  ...nl(["Svolání zastupitelstva obce", "Prezenční listina zastupitelů", "Prezenční listina občanů"]),
];

async function run() {
  const r = await publishZapis({
    cislo: "1",
    rok: "2025",
    isoDate: "2025-03-11",
    dateLabel: "11. 3. 2025",
    fullDateDot: "11.3.2025",
    pdfPath: "scripts/zapisy-pdf/zapis-2025-1.pdf",
    transcript,
  });
  console.log("OK", r.docId, "blocks", r.blocks);
}
run().catch((e) => { console.error(e); process.exit(1); });
