/* eslint-disable no-console */
// Faithful visual transcript of Zápis č. 1/2023 (16.3.2023), transcribed
// page-by-page from the official PDF images. Structure per AGENT-SPEC.md and the
// golden example scripts/build-zapis-2026-1.ts.
import { h3, h4, h5, p, vote, nl, ul, publishZapis, type Block } from "../zapis-lib";

const V8 = "PRO ( 8 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )";

const transcript: Block[] = [
  h4("Přítomni"),
  p("Aleš Papoušek, Jaroslav Mixa, Tomáš Kratochvíl, Aleš Kozel, Jana Laboutková, Petr Dub, Lucie Maršíková, Ivan Dvořák"),
  h4("Omluveni"),
  p("Martin Jiřička"),

  h3("1) Zahájení, přivítání přítomných, konstatování přítomnosti"),
  p("Starosta konstatoval, že zasedání bylo svoláno dne 8.3.2023, bylo vyvěšeno na úřední desce obecního úřadu, tj. tedy nejméně 7 dní před zasedáním. Bylo tedy svoláno řádně a včas v souladu se zákonem o obcích v platném znění. Starosta konstatoval, že podle prezenční listiny je přítomno 8 členů zastupitelstva, tedy nadpoloviční většina členů zastupitelstva. K předchozímu zápisu nebyly vzneseny námitky."),
  h5("Určení zapisovatele"),
  p("Zápisem zasedání zastupitelstva obce byla pověřena Ing. Alena Kratochvílová."),

  h3("2) Volba návrhové komise a ověřovatelů zápisu"),
  p("Starosta přednesl návrh návrhové komise a ověřovatelů zápisu."),
  h5("Návrh"),
  p("ZO schvaluje návrhovou komisi ve složení: Jaroslav Mixa, Jana Laboutková."),
  h5("Návrh"),
  p("ZO schvaluje ověřovatele zápisu ve složení Petr Dub, Tomáš Kratochvíl."),
  vote(V8),

  h3("3) Schválení programu"),
  p("Starosta přečetl program."),
  ...nl([
    "Zahájení",
    "Volba návrhové komise a ověřovatelů zápisu",
    "Schválení programu",
    "Zpráva kontrolního výboru",
    "Dodatek č. 2 ke Smlouvě o dílo se společností Intermont, Opatrný. s.r.o. pro stavební práce Krhanice – revitalizace a VZT budovy ZŠ",
    "Výběrové řízení Rekonstrukce hrobu rudoarmějců na hřbitově v Krhanicích",
    "Rozpočtová opatření",
    "Obecně závazná vyhláška obce Krhanice o nočním klidu",
    "Obecně závazná vyhláška obce Krhanice, kterou se stanoví část společného školského obvodu Základní školy Krhanice s obcí Kamenný Přívoz",
    "Volba člena finančního výboru",
    "Koupě, prodej, pronájem",
    "Různé",
    "Diskuse",
    "Usnesení a závěr",
  ]),
  p("Starosta: Má někdo návrh na změnu nebo doplnění programu?"),
  h5("Návrh"),
  p("ZO schvaluje program zasedání zastupitelstva obce."),
  vote(V8),

  h3("4) Zpráva kontrolního výboru"),
  p("Člen kontrolního výboru Aleš Kozel seznámil se zprávou kontrolního výboru ze dne 29.12.2022."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí Zprávu kontrolního výboru ze dne 29.12.2022."),

  h3("5) Dodatek č. 2 ke Smlouvě o dílo se společností Intermont, Opatrný. s.r.o. pro stavební práce Krhanice – revitalizace a VZT budovy ZŠ"),
  p("Informace starosty: Jedná se o vícepráce a méněpráce, které vznikly při rekonstrukci budovy základní školy. Práce byly odsouhlaseny stavebním dozorem a projektantem. Částka je: 2 037 726,11 Kč s DPH."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Dodatku č.2 ke Smlouvě o dílo se společností Intermont, Opatrný. s.r.o. pro stavební práce Krhanice – revitalizace a VZT budovy ZŠ. Cena díla se navyšuje o 2 037 726,11 Kč včetně DPH."),
  vote(V8),
  h5("Návrh"),
  p("ZO pověřuje starostu obce podpisem Dodatku č.2 ke Smlouvě o dílo se společností Intermont, Opatrný. s.r.o. pro stavební práce Krhanice – revitalizace a VZT budovy ZŠ."),
  vote(V8),

  h3("6) Výběrové řízení Rekonstrukce hrobu rudoarmějců na hřbitově v Krhanicích"),
  p("Informace starosty: Výběrové řízení bylo realizováno s Posázaví o.p.s. Byly osloveny tři firmy. Výběrové řízení proběhlo v pondělí 13.3.2023. Nabídku podaly dvě firmy. Hodnotícím kritériem byla nejnižší nabídková cena."),
  p("Výsledek:"),
  ...ul([
    "Číslo doručené nabídky 2. – Zdeněk Makovíni, IČ/RČ/datum narození účastníka 74225740, nabídková cena v Kč vč. DPH / cena konečná 386 620.",
    "Číslo doručené nabídky 1. – Rudolf Pospíšil, IČ/RČ/datum narození účastníka 63827735, nabídková cena v Kč vč. DPH / cena konečná 438 987.",
  ]),
  p("Nejvhodnější nabídkou, tj. nabídkou nejlépe splňující kritérium stanovené zadavatelem v textu zadávací dokumentace pro zakázku malého rozsahu mimo režim zákona č. 134/2016 Sb., o zadávání veřejných zakázek k zakázce „Krhanice – rekonstrukce válečného hrobu obětí 2. světové války“ je nabídka účastníka:"),
  p("obchodní firma/jméno: Zdeněk Makovíni"),
  p("sídlo / místo podnikání: Krhanice 193, 257 42 Krhanice"),
  p("IČO: 74225740"),
  p("Nabídková cena: 386 620 Kč"),
  p("Po výběrovém řízení:"),
  ...ul([
    "dotace 309 296,00 Kč (80%)",
    "spoluúčast obce 77 324,00 Kč (20%)",
  ]),
  h5("Rozprava"),
  p("I.Dvořák: Bude realizace do 31.10.? Starosta: Ano."),
  h5("Návrh"),
  p("ZO schvaluje uzavření smlouvy o dílo na akci „Krhanice – rekonstrukce válečného hrobu obětí 2. světové války“ s: Zdeněk Makovíni, Krhanice 193, 257 42 Krhanice, IČO: 74225740 ve výši 386 620 Kč."),
  vote(V8),
  h5("Návrh"),
  p("ZO pověřuje starostu podpisem smlouvy o dílo na akci Krhanice – rekonstrukce válečného hrobu obětí 2. světové války s: Zdeněk Makovíni, Krhanice 193, 257 42 Krhanice, IČO: 74225740."),
  vote(V8),

  h3("7) Rozpočtová opatření"),
  h4("Rozpočtové opatření č. 10/2022, č. 1/2023 a č. 2/2023"),
  p("Starosta obce seznámil s provedenými rozpočtovými opatřeními č. 10/2022, č. 1/2023 a č. 2/2023 provedenými v souladu se schválenými pravidly ze dne 22.12.2022."),
  p("Č. 10/2022: dotace rekonstrukce návsi – rozpočtována příjmová položka dotace"),
  p("Č. 1/2023: dotace Volba prezidenta ČR – rozpočtována příjmová položka dotace a výdajový paragraf dotace."),
  p("Č. 2/2023: finanční vypořádání za rok 2022 – vratka části dotace z roku 2022 na tzv. přípravnou fázi Voleb prezidenta ČR (rozpočtováno přesunem mezi výdajovými paragrafy)."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí rozpočtové opatření č. 10/2022, č. 1/2023 a č. 2/2023."),

  h4("Rozpočtové opatření č. 3/2023"),
  h5("DIAKONIE BROUMOV, SOCIÁLNÍ DRUŽSTVO"),
  p("Informace starosty: Z Diakonie Broumov nám zaslali žádost o finanční příspěvek."),
  p("Zdůvodnění: Diakonie Broumov, sociální družstvo dlouhodobě poskytuje obcím službu vývozu kontejneru s textilním materiálem, který dále třídíme a zajišťujeme jeho další využití. Tuto službu jsme byli schopni dosud poskytovat zdarma, případně s finanční podporou ve formě daru a poskytnutí součinností od obcí/měst a dalších subjektů. Tento model však z důvodů, které jsou Vám jistě známy (růst minimálních mezd, zvýšení cen nejen skládkovného, navýšení cen pohonných hmot...) nejsme dále schopni udržet."),
  p("Byl nám zaslán návrh darovací smlouvy, se kterým se zastupitelé měli možnost seznámit."),
  p("Návrh na poskytnutí daru ve výši 3.000,- Kč."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje poskytnutí finančního daru ve výši 3.000,- Kč a uzavření darovací smlouvy s Diakonie Broumov, sociální družstvo, Husova 319, Velká Ves, 550 01 Broumov, IČO: 49289977."),
  vote(V8),

  h5("OBČANSKÝ NÁVRHOVÝ PROJEKTOVÝ ROZPOČET"),
  p("Informace starosty: Nejdříve poděkoval všem občanům, kteří předložili své projekty."),
  p("Ke dni 28.2.2023 to bylo nakonec pět projektů. Dne 14.3.2023 dle schválených Pravidel pro tento projektový rozpočet bylo provedeno hodnocení ve dvou kolech. Hodnotili zastupitelé obce."),
  p("Předložené projekty:"),
  ...ul([
    "Volně přístupové posilovací stroje v areálu víceúčelového hřiště v Krhanicích u základní školy",
    "V Krhanicích chybí komunitní venkovní místo, kde by se mohly pořádat venkovní společenské akce",
    "Pumptracková dráha pro cyklisty všech věkových kategorií",
    "Vzdělávání pro zastupitele obce Krhanice",
    "KVĚTINOVÁ NÁVES u lípy",
  ]),
  p("Kritéria pro postup do 2. kola splnily 4 projekty:"),
  ...ul([
    "Volně přístupové posilovací stroje v areálu víceúčelového hřiště v Krhanicích u základní školy",
    "V Krhanicích chybí komunitní venkovní místo, kde by se mohly pořádat venkovní společenské akce",
    "Pumptracková dráha pro cyklisty všech věkových kategorií",
    "KVĚTINOVÁ NÁVES u lípy",
  ]),
  p("V 2.kole zastupitelé bodovali projekty. Vítězným projektem se stal projekt Pumptracková dráha pro cyklisty všech věkových kategorií. Tento projekt neměl umístění na obecním pozemku. V případě, že se takový pozemek nenajde, bude projektem k realizaci zvolen projekt na druhém místě: Volně přístupové posilovací stroje v areálu víceúčelového hřiště v Krhanicích u základní školy."),
  p("Protože oba projekty jsou v kategorii sportovních zařízení, lze již nyní rozpustit finanční rezervu 100.000,- Kč alokovanou v rozpočtu obce na rok 2023 na Občanský návrhový projektový rozpočet, aby se po jednání ohledně místa realizace s autorem projektu již mohlo s realizací začít. Popřípadě s druhým projektem v pořadí."),
  h5("Rozprava"),
  p("P.Bydžovský: Proč postoupil projekt, který nesplnil všechny podmínky? Starosta: Umístění nebylo v podmínkách předložení projektu. V projektu je obrázek, ze kterého se dá usuzovat, kde bude projekt umístěn."),
  p("P.Dvořák: Starosta projedná s žadatelem podrobnosti a místo realizace."),
  p("H.Strnadová: Když si seženu peníze na projekt Květinová náves, mohu svůj projekt realizovat? Starosta: O tom nerozhoduji sám."),
  h5("Návrh"),
  p("ZO schvaluje v rámci Občanského návrhového projektového rozpočtu rozpuštění jeho finanční rezervy 100.000,- Kč alokované v rozpočtu obce pro rok 2023 na „sportovní zařízení ve vlastnictví obce“."),
  vote(V8),

  h5("REGIONÁLNÍ UČEBNICE – PROJEKT"),
  p("Informace starosty: Před mnoha měsíci jsem byl informován ředitelkou naší školy o projektu regionální učebnice. Ředitelka odhadovala částku na 10 tisíc Kč. Požadoval jsem rozpočet na celou akci. Před několika týdny mi byl sdělen požadavek na částku. Vyžádal jsem si rozpočet, se kterým byli seznámeni i zastupitelé. Takový postup je špatný. Nyní musíme rozhodnout, zda uvolníme částku na toto regionální učebnici. Zastupitelé obdrželi pouze pro rozhodování vzorovou verzi učebnice."),
  h5("Rozprava"),
  p("I.Dvořák: Poděkoval za poskytnutí této knihy. Dle něho je to dobrý nápad. Neštěstné bylo prvotní řešení. Osobně by se přiklonil k pořízení."),
  p("L.Maršíková: Určitě by byla učebnice přínosem. Doporučila, aby autoři požádali o grant. Pokud by se nepodařilo potřebné peníze sehnat, potom bychom o příspěvku jednali."),
  p("J.Bydžovská: Jaká byla geneze této myšlenky? Na přípravě se podíleli i žáci základní školy. Starosta: Iniciátorkou byla ředitelka základní školy v Netvořicích. Nakonec se do projektu vložilo Posázaví."),
  p("P.Bydžovský: Kolik vychází částka na jednu knihu? Starosta: 3.300,- Kč."),
  p("Proběhla všeobecná diskuse."),
  p("Starosta: Budeme hlasovat o částce 66.000,- Kč, zda zůstane v Rozpočtovém opatření č. 3."),
  h5("Návrh"),
  p("ZO schvaluje snížení částky výdajů v rozpočtovém opatření č. 3/2023 na základní školu – poskytnutí finančního příspěvku na regionální učebnici 66 tisíc Kč."),
  vote("PRO ( 6 ) – PROTI ( 1 - Kratochvíl ) – ZDRŽEL SE ( 1 - Laboutková )"),
  p("Předseda finančního výboru Petr Dub seznámil s rozpočtovým opatřením č. 3/2023."),
  h5("Rozprava"),
  p("I.Dvořák: Dotaz na dar ve výši 30 tisíc Kč – kdo ho poskytl? Starosta: Dárce si nepřeje být jmenován."),
  p("I.Dvořák: Dotaz na částku 230 tisíc Kč. Starosta: Částka se týká dešťové kanalizace, která se bude rekonstruovat souběžně s rekonstrukcí vodovodu k Dlážděnce u hlavní silnice."),
  p("I.Dvořák: Dotaz na částku 165 tisíc Kč na novou bránu k areálu TJ Sokol Krhanice. Starosta: Byl by to nový vjezd, který by vyřešil hned několik věcí, zejména přístup k ploše pro pódium a odvoz staré trávy. Vyjádřil svůj názor, že by se částka dala využít jinak. T.Kratochvíl: Vysvětlil proč i z hlediska hasičů by tuto bránu uvítali. Do zadní části areálu není přístup."),
  h5("Návrh"),
  p("ZO schvaluje snížení částky výdajů v rozpočtovém opatření č. 3/2023 na sportovní zařízení - zhotovení samostatného vjezdu do areálu TJ Sokol Krhanice v částce 165.000,- Kč."),
  vote("PRO ( 2 – Dvořák, Maršíková ) – PROTI ( 5 ) – ZDRŽEL SE ( 1 - Laboutková )"),
  p("I.Dvořák: Dotaz na Senior Taxi – Kolik bylo vydáno karet? Starosta: Cca 20."),
  p("L.Maršíková: Dotaz na navýšení 247 tisíc Kč na prostor u obchodu. Starosta: Bude v tom i prostor za obchodem."),
  p("L.Maršíková: Dotaz zda bude podesty u obchodu dělat taky pan Žaba. Starosta: Ne, pan Pospíšil."),
  p("L.Maršíková: Dotaz na částku 156 tisíc Kč, která se týká obecních bytů. Starosta: Zahrnuje rekonstrukci bytu a částky na energie, vodu a plyn v bytech."),
  h5("Návrh"),
  p("ZO schvaluje rozpočtové opatření č. 3/2023."),
  vote("PRO ( 6 ) – PROTI ( 1 - Maršíková ) – ZDRŽEL SE ( 1 - Dvořák )"),

  h3("8) Obecně závazná vyhláška obce Krhanice o nočním klidu"),
  p("Místostarosta obce seznámil s OZV o nočním klidu – dochází k zahrnutí nových kulturních akcí, kdy dojde k omezení nočního klidu."),
  h5("Rozprava"),
  p("L.Maršíková: Je možné ještě nějaké akce doplnit? Starosta: Jak jsem posílal v e-mailu, ano, do 3.června."),
  h5("Návrh"),
  p("ZO schvaluje Obecně závaznou vyhlášku obce Krhanice o nočním klidu."),
  vote(V8),

  h3("9) Obecně závazná vyhláška obce Krhanice, kterou se stanoví část společného školského obvodu Základní školy Krhanice s obcí Kamenný Přívoz"),
  p("Starosta obce seznámil s OZV o stanovení části společného školského obvodu Základní školy Krhanice s obcí Kamenný Přívoz."),
  h5("Rozprava"),
  p("I.Dvořák: Jak to Kamenný Přívoz řešil nyní? Starosta: Bez dohody a dlouhodobě."),
  p("I.Dvořák: Je tato vyhláška potřeba, nebylo by lepší nechat rodičům možnost výběru, do které školy své dítě umístí? T.Kratochvíl: Rodiče, kteří sami navštěvovali základní školu v Krhanicích, považují za samozřejmé, že jejich děti nebudou chodit jinam. To jen někteří rodiče upřednostňují jiné školy. J.Laboutková: Schválením nové vyhlášky se nic nezmění. Jen se potvrdí stávající stav."),
  h5("Návrh"),
  p("ZO schvaluje Obecně závaznou vyhlášku obce Krhanice, kterou se stanoví část společného školského obvodu základní školy."),
  vote(V8),

  h3("10) Volba člena finančního výboru"),
  p("Předseda finančního výboru Petr Dub podal návrh na doplnění člena Finančního výboru:"),
  p("člen : Soňa Valášková"),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje za člena finančního výboru Soňu Valáškovou."),
  vote(V8),
  p("Finanční výbor je z hlediska počtu členů kompletní."),

  h3("11) Koupě, prodej, pronájem"),
  ...ul([
    "prodat pozemek par. č. 1979/4 k.ú. Krhanice, o výměře 174 m²; pozemek par. č. 1981/3 k.ú. Krhanice, o výměře 138 m², který vznikne dle geometrického plánu č. 1038-5/2021 oddělením z pozemku parc. č. 1981/2; pozemek par. č. 2051/8 k.ú. Krhanice, o výměře 80 m², který vznikne dle geometrického plánu č. 1039-6/2021 oddělením z pozemku parc. č. 2051/5 a pozemek par. č. 2051/9 k.ú. Krhanice, o výměře 88 m², který vznikne dle geometrického plánu č. 1039-6/2021 oddělením z pozemku parc. č. 2051/5, které využívá Správa železnic, státní organizace, IČO 70994234, Dlážděná 1003/7, Praha 1 v rámci své činnosti při zajišťování provozování železniční dopravní cesty jako veřejné služby za cenu znaleckého posudku č. 5791 – 23/2022 ve výši 239.780,- Kč.",
  ]),
  p("Informace starosty: Již jsme několikrát řešili. Z jednání na Správě železnic a korespondence je jasné, že nelze spojovat prodej a řešení chodníku na nádraží."),
  h5("Rozprava"),
  p("I.Dvořák: Doporučoval by pokračovat v jednání."),
  h5("Návrh"),
  p("ZO schvaluje prodej pozemku par. č. 1979/4 k.ú. Krhanice, o výměře 174 m²; pozemku par. č. 1981/3 k.ú. Krhanice, o výměře 138 m², který vznikne dle geometrického plánu č. 1038-5/2021 oddělením z pozemku parc. č. 1981/2; pozemek par. č. 2051/8 k.ú. Krhanice, o výměře 80 m², který vznikne dle geometrického plánu č. 1039-6/2021 oddělením z pozemku parc. č. 2051/5 a pozemek par. č. 2051/9 k.ú. Krhanice, o výměře 88 m², který vznikne dle geometrického plánu č. 1039-6/2021 oddělením z pozemku parc. č. 2051/5, které využívá Správa železnic, státní organizace, IČO 70994234, Dlážděná 1003/7, Praha 1 v rámci své činnosti při zajišťování provozování železniční dopravní cesty jako veřejné služby za cenu znaleckého posudku č. 5791 – 23/2022 ve výši 239.780,- Kč."),
  vote("PRO ( 7 ) – PROTI ( 1 - Dvořák ) – ZDRŽEL SE ( 0 )"),
  ...ul([
    "uzavřít Smlouvu o uzavření budoucí smlouvy o zřízení věcného břemene - služebnosti a smlouvu o právu provést stavbu č. I IP-12-6021683 „BN-Krhanice-kNN-č.parc. 208“ na pozemcích parc. č. 2070/5 k.ú. Krhanice a parc. č. 2070/2 k.ú. Krhanice s ČEZ Distribuce, a.s., IČ 24729035, DIČ CZ24729035, se sídlem Děčín IV-Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 3.025,- Kč na umístění zařízení distribuční soustavy – kabelu 28m + pilíř.",
  ]),
  p("Informace starosty: Jedná se o pozemek v lokalitě u nádraží vedle kamenictví."),
  h5("Rozprava"),
  p("P.Bydžovský: Požádal o upřesnění, kam kabel povede. Starosta: Ukázal na mapě."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o uzavření budoucí smlouvy o zřízení věcného břemene - služebnosti a smlouvu o právu provést stavbu č. I IP-12-6021683 „BN-Krhanice-kNN-č.parc. 208“ na pozemcích parc. č. 2070/5 k.ú. Krhanice a parc. č. 2070/2 k.ú. Krhanice s ČEZ Distribuce, a.s., IČ 24729035, DIČ CZ24729035, se sídlem Děčín IV-Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 3.025,- Kč na umístění zařízení distribuční soustavy – kabelu 28m + pilíř."),
  vote(V8),
  ...ul([
    "uzavřít Smlouvu o uzavření budoucí smlouvy o zřízení věcného břemene - služebnosti a smlouvu o právu provést stavbu na pozemku parc. č. 1956/9 k.ú. Krhanice s Andreou Sitta, Hlavní 94, 252 26 Třebotov na dobu neurčitou za cenu 3000,- Kč na umístění zařízení distribuční soustavy – kabelu 25 m.",
  ]),
  p("Informace starosty: Jedna se o položení elektrického kabelu přípojky rodinného domu v Prosečnici."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o uzavření budoucí smlouvy o zřízení věcného břemene - služebnosti a smlouvu o právu provést stavbu na pozemku parc. č. 1956/9 k.ú. Krhanice s Andreou Sitta, Hlavní 94, 252 26 Třebotov na dobu neurčitou za cenu 3000,- Kč na umístění zařízení distribuční soustavy – kabelu 25 m."),
  vote(V8),
  ...ul([
    "bezúplatné nabytí vodovodního řadu N1-1 na pozemku parc.č. 299/1 k.ú. Krhanice realizovaného Vodohospodářskou společností Benešov, s. r. o. a zkolaudovaného Městským úřadem Benešov do vlastnictví obce Krhanice v hodnotě 172.271,- Kč od: Borys Moshkola, Iuliia Moshkola, Slunečná 56, 254 01 Jílové u Prahy a současně uzavřít smlouvu o zřízení věcného břemene na vodovodní řad N1-1 pro pozemek parc.č. 299/1 k.ú. Krhanice na dobu neurčitou za cenu 3.000,- Kč.",
  ]),
  p("Informace starosty: Jedná se o lokalitu naproti Hodkovu v Krhanicích. Dle dohody obec převezme vodovod, pokud ho zrealizuje VHS Benešov. Podmínka byla splněna."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje bezúplatné nabytí vodovodního řadu N1-1 na pozemku parc.č. 299/1 k.ú. Krhanice realizovaného Vodohospodářskou společností Benešov, s. r. o. a zkolaudovaného Městským úřadem Benešov do vlastnictví obce Krhanice v hodnotě 172.271,- Kč od: Borys Moshkola, Iuliia Moshkola, Slunečná 56, 254 01 Jílové u Prahy a současně uzavřít smlouvu o zřízení věcného břemene na vodovodní řad N1-1 pro pozemek parc.č. 299/1 k.ú. Krhanice na dobu neurčitou za cenu 3.000,- Kč."),
  vote(V8),

  h3("12) Různé"),
  h4("Zpráva o výsledku přezkoumání hospodaření obce Krhanice"),
  p("Starosta seznámil se Zápisem z přezkoumání hospodaření obce ze dne 7.3.2023 s výsledkem nebyly zjištěny chyby a nedostatky – kontrolu provedl Krajský úřad Středočeského kraje, Odbor interního auditu a kontroly."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí Zprávu o výsledku přezkoumání hospodaření obce ze dne 7.3.2023."),

  h4("Inventarizační zpráva obce Krhanice za rok 2022"),
  p("Předseda inventarizační komise Aleš Papoušek přečetl inventarizační zprávu o proběhlé inventarizaci za rok 2022. Zpráva byla předložena zastupitelstvu k vyhodnocení."),
  p("Směrnice o inventarizaci č. 2/2013 ze dne 26.9.2013:"),
  p("2.11. Postupy pro vyhodnocení inventarizační zprávy"),
  p("Inventarizační zpráva bude vyhodnocena zastupitelstvem obce. Zastupitelstvo obce rozhodne o opatřeních k odstranění negativních zjištění (včetně termínu a odpovědných osob)."),
  p("V Inventarizační zprávě nebyla negativní zjištění ohledně majetku obce."),
  h5("Rozprava"),
  p("L.Maršíková: K jakému datu se zjišťuje stav majetku? Starosta: K 31.12."),
  h5("Návrh"),
  p("ZO bere na vědomí Inventarizační zprávu obce Krhanice za rok 2022."),

  h4("Digitální technická mapa Středočeského kraje"),
  p("Obec má povinnost pořídit digitální technickou mapu svých sítí. Spolupracujeme s určenou firmou ze strany Středočeského kraje – Hrdlička, s. r. o. Tato firma pořizuje data pro Digitální technickou mapu Středočeského kraje (DTM SK), jak z majetku kraje, tak i mnohých obcí a měst. Pro úspěšnost realizace projektu DTM SK je nezbytné, aby byla součinnost mezi krajem a obcemi/městy v dané problematice stvrzena Smlouvou o spolupráci při tvorbě, aktualizaci a správě Digitální technické mapy Středočeského kraje (dále Smlouva)."),
  p("Tato Smlouva byla projednána v Radě SK a přijetím ze strany obce/města bude mj. potvrzena uznatelnost nákladů na činnost dodavatele dle metodiky dotačního programu EU (OP PIK), z kterého je projekt financován (uznatelné jsou výdaje na mapování technické a dopravní infrastruktury v majetku obce, popř. vodovody, kanalizace a veřejné osvětlení v majetku jiné právnické osoby 100% vlastněné obcí). Zastupitelstvo obce projedná smlouvu zaslanou ze strany Středočeského kraje."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o spolupráci při tvorbě, aktualizaci a správě Digitální technické mapy Středočeského kraje se Středočeským krajem, IČO: 70891095, Zborovská 11, 150 21 Praha 5."),
  vote(V8),

  h4("Krhanice - chodník podél silnice III/1066"),
  p("Informace starosty: Žádali jsme o dotaci na Státním fondu dopravní infrastrukury. Dotaci jsme z důvodu vyčerpání částky alokované na všechny dotace neobdrželi. Můžeme podat žádost znovu, protože žádost je v pořádku. Nyní se otevírá možnost případného podání žádosti na Posázaví, o.p.s. Dotace není vypsána, ale je třeba být připraven. Podmínky budou jiné zejména z hlediska zpracování rozpočtu, recyklace materiálu vytěženého při realizaci,… Zároveň potřebujeme vypsat výběrové řízení na podání nabídek na zhotovení chodníku, abychom měli náskok v případě posunu k vypsání dotace. Proto začnu řešit nastudování nových podmínek, úpravu rozpočtu, výběrové řízení,…"),
  h5("Rozprava"),
  p("P.Bydžovský: O jaký objem asfaltu se jedná? Mohl by se použít na vjezd na hřiště, aby se ušetřily peníze za deponii. Místostarosta: Podklad ve vjezdu musí být takový, aby vydržel zátěž a jakou se počítá."),
  h5("Návrh"),
  p("ZO pověřuje starostu obce realizací výběrového řízení na projekt „Krhanice - chodník podél silnice III/1066“ ve spolupráci s Posázavím o.p.s., Zámek Jemniště 1, 257 01 Postupice, IČO 27129772."),
  vote(V8),

  h4("Anketa veřejné osvětlení"),
  p("Starosta seznámil s výsledky ankety o veřejném osvětlení."),
  ...ul([
    "Nevypínat: 73 (16%)",
    "24:00 - 3:00: 29 (6%)",
    "24:00 - 4:00: 213 (47%)",
    "1:00 - 3:00: 39 (9%)",
    "1:00 - 4:00: 96 (21%)",
    "celkem: 450 (100%)",
    "Mohlo hlasovat občanů starších 15 let: 779",
  ]),
  p("Roční náklady na energii: 316 242,30 Kč"),
  p("Úspora bude pro - 4 hodiny 36,40% - za 8 měsíců 70.000,- Kč (ročně 103 600 Kč)"),
  p("S firmou, která má na starosti veřejné osvětlení v obci jsem předběžně dohodnut, že ke Dni země, tj. 22.4.2023, bude osvětlení v noci vypínáno."),

  h4("Anketa odpady"),
  p("Místostarosta seznámil s výsledky ankety o odpadech."),
  p("Bylo osloveno celkem 349 domácností. Bylo odevzdáno 204 dotazníků, tj. 58,45%, zaokrouhleně 60% domácností odevzdalo dotazník. Řada domácností již v roce 2023 přešla na menší objem popelnice nebo menší četnost svozu. Většina odpověděla na rok 2024 je přechod z týdenního svozu na kombinovaný nebo čtrnáctidenní svoz. Od 40% procent domácností jsme nezískali zpětnou vazbu. Nyní vstoupíme do jednání s Technickými službami Benešov, kde je seznámíme s výsledky a dohodneme další postup."),
  p("Topíme v kamnech, krbu: 126 domácností, tj. 62%"),
  p("Tašky velké papír-sklo-plasty: 55 domácností"),
  p("Tašky velké kovy: 9 domácností"),
  p("Tašky malé papír-sklo-plasty: 10 domácností"),
  p("Tašky malé kovy: 11 domácností"),
  p("Kompostéry dotace: 46 domácností"),
  p("Kompostéry spoluúčast: 50% - 17 domácností, 60% - 5 domácností, 70% - 3 domácnosti"),
  p("Kuchyňský odpad: 48 domácností"),
  p("Proběhla diskuse o četnosti svozu, množství odpadu na občana a rok."),

  h4("Omezení dopravy v obci – probíhající akce"),
  ...nl([
    "Pokračuje rekonstrukce návsi. Budování chodníku souběžně se silnicí, odstraňování chodníku směrem k pítku. Pokládka dešťové kanalizace z návsi směrem k pítku. Rekonstrukce chodníku z návsi směrem k pítku.",
    "Rekonstrukce hlavního vodovodního přivaděče za křižovatkou směrem na Lešany k odbočení k Dlážděnce.",
  ]),

  h4("Týden prodeje známek na popelnice 2023"),
  p("Týden prodeje známek na popelnice probíhá na Obecním úřadě Krhanice, a to:"),
  ...ul([
    "Pondělí 20.3.2023 od 8:00 do 12:00 hod.; od 13:00 do 18:00 hod.",
    "Úterý 21.3.2023 od 8:00 do 12:00 hod.",
    "Středa 22.3.2023 od 8:00 do 12:00 hod.; od 13:00 do 18:00 hod.",
    "Čtvrtek 23.3.2023 od 8:00 do 12:00 hod.",
    "Pátek 24.3.2023 od 8:00 do 12:00 hod.",
    "Sobota 25.3.2023 od 8:00 do 11:00 hod.",
    "Neděle 26.3.2023 od 8:00 do 11:00 hod.",
  ]),
  p("Známka na popelnice pro rok 2023 musí být vylepena na svoz 28.3.2023."),

  h3("13) Diskuse"),
  ...ul([
    "I.Dvořák: Poděkoval spolku Karhany za masopust.",
    "R.Novotný: Od kdy se budou zhasínat světla? Starosta: Na Den země 22.4.2023.",
    "P.Bydžovský: Dá se zhasínat jen část světel? Starosta: Ne, protože historicky se dělalo osvětlení tak, že nejde například nechat svítit světla u hlavní silnice.",
  ]),

  h3("14) Usnesení a závěr"),
  p("Zastupitelstvo obce bylo ukončeno v 20:07 hod."),

  p("Datum pořízení zápisu: 24.3.2023"),
  p("Ověřovatelé zápisu a starosta obce, podepsáno v listinné podobě."),
  h4("Přílohy"),
  ...nl([
    "Svolání zastupitelstva obce",
    "Prezenční listina zastupitelů",
    "Prezenční listina občanů",
  ]),
];

async function run() {
  const r = await publishZapis({
    cislo: "1",
    rok: "2023",
    isoDate: "2023-03-16",
    dateLabel: "16. 3. 2023",
    fullDateDot: "16.3.2023",
    pdfPath: "scripts/zapisy-pdf/zapis-2023-1.pdf",
    transcript,
  });
  console.log("OK", r.docId, "blocks", r.blocks);
}
run().catch((e) => { console.error(e); process.exit(1); });
