/* eslint-disable no-console */
import { h3, h4, h5, p, vote, nl, ul, publishZapis, type Block } from "../zapis-lib";

const V7 = "PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )";

const transcript: Block[] = [
  h4("Přítomni"),
  p("Aleš Papoušek, Jaroslav Mixa, Tomáš Kratochvíl, Jana Laboutková, Petr Dub, Martin Jiřička, Lucie Maršíková"),
  h4("Omluveni"),
  p("Šárka Dušová, Aleš Kozel"),

  h3("1) Zahájení, přivítání přítomných, konstatování přítomnosti"),
  p("Starosta konstatoval, že zasedání bylo svoláno dne 28.5.2026, bylo vyvěšeno na úřední desce obecního úřadu, tj. tedy nejméně 7 dní před zasedáním. Bylo tedy svoláno řádně a včas v souladu se zákonem o obcích v platném znění. Starosta konstatoval, že podle prezenční listiny je přítomno 7 členů zastupitelstva, tedy nadpoloviční většina členů zastupitelstva. K předchozímu zápisu nebyly vzneseny námitky."),
  h5("Určení zapisovatele"),
  p("Zápisem zasedání zastupitelstva obce byla pověřena Ing. Alena Kratochvílová."),

  h3("2) Volba návrhové komise a ověřovatelů zápisu"),
  p("Starosta přednesl návrh návrhové komise a ověřovatelů zápisu."),
  h5("Návrh"),
  p("ZO schvaluje návrhovou komisi ve složení: Jana Laboutková, Jaroslav Mixa."),
  h5("Návrh"),
  p("ZO schvaluje ověřovatele zápisu ve složení Petr Dub, Tomáš Kratochvíl."),
  vote(V7),

  h3("3) Schválení programu"),
  p("Starosta přečetl program."),
  ...nl([
    "Zahájení",
    "Volba návrhové komise a ověřovatelů zápisu",
    "Schválení programu",
    "Závěrečný účet obce Krhanice pro rok 2025 a Závěrečné účty svazku obcí pro rok 2025",
    "Zpráva finančního výboru o kontrole hospodaření obce Krhanice za rok 2025; Zpráva o výsledcích veřejnosprávních kontrol hospodaření Mateřské školy Krhanice a Základní školy Krhanice za rok 2025",
    "Schválení účetní závěrky obce Krhanice za rok 2025; Schválení účetní závěrky Mateřské školy Krhanice a Základní školy Krhanice za rok 2025",
    "Rozpočtové opatření",
    "Zpráva o uplatňování územního plánu Krhanice",
    "Koupě, prodej, pronájem",
    "Obecně závazné vyhlášky: noční klid",
    "Různé",
    "Diskuse",
    "Závěr",
  ]),
  p("Starosta: Má někdo návrh na změnu nebo doplnění programu?"),
  h5("Návrh"),
  p("ZO schvaluje program zasedání zastupitelstva obce."),
  vote(V7),

  h3("4) Závěrečný účet obce Krhanice pro rok 2025 a Závěrečné účty svazku obcí"),
  p("Starosta seznámil se Závěrečným účtem obce Krhanice pro rok 2025."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Závěrečný účet obce Krhanice za rok 2025 a dává souhlas s celoročním hospodařením, a to bez výhrad."),
  vote(V7),

  h4("DSO Bene-Bus; Týnecko-svazek obcí; Posázavský vodovod – dobrovolný svazek obcí"),
  p("Informace starosty:"),
  p("DSO BENE-BUS: Byl nám předložen návrh Závěrečného účtu za rok 2025 a Zpráva o výsledku přezkoumání hospodaření za rok 2025. Vyvěšeno dne 18.5.2026. Schvalující orgán – valná hromada svazku."),
  p("TÝNECKO-SVAZEK OBCÍ: Byl nám předložen návrh Závěrečného účtu za rok 2025 a Zpráva o výsledku přezkoumání hospodaření za rok 2025. Vyvěšeno dne 25.3.2026. Schvalující orgán – valná hromada svazku."),
  p("SPOLEČNÁ VODA D.S.O.: Byl nám předložen návrh Závěrečného účtu za rok 2025 a Zpráva o výsledku přezkoumání hospodaření za rok 2025. Vyvěšeno dne 1.6.2026. Schvalující orgán – správní rada členů."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí Závěrečný účet dobrovolného svazku obcí BENE-BUS za rok 2025 a Zprávu o výsledku přezkoumání hospodaření za rok 2025 dobrovolného svazku obcí BENE-BUS."),
  h5("Návrh"),
  p("ZO bere na vědomí Závěrečný účet Týnecko-svazek obcí za rok 2025 a Zprávu o výsledku přezkoumání hospodaření za rok 2025 Týnecko – svazek obcí."),
  h5("Návrh"),
  p("ZO bere na vědomí Závěrečný účet Společná voda d.s.o. za rok 2025 a Zprávu o výsledku přezkoumání hospodaření za rok 2025 Společná voda d.s.o."),

  h3("5) Zpráva finančního výboru o kontrole hospodaření obce Krhanice za rok 2025; Zpráva o výsledcích veřejnosprávních kontrol hospodaření Mateřské školy Krhanice a Základní školy Krhanice za rok 2025"),
  p("Předseda finančního výboru Petr Dub seznámil s kontrolou hospodaření obce Krhanice za rok 2025 ze dne 6.5.2026. A dále seznámil s proběhlými veřejnosprávními kontrolami hospodaření příspěvkových organizací Mateřské školy Krhanice a Základní školy Krhanice. Kontroly proběhly dne 6.5.2026."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí zprávu finančního výboru o kontrole hospodaření obce Krhanice za rok 2025 ze dne 6.5.2026."),
  h5("Návrh"),
  p("ZO bere na vědomí protokoly o průběhu a výsledcích veřejnosprávních kontrol příspěvkových organizací Základní škola Krhanice a Mateřská škola Krhanice za rok 2025 ze dne 6.5.2026."),

  h3("6) Schválení účetní závěrky obce Krhanice za rok 2025; Schválení účetní závěrky Mateřské školy Krhanice a Základní školy Krhanice za rok 2025"),
  p("Starosta seznámil s průběhem procesu schvalování účetní závěrky a dále přečetl Protokoly o schvalování účetní závěrky za rok 2025 pro obec Krhanice, pro Mateřskou školu Krhanice a Základní školu Krhanice."),
  p("Starosta přečetl „Protokol o schvalování účetní závěrky za rok 2025 obce Krhanice“."),
  p("Starosta přečetl „Protokol o schvalování účetní závěrky za rok 2025 příspěvkové organizace Mateřská škola Krhanice, okres Benešov“."),
  p("Starosta přečetl „Protokol o schvalování účetní závěrky za rok 2025 příspěvkové organizace Základní škola Krhanice, okres Benešov“."),
  p("Zastupitelé se postupně každý za sebe vyjádřili do protokolu k účetním závěrkám obce a příspěvkových organizací."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje účetní závěrku obce Krhanice za rok 2025; schvalovaná účetní závěrka poskytuje věrný a poctivý obraz předmětu účetnictví a finanční situace účetní jednotky."),
  vote(V7),
  h5("Návrh"),
  p("ZO schvaluje účetní závěrku příspěvkové organizace Mateřská škola Krhanice, okres Benešov za rok 2025; schvalovaná účetní závěrka poskytuje věrný a poctivý obraz předmětu účetnictví a finanční situace účetní jednotky."),
  vote(V7),
  h5("Návrh"),
  p("ZO schvaluje účetní závěrku příspěvkové organizace Základní škola Krhanice, okres Benešov za rok 2025; schvalovaná účetní závěrka poskytuje věrný a poctivý obraz předmětu účetnictví a finanční situace účetní jednotky."),
  vote(V7),
  h5("Návrh"),
  p("ZO schvaluje výsledek hospodaření ve schvalovacím řízení za rok 2025 obce Krhanice ve výši 14 266 797,32 Kč a jeho převod na účet 432 výsledek hospodaření předchozích účetních období."),
  vote(V7),
  h5("Návrh"),
  p("ZO schvaluje hospodářský výsledek příspěvkové organizace Základní škola Krhanice za rok 2025 ve výši 51 971,67 Kč a jeho příděl do rezervního fondu."),
  vote(V7),
  h5("Návrh"),
  p("ZO schvaluje hospodářský výsledek příspěvkové organizace Mateřská škola Krhanice za rok 2025 ve výši 2 140 Kč a jeho příděl do rezervního fondu."),
  vote(V7),
  h5("Návrh"),
  p("ZO schvaluje Protokol o schvalování účetní závěrky za rok 2025 obce Krhanice."),
  vote(V7),
  h5("Návrh"),
  p("ZO schvaluje Protokol o schvalování účetní závěrky za rok 2025 příspěvkové organizace Mateřská škola Krhanice, okres Benešov."),
  vote(V7),
  h5("Návrh"),
  p("ZO schvaluje Protokol o schvalování účetní závěrky za rok 2025 příspěvkové organizace Základní škola Krhanice, okres Benešov."),
  vote(V7),

  h3("7) Rozpočtové opatření"),
  p("Předseda finančního výboru Petr Dub seznámil s rozpočtovým opatřením č. 2/2026."),
  h5("Rozprava"),
  p("L.Maršíková: Byla na dopravní hřiště nějaká poptávka od rodičů? T.Kratochvíl: Poptávka byla především od rodičů dětí, které chodí do mateřské školy."),
  p("L.Maršíková: Byla oslovena jen jediná firma, částka se mi zdá dost vysoká. Proč byla oslovena zrovna tato firma? Starosta: Firma byla doporučena starostou Týnce a jeho zaměstnancem, který podobné stavby řešil."),
  p("I.Dvořák: Navrhl udělat anketu mezi občany."),
  p("J.Steinhüblová: Dopravní hřiště už chtěla minulá paní ředitelka."),
  p("Proběhla diskuse bez přijetí závěrů."),
  p("I.Dvořák: Dotaz na záměr s pozemkem na Rafandě? Starosta: Nebude to stavební pozemek, obec ho bude využívat např. na uskladnění materiálu."),
  h5("Návrh"),
  p("ZO schvaluje navýšení provozního příspěvku Základní škole Krhanice ve výši 50 000 Kč (příspěvek na provoz ZŠ Krhanice – vybavení jídelna)."),
  vote(V7),
  h5("Návrh"),
  p("ZO schvaluje navýšení příspěvku na financování nepedagogických pracovníků a ostatních neinvestičních výdajů Základní školy Krhanice ve výši 214 000 Kč (na zajištění plavání a v souvislosti se změnou tabulek na platy od 1.4.2026)."),
  vote(V7),
  h5("Návrh"),
  p("ZO schvaluje navýšení příspěvku na financování nepedagogických pracovníků a ostatních neinvestičních výdajů Mateřské školy Krhanice ve výši 17 000 Kč (v souvislosti se změnou tabulek na platy od 1.4.2026)."),
  vote(V7),
  h5("Návrh"),
  p("ZO schvaluje rozpočtové opatření č. 2/2026."),
  vote("PRO ( 6 ) – PROTI ( 1 - Maršíková ) – ZDRŽEL SE ( 0 )"),
  p("Starosta seznámil s rozpočtovými opatřeními dobrovolných svazků obcí:"),
  ...ul(["Bene-Bus č. 1/2026", "Společná voda d.s.o. č. 1/2026 a 2/2026."]),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí rozpočtové opatření č. 1/2026 Bene-Bus."),
  h5("Návrh"),
  p("ZO bere na vědomí rozpočtové opatření č. 1/2026 a č. 2/2026 Společná voda d.s.o."),

  h3("8) Zpráva o uplatňování územního plánu Krhanice"),
  p("Informace starosty: Na minulém zastupitelstvu byla předložena Zpráva o uplatňování územního plánu, kterou zastupitelé vzali na vědomí. Tato Zpráva byla poté veřejnou vyhláškou postoupena dotčeným orgánům a k připomínkám veřejnosti."),
  p("Ve Zprávě bylo vyhodnoceno, jak se naplňuje územní plán z hlediska reálné zastavěnosti za 10/2019 – 01/2026. Zpráva obsahovala i požadavky na změnu územního plánu."),
  h5("Nyní byla vypracována"),
  ...ul([
    "Důvodová zpráva, výsledek vyhodnocení projednání návrhu Zprávy o uplatňování územního plánu Krhanice obsahující zadání změny č. 2 územního plánu Krhanice s vyhodnocením stanovisek, připomínek, požadavků a podnětů. Byla podána jedna připomínka/ podnět.",
    "Návrh „Územního plánu Krhanice s prvky regulačního plánu, Zpráva o uplatňování za uplynulé období 10/2019 - 01/2026“ – upraven ke schválení červen 2026",
  ]),
  h5("Odůvodnění"),
  p("Obecní úřad Krhanice, jako pořizovatel příslušný podle § 46 odst. 1 písm. c) zákona č. 283/2021 Sb., stavební zákon dokončil práce spojené s pořizováním zprávy o uplatňování územního plánu, o jejímž pořízení rozhodlo zastupitelstvo obce."),
  p("Pořizovatel prostřednictvím osoby splňující kvalifikační požadavky pro výkon územně plánovací činnosti po zákonem stanovených lhůtách obdržené písemnosti v součinnosti s určeným zastupitelem vyhodnotil a návrh zprávy obsahující návrh zadání změny č. 2 upravil."),
  p("V souladu s ustanovením § 107 odst. 3 stavebního zákona Obecní úřad Krhanice předkládá zastupitelstvu obce upravený návrh Územního plánu Krhanice s prvky regulačního plánu, Zprávu o uplatňování za uplynulé období 10/2019 – 01/2026 ke schválení."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí „Důvodovou zprávu, výsledek vyhodnocení projednání Zprávy o uplatňování Územního plánu Krhanice obsahující zadání změny č. 2 územního plánu Krhanice s vyhodnocením stanovisek, připomínek, požadavků a podnětů“."),
  h5("Návrh"),
  p("ZO projednalo výslednou verzi „Územního plánu Krhanice s prvky regulačního plánu, Zprávy o uplatňování za uplynulé období 10/2019 – 01/2026“, obsahující zadání změny č. 2, z května 2026."),
  h5("Návrh"),
  p("ZO schvaluje v souladu s ustanovením § 107 zákona č. 283/2021 Sb., stavební zákon, v platném znění, ve spojení s § 27 stavebního zákona „Územní plán Krhanice s prvky regulačního plánu, Zprávu o uplatňování za uplynulé období 10/2019 – 01/2026“, obsahující zadání změny č. 2, z května 2026, uvedenou v příloze č. 1 tohoto usnesení."),
  vote(V7),

  h3("9) Koupě, prodej, pronájem"),

  ...ul(["pronajmout část pozemku parc. č. 224/4 k.ú. Krhanice o výměře 1 m² pro propagaci činnosti spolku za cenu 1,- Kč/1 m²/rok od 9.6.2026 do 8.6.2030."]),
  p("Informace starosty: Jedná se o žádost spolku Unie rodičů ZŠ Krhanice, který má před školou pozemek na nástěnku – propagace činnosti spolku."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronajmout část pozemku parc. č. 224/4 k.ú. Krhanice o výměře 1 m² pro propagaci činnosti spolku za cenu 1,- Kč/1 m²/rok od 9.6.2026 do 8.6.2030 Unii rodičů ZŠ Krhanice, z.s., IČO 22877177, Krhanice 149, 257 42 Krhanice."),
  vote(V7),

  ...ul(["zřídit věcné břemeno podzemního/nadzemního komunikačního vedení veřejné komunikační sítě a uzavřít Smlouvu o budoucí smlouvě o zřízení služebnosti č. 11010-110319 na pozemcích parc.č. 1972/1, 2109, 2095, 1978/13, 1972/6, 111/2, 1985/12, 1978/6, 224/7, 224/4, 224/25, 224/6, 227/8, 227/7, 224/1, 220/4, 220/3, 244/8, 241/23, 244/10, 241/22, 241/16, 313/40, 312/54, 312/48, 312/53, 312/67 a 1981/1 k.ú. Krhanice s CETIN a.s., IČO 04084063, Českomoravská 2510/19, Libeň, 190 00 Praha 9 na dobu neurčitou za cenu 164 400,- Kč."]),
  p("Informace starosty: Jedná se o pokládce optického kabelu."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje zřídit věcné břemeno podzemního/nadzemního komunikačního vedení veřejné komunikační sítě a uzavřít Smlouvu o budoucí smlouvě o zřízení služebnosti č. 11010-110319 na pozemcích parc.č. 1972/1, 2109, 2095, 1978/13, 1972/6, 111/2, 1985/12, 1978/6, 224/7, 224/4, 224/25, 224/6, 227/8, 227/7, 224/1, 220/4, 220/3, 244/8, 241/23, 244/10, 241/22, 241/16, 313/40, 312/54, 312/48, 312/53, 312/67 a 1981/1 k.ú. Krhanice s CETIN a.s., IČO 04084063, Českomoravská 2510/19, Libeň, 190 00 Praha 9 na dobu neurčitou za cenu 164 400,- Kč."),
  vote(V7),

  ...ul(["pronajmout část pozemku parc. č. 1884/4 k.ú. Krhanice o výměře 92 m² pro zřízení dočasné zahrádky za cenu 15,- Kč/1 m²/rok od 1.8.2026 do 31.7.2030."]),
  p("Informace starosty: Jedná se o žádost Heleny Voldřichové, která má tento pozemek pronajatý a smlouvu jí obnovujeme."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronajmout část pozemku parc. č. 1884/4 k.ú. Krhanice o výměře 92 m² pro zřízení dočasné zahrádky za cenu 15,- Kč/1 m²/rok od 1.8.2026 do 31.7.2030 Heleně Voldřichové, Lamačova 913/33, 152 00 Praha 5."),
  vote(V7),

  ...ul(["pronajmout část pozemku parc. č. 1884/4 k.ú. Krhanice o výměře 40 m² pro zřízení dočasné zahrádky za cenu 15,- Kč/1 m²/rok od 1.10.2026 do 30.9.2030."]),
  p("Informace starosty: Jedná se o žádost Lenky Bačkovské, která má tento pozemek pronajatý a smlouvu jí obnovujeme."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronajmout část pozemku parc. č. 1884/4 k.ú. Krhanice o výměře 40 m² pro zřízení dočasné zahrádky za cenu 15,- Kč/1 m²/rok od 1.10.2026 do 30.9.2030 Mgr. Lence Bačkovské, Nad pískovnou 56, 140 00 Praha 4."),
  vote(V7),

  ...ul(["pronajmout část pozemku parc. č. 1884/4 k.ú. Krhanice o výměře 166 m² pro zřízení dočasné zahrádky za cenu 15,- Kč/1 m²/rok od 1.12.2026 do 30.11.2030."]),
  p("Informace starosty: Jedná se o žádost Lenky Padevětové, která má tento pozemek pronajatý a smlouvu jí obnovujeme."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronajmout část pozemku parc. č. 1884/4 k.ú. Krhanice o výměře 166 m² pro zřízení dočasné zahrádky za cenu 15,- Kč/1 m²/rok od 1.12.2026 do 30.11.2030 Lence Padevětové, Slivenecká 109/31, 150 00 Praha 5."),
  vote(V7),

  ...ul(["pronajmout část pozemku parc. č. 312/19 k.ú. Krhanice o výměře 120 m² pro zřízení dočasné zahrádky za cenu 15,- Kč/1 m²/rok od 1.8.2026 do 31.7.2030."]),
  p("Informace starosty: Jedná se o žádost Davida Modřanského, který má tento pozemek pronajatý a smlouvu mu obnovujeme."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronajmout část pozemku parc. č. 312/19 k.ú. Krhanice o výměře 120 m² pro zřízení dočasné zahrádky za cenu 15,- Kč/1 m²/rok od 1.8.2026 do 31.7.2030 Davidu Modřanskému, Krhanice 70, 257 42 Krhanice."),
  vote(V7),

  ...ul(["pronajmout část pozemku parc. č. 312/19 k.ú. Krhanice o výměře 66 m² pro zřízení dočasné zahrádky za cenu 15,- Kč/1 m²/rok od 1.8.2026 do 31.7.2030."]),
  p("Informace starosty: Jedná se o žádost Davida Richtra, který má tento pozemek pronajatý a smlouvu mu obnovujeme."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronajmout část pozemku parc. č. 312/19 k.ú. Krhanice o výměře 66 m² pro zřízení dočasné zahrádky za cenu 15,- Kč/1 m²/rok od 1.8.2026 do 31.7.2030 Davidu Richtrovi, Krhanice 71, 257 42 Krhanice."),
  vote(V7),

  ...ul(["pronajmout část pozemku parc. č. 312/19 k.ú. Krhanice o výměře 50 m² pro zřízení dočasné zahrádky za cenu 15,- Kč/1 m²/rok od 9.6.2026 do 8.6.2030."]),
  p("Informace starosty: Jedná se o žádost Lucie Richtrové, která má tento pozemek pronajatý a smlouvu jí obnovujeme."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronajmout část pozemku parc. č. 312/19 k.ú. Krhanice o výměře 50 m² pro zřízení dočasné zahrádky za cenu 15,- Kč/1 m²/rok od 9.6.2026 do 8.6.2030 Lucii Richtrové, Krhanice 71, 257 42 Krhanice."),
  vote(V7),

  ...ul(["pronajmout část pozemku parc. č. 312/19 k.ú. Krhanice o výměře 105 m² pro zřízení dočasné zahrádky za cenu 15,- Kč/1 m²/rok od 9.6.2026 do 8.6.2030 a pronajmout část pozemku parc. č. 312/19 k.ú. Krhanice o výměře 7,5 m² pro uložení movitých věcí za cenu 15,- Kč/1 m²/rok od 9.6.2026 do 8.6.2030."]),
  p("Informace starosty: Jedná se o žádost Jaroslava Mixy."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronajmout část pozemku parc. č. 312/19 k.ú. Krhanice o výměře 105 m² pro zřízení dočasné zahrádky za cenu 15,- Kč/1 m²/rok od 9.6.2026 do 8.6.2030 a pronajmout část pozemku parc. č. 312/19 k.ú. Krhanice o výměře 7,5 m² pro uložení movitých věcí za cenu 15,- Kč/1 m²/rok od 9.6.2026 do 8.6.2030 Jaroslavu Mixovi, Krhanice 72, 257 42 Krhanice."),
  vote("PRO ( 6 ) – PROTI ( 0 ) – ZDRŽEL SE ( 1 - Mixa )"),

  ...ul(["pronajmout část pozemku parc. č. 312/8 k.ú. Krhanice o výměře 11,25 m² pro umístění vozíku za auto za cenu 15,- Kč/1 m²/rok od 9.6.2026 do 8.6.2030."]),
  p("Informace starosty: Jedná se o žádost Jaroslava Mixy."),
  h5("Rozprava"),
  p("L.Maršíková: Navrhovala vynechat tento bod a popovídat si se zastupiteli, zda je žádoucí zpoplatňovat parkování na obecním pozemku. J.Mixa: Nemám problém nájem zaplatit."),
  h5("Návrh"),
  p("ZO schvaluje pronajmout část pozemku parc. č. 312/8 k.ú. Krhanice o výměře 11,25 m² pro umístění vozíku za auto za cenu 15,- Kč/1 m²/rok od 9.6.2026 do 8.6.2030 Jaroslavu Mixovi, Krhanice 72, 257 42 Krhanice."),
  vote("PRO ( 5 ) – PROTI ( 0 ) – ZDRŽEL SE ( 2 – Maršíková, Mixa )"),

  ...ul(["prodat oddělenou část pozemku parc. č. 403/8 k.ú. Krhanice o výměře 7 000 m², který vznikne oddělením z pozemku parc. č. 403/2 k.ú. Krhanice na základě geometrického plánu č. 1177-114/2024 za celkovou cenu 321 680 Kč, stanovenou na základě znaleckého posudku číslo 5088/69/26. Do kupní ceny bude připočten výdaj na znalecký posudek ve výši 4 000 Kč. Vklad na katastr nemovitostí hradí kupující a koupit oddělenou část pozemku parc.č. 361/3 k.ú. Krhanice o výměře 7 000 m², který vznikne oddělením z pozemku parc.č. 361/1 k.ú. Krhanice na základě geometrického plánu č. 1177-114/2024 za celkovou cenu 303 590 Kč, stanovenou na základě znaleckého posudku číslo 5089/70/26. Do kupní ceny bude připočten výdaj na znalecký posudek ve výši 4 000 Kč. Vklad na katastr nemovitostí hradí kupující."]),
  p("Informace starosty: Jedná se o vzájemný prodej části pozemků. Velikosti jsou 7000 m2. Cena oddělených pozemků je dle znaleckých posudků."),
  h5("Rozprava"),
  p("L.Maršíková: Předpokladem vzájemného prodeje bylo vybudování přírodního valu, aby prach z lomu nešel na Krhanice. Starosta: Lom už odstranil val z naveženého materiálu, ze kterého se prášilo do obce, zapustil drtičku a používá skrápění."),
  h5("Návrh"),
  p("ZO schvaluje prodat oddělenou část pozemku parc. č. 403/8 k.ú. Krhanice o výměře 7 000 m², který vznikne oddělením z pozemku parc. č. 403/2 k.ú. Krhanice na základě geometrického plánu č. 1177-114/2024 za celkovou cenu 321 680 Kč, stanovenou na základě znaleckého posudku číslo 5088/69/26 kupujícímu NATY TERRA, s.r.o., IČO 09462741, Žitavského 1178, Zbraslav, 156 00 Praha 5. Do kupní ceny bude připočten výdaj na znalecký posudek ve výši 4 000 Kč. Vklad na katastr nemovitostí hradí kupující a koupit oddělenou část pozemku parc.č. 361/3 k.ú. Krhanice o výměře 7 000 m², který vznikne oddělením z pozemku parc.č. 361/1 k.ú. Krhanice na základě geometrického plánu č. 1177-114/2024 za celkovou cenu 303 590 Kč, stanovenou na základě znaleckého posudku číslo 5089/70/26 od prodávajícího NATY TERRA, s.r.o., IČO 09462741, Žitavského 1178, Zbraslav, 156 00 Praha 5. Do kupní ceny bude připočten výdaj na znalecký posudek ve výši 4 000 Kč. Vklad na katastr nemovitostí hradí kupující."),
  vote("PRO ( 6 ) – PROTI ( 0 ) – ZDRŽEL SE ( 1 - Maršíková )"),

  ...ul(["zřídit věcné břemeno kabelového vedení NN a skříně a uzavřít Smlouvu o zřízení věcného břemene – služebnosti č. IV-12-6033714/1 Krhanice na pozemcích parc.č. 38/6, 1972/1 a 1977 k.ú. Krhanice s ČEZ Distribuce, a.s., IČO 24729035, DIČ CZ24729035, se sídlem Děčín IV Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 68 378 Kč."]),
  p("Informace starosty: V minulosti byla schválena smlouva o smlouvě budoucí. Katastr provedl změnu v pozemcích v dané lokalitě. Musíme schválit smlouvu s pozemky dle katastru."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje zřídit věcné břemeno kabelového vedení NN a skříně a uzavřít Smlouvu o zřízení věcného břemene – služebnosti č. IV-12-6033714/1 na pozemcích parc.č. 38/6, 1972/1 a 1977 k.ú. Krhanice s ČEZ Distribuce, a.s., IČO 24729035, DIČ CZ24729035, se sídlem Děčín IV Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 68 378 Kč."),
  vote(V7),

  ...ul(["zřídit věcné břemeno kabelového vedení NN a uzavřít Smlouvu o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby č. IV-12-6035954NB01 na pozemcích parc.č. 1435/20 a 1435/49 k.ú. Krhanice s ČEZ Distribuce, a.s., IČO 24729035, DIČ CZ24729035, se sídlem Děčín IV Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 100 500 Kč na umístění zařízení distribuční soustavy - kabelové vedení NN."]),
  p("Informace starosty: Jedná se o pokládku elektrického kabelu na Rafandě."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje zřídit věcné břemeno kabelového vedení NN a uzavřít Smlouvu o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby č. IV-12-6035954NB01 na pozemcích parc.č. 1435/20 a 1435/49 k.ú. Krhanice s ČEZ Distribuce, a.s., IČO 24729035, DIČ CZ24729035, se sídlem Děčín IV Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 100 500 Kč na umístění zařízení distribuční soustavy - kabelové vedení NN."),
  vote(V7),

  h4("Parcelace Černý – dělení a scelení pozemků"),
  p("Informace starosty: Z pozemků parc.č. 162/2 a 162/5 k.ú. Krhanice se oddělí části, které přináleží komunikaci na pozemku parc.č. 1978/13 k.ú. Krhanice, který je ve vlastnictví obce Krhanice. Budeme kupovat za 1000,- Kč/m². Dělení pozemku bylo také projednáno a schváleno na Městském úřadě Týnec nad Sázavou. Na těchto pozemcích bude obec budovat chodník."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje koupit pozemek oddělenou část pozemku parc.č. 1978/13 k.ú. Krhanice, a to díl „a“ o výměře 23 m² a díl „b“ o výměře 25 m², které budou sloučeny do pozemku parc.č. 1978/13 k.ú. Krhanice na základě geometrického plánu č. 1321/59/2025 za cenu 1 000,- Kč/1 m² od Tomáše Černého a PhDr. Dany Černé, Jana Zajíce 2000, 258 01 Vlašim. Náklady spojené s odkoupením bude hradit obec (geometrický plán, vklad na katastr, ...)."),
  vote(V7),

  h4("Odkoupení pozemku 148/7 k.ú. Krhanice a oddělené části pozemku z p.č. 148/32 k.ú. Krhanice"),
  p("Informace starosty: Dne 26.8.2025 jsme na zastupitelstvu schválili záměr odkoupení části pozemku parc.č. 148/32 k.ú. Krhanice o výměře cca 2000 m² a pozemku parc.č. 148/7 k.ú. Krhanice o výměře 162 m² za cenu 35 Kč/1 m². Náklady spojené s odkoupením bude hradit obec (geometrický plán, vklad na katastr, ...). Nyní je vypracován již geometrický plán č. 1316-5635/2025, kde došlo k upřesnění výměry části odděleného pozemku parc.č. 148/32 k.ú. Krhanice. Dělení pozemku bylo také projednáno a schváleno na Městském úřadě Týnec nad Sázavou."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje koupit pozemek parc. č. 148/7 k.ú. Krhanice o výměře 162 m² a koupit oddělenou část pozemku parc.č. 148/52 k.ú. Krhanice o výměře 1 977 m², který vznikne oddělením z pozemku parc.č. 148/32 k.ú. Krhanice na základě geometrického plánu č. 1316/5635/2025 za cenu 35,- Kč/1m² od Jana Kadeřábka, Krhanice č.p. 1, 257 42 Krhanice. Náklady spojené s odkoupením bude hradit obec (geometrický plán, vklad na katastr, ...)."),
  vote(V7),

  h3("10) Obecně závazné vyhlášky: noční klid"),
  p("Informace místostarosty o návrhu vyhlášky."),
  p("Noční klid – aktualizace termínu jedné akce a doplnění jedné akce."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Obecně závaznou vyhlášku obce Krhanice o nočním klidu."),
  vote(V7),

  h3("11) Různé"),

  h4("Smlouva č. 7251300013 o poskytnutí podpory ze Státního fondu životního prostředí České republiky"),
  p("Starosta informoval o dalším postupu v rámci projektu „Fotovoltaika na střeše klubovny zázemí víceúčelového hřiště v Krhanicích“, na který jsme získali dotaci ve výši 303 283,33 Kč ze Státního fondu životního prostředí České republiky v rámci Programu financovaného z prostředků Modernizačního fondu – nyní se bude uzavírat Smlouva o poskytnutí podpory ze SFŽP."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy č. 7251300013 o poskytnutí podpory ze Státního fondu životního prostředí České republiky pro projekt „Fotovoltaika na střeše klubovny zázemí víceúčelového hřiště v Krhanicích“ se Státním fondem životního prostředí České republiky v rámci Programu financovaného z prostředků Modernizačního fondu a schvaluje přijetí dotace ve výši 303 283,33 Kč."),
  vote(V7),
  h5("Návrh"),
  p("ZO pověřuje starostu obce uzavřením Smlouvy č. 7251300013 o poskytnutí podpory ze Státního fondu životního prostředí České republiky pro projekt „Fotovoltaika na střeše klubovny zázemí víceúčelového hřiště v Krhanicích“ se Státním fondem životního prostředí České republiky v rámci Programu financovaného z prostředků Modernizačního fondu."),
  vote(V7),

  h4("FVE klubovna – dodatek č. 1 ke SoD"),
  p("Starosta informoval o Dodatku č. 1 ke smlouvě o dílo č. SoD/01/2026 ze dne 30.3.2026 pro FVE na klubovně v zázemí víceúčelového hřiště."),
  p("Předmětem dodatku je doplnění bližší specifikace instalovaných fotovoltaických panelů jako nového bodu č. 3 a 4. do čl. IV."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Dodatku č. 1 ke Smlouvě o dílo č. SoD/01/2026 Fotovoltaika na střeše klubovny zázemí víceúčelového hřiště v Krhanicích s firmou VA ELECTRICS s.r.o., IČO: 23491213, se sídlem Okružní 871/6, 500 03 Hradec Králové."),
  vote(V7),
  h5("Návrh"),
  p("ZO pověřuje starostu obce podpisem Dodatku č. 1 ke Smlouvě o dílo č. SoD/01/2026 Fotovoltaika na střeše klubovny zázemí víceúčelového hřiště v Krhanicích s firmou VA ELECTRICS s.r.o., IČO: 23491213, se sídlem Okružní 871/6, 500 03 Hradec Králové."),
  vote(V7),

  h4("Vodné"),
  p("Starosta seznámil se zaslanou aktualizací ceny vodného od 1.7.2026 od VHS Benešov, a.s. Navýšení ceny je v důsledku nenadálého cenového skoku v oblasti pohonných hmot, chemikálií a provozních nákladů 2026."),
  p("Stávající cena vodného: 1.1-30.6.2026: PV = 84,07 Kč vč. DPH"),
  p("Nová cena vodného od 1.7.2026: PV = 84,45 Kč vč. DPH"),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje cenu vodného od 1.7.2026 v částce 84,45 Kč vč. DPH."),
  vote(V7),

  h4("Týnecko-svazek obcí"),
  p("Starosta seznámil se Zápisem č. 2026/1 z valné hromady „Týnecko-svazek obcí“ ze dne 20.5.2026, kdy došlo k rozhodnutí Valné hromady Týnecko-svazek obcí o zrušení svazku s likvidací a to ke dni 31.5.2026."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí rozhodnutí Valné hromady Týnecko-svazek obcí o zrušení svazku s likvidací, a to ke dni 31.5.2026."),

  h4("Konkurzní řízení ředitel/ředitelka Základní školy Krhanice"),
  p("Starosta obce seznámil s výběrovým řízením na ředitele/ředitelku Základní školy. Do konkursního řízení se přihlásili 3 uchazeči. Výběrové řízení bylo dvoukolové."),
  p("Konkurzní komise byla složena z:"),
  ...ul([
    "2 členové za zřizovatele",
    "1 člen za Českou školní inspekci",
    "1 člen za Krajský úřad Středočeského kraje",
    "1 člen jako odborník v oblasti organizace a řízení ve školství",
    "1 člen jako odborník v oblasti státní správy",
    "1 člen za pedagogy Základní školy Krhanice",
    "1 člen jako zástupce za Školskou radu při ZŠ Krhanice",
  ]),
  p("V 1.kole konkurzní komise posuzovala, zda:"),
  ...nl([
    "jednotlivé obálky přihlášek do konkursu byly doručeny v termínu",
    "jednotlivé obálky přihlášek do konkursu byly v neporušeném stavu",
    "požadované dokumenty měly formální správnost a byly úplné",
  ]),
  p("Všichni tři uchazeči splnili všechny požadavky."),
  p("Byli pozváni na vlastní konkursní řízení, které proběhlo formou řízeného rozhovoru. Vlastního konkursního řízení se pak účastnili 2 uchazeči."),
  p("Na vlastním konkursním řízení byly uchazečům kladeny zejména dotazy z oblastí školské problematiky a řízení základní školy."),
  p("Jednotliví členové komise posuzovali vhodnost jednotlivých uchazečů na pozici ředitele/ředitelky základní školy, oba uchazeči uspěli. Poté členové konkursní komise stanovili jednotlivé pořadí uchazečů."),
  p("Na prvním místě se umístila Mgr. Bc. Věra Ráblová."),
  p("Tato uchazečka byla doporučena zřizovateli jako nejlepší uchazeč na pozici ředitelky Základní školy Krhanice."),
  p("Zřizovatel, starosta obce Krhanice, jmenoval ředitelkou Základní školy Krhanice Mgr. Bc. Věru Ráblovou s účinností od 1.7.2026."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí jmenování Mgr. Bc. Věry Ráblové, ředitelkou Základní školy Krhanice, okres Benešov s účinností od 1.7.2026."),

  h4("Lavička Aktivních Krhanic"),
  h5("Závěr z jednání zastupitelů"),
  p("Uzavřeli jsme záležitost ohledně nesrovnalostí lavičky u tůní u spolku Aktivní Krhanice, aby tato situace nevedla ke špatnému precedentu. Pouze si shrneme, jaký byl postup v této záležitosti."),
  p("Na základě e-mailové komunikace byla stanovena dohoda, jakým způsobem bude lavička realizována. Tato dohoda nebyla respektována a lavička byla pevně spojena se zemí. V důsledku toho se věc dostala do řešení ze strany starosty obce se spolkem Aktivní Krhanice. Následně se tato záležitost dostala na zastupitelstvo obce."),
  p("Zastupitelé po seznámení s materiály konstatují, že bylo jednáno v rozporu s vyjádřením obce, ale následně byla situace napravena a lavička nyní vyhovuje dohodám a stanoveným pravidlům."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),

  h4("Veřejné prostranství v obci"),
  p("Starosta obce přečetl právní posouzení záborů obecních prostranství v návaznosti na akci Masopustní veselice 2026, kdy byl mimo jiné neoprávněně zabrán k akci pozemek obce Krhanice bez souhlasu obce. Závěr: V případě společenské akce, v podkladech označované jako „Masopustní veselice 2026 – hlavní pořadatel Karhany, z.s.“, byl pozemek p.č. 2024 v k.ú. Krhanice, LV 10001 užíván neoprávněně, neboť povolený rozsah záboru byl zcela závazný a nemohl být jednostranně rozšiřován/navyšován. A to bez ohledu na skutečnost jaký typ společenské akce se konal."),
  h5("Rozprava"),
  p("I.Dvořák: Kolik stála tato zpráva? Starosta: Byla zadarmo."),

  h3("12) Diskuse"),
  ...ul([
    "I.Dvořák: Jaký bude další postup u územního plánu? Starosta: Seznámím paní Bechyňovou s přijatými usneseními. Je teď na dovolené.",
    "L.Maršíková: Ráda by oslovila představitele spolků v Krhanicích, zastupitele a občany k dárcovství kostní dřeně. Osvěta by proběhla na akci Zažít Krhanice jinak.",
    "I.Dvořák: V jaké fázi je zpomalovací ostrůvek na příjezdu od statku do Krhanic? Starosta: Stavební povolení bylo vydáno. Tato akce má návaznost na jinou akci Na Žlabech.",
    "I.Zahrádková: Dotaz: Víme kolik dětí bude do budoucna v mateřské škole? Proběhla diskuse k této otázce bez přijetí závěrů.",
    "H.Strnadová: Dotaz na řešení dopravy před mateřskou a základní školou. Rodiče vozí děti do školy auty. Prostředí je nebezpečné pro děti, které chodí pěšky. Proběhla diskuse o možnostech řešení bez přijatých závěrů.",
    "J.Bydžovská: Připomínka k masopustu. Ocení informace, jak postupovat při získání dotace, pokud se akce koná na veřejných i soukromých pozemcích. Starosta: Udělám jednání a pak navrhneme řešení.",
  ]),

  h3("13) Závěr"),
  p("Zastupitelstvo obce bylo ukončeno v 19:47 hod."),

  p("Datum pořízení zápisu: 17.6.2026"),
  h4("Přílohy"),
  ...nl(["Svolání zastupitelstva obce", "Prezenční listina zastupitelů", "Prezenční listina občanů", "Zpráva o uplatňování územního plánu Krhanice"]),
];

async function run() {
  const r = await publishZapis({
    cislo: "2",
    rok: "2026",
    isoDate: "2026-06-08",
    dateLabel: "8. 6. 2026",
    fullDateDot: "8.6.2026",
    pdfPath: "scripts/zapisy-pdf/zapis-2026-2.pdf",
    transcript,
  });
  console.log("OK", r.docId, "blocks", r.blocks);
}
run().catch((e) => { console.error(e); process.exit(1); });
