/* eslint-disable no-console */
// Faithful, visually-transcribed minutes of Zápis č. 4/2025 (26.8.2025).
// Read page-by-page from the official PDF (text layer is corrupt). Structure
// follows the approved golden sample scripts/build-zapis-2026-1.ts.
import { h3, h4, h5, p, vote, nl, ul, publishZapis, type Block } from "../zapis-lib";

const V8 = "PRO ( 8 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )";

const transcript: Block[] = [
  h4("Přítomni"),
  p("Aleš Papoušek, Jaroslav Mixa, Tomáš Kratochvíl, Jana Laboutková, Petr Dub, Aleš Kozel, Lucie Maršíková, Šárka Dušová"),
  h4("Omluveni"),
  p("Martin Jiřička"),

  h3("1) Zahájení, přivítání přítomných, konstatování přítomnosti"),
  p("Starosta konstatoval, že zasedání bylo svoláno dne 18.8.2025, bylo vyvěšeno na úřední desce obecního úřadu, tj. tedy nejméně 7 dní před zasedáním. Bylo tedy svoláno řádně a včas v souladu se zákonem o obcích v platném znění. Starosta konstatoval, že podle prezenční listiny je přítomno 8 členů zastupitelstva, tedy nadpoloviční většina členů zastupitelstva."),
  h5("Určení zapisovatele"),
  p("Zápisem zasedání zastupitelstva obce byla pověřena Ing. Alena Kratochvílová."),

  h3("2) Volba návrhové komise a ověřovatelů zápisu"),
  p("Starosta přednesl návrh návrhové komise a ověřovatelů zápisu."),
  h5("Návrh"),
  p("ZO schvaluje návrhovou komisi ve složení: Jana Laboutková, Jaroslav Mixa."),
  h5("Návrh"),
  p("ZO schvaluje ověřovatele zápisu ve složení Aleš Kozel, Petr Dub."),
  vote(V8),

  h3("3) Schválení programu"),
  p("Starosta přečetl program."),
  ...nl(["Zahájení", "Volba návrhové komise a ověřovatelů zápisu", "Schválení programu", "Rozpočtové opatření", "Koupě, prodej, pronájem", "Různé", "Diskuse", "Závěr"]),
  p("Starosta: Má někdo návrh na změnu nebo doplnění programu?"),
  h5("Návrh"),
  p("ZO schvaluje program zasedání zastupitelstva obce."),
  vote(V8),

  h3("4) Rozpočtové opatření"),
  h4("Rozpočtové opatření č. 4/2025"),
  p("Předseda finančního výboru Petr Dub seznámil s rozpočtovým opatřením č. 4/2025."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje rozpočtové opatření č. 4/2025."),
  vote("PRO ( 7 ) – PROTI ( 1 – Maršíková ) – ZDRŽEL SE ( 0 )"),

  h3("5) Koupě, prodej, pronájem"),
  ...ul(["pronajmout části pozemků parc. č. 132/1, 1988 a 128/10 k.ú. Krhanice o celkové výměře 165 m² dle přílohy od 1.11.2025 na dobu 4 let za cenu 15,- Kč/m²."]),
  p("Informace starosty: Pokračování v pronájmu – Kalousek David."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronájem části pozemků parc. č. 132/1, 1988 a 128/10 k.ú. Krhanice o celkové výměře 165 m² dle přílohy a uzavření smlouvy, a to od 1.11.2025 na dobu 4 let za cenu 15,- Kč/m² Davidu Kalouskovi, Krhanice č.ev. 112, 257 42 Krhanice."),
  vote(V8),
  ...ul(["pronajmout části pozemků parc. č. 132/1, 1988 a 128/10 k.ú. Krhanice o celkové výměře 209 m² dle přílohy od 1.11.2025 na dobu 4 let za cenu 15,- Kč/m²."]),
  p("Informace starosty: Pokračování v pronájmu – Povolná Monika."),
  h5("Rozprava"),
  p("L.Maršíková: Dotaz, zda je to jen pokračování smlouvy za vyšší peníze nebo je tam ještě další změna. Starosta: Není."),
  h5("Návrh"),
  p("ZO schvaluje pronájem části pozemků parc. č. 132/1, 1988 a 128/10 k.ú. Krhanice o celkové výměře 209 m² dle přílohy a uzavření smlouvy, od 1.11.2025 na dobu 4 let za cenu 15,- Kč/m² Monice Povolné, Krhanice č.ev.162, 257 42 Krhanice."),
  vote(V8),
  p("U Dlážděnky směrem k nádrži u vrby je zrekonstruovaný chodník. Část chodníku je na soukromém pozemku. Po dohodě s majiteli od nich vykoupíme dle geometrického plánu části jejich pozemku. Dohoda je za symbolickou 1 Kč/1 m². Byl vyhotoven oddělující geometrický plán."),
  h5("Rozprava"),
  p("L.Maršíková: Kdo chodník realizoval a za kolik? Nelíbí se mi zvlněný povrch. Starosta: Chodník kopíruje Dlážděnku. Jinak bychom museli přeložit celou tuto komunikaci. Realizaci provedla firma Žaba. Cenu Vám pošlu."),
  h5("Návrh"),
  p("ZO schvaluje odkoupení části pozemku st.p. 244/1 k.ú. Krhanice díl a o výměře 3 m² a část pozemku parc.č. 230/1 k.ú. Krhanice, díl b o výměře 9 m², a to dle geometrického plánu č. 1204-63/2025 za cenu 1 Kč/1 m² od Šárky Němečkové a Jakuba Moláčka, Krhanice č.p. 94, 257 42 Krhanice."),
  vote(V8),

  p("Dále jsme obdrželi tyto žádosti týkající se majetku:"),
  h4("1. Odkup části obecního pozemku p.č. 416/3 o výměře 77 m², Podroužek Jan, Krhanice č.p. 116."),
  p("Starosta: Jedná se přístupovou cestu k rodinnému domu. Cestu obec nevyužívá. Požadavek je pouze na tu část cesty, která končí u rohu plotu další nemovitosti níže."),
  h5("Rozprava"),
  p("L.Maršíková: Máme písemný souhlas majitelů sousedních nemovitostí? Starosta: Nemáme. Osobně jsem je se záměrem kontaktoval. Oba souhlasí."),
  p("Š.Dušová: Je už stanovena cena za metr čtvereční? Starosta: Schvalujeme jen záměr. Necháme si vypracovat znalecký posudek."),
  h5("Návrh"),
  p("ZO schvaluje záměr odprodat část obecního pozemku parc.č. 416/3 k.ú. Krhanice o výměře cca 77 m². Pro prodej této části pozemku bude vyhotoven geometrický plán a znalecký posudek."),
  vote("PRO ( 7 ) – PROTI ( 1 - Maršíková ) – ZDRŽEL SE ( 0 )"),
  h4("2. Nabídka prodeje části pozemku p.č. 148/32 k.ú. Krhanice a nabídka prodeje pozemku parc.č. 148/7 k.ú. Krhanice obci, a to od Jana Kadeřábka, Krhanice č.p. 1."),
  p("Starosta: Došlo k dohodě s panem Kadeřábkem. Obec do budoucna plánuje vytvořit si v dané lokalitě technické zázemí."),
  h5("Rozprava"),
  p("L.Maršíková: Jaký má obec záměr s tímto pozemkem? Starosta: Chtěli bychom zde vybudovat technické zázemí obce."),
  p("L.Maršíková: Zůstane tam obratiště pro popeláře? Starosta: Popeláři se otáčí na protější straně."),
  h5("Návrh"),
  p("ZO schvaluje záměr odkoupení části pozemku parc.č. 148/32 k.ú. Krhanice o výměře cca 2000 m² a pozemku parc.č. 148/7 k.ú. Krhanice o výměře 162 m² za cenu 35 Kč/1 m². Náklady spojené s odkoupením bude hradit obec (geometrický plán, vklad na katastr, ...)."),
  vote(V8),

  h3("6) Různé"),
  h4("Dotace z Fondu podpory dobrovolných hasičů a složek IZS – Středočeský kraj"),
  p("Byla nám schválena ze strany Středočeského kraje dotace ve výši 98 000,- Kč na nákup vybavení jednotky SDH obce Krhanice věcnými prostředky pro zvýšení ochrany hasičů a zlepšení vybavenosti jednotky. Jedná se o tyto věci:"),
  ...ul([
    "Přilba pro hašení v otevřeném terénu a pro technické zásahy: počet kusů 10, cena za kus s DPH 6 490,00 Kč, celkem s DPH 64 900,00 Kč",
    "AKU úhlová bruska: počet kusů 1, cena za kus s DPH 8 908,00 Kč, celkem s DPH 8 908,00 Kč",
    "Úniková kukla s filtrem: počet kusů 1, cena za kus s DPH 7 511,00 Kč, celkem s DPH 7 511,00 Kč",
    "Zásahový oděv I (třívrstvý oděv pro hasiče): počet kusů 1, cena za kus s DPH 22 380,00 Kč, celkem s DPH 22 380,00 Kč",
    "CELKEM: 103 699,00 Kč",
  ]),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje přijetí dotace z rozpočtu Středočeského kraje z Fondu podpory dobrovolných hasičů a složek IZS a uzavření veřejnoprávní smlouvy o poskytnutí dotace se Středočeským krajem pro dotaci Vybavení jednotky SDH obce Krhanice věcnými prostředky pro zvýšení ochrany hasičů a zlepšení vybavenosti jednotky."),
  vote(V8),

  h4("Dotace z Fondu obnovy venkova – Středočeský kraj"),
  p("Obec má záměr přístavby mateřské školy. Středočeský kraj poskytuje dotaci z Fondu obnovy venkova. Pro podání žádosti musíme mít uzavřenu smlouvu o dílo na realizaci přístavby."),
  p("Poskytovatel dotace: Středočeský kraj"),
  p("Název dotace: „Program 2025-2028 pro poskytování dotací na rozvoj obcí do 2000 obyvatel ze Středočeského Fondu obnovy venkova“"),
  p("Název projektu: Přístavba Mateřské školy Krhanice"),
  p("Předpokládané náklady akce: 3 351 547,16 Kč (orientační rozpočet)"),
  p("Požadovaná dotace: 1 135 000 Kč"),
  h5("Rozprava"),
  p("L.Maršíková: Částka tisíc korun je maximální? Starosta: Ano. Výše dotace je stanovena podle počtu obyvatel dle Českého statistického úřadu k 1.1.2025."),
  p("Š.Dušová: Jak bude financován zbytek? Starosta: Z rozpočtu obce."),
  p("Š.Dušová: Kdo stavbu oceňoval? Starosta: Rozpočtář od projektanta Moravce."),
  p("L.Maršíková: Je nutná spolupráce s Posázavím? Starosta: Ano. Spolupracujeme dlouhodobě. Dlouhodobě s Posázavím spolupracuje i mateřská a základní škola. Za mě výborná spolupráce a máme záruku, že vše proběhne, jak má. Jedná se o placenou službu."),
  p("Proběhla diskuse o stavbě, bourání, dispozicích, důvodech přístavby, přístavbě v minulosti a jejím financováním, dotaci, výběrovém řízení, ... bez přijetí závěrů."),
  h5("Návrh"),
  p("ZO schvaluje podání žádosti o dotaci pro projekt „Přístavba Mateřské školy Krhanice“ z rozpočtu Středočeského kraje Program 2025-2028 pro poskytování dotací na rozvoj obcí do 2000 obyvatel ze Středočeského Fondu obnovy venkova a schvaluje finanční spoluúčast obce."),
  vote("PRO ( 6 ) – PROTI ( 2 – Maršíková, Dušová ) – ZDRŽEL SE ( 0 )"),
  h5("Výběrové řízení"),
  p("Pověření starosty k vypsání výběrového řízení. Oslovíme nejméně 3 firmy."),
  h5("Návrh"),
  p("ZO schvaluje vypsání výběrového řízení na dodavatele stavby pro projekt „Přístavba Mateřské školy Krhanice“ s oslovením nejméně 3 firem."),
  vote("PRO ( 6 ) – PROTI ( 2 – Maršíková, Dušová ) – ZDRŽEL SE ( 0 )"),
  h5("Návrh"),
  p("ZO pověřuje starostu obce realizací vypsání výběrového řízení na dodavatele stavby pro projekt „Přístavba Mateřské školy Krhanice“."),
  vote("PRO ( 6 ) – PROTI ( 2 – Maršíková, Dušová ) – ZDRŽEL SE ( 0 )"),
  h5("Návrh"),
  p("ZO schvaluje spolupráci s Posázavím o.p.s., Zámek Jemniště 1, 257 01 Postupice, IČO 27129772 při zajištění poradenství při realizaci výběrového řízení pro projekt „Přístavba Mateřské školy Krhanice“."),
  vote("PRO ( 6 ) – PROTI ( 2 – Maršíková, Dušová ) – ZDRŽEL SE ( 0 )"),

  h4("Inventarizace 2025"),
  p("Informace starosty: Standardním způsobem provedeme inventarizaci. Schválíme Plán inventur na rok 2025 včetně přílohy č. 1 – Seznamu inventurních soupisů s konkrétním postupem pro provedení inventarizace majetku a závazků obce. Jsou zde uvedeny konkrétní osoby, termíny a úkoly. Pro rok 2025 se zřizuje jedna inventarizační komise pro střediska – Obecní úřad Krhanice, Knihovna, Hasičská zbrojnice ve složení: Aleš Papoušek, Jana Cachová, Lenka Termerová, Jaroslav Mixa a Petr Dub."),
  p("Stav majetku a závazků bude zjišťován k datu 31. 12. 2025. Inventurní soupisy bude inventarizační komise vyhotovovat průběžně v měsíci lednu 2026. Inventarizační komise vyhotoví Inventarizační zprávu nejpozději do 6. 2. 2026."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Plán inventur na rok 2025."),
  vote(V8),

  h4("Rozpočet 2026"),
  p("Informace starosty: Pro sestavení rozpočtu obce Krhanice na rok 2026 bude zřízena Komise pro sestavení rozpočtu pro rok 2026 v počtu 6 členů. Z pozice předsedy Komise navrhuji tyto členy: Aleš Papoušek, Jana Laboutková, Petr Dub, Alena Kratochvílová, Markéta Vaňková a Jana Cachová."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje složení Komise pro sestavení rozpočtu pro rok 2026: Aleš Papoušek, Jana Laboutková, Petr Dub, Alena Kratochvílová, Markéta Vaňková a Jana Cachová."),
  vote("PRO ( 6 ) – PROTI ( 2 – Maršíková, Dušová ) – ZDRŽEL SE ( 0 )"),

  h3("7) Diskuse"),
  ...ul([
    "Š.Dušová: Dotaz na pana místostarostu, zda odpověděl paní Ledecké. Místostarosta: Odpověděl jsem, kontejnerové stání rušit nebudeme. Odpověď od ní nepřišla.",
    "I.Zahrádková: Dotaz na tréninkové hřiště, zda je něco nového. Starosta: Měl jsem tu firmu, která zpracuje rozpočet na hřiště a podle výsledků se rozhodneme. Proběhla diskuse o hřišti, využívání ze strany školy, ... bez přijetí závěrů.",
    "Š.Dušová: Dotaz na cestu proti nádraží ke kamenictví, zda došlo k nějaké změně. Starosta: Cesta nebude nikdy průchozí. Vedla by přes soukromý pozemek. Starosta ukázal na katastrální mapě, kudy povede bezpečný přístup pro chodce k vlakové a autobusové zastávce.",
    "D.Nováková: Dotaz na přechod pro chodce od vlakového nádraží k tenisovým kurtům. Starosta: Už se v minulosti řešilo. Přechod tam být nemůže. Je tam pouze přechodové místo.",
    "D.Nováková: Dotaz na podobné akce pro občany jako v minulosti byl zájezd na Hobby České Budějovice. Místostarosta: Je to o zájmu. Pokud není, akce se nedělá.",
  ]),

  h3("8) Závěr"),
  p("Zastupitelstvo obce bylo ukončeno v 19:03 hod."),

  p("Datum pořízení zápisu: 28.6.2025"),
  p("Ověřovatelé zápisu a starosta obce, podepsáno v listinné podobě."),
  h4("Přílohy"),
  ...nl(["Svolání zastupitelstva obce", "Prezenční listina zastupitelů", "Prezenční listina občanů"]),
];

async function run() {
  const r = await publishZapis({
    cislo: "4",
    rok: "2025",
    isoDate: "2025-08-26",
    dateLabel: "26. 8. 2025",
    fullDateDot: "26.8.2025",
    pdfPath: "scripts/zapisy-pdf/zapis-2025-4.pdf",
    transcript,
  });
  console.log("OK", r.docId, "blocks", r.blocks);
}
run().catch((e) => { console.error(e); process.exit(1); });
