/* eslint-disable no-console */
import { h3, h4, h5, p, vote, nl, ul, publishZapis, type Block } from "../zapis-lib";

const V9 = "PRO ( 9 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )";

const transcript: Block[] = [
  h4("Přítomni"),
  p("Aleš Papoušek, Jaroslav Mixa, Tomáš Kratochvíl, Jana Laboutková, Martin Jiřička, Petr Dub, Aleš Kozel, Lucie Maršíková, Šárka Dušová"),

  h3("1) Zahájení, přivítání přítomných, konstatování přítomnosti"),
  p("Starosta konstatoval, že zasedání bylo svoláno dne 11.11.2025, bylo vyvěšeno na úřední desce obecního úřadu, tj. tedy nejméně 7 dní před zasedáním. Bylo tedy svoláno řádně a včas v souladu se zákonem o obcích v platném znění. Starosta konstatoval, že podle prezenční listiny je přítomno 9 členů zastupitelstva, tedy nadpoloviční většina členů zastupitelstva."),
  h5("Určení zapisovatele"),
  p("Zápisem zasedání zastupitelstva obce byla pověřena Ing. Alena Kratochvílová."),

  h3("2) Volba návrhové komise a ověřovatelů zápisu"),
  p("Starosta přednesl návrh návrhové komise a ověřovatelů zápisu."),
  h5("Návrh"),
  p("ZO schvaluje návrhovou komisi ve složení: Jana Laboutková, Jaroslav Mixa."),
  h5("Návrh"),
  p("ZO schvaluje ověřovatele zápisu ve složení Petr Dub, Martin Jiřička."),
  vote(V9),

  h3("3) Schválení programu"),
  p("Starosta přečetl program."),
  ...nl([
    "Zahájení",
    "Volba návrhové komise a ověřovatelů zápisu",
    "Schválení programu",
    "Zpráva Kontrolního výboru",
    "Zpráva Finančního výboru",
    "Rozpočtové opatření",
    "Koupě, prodej, pronájem",
    "Různé",
    "Diskuse",
    "Závěr",
  ]),
  p("Starosta: Má někdo návrh na změnu nebo doplnění programu?"),
  h5("Návrh"),
  p("ZO schvaluje program zasedání zastupitelstva obce."),
  vote(V9),

  h3("4) Zpráva Kontrolního výboru"),
  p("Předseda kontrolního výboru Martin Jiřička seznámil přítomné se zprávou Kontrolního výboru ze dne 29.9.2025."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí Zprávu Kontrolního výboru ze dne 29.9.2025."),

  h3("5) Zpráva Finančního výboru"),
  p("Předseda finančního výboru Petr Dub seznámil s kontrolou hospodaření obce Krhanice za období leden–září 2025 ze dne 3.11.2025. A dále seznámil s proběhlými veřejnosprávními kontrolami hospodaření příspěvkových organizací Mateřské školy Krhanice a Základní školy Krhanice. Kontroly proběhly dne 3.11.2025."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí zprávu Finančního výboru o kontrole hospodaření obce Krhanice za období leden – září 2025 ze dne 3.11.2025."),
  h5("Návrh"),
  p("ZO bere na vědomí protokoly o průběhu a výsledcích veřejnosprávních kontrol příspěvkových organizací Základní škola Krhanice a Mateřská škola Krhanice za období leden–září 2025 ze dne 3.11.2025."),

  h3("6) Rozpočtové opatření"),
  h4("Rozpočtové opatření č. 5/2025 – starosta"),
  p("Jednalo se o dotaci od Středočeského kraje dotace na vybavení jednotky SDH obce Krhanice věcnými prostředky pro zvýšení ochrany hasičů a zlepšení vybavenosti jednotky ve výši 98 tisíc Kč."),
  p("Dotace byla zahrnuta do příjmů a výdajů."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí rozpočtové opatření č. 5/2025."),

  h4("Rozpočtové opatření č. 2 DSO BENE-BUS"),
  p("Informace starosty: Bylo nám předloženo rozpočtové opatření č. 2 DSO BENE-BUS. Vyvěšeno dne 10.11.2025. Orgán určený ke schválení – valná hromada."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí Rozpočtové opatření č.2 k SR na rok 2025 DSO BENE-BUS."),

  h4("Rozpočtové opatření č. 4/2025 a 5/2025 SPOLEČNÁ VODA D.S.O."),
  p("Informace starosty: Byly nám předloženy rozpočtová opatření č. 4/2025 (vyvěšeno 10.9.2025) a 5/2025 (vyvěšeno 7.10.2025) Společná voda d.s.o. Orgán určený ke schválení – valná hromada."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí Rozpočtové opatření č. 4/2025 a 5/2025 Společná voda d.s.o."),

  h4("Rozpočtové opatření č. 6/2025"),
  p("Předseda finančního výboru Petr Dub seznámil s rozpočtovým opatřením č. 6/2025."),
  p("Tomáš Kratochvíl seznámil s Darovací smlouvou na finanční dar ve výši 14 400 Kč na spolufinancování nákupu „Zkušební zařízení pro zkoušky funkčnosti a těsnosti prostředků chemické služby – územní odbor Kladno, stanice HZS Jílové u Prahy“."),
  p("Starosta seznámil se situací v jídelně – nákup nového konvektomatu s příslušenstvím. Základní škole (středisku školní jídelna) bude zaslán investiční příspěvek do Fondu investic, z něj bude nový konvektomat pořízen."),
  h5("Rozprava"),
  p("L.Maršíková: Co se stane, pokud všechny obce neposkytnou svůj příspěvek? T.Kratochvíl: Bylo řečeno, že se pokusí získat sponzorský dar, aby se dala dohromady částka celá."),
  p("A.Kozel: Chtěl vysvětlit, kde servis dýchacích přístrojů probíhal doposud? T.Kratochvíl: Jezdíme na stanici HZS Jílové u Prahy."),
  p("L.Maršíková: Dotaz k položce Obnova místních kulturních památek. K čemu byla částka určena? Starosta: Na případné opravy, ale žádné se nerealizovaly."),
  p("L.Maršíková: Dotaz na položku právní služby. Starosta: Právník, který bydlel v Krhanicích a který řešil přestupky v rámci dobrých vztahů bezúplatně, se odstěhoval. Řešením je právník z Jílového u Prahy, ale už za úplatu."),
  p("L.Maršíková: Jak často se schází přestupková komise a kolik přestupků řeší? Starosta: 10 až 15 přestupků za rok."),
  p("I.Dvořák: O jaký druh přestupků se jedná? Starosta: Zejména urážky a fyzické napadení."),
  p("I.Dvořák: Dotaz, zda všechny akce nerealizované letos se uskuteční v příštím roce? Starosta: Až na jednu ano."),
  p("I.Dvořák: Která akce se nebude realizovat? Starosta: Nejspíše ta, na kterou zatím nemáme stavební povolení (komunikace Na Žlabech)."),
  p("I.Dvořák: Dotaz, kdy bude předložena zpráva o územním plánu? Starosta: Předpoklad prosinec."),
  p("L.Maršíková: Dotaz na dar na přístavbu hasičské zbrojnice, zda byl poskytnut konkrétně na tuto přístavbu a kým? Starosta: Ano, dar byl poskytnut na přístavbu hasičské zbrojnice fyzickou osobou, občanem Krhanic, která si nepřeje být jmenována a její přání budeme respektovat."),
  p("L.Maršíková: Cena konvektomatu mi připadá příliš vysoká. Radili jste se s někým? Starosta: Radil jsem se s manažerem, který realizuje kuchyně značky Electrolux."),
  p("I.Dvořák: Co se stane s tím starým konvektomatem? Starosta: Je účetně odepsaný, bude zlikvidován."),
  p("R.Novotný: Možná by bylo dobré zvolit prodlouženou záruku. Starosta: Prověřím tuto možnost."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Darovací smlouvy s organizací Česká republika – Hasičský záchranný sbor Středočeského kraje, IČO 70885371, se sídlem Jana Palacha 1970, 272 01 Kladno na poskytnutí finančního daru ve výši 14 400 Kč na spolufinancování nákupu „Zkušební zařízení pro zkoušky funkčnosti a těsnosti prostředků chemické služby – územní odbor Kladno, stanice HZS Jílové u Prahy“."),
  vote(V9),
  h5("Návrh"),
  p("ZO schvaluje poskytnutí investičního příspěvku na nákup konvektomatu s příslušenstvím do příspěvkové organizace Základní škola Krhanice – středisko Školní jídelna ve výši 265 000,- Kč."),
  vote(V9),
  h5("Návrh"),
  p("ZO schvaluje rozpočtové opatření č. 6/2025."),
  vote(V9),

  h3("7) Koupě, prodej, pronájem"),
  ...ul(["prodat část pozemku parc.č. 1985/1 Krhanice o výměře 2 m² – díl a dle geometrického plánu č. 1230-113/2025 za cenu za cenu 1000,- Kč/1 m²."]),
  p("Informace starosty: Jedná se o přístavbu domu, která zasahuje 2 m² do obecního pozemku. Zbourat nejde."),
  h5("Rozprava"),
  p("Proběhla diskuse o tom, že digitalizací byla zjištěna celá řada nesrovnalostí. Toto je příklad toho, kdy majitel nemovitosti sjednat nápravu."),
  h5("Návrh"),
  p("ZO schvaluje prodej části pozemku parc.č. 1985/1 Krhanice o výměře 2 m² – díla dle geometrického plánu č. 1230-113/2025 za cenu za cenu 1000,- Kč/1 m² Milanu Pešanovi, Krhanice č.p. 75, 257 42 Krhanice."),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 2 – Maršíková, Dušová )"),

  ...ul(["prodat pozemek parc.č. 312/47 k.ú. Krhanice o výměře 68 m² za cenu 500,- Kč/1 m²."]),
  p("Informace starosty: Jedná se o pozemek, který obec nevyužívá. Majitelé nemovitosti Krhanice č.p. 125 a sousedka rekreantka podepsali, že souhlasí s odprodejem Lence Beranové."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje prodej pozemku parc.č. 312/47 k.ú. Krhanice o výměře 68 m² za cenu 500,- Kč/1 m² Lence Beranové, Krhanice č.ev. 135, 257 42 Krhanice."),
  vote("PRO ( 7 ) – PROTI ( 1 – Dušová ) – ZDRŽEL SE ( 1 – Maršíková )"),

  ...ul(["uzavřít Smlouvu o zřízení věcného břemene – uložení vodovodní přípojky pro pozemek 313/14 k.ú. Krhanice na pozemku parc.č. 313/32 k.ú. Krhanice dle geometrického plánu č. 1294-272/2025 na dobu neurčitou za cenu 3 000,- Kč."]),
  p("Informace starosty: Jedná se o věcné břemeno na vodovodní přípojku vybudovanou k rodinnému domu v lokalitě nedaleko Hodkova."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o zřízení věcného břemene – uložení vodovodní přípojky pro pozemek 313/14 k.ú. Krhanice na pozemku parc.č. 313/32 k.ú. Krhanice dle geometrického plánu č. 1294-272/2025 na dobu neurčitou za cenu 3 000,- Kč s Kocourovou Kateřinou, Krhanice č.p. 130, 257 42 Krhanice."),
  vote(V9),

  ...ul(["uzavřít Smlouvu o zrušení služebnosti, kdy dojde ke zrušení věcného břemene pro Oprávněnou stranu z věcného břemene Obec Krhanice a Povinnou stranu Janu Troníčkovou v tomto rozsahu: ruší se Věcné břemeno chůze a jízdy ve prospěch pozemku parc. č. 244/10 k.ú. Krhanice k tíži pozemku č. parc. 244/5 k.ú. Krhanice."]),
  p("Informace starosty: Jana Troníčková požádala o zrušení věcného břemene chůze a jízdy přes její pozemek parc.č. 244/5 k.ú. Krhanice k obecnímu pozemku parc.č. 244/10 k.ú. Krhanice, neboť toto věcné břemeno pozbylo smyslu."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o zrušení služebnosti: zrušení věcného břemene chůze a jízdy ve prospěch pozemku parc. č. 244/10 k.ú. Krhanice k tíži pozemku č. parc. 244/5 k.ú. Krhanice pro Oprávněnou stranu z věcného břemene Obec Krhanice a Povinnou stranu z věcného břemene Janu Troníčkovou, Chrást nad Sázavou 219, 257 41 Týnec nad Sázavou."),
  vote(V9),

  ...ul(["uzavřít Dohodu o zrušení věcného břemene chůze a jízdy, kdy dojde ke zrušení věcného břemene pro Povinnou stranu z věcného břemene Obec Krhanice a Oprávněnou stranu Jitka González Bruna v tomto rozsahu: ruší se Věcné břemeno chůze a jízdy ve prospěch pozemku parc. č. 102/18 k tíži pozemku č. parc. 102/20, 102/38, 102/7 a 87/6 k.ú. Krhanice."]),
  p("Informace starosty: Jitka González Bruna požádala o zrušení věcného břemene chůze a jízdy přes obecní pozemky parc.č. 102/20, 102/38, 102/7 a 87/6 k.ú. Krhanice k jejímu pozemku parc.č. 102/18 k.ú. Krhanice, neboť toto věcné břemeno pozbylo smyslu."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Dohody o zrušení věcného břemene chůze a jízdy: zrušení věcného břemene chůze a jízdy ve prospěch pozemku parc. č. 102/18 k tíži pozemku č. parc. 102/20, 102/38, 102/7 a 87/6 k.ú. Krhanice pro Povinnou stranu z věcného břemene Obec Krhanice a Oprávněnou stranu z věcného břemene Jitku González Bruna, Krhanice č.ev. 45, 257 42 Krhanice."),
  vote(V9),

  h3("8) Různé"),
  h4("Společná voda – fúze svazku Vodovodní přivaděč Javorník"),
  p("K 1.1.2026 proběhne fúze svazků Vodovodní přivaděč Javorník – Benešov, dobrovolný svazek obcí, IČO: 02468085 a Společná voda d.s.o., IČO: 17408288. Výše uvedené svazky připravily návrh Smlouvy o fúzi sloučením svazků v souladu s příslušnými ustanoveními zákona č. 89/2012 Sb., Občanský zákoník. Proces fúze proběhne sloučením zúčastněných svazků, při kterém dojde ke zrušení a zániku svazku Vodovodní přivaděč Javorník – Benešov, dobrovolný svazek obcí, IČO: 02468085, se sídlem: Masarykovo náměstí 100, 256 01 Benešov, bez likvidace s tím, že jmění tohoto svazku, včetně členství členů zanikajícího svazku (pokud jejich členství v nástupnickém svazku nevzniklo dříve nebo pokud v důsledku fúze ze svazku nevystoupí), přechází na nástupnický svazek Společná voda d.s.o., IČO: 17408288, sídlo: Černoleská 1600, 256 01 Benešov, který v důsledku této fúze nezanikne a bude i nadále existovat. V souvislosti s předmětnou fúzí nedochází ke změně názvu nástupnického svazku. Rozhodný den fúze sloučením je den 1.1.2026."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje:"),
  ...nl([
    "souhlas s fúzí svazku Vodovodní přivaděč Javorník – Benešov, dobrovolný svazek obcí, IČO: 02468085, se sídlem: Masarykovo náměstí 100, 256 01 Benešov, sloučením se svazkem Společná voda d.s.o., IČO: 17408288, se sídlem: Černoleská 1600, 256 01 Benešov, s tím, že zanikající svazek ke dni 1. 1. 2026 zanikne bez likvidace,",
    "návrh smlouvy o fúzi svazku Vodovodní přivaděč Javorník – Benešov, dobrovolný svazek obcí, IČO: 02468085, se sídlem: Masarykovo náměstí 100, 256 01 Benešov, sloučením se svazkem Společná voda d.s.o., IČO: 17408288, se sídlem: Černoleská 1600, 256 01 Benešov, s rozhodným dnem 1. 1. 2026.",
  ]),
  h5("Návrh"),
  p("ZO pověřuje starostu obce zabezpečit provedení potřebných úkonů vedoucích k realizaci částí I. až II. usnesení o fúzi svazku Vodovodní přivaděč Javorník – Benešov, dobrovolný svazek obcí, IČO: 02468085, se sídlem: Masarykovo náměstí 100, 256 01 Benešov, sloučením se svazkem Společná voda d.s.o., IČO: 17408288, se sídlem: Černoleská 1600, 256 01 Benešov, zejména hlasovat na valné hromadě nástupnického svazku Společná voda d.s.o., IČO: 17408288, se sídlem: Černoleská 1600, 256 01 Benešov, pro plánovanou fúzi sloučením, podepsat všechny potřebné dohody a smlouvy. Starosta je oprávněn ve stejném rozsahu na základě písemné plné moci zmocnit další osobu k těmto úkonům v případě jeho nepřítomnosti."),
  vote(V9),

  h4("FVE klubovna"),
  p("Obec žádala o dotaci na projekt: Fotovoltaika na střeše klubovny zázemí víceúčelového hřiště v Krhanicích z výzvy Modernizačního fondu RES+, který pomáhá obcím do 3000 obyvatel s výstavbou fotovoltaických elektráren. Obdrželi jsme Rozhodnutí o poskytnutí finančních prostředků ze Státního fondu životního prostředí České republiky v rámci Programu financovaného z prostředků Modernizačního fondu. Výše dotace bude 303 283,40 Kč. Předpokládané náklady projektu jsou zaokrouhleně 510 tisíc Kč."),
  p("Nyní starosta obce musí vypsat výběrové řízení na dodavatele ve spolupráci s Posázaví o.p.s."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),

  h4("Vodné od 1.1.2026"),
  p("Informace starosty: Byla nám zaslána kalkulace vodného od 1.1.2026. Změna vodného reaguje na změnu nákupu pitné vody ze Želivky. Navýšila se cena za 1 m³ pitné vody o 1,06 Kč. Celkově se zvedne cena 1 m³ o 1,08 Kč s DPH. Konečná cena bude 84,07 Kč s DPH/1 m³ pitné vody."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí cenu vodného od 1.1.2026 ve výši 84,07 Kč s DPH/1 m³."),

  h4("Dobrovolné svazky obcí : BENE-BUS, SPOLEČNÁ VODA"),
  h4("DSO BENE-BUS:"),
  p("Informace starosty: Byl nám předložen návrh Rozpočtu 2026 a návrh Střednědobého výhledu rozpočtu 2027-2029. Vyvěšeno dne 10.11.2025. Orgán určený ke schválení – valná hromada. Návrh rozpočtu – schodkový, schodek bude krytý finančními prostředky minulých let."),
  h4("SPOLEČNÁ VODA D.S.O.:"),
  p("Informace starosty: Byl nám předložen návrh Rozpočtu 2026 a návrh Střednědobého výhledu rozpočtu 2027-2029. Vyvěšeno dne 14.11.2025. Orgán určený ke schválení – valná hromada. Návrh rozpočtu – schodkový, schodek bude krytý finančními prostředky minulých let."),
  h4("Týnecko-svazek obcí:"),
  p("Informace starosty: Byl nám předložen návrh Rozpočtu 2026 a návrh Střednědobého výhledu rozpočtu na rok 2027-2028. Vyvěšeno dne 19.11.2025. Orgán určený ke schválení – valná hromada. Návrh rozpočtu – vyrovnaný."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí, že Rozpočet Bene-Bus dobrovolný svazek obcí na rok 2026 je schodkový a schodek rozpočtu bude financován z finančních prostředků minulých let a bere na vědomí Střednědobý výhled rozpočtu Bene-Bus dobrovolný svazek obcí na období 2027-2029."),
  h5("Návrh"),
  p("ZO bere na vědomí, že Rozpočet Společná voda d.s.o. na rok 2026 je schodkový a schodek rozpočtu bude financován z finančních prostředků minulých let a bere na vědomí Střednědobý výhled rozpočtu Společná voda d.s,o. na období 2027-2029."),
  h5("Návrh"),
  p("ZO bere na vědomí, že Rozpočet Týnecko-svazek obcí na rok 2026 je vyrovnaný a bere na vědomí Střednědobý výhled rozpočtu na rok 2027-2028 Týnecko-svazek obcí."),

  h4("Obecní knihovna Krhanice"),
  p("Informace starosty: Budeme uzavírat novou Smlouvu o poskytování služeb v rámci výkonu regionálních funkcí knihoven pro základní knihovnu. Půjde o mechanismus dvoustranného smluvního zajištění výkonu regionálních funkcí v oblasti knihovnictví."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Výpověď smlouvy o poskytování odborné pomoci knihovnám v rámci zajišťování plnění regionálních funkcí a jeho koordinace Středočeským krajem ze dne 09.08.2006 číslo 368/KUL/2006."),
  vote(V9),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o poskytování služeb v rámci výkonu regionálních funkcí knihoven pro základní knihovnu č. BN/042/2025 (pro Obecní knihovnu Krhanice)."),
  vote(V9),

  h3("9) Diskuse"),
  ...ul([
    "L.Maršíková: Dotaz na dotaci na fotovoltaiku, kdy se bude realizovat a zda bude využita jenom pro klubovnu? Starosta: V příštím roce, je záměrem připojit k přebytkům elektrické energie základní školu.",
    "I.Dvořák: Dotaz, zda obec umožňuje přepronajímání pronajatého majetku. Starosta: ne.",
    "I.Dvořák: Konkrétně dotaz na Sokol, zda obec ví, na jakých podmínek hřiště pronajímá na akce, které pořádá na hřišti někdo jiný. Starosta: Sokol má majetek ve výpůjčce a může ho dále pronajímat. Sokol takto získává finanční prostředky a od obce nepožaduje veškeré náklady na údržbu hřiště a budovy. Proběhla diskuse, která měla spekulativní charakter, a proto byla ze strany předsedajícího ukončena.",
    "I.Dvořák: Dotaz k novele školského zákona, zda obec má představu o nákladech za nepedagogické pracovníky? Starosta: Ano. Spolupracuji s ředitelkami mateřské školy a základní školy.",
    "I.Dvořák: Vzdělávání učitelů jde taky za obcí? Starosta: Ano. Již v minulosti jsme přispívali základní škole na vzdělávání kuchařek, na plavání, na učební pomůcky. Vzdělávání učitelů po novu bude financovat taky.",
    "I.Dvořák: Dotaz na slučování mateřské a základní školy. Starosta: Zatím to neřešíme. Díky podmínce počtu dětí v mateřské škole nad 180 se slučováním počítáme.",
    "I.Dvořák: Ředitelce základní školy končí období, na které byla jmenována do této funkce. Ze školského zákona musí být nový konkurz. Kdy bude vypsán? Starosta: Není povinnost vypsat dle nového školského zákona konkurz na ředitele/ku základní školy. Jsem ve fázi rozhodování, zda konkurz vyhlásím. Je to v mé kompetenci.",
  ]),

  h3("10) Závěr"),
  p("Zastupitelstvo obce bylo ukončeno v 19:17 hod."),

  p("Datum pořízení zápisu: 3.12.2025"),
  p("Ověřovatelé zápisu a starosta obce, podepsáno v listinné podobě."),
  h4("Přílohy"),
  ...nl(["Svolání zastupitelstva obce", "Prezenční listina zastupitelů", "Prezenční listina občanů"]),
];

async function run() {
  const r = await publishZapis({
    cislo: "5",
    rok: "2025",
    isoDate: "2025-11-19",
    dateLabel: "19. 11. 2025",
    fullDateDot: "19.11.2025",
    pdfPath: "scripts/zapisy-pdf/zapis-2025-5.pdf",
    transcript,
  });
  console.log("OK", r.docId, "blocks", r.blocks);
}
run().catch((e) => { console.error(e); process.exit(1); });
