/* eslint-disable no-console */
// One-off: faithful visual transcript of Zápis č. 4/2022 (18.7.2022),
// transcribed page-by-page from the official PDF (12 pages). Structure follows
// the approved golden sample scripts/build-zapis-2026-1.ts.
import { h3, h4, h5, p, vote, nl, ul, publishZapis, type Block } from "../zapis-lib";

const V8 = "PRO ( 8 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )";

const transcript: Block[] = [
  h4("Přítomni"),
  p("Aleš Papoušek, Jaroslav Mixa, Václav Zíta, Tomáš Kratochvíl, Petr Dub, Martin Jiřička, Bohuslav Kadeřábek, Jana Laboutková"),
  h4("Omluveni"),
  p("Edita Jarošová"),

  h3("1) Zahájení, přivítání přítomných, konstatování přítomnosti"),
  p("Starosta konstatoval, že zasedání bylo svoláno dne 8.7.2022 bylo vyvěšeno na úřední desce obecního úřadu, tj. tedy nejméně 7 dní před zasedáním. Bylo tedy svoláno řádně a včas v souladu se zákonem o obcích v platném znění. Starosta konstatoval, že podle prezenční listiny je přítomno 8 členů zastupitelstva, tedy nadpoloviční většina členů zastupitelstva. K předchozímu zápisu nebyly vzneseny námitky."),
  h5("Určení zapisovatele"),
  p("Zápisem zasedání zastupitelstva obce byla pověřena Ing. Alena Kratochvílová."),
  p("Starosta přečetl program."),
  ...nl([
    "Zahájení",
    "Volba návrhové komise a ověřovatelů zápisu",
    "Krhanice – rekonstrukce návsi a okolních chodníků – oznámení výsledku výběrového řízení",
    "Koupě, prodej, pronájem",
    "Různé",
    "Diskuse",
    "Usnesení a závěr",
  ]),
  p("Proběhlo hlasování o programu."),
  h5("Návrh"),
  p("ZO schvaluje program zasedání zastupitelstva obce."),
  vote(V8),

  h3("2) Volba návrhové komise a ověřovatelů zápisu"),
  p("Starosta přednesl návrh návrhové komise a ověřovatelů zápisu."),
  h5("Návrh"),
  p("ZO schvaluje návrhovou komisi ve složení Jaroslav Mixa, Jana Laboutková."),
  h5("Návrh"),
  p("ZO schvaluje ověřovatele zápisu ve složení Petr Dub, Bohuslav Kadeřábek."),
  vote(V8),

  h3("3) Krhanice – rekonstrukce návsi a okolních chodníků – oznámení výsledku výběrového řízení"),
  p("Informace starosty: Výběrové řízení bylo realizováno s Posázaví o.p.s. Dle dotačních podmínek byly osloveny tři firmy. Výběrové řízení proběhlo ve středu 22.6.2022. Nabídku podaly dvě firmy, jedna se z časových důvodů omluvila. Hodnotícím kritériem byla nejnižší nabídková cena."),
  p("Výsledek:"),
  ...ul([
    "1. Jaroslav Žaba, IČ 86934431, Nabídková cena vč. DPH 6 134 213,44",
    "2. LAROS s.r.o., IČ 49826514, Nabídková cena vč. DPH 6 251 991,29",
  ]),
  p("Nejvhodnější nabídkou, tj. nabídkou nejlépe splňující kritérium stanovené zadavatelem v textu zadávací dokumentace pro zakázku malého rozsahu mimo režim zákona č. 134/2016 Sb., o zadávání veřejných zakázek k zakázce „Krhanice – rekonstrukce návsi a okolních chodníků“ je nabídka účastníka:"),
  p("obchodní firma: Jaroslav Žaba"),
  p("sídlo / místo podnikání: Pecerady 69, 257 41 Týnec nad Sázavou"),
  p("IČO: 86934431"),
  p("Nabídková cena bez DPH: 5 069 597,89 Kč"),
  p("DPH: 1 064 615,56 Kč"),
  p("Nabídková cena s DPH: 6 134 213,44 Kč"),
  h5("Rozprava"),
  p("I.Dvořák: Bude rekonstruovat vše? Starosta: Kromě rekonstrukce vodovodu ano."),
  p("H.Strnadová: Má tato firma nějaké zkušenosti? Pokud vím, dělá pouze výkopové práce. Starosta: Zkušenosti z okolních měst a obcí."),
  p("I.Dvořák: Dotaz na délku realizace. Starosta: Pan Žaba by chtěl zrealizovat do konce roku 2022."),
  p("I.Dvořák: Dotaz na financování. Starost: Dotace + spoluúčast."),
  p("H.Strnadová: Jak je řešeno zavlažování stromů na návsi? Starosta: Stávající řešení je dostačující."),
  p("V.Ditrich: Dotaz na výškové řešení trasy. Starosta: Jako stávající."),
  p("S.Nebeský: Vyjádřil názor, že navržené řešení neodpovídá tomu, že náves má být reprezentativní."),
  h5("Návrh"),
  p("ZO schvaluje uzavření smlouvy o dílo na akci Krhanice – rekonstrukce návsi a okolních chodníků s firmou Jaroslav Žaba, Pecerady 69, 257 41 Týnec nad Sázavou, IČO: 86934431 ve výši 6.134.213,44 Kč."),
  vote(V8),
  h5("Návrh"),
  p("ZO pověřuje starostu uzavřením a podpisem smlouvy o dílo na akci Krhanice – rekonstrukce návsi a okolních chodníků s firmou Jaroslav Žaba, Pecerady 69, 257 41 Týnec nad Sázavou, IČO: 86934431."),
  vote(V8),

  h3("4) Rozpočtové opatření"),
  h4("Krhanice – rekonstrukce místní komunikace na pozemku parc. č. 109/11"),
  p("Informace starosty: Jedná se o rekonstrukci místní komunikace na p.č. 109/11 k.ú. Krhanice."),
  p("Zahájení prací: 1.8.2022."),
  p("Dokončení prací: 31.10.2022."),
  p("Zhotovitel:"),
  p("obchodní firma/jméno: B E S  s.r.o."),
  p("sídlo / místo podnikání: Sukova 625, 256 01 Benešov"),
  p("IČO: 437 92 553"),
  p("Nabídková cena bez DPH: 448 117,23 Kč"),
  p("Cena s DPH: 542.221,84 Kč"),
  h5("Rozprava"),
  p("Paní Váňová: Které komunikace se to týká? Starosta: Druhá nad obecním úřadem, ke Štěpánům."),
  h5("Návrh"),
  p("ZO schvaluje uzavření smlouvy o dílo na akci Krhanice – MK na p.č. 109/11 – obnova MK s firmou: B E S  s.r.o., Sukova 625, 256 01 Benešov, IČO: 437 92 553 ve výši 448 117,23 Kč bez DPH."),
  vote(V8),
  h5("Návrh"),
  p("ZO pověřuje starostu uzavřením a podpisem smlouvy o dílo na akci Krhanice – MK na p.č. 109/11 – obnova MK s firmou: B E S  s.r.o., Sukova 625, 256 01 Benešov, IČO: 437 92 553."),
  vote(V8),

  h4("Žádost Naše Krhanice, z.s."),
  p("Informace: Byla předložena žádost o finanční příspěvek na konání akce Slavnosti sv. Josefa ve výši 10.000,- Kč. Jednalo by se o akci pro občany Krhanic a Prosečnice. Příspěvek by byl použit na příspěvek na program dětem, na hudební produkci a poplatek OSA. Výše příspěvku je stejná jako pro ostatní spolky."),

  h4("NAŠE KRHANICE – TERMÍN AKCE"),
  p("Informace T. Kratochvíla: Přečetl dopis – žádost o souhlas s pořádáním akce Slavnosti sv. Josefa na tréninkovém hřišti a prostoru před školou v sobotu 17.9.2022 (od 14:00 hod. do 2:00 hod. 18.9.2022). Přípravu plochy si provede spolek v sobotu 10.9.2022."),
  h5("Rozprava"),
  p("L.Maršíková: Poznámka k termínu, kryje se s termínem naší akce."),
  p("Proběhla diskuse o krytí se termínů. Závěr: Paní Maršíková a pan Papoušek se sejdou a dohodnou se."),
  h5("Návrh"),
  p("ZO schvaluje poskytnutí finančního příspěvku ve výši 10.000,- Kč pro Naše Krhanice, z.s., Krhanice 252, 257 42 Krhanice, IČO: 17149487 na akci Slavnosti sv. Josefa. S organizací bude uzavřena veřejnoprávní smlouva."),
  vote("PRO ( 5 ) – PROTI ( 0 ) – ZDRŽEL SE ( 3 - Papoušek, Mixa, Laboutková )"),
  h5("Návrh"),
  p("ZO schvaluje bezúplatný pronájem tréninkového hřiště a prostoru před Základní školou Krhanice ve dnech 10.9.2022, 17.9.2022, 18.9.2022 pro Naše Krhanice, z.s., Krhanice 252, 257 42 Krhanice, IČO: 17149487."),
  vote("PRO ( 5 ) – PROTI ( 0 ) – ZDRŽEL SE ( 3 - Papoušek, Mixa, Laboutková )"),

  h4("Žádost RUAH, o.p.s."),
  p("Informace: Byla předložena žádost – přečteno. Jedná se o příspěvek na nákup automobilu pro výkon sociální práce v obci. RUAH působí v obci již mnoho let ku spokojenosti občanů."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje poskytnutí finančního příspěvku ve výši 29.232,- Kč pro RUAH, o.p.s., Křižíkova 2158, 256 01 Benešov, IČO:  24312355 na nákup automobilu pro výkon sociální práce v obci. S organizací bude uzavřena veřejnoprávní smlouva."),
  vote(V8),

  h4("Základní škola – středisko školní jídelna: navýšení provozního příspěvku"),
  p("Informace starosty: Dopis ZŠ – navýšení příspěvku pro školní jídelnu o 28.000, - Kč. Jedná se o příspěvek do školní jídelny na nákup ovoce pro děti a na školení zaměstnanců. Díky poskytnutému příspěvku bude školní jídelna moci udržet pestrost nabídky jídla, zejména ovoce a zeleniny. Další požadavek je na školení zaměstnanců jídelny připravující jídlo."),
  h5("Rozprava"),
  p("I.Dvořák: V rozpočtovém opatření je částka 32 tisíc? Starosta: K částce je připočteno pastelkovné ve výši 4 tisíce Kč."),
  h5("Návrh"),
  p("ZO schvaluje navýšení provozního příspěvku ve výši 28.000, - Kč pro Základní školu Krhanice, okres Benešov pro středisko školní jídelna."),
  vote(V8),
  p("Předseda finančního výboru Bohuslava Kadeřábka přednesl odůvodnění rozpočtového opatření č. 5/2022."),
  h5("Rozprava"),
  p("I.Dvořák: Dotaz na mateřskou školu. Čeho se částka konkrétně týká? Starosta: Vybudování venkovního WC pro děti a oprava spodní části fasády."),
  p("J.Bydžovská: Dotaz na opravu památky u Hodkova. Starosta: Jedná se o kotvu. Bude umístěna na kamenný podstavec."),
  p("L.Maršíková: Kam se umístí stůl na ping pong? Starosta: Bude skládací v klubovně."),
  h5("Návrh"),
  p("ZO schvaluje rozpočtové opatření č. 5/2022."),
  vote(V8),

  h3("5) Koupě, prodej, pronájem"),
  ...ul(["pronajmout část pozemku parc.č. 1884/4 k.ú. Krhanice o výměře 151 m² od 1.8.2022 do 31.7.2026 za cenu 10,- Kč/1 m²/rok za účelem dočasného zřízení zahrádky."]),
  p("Informace starosty: Jedná se o pokračování stávajícího pronájmu pozemku – Helena Voldřichová. Dosavadní smlouva končí dne 31.7.2022"),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronajmout část pozemku parc.č. 1884/4 k.ú. Krhanice o výměře 151 m² od 1.8.2022 do 31.7.2026 za cenu 10,- Kč/1 m²/rok za účelem dočasného zřízení zahrádky Heleně Voldřichové, Lamačova 913/33, 150 00 Praha 3."),
  vote(V8),
  ...ul(["pronajmout část pozemku parc.č. 312/19 k.ú. Krhanice o výměře 120 m² od 1.8.2022 do 31.7.2026 za cenu 10,- Kč/1 m²/rok za účelem dočasného zřízení zahrádky."]),
  p("Informace starosty: Jedná se o pokračování stávajícího pronájmu pozemku – David Modřanský. Smlouva skončila 30.4.2022. Bude dopočítáno nájemné za dobu prokazatelného užívání."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronajmout část pozemku parc.č. 312/19 k.ú. Krhanice o výměře 120 m² od 1.8.2022 do 31.7.2026 za cenu 10,- Kč/1 m²/rok za účelem dočasného zřízení zahrádky Davidovi Modřanskému, Krhanice 70, 257 42 Krhanice."),
  vote(V8),
  ...ul(["pronajmout část pozemku parc.č. 312/19 k.ú. Krhanice o výměře 66 m2 od 1.8.2022 do 31.7.2026 za cenu 10,- Kč/1 m2/rok za účelem dočasného zřízení zahrádky."]),
  p("Informace starosty: Jedná se o pokračování stávajícího pronájmu pozemku – David Richtr. Smlouva skončila 30.6.2022. Bude dopočítáno nájemné za dobu prokazatelného užívání."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronajmout část pozemku parc.č. 312/19 k.ú. Krhanice o výměře 66 m² od 1.8.2022 do 31.7.2026 za cenu 10,- Kč/1 m²/rok za účelem dočasného zřízení zahrádky Davidovi Richtrovi, Krhanice 71, 257 42 Krhanice."),
  vote(V8),
  ...ul(["pronajmout část pozemku parc.č. 1884/4 k.ú. Krhanice o výměře 40 m2 od 1.10.2022 do 30.9.2026 za cenu 10,- Kč/1 m2/rok za účelem dočasného zřízení zahrádky."]),
  p("Informace starosty: Jedná se o pokračování stávajícího pronájmu pozemku – Lenka Bačkovská. Smlouva skončí 30.9.2022."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronajmout část pozemku parc.č. 1884/4 k.ú. Krhanice o výměře 40 m² od 1.10.2022 do 30.9.2026 za cenu 10,- Kč/1 m²/rok za účelem dočasného zřízení zahrádky Mgr. Lence Bačkovské, Nad pískovnou 56, 140 00 Praha 4."),
  vote(V8),
  ...ul(["pronajmout část pozemku parc.č. 229/1 k.ú. Krhanice o výměře 36 m2 od 1.11.2022 do 31.10.2026 za cenu 10,- Kč/1 m2/rok za účelem souvisejícím se stáním pro automobily."]),
  p("Informace starosty: Jedná se o pokračování stávajícího pronájmu pozemku – Jaroslav Hudček. Smlouva skončí 31.10.2022."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronajmout část pozemku parc.č. 229/1 k.ú. Krhanice o výměře 36 m² od 1.11.2022 do 31.10.2026 za cenu 10,- Kč/1 m²/rok za účelem souvisejícím se stáním pro automobily Jaroslavu Hudečkovi, Krhanice 59, 257 42 Krhanice."),
  vote(V8),
  ...ul(["pronajmout část pozemku parc.č. 1884/4 k.ú. Krhanice o výměře 166 m2 od 1.12.2022 do 30.11.2026 za cenu 10,- Kč/1 m2/rok za účelem dočasného zřízení zahrádky."]),
  p("Informace starosty: Jedná se o pokračování stávajícího pronájmu pozemku, pouze změna majitele chaty – Lenka Padevětová."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronajmout část pozemku parc.č. 1884/4 k.ú. Krhanice o výměře 166 m² od 1.12.2022 do 30.11.2026 za cenu 10,- Kč/1 m²/rok za účelem dočasného zřízení zahrádky Lence Padevětové, Slivenecká 109/31, 152 00 Praha 5."),
  vote(V8),
  ...ul(["uzavření smlouvy o zřízení věcného břemene – uložení elektrické přípojky pro pozemek parc.č. 1429/2 k.ú. Krhanice na pozemku parc.č. 1435/20 k.ú. Krhanice na dobu neurčitou za cenu 3.000,- Kč."]),
  p("Informace starosty: Jedná se o elektrickou přípojku pro pozemek 1429/2 – majitel Robert Novotný."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření smlouvy o zřízení věcného břemene – uložení elektrické přípojky pro pozemek parc.č. 1429/2 k.ú. Krhanice na pozemku parc.č. 1435/20 k.ú. Krhanice na dobu neurčitou za cenu 3.000,- Kč s Robertem Novotných, Krhanice 62, 257 42 Krhanice."),
  vote(V8),
  ...ul(["uzavření smlouvy o zřízení věcného břemene – uložení vodovodní přípojky pro pozemek parc.č. 1964/4 k.ú. Krhanice na pozemcích parc.č. 1965/1 a parc.č. 2080/1 k.ú. Krhanice na dobu neurčitou za cenu 6.000,- Kč."]),
  p("Informace starosty: Jedná se o vodovodní přípojku pro pozemek 1964/4 – Miroslav Hnilička."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření smlouvy o zřízení věcného břemene – uložení vodovodní přípojky pro pozemek parc.č. 1964/4 k.ú. Krhanice na pozemcích parc.č. 1965/1 a parc.č. 2080/1 k.ú. Krhanice na dobu neurčitou za cenu 6.000,- Kč s Miroslavem Hniličkou, Markušova 1631/1, 149 00 Praha 4 - Chodov."),
  vote(V8),
  ...ul(["uzavření smlouvy o zřízení věcného břemene – uložení vodovodní přípojky pro pozemek parc.č. 127/7 k.ú. Krhanice na pozemcích parc.č. 127/8 a parc.č. 128/9 k.ú. Krhanice na dobu neurčitou za cenu 6.000,- Kč."]),
  p("Informace starosty: Jedná se o vodovodní přípojku pro pozemek 127/7 – Moniku Víškovou."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření smlouvy o zřízení věcného břemene – uložení vodovodní přípojky pro pozemek parc.č. 127/7 k.ú. Krhanice na pozemcích parc.č. 127/8 a parc.č. 128/9 k.ú. Krhanice na dobu neurčitou za cenu 6.000,- Kč s Monikou Víškovou, Jílovská 261, 257 41 Týnec nad Sázavou."),
  vote(V8),
  ...ul(["uzavření smlouvy o smlouvě budoucí o zřízení věcného břemene a dohodu o umístění stavby č. IE-12-6011284/VB/1 pro stavbu „Krhanice-demontáž NN – nový kNN“ na pozemcích parc.č.  220/4, 220/3, 1978/13, 241/23, 244/8, 2070/5, 224/1, 227/8, 227/7, 220/8 k.ú. Krhanice s ČEZ Distribuce, a.s., IČO: 24729035, se sídlem, Teplická 874/8, Děčín IV-Podmokly, 405 02 Děčín na dobu neurčitou za cenu 38.600,- Kč."]),
  p("Informace starosty: Jedná se o lokalitu od transformátoru u Dlážděnky směrem k viaduktu až do komunikace ke kamenictví."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření smlouvy o smlouvě budoucí o zřízení věcného břemene a dohodu o umístění stavby č. IE-12-6011284/VB/1 pro stavbu „Krhanice-demontáž NN – nový kNN“ na pozemcích parc.č.  220/4, 220/3, 1978/13, 241/23, 244/8, 2070/5, 224/1, 227/8, 227/7, 220/8 k.ú. Krhanice s ČEZ Distribuce, a.s., IČO: 24729035, se sídlem, Teplická 874/8, Děčín IV-Podmokly, 405 02 Děčín na dobu neurčitou za cenu 38.600,- Kč."),
  vote(V8),
  ...ul(["Koupě pozemků Na Starém hřišti pod budoucí místní komunikací"]),
  p("Informace starosty: Jedná se o pozemek a část pozemku, který bude je nyní částečně užíván k příjezdu k nemovitosti. V budoucnu bude převeden na místní komunikaci a zapsán do katastru nemovitostí."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje záměr koupě pozemku parc. č. 148/28 k.ú. Krhanice o výměře 103 m² a nově vzniklý pozemek díl „a“ z pozemku parc.č. 152 k.ú. Krhanice o výměře 75 m², který vznikne na základě geometrického plánu č. 1063-141/2021, za cenu 160,- Kč/m². Obec Krhanice (kupující) uhradí související náklady – vyjmutí ze ZPF a návrhy na vklad do katastru nemovitostí."),
  vote(V8),

  h3("6) Různé"),
  h4("Obecně závazná vyhláška obce"),
  p("Informace místostarosty: Bude se aktualizovat vyhláška o nočním klidu – byla doplněna akce Slavnosti sv. Josefa a jsou aktualizovány termíny u tradičních akcí."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Obecně závaznou vyhlášku obce Krhanice, o nočním klidu."),
  vote(V8),

  h4("Zvýšení ceny vody předané z přivaděče Posázavský vodovod"),
  p("Informace starosty: S účinností od 1.7.2022 došlo ke zvýšení ceny vody předané z přivaděče Posázavský vodovod o 2,26 Kč bez DPH/m3 (na 33,50 Kč bez DPH/m3). Toto navýšení zohledňuje nárůst cen elektrické energie a bylo schváleno na zasedání správní rady členů Posázavský vodovod – DSO konaném dne 2.6.2022. Vyšší cena vody předané se samozřejmě projevuje i v napojených lokalitách. V lokalitě Krhanice tak dochází ke zvýšení ceny vodného o 2,75 Kč s DPH/m3 (na 63,15 Kč s DPH/m3). Do lokality Krhanice vstupuje jednotková cena vody z Posázavského přivaděče."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí a schvaluje cenu vodného ve výši 63,15 Kč/m3 s DPH s účinností od 1.7.2022."),
  vote(V8),

  h4("DSO BENE-BUS: Závěrečný účet"),
  p("Informace starosty: Byl nám předložen Závěrečný účet za rok 2021 a Zpráva o výsledku přezkoumání hospodaření za rok 2021."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Závěrečný účet DSO BENE-BUS za rok 2021 a souhlasí s celoročním hospodařením, a to bez výhrad."),
  vote(V8),
  h5("Návrh"),
  p("ZO bere na vědomí Zprávu o výsledku přezkoumání hospodaření za rok 2021 DSO BENE-BUS."),

  h4("AKTIVNÍ KRHANICE – ROZŠÍŘENÍ OVOCNÉ ALEJE"),
  p("Informace starosty: Přečetl dopis – žádost o souhlas s rozšířením ovocné aleje – parc. č. 2024 k.ú. Krhanice. Spolek Aktivní Krhanice bude žádat o grant. Podmínky budou jako v předešlém případě: Udržitelnost jde plně za spolkem."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje záměr rozšíření ovocné aleje na pozemku parc. č. 2024 k.ú. Krhanice ze strany spolku Aktivní Krhanice, z.s., Krhanice 35, 257 42 Krhanice, IČO: 09017429 s podmínkou udržitelnosti ze strany spolku."),
  vote(V8),

  h4("PŘECHODOVÉ MÍSTO PŘES KOLEJE V KRHANICÍCH"),
  p("Martin Jiřička přečetl dopis ze Správy železnic."),
  h5("Rozprava"),
  p("H.Stranadová: Jak zajistíte bezpečný příchod na nádraží? Starosta: Proběhlo jednání – chodník tam není možný."),
  p("L.Maršíková: Návrh, zda by nebyl možný příchod z křižovatky za viaduktem. Starosta: Napíšu dopis s dotazem na Správu železnic."),
  p("S.Nebeský: Řešil by chodníky komplexně."),

  h4("PRONÁJEM KLUBOVNY – NOVÁ PRAVIDLA"),
  p("Pro oblast školství v rámci dotazníkové akce bylo jednou z priorit více kroužků v základní škole. Přestože je tato priorita závislá na dobrovolnících, kteří kroužky povedou a dále zejména na škole. Tuto aktivitu jsme se rozhodli zařadit do aktualizovaného využívání zázemí klubovny víceúčelového hřiště. Zázemí klubovny je v současné době „drženo“ zejména pro školu z důvodu probíhající rekonstrukce budovy. Toto i nadále bude zachováno. V odpoledních hodinách zkusíme klubovnu nabídnout zejména k využití dobrovolníkům pro kroužky dětí."),
  p("Od 1.9.2022 budou aktualizována pravidla využívání klubovny. Zásadní bude změna okruhu nájemců na občany s trvalým pobytem, fyzické a právnické osoby se sídlem v obci Krhanice."),
  p("Zrušíme Podmínky pronájmu klubovny zázemí víceúčelového hřiště na jednorázové akce nepravidelného charakteru schválené zastupitelstvem obce Krhanice č. 1/2022 ze dne 21.2.2022, a to ke dni 31.8.2022."),
  p("Zájemci budou uzavírat s obcí smlouvu o pronájmu, a to dle zákona o obcích. Schválíme nová Pravidla pronájmu a schválíme novou kalkulaci od 1.9.2022."),
  p("Z hlediska zákona o obcích: Klubovna je majetkem obce. Při pronájmu (pořádání kroužku) podá žadatel žádost o pořádání kroužku, tento pronájem bude vyvěšen a po schválení bude uzavřena příslušná smlouva. Při nepravidelných jednorázových akcích – bude řešeno dle zákona o obcích, v případě akce do 30 dnů bez vyvěšování."),
  p("Do klubovny bude zakoupen pingpongový stůl, společenské hry a zamykatelná skříň. Starosta jedná se sponzorem, který by do klubovny zakoupil dataprojektor včetně montáže."),
  h5("Rozprava"),
  p("Paní Váňová: Vlastník nemovitosti, který nemá v obci trvalé bydliště si klubovnu pronajmout nemůže? Starosta: Zatím nemůže. Pokud se pravidla osvědčí, můžeme je případně rozšířit."),
  p("Paní Váňová: Budou pravidla vyvěšena na stránkách obce? Starosta: Stávající jsou a nová budou taky vyvěšena."),
  p("L.Maršíková: Připadá mi to dost drahé pro spolek, který není výdělečný. Proběhla diskuse o stávajících a nových cenách. Závěr: Doplněna položka ceny pronájmu pro spolky se sídlem v obci Krhanice."),
  h5("Návrh"),
  p("ZO schvaluje Pravidla pronájmu klubovny zázemí víceúčelového hřiště s účinností od 1.9.2022."),
  vote(V8),

  h4("CHODNÍK KE STATKU"),
  p("Na jaře jsme s projektantem řešili chodník směrem ke statku. Projektant prověřil možnosti provedení chodníku podél silnice III/1066 ve směru Krhanice (od schodiště naproti obecnímu úřadu po areál kravína). Chodník je navržen v šířce 1,5 m podél jižní strany vozovky silnice III/1066. Co se týče dotčených pozemků tak se jedná o pozemky Obce Krhanice a pravděpodobný zásah do soukromého pozemku. Bez geodetického zaměření polohopisu současného stavu nelze s určitostí zásah do tohoto pozemku potvrdit. Podél stávající vozovky jsou otevřené zatravněné/dlážděné příkopy pro odvod dešťových vod z vozovky. V případě stavby chodníku přimknutého k vozovce bude tento způsob odvodnění nefunkční, neboť obruba chodníku zamezí natékání dešťových vod do příkopů. Návrh chodníku by tak vyžadoval provedení nové dešťové kanalizace (zatrubnění) v celé délce úseku chodníku. Délka navrhovaného chodníku činí 813,68 m. Většina soukromých pozemků na straně chodníku je níže než stávající vozovka a muselo by tak být provedeno svahování do těchto pozemků, nebo na hranici pozemku provést opěrné zdi. Některé vjezdy na pozemky mají prudký sklon směrem do soukromého pozemku. Chodník musí mít příčný sklon max. 2,0%. Tím by došlo k výraznému zhoršení stávajícího sklonu vjezdu. Provedení chodníku v nezastavěné části obce předpokládá vybudování veřejného osvětlení v části od poslední lampy."),
  p("Hrubý rozpočet stavby:"),
  ...ul([
    "chodník délky 813 m, plocha chodníku 1221,5 m² – 11,5 mil. Kč bez DPH",
    "dešťová kanalizace DN 300, dl. 750 m – 5,2 mil. Kč bez DPH",
    "veřejné osvětlení dl. 350 m – 0,7 mil. Kč bez DPH",
    "Celkem bez DPH – 17,4 mil. Kč bez DPH",
    "Celkem s DPH 21% – 21,23 mil. Kč",
  ]),
  p("Závěr projektanta: Cena díla je značná. Co se týče dotačních titulů, tak neznámějším a nejčastějším je Státní fond dopravní infrastruktury. V žádosti se musí prokazovat určité intenzity chodců, nehodovost a cílová destinace (vhodné jsou nějaké úřední budovy, škola, hřiště apod.)."),
  p("Proto jsme se rozhodli řešení chodníku pouze po dopravní značku konce obce a etapizaci budování chodníku. Necháme si zpracovat etapizaci chodníku v návaznosti na dotační titul, a to u firmy LUCIDA s.r.o."),
  h5("Rozprava"),
  p("P.Bydžovský: Z čeho je chodník rozpočtovaný? Takto vychází 1 metr na 25 tisíc Kč. Starosta: Není to jen chodník, ale i dešťová kanalizace a osvětlení. Samotný chodník by vyšel na 11,5 miliónu Kč."),
  h5("Návrh"),
  p("ZO schvaluje spolupráci při přípravě projektové dokumentace v rámci etapizace prací při budování chodníku od parku nad obecním úřadem po značku konce obce směrem ke statku s firmou LUCIDA s.r.o., Marie Cibulkové 365/34, Praha 4, IČO: 25651099."),
  vote(V8),

  h4("NĚKOLIKA VĚTAMI"),
  p("Starosta přečetl „Několika větami“ – informace, co se v obci stalo, udělalo, … od května 2022."),

  h4("INFORMACE – POKRAČOVÁNÍ NATÁČENÍ SERIÁLU „CO JSTE HASIČI“"),
  p("V srpnu a v září bude v obci pokračovat natáčení 2.série seriálu „Co jste hasiči“."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),

  h4("UZAVÍRKA SILNICE II/105 KAMENNÝ PŘÍVOZ – JÍLOVÉ U PRAHY"),
  p("Uzavírka je plánována od 1.8. do 15.12.2022. Probíhá plánování objízdných tras. Částečně bude přes Krhanice."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),

  h4("NÁZEV: REKONSTRUKCE HLAVNÍHO VODOVODNÍHO PŘIVADĚČE DO OBCE KRHANICE"),
  p("Dotace ze Středočeského infrastrukturního fondu; Drobné vodohospodářské projekty - ISF/DVP/047805/2022"),
  p("18.07.2022  Změna stavu z 'žádost zkontrolována KÚ' na 'schváleno'"),
  p("Dotace - typ dotace: investiční"),
  p("Požadovaná investiční dotace: 1 000 000 Kč"),
  p("Celková požadovaná dotace dle Programu 2022: 1 000 000 Kč"),
  p("Vlastní investiční zdroje: 2 116 662 Kč"),
  p("Vlastní zdroje žadatele: 2 116 662 Kč"),
  p("Předpokládané investiční náklady: 3 116 662 Kč"),
  p("Výběrové řízení bude realizováno ve spolupráci s partnerem Posázaví o.p.s."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje přijetí dotace ze Středočeského kraje, Středočeského infrastrukturního fondu – Drobné vodohospodářské projekty na akci Rekonstrukce hlavního vodovodního přivaděče do obce Krhanice a souhlasí s podmínkami dotace."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje vypsání výběrového řízení na dodavatele stavby pro projekt „Rekonstrukce hlavního vodovodního přivaděče do obce Krhanice“."),
  vote(V8),
  h5("Návrh"),
  p("ZO pověřuje starostu obce realizací vypsání výběrového řízení na dodavatele stavby pro projekt „Rekonstrukce hlavního vodovodního přivaděče do obce Krhanice“."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje spolupráci s Posázavím o.p.s., Zámek Jemniště 1, 257 01 Postupice, IČ 27129772 při zajištění poradenství při realizaci výběrového řízení pro projekt „Rekonstrukce hlavního vodovodního přivaděče do obce Krhanice“."),
  vote(V8),

  h3("7) Diskuse"),
  ...ul([
    "H.Strnadová: Architekt udělal před školou prostor, který je uzavřený. Je to zajímavý nápad. Starosta: Muselo by se ale zamezit příjezdu rodičů až ke škole.",
    "H.Strnadová: Konzultovali jste s někým, jak by měla vypadat nová náves? Proběhla diskuse bez přijetí závěrů.",
    "Paní Váňová: Dotaz na pokácené dřevo ve Svatovicích. Starosta: Pokácené stromy je možné odkoupit za cenu stanovenou zastupitelstvem.",
    "I.Dvořák: Dotaz k základní škole. Na minulém zastupitelstvu zaznělo, že se prodlouží termín dokončení. Už se ví, o kolik se práce prodraží? Starosta: Na posledním kontrolním dni zástupce firmy sdělil, že bude předloženo.",
    "S.Anfilov: Dotaz na zastupitele, zda nevadí, že spolek, který v době konání předchozího zastupitelstva ještě oficiálně neexistoval, žádal o pronájem obecní plochy. T.Kratochvíl: Proto jsme udělili předběžný souhlas. Proběhla diskuse bez přijetí závěrů.",
  ]),

  h3("8) Usnesení a závěr"),
  p("Návrhová komise přečetla usnesení zastupitelstva obce."),
  vote(V8),
  p("Závěr: Zastupitelstvo obce bylo ukončeno v 20:35 hod."),

  p("Datum pořízení zápisu: 25.7.2022"),
  p("Ověřovatelé zápisu a starosta obce, podepsáno v listinné podobě."),
  h4("Přílohy"),
  ...nl(["Svolání zastupitelstva obce", "Prezenční listina zastupitelů", "Prezenční listina občanů"]),
];

async function run() {
  const r = await publishZapis({
    cislo: "4",
    rok: "2022",
    isoDate: "2022-07-18",
    dateLabel: "18. 7. 2022",
    fullDateDot: "18.7.2022",
    pdfPath: "scripts/zapisy-pdf/zapis-2022-4.pdf",
    transcript,
  });
  console.log("OK", r.docId, "blocks", r.blocks);
}
run().catch((e) => { console.error(e); process.exit(1); });
