/* eslint-disable no-console */
import { h3, h4, h5, p, vote, nl, ul, publishZapis, type Block } from "../zapis-lib";

const V9 = "PRO ( 9 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )";

const transcript: Block[] = [
  h4("Přítomni"),
  p("Aleš Papoušek, Jaroslav Mixa, Tomáš Kratochvíl, Aleš Kozel, Jana Laboutková, Martin Jiřička, Petr Dub, Lucie Maršíková, Hana Strnadová"),

  h3("1) Zahájení, přivítání přítomných, konstatování přítomnosti"),
  p("Starosta konstatoval, že zasedání bylo svoláno dne 28.2.2024, bylo vyvěšeno na úřední desce obecního úřadu, tj. tedy nejméně 7 dní před zasedáním. Bylo tedy svoláno řádně a včas v souladu se zákonem o obcích v platném znění. Starosta konstatoval, že podle prezenční listiny je přítomno 9 členů zastupitelstva, tedy nadpoloviční většina členů zastupitelstva. K předchozímu zápisu nebyly vzneseny námitky."),
  h5("Určení zapisovatele"),
  p("Zápisem zasedání zastupitelstva obce byla pověřena Ing. Alena Kratochvílová."),

  h3("2) Volba návrhové komise a ověřovatelů zápisu"),
  p("Starosta přednesl návrh návrhové komise a ověřovatelů zápisu."),
  h5("Návrh"),
  p("ZO schvaluje návrhovou komisi ve složení: Jaroslav Mixa, Jana Laboutková."),
  h5("Návrh"),
  p("ZO schvaluje ověřovatele zápisu ve složení Tomáš Kratochvíl, Petr Dub."),
  vote(V9),

  h3("3) Schválení programu"),
  p("Starosta přečetl program."),
  ...nl([
    "Zahájení",
    "Volba návrhové komise a ověřovatelů zápisu",
    "Schválení programu",
    "Zpráva Kontrolního výboru",
    "Rozpočtové opatření",
    "Obecně závazná vyhláška obce",
    "Koupě, prodej, pronájem",
    "Různé",
    "Diskuse",
    "Závěr",
  ]),
  p("Starosta: Má někdo návrh na změnu nebo doplnění programu?"),
  h5("Návrh"),
  p("ZO schvaluje program zasedání zastupitelstva obce."),
  vote(V9),

  h3("4) Zpráva kontrolního výboru"),
  p("Předseda kontrolního výboru Martin Jiřička seznámil se zprávou kontrolního výboru ze dne 18.12.2023."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí Zprávu kontrolního výboru ze dne 18.12.2023."),

  h3("5) Rozpočtové opatření"),
  h4("Rozpočtové opatření č. 1/2024"),
  p("Předseda finančního výboru Petr Dub seznámil s rozpočtovým opatřením č. 1/2024."),
  h5("Rozprava"),
  p("H.Strnadová: Dotaz na vratku ze základní školy. Starosta: Zásadní je úspora za energie a z oprav budovy."),
  p("L.Maršíková: Dotaz na rekonstrukci bytu. Máme nějaký odhad? Starosta: Řešili jsme to ve Stavební komisi, poptáme místní firmy. Byt má návaznost na místo pedagoga v základní škole."),
  p("L.Maršíková: Dotaz na opravu střešní konstrukce. Ocenila, že bude oslovena další firma."),
  p("L.Maršíková: Při opravě střešní krytiny nebyla řešena sanace krovů? Starosta: Ne, byla položena pouze nová krytina."),
  p("I.Dvořák: Dotaz na vratku provozního příspěvku školy. Škola dostává příspěvek na základě počtu žáků. Z Ministerstva školství by měl přijít příspěvek 30 tisíc na žáka. Starosta: Je to o rozpočtovém určení daní."),
  p("I.Dvořák: Dotaz, zda má škola dostatek finančních prostředků na platy pro nepedagogické zaměstnance. Starosta: Dle sdělení ředitelky, tak v podstatě ano."),
  p("I.Dvořák: Dotaz na cestu k Borové. Bude se řešit i odvodnění? J.Mixa udělá se 30 cm štěrkové lože, do kterého se panely uloží."),
  p("H.Strnadová: Panely budou klouzat. Panely v zatáčce na začátku cesty kloužou, je na nich písek. Proběhla diskuse se závěrem: Zvýší se údržba na panelech u zrcadla."),
  h5("Návrh"),
  p("ZO schvaluje rozpočtové opatření č. 1/2024."),
  vote(V9),

  h3("6) Obecně závazná vyhláška obce Krhanice o nočním klidu"),
  p("Místostarosta obce seznámil s obecně závaznou vyhláškou o nočním klidu – dochází k zahrnutí nových kulturních akcí, kdy dojde k omezení nočního klidu."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  p("A.Kozel odešel v 18:26 hod."),
  h5("Návrh"),
  p("ZO schvaluje Obecně závaznou vyhlášku obce Krhanice o nočním klidu."),
  vote("PRO ( 8 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )"),

  h3("7) Koupě, prodej, pronájem"),
  ...ul([
    "uzavřít Smlouvu o výpůjčce části pozemku parc.č. 502 k.ú. Krhanice o výměře 138 m² za účelem výstavby a udržování 3 tůní bezúplatně od 8.3.2024 do 7.3.2028.",
  ]),
  p("Informace starosty:"),
  p("Smlouvu o výpůjčce – Byla doplňována ze strany obce a spolku do finální podoby."),
  p("A.Kozel přišel v 18:30 hod."),
  h5("Rozprava"),
  p("L.Maršíková: Bude spolek zodpovídat za černou skládku, pokud by tam vznikla? Starosta: V tom případě se obraťte na obec, pan místostarosta skládku odstraní."),
  p("P.Dvořáková: Je potřeba smlouva o výpůjčce? Starosta: Je to stavba na cizím pozemku. Navíc podléhá vodoprávnímu řízení."),
  p("Proběhla diskuse – na výsadbu keřů, stromů a umístění laviček nepevně spojených se zemí není potřeba smlouva."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o výpůjčce části pozemku parc.č. 502 k.ú. Krhanice o výměře 138 m² za účelem výstavby a udržování 3 tůní bezúplatně od 8.3.2024 do 7.3.2028 se spolkem Aktivní Krhanice, z.s., se sídlem Krhanice č.p. 35, 257 42 Krhanice, IČO: 09017429."),
  vote("PRO ( 5 ) – PROTI ( 1 - Kratochvíl ) – ZDRŽEL SE ( 3 – Maršíková, Strnadová, Kozel )"),
  ...ul([
    "prodat oddělenou část z pozemku parc.č. 403/2 k.ú. Krhanice o výměře cca 7000 m² za cenu 150 Kč/1m².",
  ]),
  p("Informace starosty: Starosta seznámil s dopisem od Kámen Zbraslav. Cena za m² je podle obdobného prodeje v dané lokalitě. Druhou možností je odhad ceny odhadcem. Obec v minulosti usilovala o získání pozemku 361/1 k.ú. od Pozemkového fondu. Pozemek byl předmětem soudního řízení a následně byl vydán v restituci. Pozemek nakonec odkoupil Kámen Zbraslav. Je to pro nás pozemek důležitý jako izolační zeleň vůči zástavbě."),
  h5("Rozprava"),
  p("H.Strnadová: Nebude lom na pozemku (co by obec prodávala) těžit? Starosta: Rozsah těžby je povolený v minulosti. Mohou odtěžit celý kopec."),
  p("I.Dvořák: Za kolik chce lom pozemek obci prodat? Starosta: Za stejnou částku, co obec, tedy 150 Kč/1m²."),
  p("Starosta: Lom by na získaném pozemku vybudoval ochranný val."),
  p("V.Duša: V českém právu nelze nikomu nic prodat s podmínkou."),
  p("Proběhla diskuse se závěrem, že se bude s lomem o prodeji a koupi jednat."),
  h5("Návrh"),
  p("ZO pověřuje starostu svoláním schůzky s firmou Kámen Zbraslav, a.s. o vzájemném prodeji části pozemků."),
  vote("PRO ( 5 ) – PROTI ( 3 – Papoušek, Mixa, Kozel ) – ZDRŽEL SE ( 1 - Kratochvíl )"),
  ...ul([
    "uzavřít Smlouvu o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby č. IZ-12-6003886 na pozemcích parc. č. 1942/9 a 1956/33 k.ú. Krhanice s ČEZ Distribuce, a.s., IČO 24729035, DIČ CZ24729035, se sídlem Děčín IV-Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 8390 Kč na umístění zařízení kabelového vedení a pojistkové skříně.",
  ]),
  p("Informace starosty: jedná se o pozemky v chatové oblasti v Prosečnici."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby č. IZ-12-6003886 na pozemcích parc. č. 1942/9 a 1956/33 k.ú. Krhanice s ČEZ Distribuce, a.s., IČO 24729035, DIČ CZ24729035, se sídlem Děčín IV-Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 8390 Kč na umístění zařízení kabelového vedení a pojistkové skříně."),
  vote(V9),

  h3("8) Různé"),
  h4("Zpráva o výsledku přezkoumání hospodaření obce Krhanice"),
  p("Starosta seznámil se Zápisem z přezkoumání hospodaření obce ze dne 23.1.2024 s výsledkem nebyly zjištěny chyby a nedostatky – kontrolu provedl Krajský úřad Středočeského kraje, Odbor interního auditu a kontroly."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí Zprávu o výsledku přezkoumání hospodaření obce za rok 2023 ze dne 23.1.2024."),

  h4("Inventarizační zpráva obce Krhanice za rok 2023"),
  p("Předseda inventarizační komise Aleš Papoušek přečetl inventarizační zprávu o proběhlé inventarizaci za rok 2023."),
  p("Inventarizace proběhla v řádném termínu, informace o stavu na jednotlivých účtech jsou uvedeny v příloze. Zhodnocení hospodaření obce bude v rámci Závěrečného účtu a schválení účetní závěrky na příštím zastupitelstvu."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí Inventarizační zprávu obce Krhanice za rok 2023."),

  h4("Úřad práce – veřejně prospěšné práce"),
  p("Informace starosty: Úřad práce má program pro podporu nezaměstnaných. Pro osoby se sníženou možností získání zaměstnání jsme schopni vytvořit dočasně 1 pracovní místo."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje a souhlasí s účastí obce Krhanice v rámci projektu Úřadu práce Příbram, pobočka Benešov v zaměstnávání osob se sníženou možností získání zaměstnání – 1 pracovní místo."),
  vote(V9),

  h4("Výběrové řízení chodník „Krhanice - chodník podél silnice III/1066“"),
  p("Informace starosty: Na akci Krhanice – chodník podél silnice III/1066 jsme dotaci na Státním fondu dopravní infrastruktury neobdrželi."),
  p("Proběhlo výběrové řízení, ve kterém byly osloveny 4 firmy k předložení nabídky."),
  p("Výběrové řízení proběhlo v pondělí 4.3.2024."),
  p("Nabídku podaly tři firmy."),
  p("Hodnotícím kritériem byla nejnižší nabídková cena."),
  p("Výsledek:"),
  ...ul([
    "1. LAROS s.r.o., IČ 49826514, nabídková cena 5 837 783,14 Kč",
    "2. Jaroslav Žaba, IČ 86934431, nabídková cena 5 449 017,70 Kč",
    "3. Zdeněk Makovíni, IČ 74225740, nabídková cena 5 629 901,96 Kč",
  ]),
  p("Nejvhodnější nabídkou, tj. nabídkou nejlépe splňující kritérium stanovené zadavatelem v textu zadávací dokumentace pro zakázku malého rozsahu mimo režim zákona č. 134/2016 Sb., o zadávání veřejných zakázek k zakázce „Krhanice - chodník podél silnice III/1066“ je nabídka účastníka:"),
  p("obchodní firma/jméno: Jaroslav Žaba"),
  p("Sídlo: Pecerady 69, 257 41 Týnec nad Sázavou"),
  p("IČO: 86934431"),
  p("Nabídková cena 5 449 017,70 Kč bez DPH"),
  p("DPH: 1 144 293,72 Kč"),
  p("Nabídková cena 6 593 311,41 Kč Kč s DPH"),
  h5("Rozprava"),
  p("L.Maršíková: V rozpočtu je dešťová kanalizace, která se již pokládala. Starosta: Pokud nám schválí MěÚ Benešov změnu stavby před dokončením, kdy se napojíme na pokládanou kanalizaci, tato část nebude fakturována. V opačném případě musíme stavbu udělat dle stavebního povolení."),
  p("I.Dvořák: Dotaz, kam vede dešťová kanalizace? Starosta ukázal na mapě."),
  p("P.Bydžovský: Čtyřicítka roura dešťové kanalizace při přívalovém dešti nebude dostačující. Starosta: Podle projektanta ano."),
  h5("Návrh"),
  p("ZO bere na vědomí neschválení žádosti o dotaci pro projekt „Krhanice – chodník podél silnice III/1066 na Státním fondu dopravní infrastruktury."),
  h5("Návrh"),
  p("ZO schvaluje uzavření smlouvy o dílo na akci „Krhanice - chodník podél silnice III/1066“ s Jaroslavem Žabou, Pecerady 69, 257 41 Týnec nad Sázavou, IČO: 86934431 ve výši 6 593 311,41 Kč."),
  vote(V9),
  h5("Návrh"),
  p("ZO pověřuje starostu podpisem smlouvy o dílo na akci „Krhanice - chodník podél silnice III/1066“ s Jaroslavem Žabou, Pecerady 69, 257 41 Týnec nad Sázavou, IČO: 86934431."),
  vote(V9),

  h4("Dotace"),
  p("Informace starosty:"),

  h4("Tělocvična obce Krhanice"),
  p("Obec Krhanice v roce 2023 požádala o dotaci na tělocvičnu u Národní sportovní agentury. Rozpočet byl 45 862 470 Kč, požadovaná dotace je 30 000 000 Kč. Výsledek: dotaci neobdržíme."),
  h5("Návrh"),
  p("ZO bere na vědomí neschválení žádosti o dotaci pro projekt „Tělocvična obce Krhanice“ ze strany Národní sportovní agentury."),

  h4("Dotace na fotovoltaiku střechy klubovny"),
  p("Fotovoltaika: jedná se o výzvu"),
  h5("Výzva RES+ č. 3/2024 - KOMUNÁLNÍ FVE NA VEŘEJNÝCH BUDOVÁCH PRO MALÉ OBCE"),
  ...ul([
    "Předmětem podpory je instalace nových fotovoltaických elektráren (dále jen „FVE“) s instalovaným výkonem do 1 MWp (včetně) na jedno předávací místo do distribuční nebo přenosové soustavy (dále jen „DS/PS“).",
    "Oprávněnými žadateli jsou obce na území ČR s maximálním počtem obyvatel 3000 k 1. 1. 2023 dle údajů Českého statistického úřadu.",
    "Výše dotace je až 75 % z celkových výdajů projektu.",
  ]),
  p("Stav: schváleno od ČEZu fotovoltaika na klubovně."),
  h5("Rozprava"),
  p("H.Strnadová: Elektrickou energii by využívala obec? Starosta: Ano."),
  p("L.Maršíková: Spoluúčast je 25%. Spočítal někdo, zda se to vyplatí? Starosta: ČEZ nyní změnil podmínky. Nelze to přesně propočítat. Náklady na pořízení bez baterie by byly cca 400 tisíc Kč."),
  p("P.Bydžovský: Kde je přípojné místo na veřejné osvětlení? Stálo by za to uvažovat o využití energie pro veřejné osvětlení. Nemusely by se platit poplatky za přenos."),
  p("P.Dvořáková: Návrh oslovit ČEZ, který by vybudoval sám fotovoltaiku bez vstupních nákladů zájemce."),
  p("Proběhla diskuse o zkušenostech s fotovoltaikou."),
  h5("Návrh"),
  p("ZO schvaluje podání žádosti o dotaci na SFŽP v rámci výzvy RES+ č. 3/2024 – Komunální FVE na veřejných budovách pro malé obce pro projekt „Fotovoltaika na střeše klubovny zázemí víceúčelového hřiště v Krhanicích“."),
  vote("PRO ( 5 ) – PROTI ( 4 – Maršíková, Strnadová, Mixa, Kozel ) – ZDRŽEL SE ( 0 )"),

  h4("Dotace – dopravní automobil pro zásahovou jednotku hasičů"),
  p("Dopravní automobil pro zásahovou jednotku hasičů:"),
  p("Podání dotace na Středočeský kraj v rámci „Programu 2024 pro poskytování dotací z rozpočtu Středočeského kraje ze Středočeského Fondu podpory dobrovolných hasičů a složek IZS“ ve spolupráci s Posázavím o.p.s."),
  p("Informace Tomáše Kratochvíla, který vysvětlil, proč zásahová jednotka potřebuje dopravní automobil a jaké zkušenosti s pořízením mají okolní obce."),
  p("Navrhl tyto firmy k oslovení:"),
  ...nl([
    "MAN Truck & Bus Czech Republic, Rudolfa Diesela 600, 250 70 Postřižín ČR, jiri.votava@man.eu, tel: 736 620 182, IČ/DIČ 46965904/CZ46965904",
    "EMBEFOR s.r.o., Korunní 2569/108, 10100 Praha CZ, info@embefor.cz, tel: 774 840 103, IČ/DIČ 06130900/CZ06130900",
    "JÍŠA s.r.o., Kolčavská 1, 180 00 Praha 9 - Libeň, zakazky@jisa.cz, +420 284 820 857, IČ/DIČ 26724332/CZ26724332",
    "PROGRES SERVIS SIBŘINA s.r.o., Masojedy 59, 282 01 Masojedy u Českého Brodu, info@progressibrina.cz, +420 281 091 311, IČ/DIČ 00549142/CZ00549142",
  ]),
  h5("Rozprava"),
  p("H.Strnadová: Jaká bude cena? T.Kratochvíl: Záleží na našich požadavcích. Např. Lešany pořídily dopravní automobil za cca 1300000 Kč."),
  h5("Návrh"),
  p("ZO schvaluje podání žádosti o dotaci pro projekt „Dopravní automobil pro JSDHO Krhanice“ na Středočeském kraji v rámci Programu 2024 pro poskytování dotací z rozpočtu Středočeského kraje ze Středočeského Fondu podpory dobrovolných hasičů a složek IZS."),
  vote("PRO ( 8 ) – PROTI ( 0 ) – ZDRŽEL SE ( 1 – Strnadová )"),
  h5("Návrh"),
  p("ZO pověřuje starostu obce realizací výběrového řízení na projekt „Dopravní automobil pro JSDHO Krhanice“ ve spolupráci s Posázavím o.p.s., Zámek Jemniště 1, 257 01 Postupice, IČO 27129772."),
  vote("PRO ( 8 ) – PROTI ( 0 ) – ZDRŽEL SE ( 1 – Strnadová )"),

  h4("Klubovna zázemí víceúčelového hřiště"),
  p("Informace starosty o anketě o klubovně, návrhu nových pravidel."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Pravidla pronájmu klubovny zázemí víceúčelového hřiště s účinností od 11.3.2024."),
  vote(V9),

  h4("Okružní křižovatka"),
  p("Starosta seznámil přítomné s uzavírkou křižovatky kvůli výstavbě okružní křižovatky. Pro nás je zásadní chodník přes křižovatku, kdy se vyřeší problém s přecházením občanů. Obecní úřad řeší výjimku ze zákazu vjezdu na komunikaci k lomu, aby si občané nevyřizovali sami."),
  h5("Rozprava"),
  p("P.Dvořáková: Dotaz na dopravu dětí do Týnce. Starosta: Jízdní řády jsem ještě neviděl."),
  p("I.Dvořák: Bude nějaká výjimka pro rodiče, co jezdí od Prosečnice? Starosta: Ano, vyřizuji jak pro žáky, tak i pro pedagogy."),
  p("I.Dvořák: Dotaz na zbývající část chodníku u viaduktu. Starosta: Měl by to letos udělat projektant."),
  p("P.Bydžovský: Nešlo by pod viaduktem místo chodníku umístit city bloky? Starosta: Zeptám se na MěÚ Benešov."),
  p("Starosta dále informoval o dočasných chodnících pro pěší při uzavírce křižovatky. V rámci jednání stavební komise jsme řešili zachování chodníku směrem k Týnci, vybudování schodů pro pěší k vlakové zastávce, úpravu cesty k rampě pro pěší, maminky s kočárky, … Zároveň budeme sledovat využívání prostor k chození k vlakové zastávce ze strany veřejnosti."),
  p("Starosta dále informoval o realizaci opatření u bývalé budovy vlakového nádraží a kolem vlakové zastávky. Po dohodě s Českými drahami zde byly umístěny betonové city bloky. Bylo tak zabráněno parkování velkých vozidel, které poškozovaly pochozí plochy k vlakové zastávce, bránily úpravě ploch kolem vlakové zastávky, …"),
  p("Proběhla diskuse k daným tématům."),

  h3("9) Diskuse"),
  ...ul([
    "L.Maršíková: Dotaz na pytle na plasty a papír k nemovitostem (pilotní projekt). J. Mixa: Byli jsme jediní, kteří to po technických službách požadovali. Zůstaneme u stávajícího systému. Náklady by byly velké (cca 70 Kč/1 pytel při svozu od nemovitosti).",
    "I.Dvořák: Dotaz na poukázky na vývoz splaškových vod na ČOV Prosečnice. Starosta: Vysvětlil, jak byl v minulosti systém zaveden. Nyní je vývoz ze strany Vodovodů a kanalizací Týnec levnější. Vývoz na poukázku firmou Nováková bude zárukou, že vývoz proběhne, a to na ČOV Prosečnice.",
    "L.Maršíková: Dotaz na revize územního rozhodnutí na splaškové řady. Starosta: Do konce června provede projektantská firma.",
    "P.Bydžovský: Tlaková kanalizace je nákladově oproti gravitační nevýhodná. Proběhla diskuse o tom, jaký typ kanalizace by byl levnější na provoz a údržbu.",
    "B.Mára: Požádal obec o údržbu cesty od Gabčíkova do rekreační oblasti Svatovice. Starosta: Komunikaci udržujeme na základě podnětů. Provedeme údržbu.",
  ]),

  h3("10) Závěr"),
  p("Zastupitelstvo obce bylo ukončeno v 20:59 hod."),

  p("Datum pořízení zápisu: 14.3.2024"),
  p("Ověřovatelé zápisu a starosta obce, podepsáno v listinné podobě."),
  h4("Přílohy"),
  ...nl([
    "Svolání zastupitelstva obce",
    "Prezenční listina zastupitelů",
    "Prezenční listina občanů",
  ]),
];

async function run() {
  const r = await publishZapis({
    cislo: "1",
    rok: "2024",
    isoDate: "2024-03-07",
    dateLabel: "7. 3. 2024",
    fullDateDot: "7.3.2024",
    pdfPath: "scripts/zapisy-pdf/zapis-2024-1.pdf",
    transcript,
  });
  console.log("OK", r.docId, "blocks", r.blocks);
}
run().catch((e) => { console.error(e); process.exit(1); });
