/* eslint-disable no-console */
// One-off: faithful transcript of Zápis č. 7/2022 (22.12.2022), transcribed
// visually from the official PDF (12 pages). Structure per the approved golden
// sample scripts/build-zapis-2026-1.ts and the contract in AGENT-SPEC.md.
import { h3, h4, h5, p, vote, nl, ul, publishZapis, type Block } from "../zapis-lib";

const V8 = "PRO ( 8 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )";

const transcript: Block[] = [
  h4("Přítomni"),
  p("Aleš Papoušek, Jaroslav Mixa, Tomáš Kratochvíl, Martin Jiřička, Jana Laboutková, Petr Dub, Lucie Maršíková, Ivan Dvořák"),
  h4("Omluveni"),
  p("Aleš Kozel"),

  h3("1) Zahájení, přivítání přítomných, konstatování přítomnosti"),
  p("Starosta konstatoval, že zasedání bylo svoláno dne 14.12.2022, bylo vyvěšeno na úřední desce obecního úřadu, tj. tedy nejméně 7 dní před zasedáním. Bylo tedy svoláno řádně a včas v souladu se zákonem o obcích v platném znění. Starosta konstatoval, že podle prezenční listiny je přítomno 8 členů zastupitelstva, tedy nadpoloviční většina členů zastupitelstva. K předchozímu zápisu nebyly vzneseny námitky."),
  h5("Určení zapisovatele"),
  p("Zápisem zasedání zastupitelstva obce byla pověřena Ing. Alena Kratochvílová."),

  h3("2) Volba návrhové komise a ověřovatelů zápisu"),
  p("Starosta přednesl návrh návrhové komise a ověřovatelů zápisu."),
  h5("Návrh"),
  p("ZO schvaluje návrhovou komisi ve složení: Jaroslav Mixa, Jana Laboutková."),
  h5("Návrh"),
  p("ZO schvaluje ověřovatele zápisu ve složení Petr Dub, Tomáš Kratochvíl."),
  vote(V8),

  h3("3) Schválení programu"),
  p("Starosta přečetl program."),
  ...nl([
    "Zahájení",
    "Volba návrhové komise a ověřovatelů zápisu",
    "Schválení programu",
    "Zpráva finančního výboru o kontrole hospodaření obce Krhanice v roce 2022; Zpráva o výsledcích veřejnosprávních kontrol hospodaření Mateřské školy Krhanice a Základní školy Krhanice v roce 2022",
    "Rozpočtové opatření",
    "Střednědobý výhled rozpočtu obce Krhanice na období 2022 – 2026; Rozpočet obce Krhanice na rok 2023",
    "Koupě, prodej, pronájem",
    "Různé",
    "Diskuse",
    "Usnesení a závěr",
  ]),
  p("Starosta: Má někdo návrh na změnu nebo doplnění programu?"),
  h5("Návrh"),
  p("ZO schvaluje program zasedání zastupitelstva obce."),
  vote(V8),

  h3("4) Zpráva finančního výboru o kontrole hospodaření obce Krhanice v roce 2022; Zpráva o výsledcích veřejnosprávních kontrol hospodaření Mateřské školy Krhanice a Základní školy Krhanice v roce 2022"),
  p("Petr Dub jako předseda Finančního výboru obce Krhanice seznámil s kontrolou hospodaření obce Krhanice v roce 2022. Dále seznámil s proběhlými veřejnosprávními kontrolami hospodaření příspěvkových organizací Mateřské školy Krhanice a Základní školy Krhanice v roce 2022. Kontroly proběhly ve dnech 16.11.2022 a 24.11.2022."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí zprávu finančního výboru o kontrole hospodaření obce Krhanice v roce 2022 ze dne 16.11.2022."),
  h5("Návrh"),
  p("ZO bere na vědomí protokoly o průběhu a výsledcích veřejnosprávních kontrol příspěvkových organizací Základní škola Krhanice a Mateřská škola Krhanice v roce 2022 ze dne 16.11.2022 a 24.11.2022."),

  h3("5) Rozpočtové opatření"),
  h4("Rozpočtové opatření č. 9/2022"),
  p("Předseda finančního výboru Petr Dub seznámil s rozpočtovým opatřením č. 9/2022."),
  h5("Rozprava"),
  p("I.Dvořák: Dotaz na odměnu od firmy EKO-KOM. Jak je vyplácena – měsíčně, čtvrtletně? Starosta: Čtvrtletně."),
  p("I.Dvořák: Dotaz na částku 200 tisíc – odvádění a čištění odpadních vod? Starosta: Byla určená pro projekční firmu – nové splaškové řady. Práce nebyla odvedena."),
  p("I.Dvořák: Kde se nachází lokalita, pro kterou měl být projekt zpracován? Starosta: Od nádrže u vrby k viaduktu a od pítka u památníku směrem k železničnímu viaduktu."),
  h5("Návrh"),
  p("ZO schvaluje rozpočtové opatření č. 9/2022."),
  vote(V8),

  h3("6) Střednědobý výhled rozpočtu obce Krhanice na období 2022 – 2026; Rozpočet obce Krhanice na rok 2023"),
  h4("Střednědobý výhled rozpočtu 2022 – 2026"),
  p("Informace starosty: Starosta seznámil přítomné se Střednědobým výhledem rozpočtu na období 2023 – 2026. Obec reaguje střednědobým výhledem rozpočtu na aktuální stav rozpočtu obce. Hospodaření obce (výhled a rozpočet) bude v r. 2023 ovlivňovat dokončení realizace akce Zateplení, výměna zdroje tepla v ZŠ v obci Krhanice a Pořízení centrální vzduchotechniky do ZŠ Krhanice, která bude nadále financována z dotačních prostředků, vlastních zdrojů a podpory ze SFŽP formou zápůjčky. Od r. 2023 jsou ve výhledu zahrnuty splátky zápůjčky a související úroky. Ve výhledu jsou zahrnuty investiční akce (Rekonstrukce hlavního vodovodního přivaděče do obce Krhanice – zahájení, Rekonstrukce památníku obětem 2.světové války - zahájení a Rekonstrukce návsi a okolních chodníků – dokončení), zde je spoluúčast obce a dotace."),
  p("Tyto akce mají prioritu a od nich se odvíjí financování, a tedy i střednědobý výhled a dále rozpočet obce."),
  h5("Rozprava"),
  p("I.Dvořák: Dotaz, zda se výhled dělá a schvaluje každý rok?: Starosta: Ano."),
  p("L.Maršíková: Pro upřesnění – obec realizuje chodník podél silnice III/1066, dostaneme dotaci? Starosta: Dotaci jsme nezískali, ale dle doporučení můžeme požádat znovu."),
  h5("Návrh"),
  p("ZO schvaluje Střednědobý výhled rozpočtu obce Krhanice na období 2023 – 2026."),
  vote("PRO ( 7 ) – PROTI ( 1 - Maršíková ) – ZDRŽEL SE ( 0 )"),

  h4("Rozpočet obce Krhanice na rok 2023"),
  h5("Informace starosty – oblast přípravy rozpočtu 2023"),
  p("Informace starosty: Starosta seznámil s oblastí přípravy rozpočtu: oslovení žadatelů a příspěvkových organizací, jednání Komise pro sestavení rozpočtu, … až po zveřejnění návrhu rozpočtu."),

  h4("ROZPOČET 2023"),
  h5("Dobrovolné svazky obcí: Bene-Bus, Týnecko-svazek obcí, Posázavský vodovod - DSO"),

  h5("DSO Bene-Bus"),
  p("Starosta seznámil s Rozpočtem na rok 2023 – přebytkový. Provozní příspěvek obce Krhanice bude činit 292.320,- Kč."),
  p("Bene-Bus předložil také Střednědobý výhled rozpočtu na období 2024-2026."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Rozpočet Bene-Bus na rok 2023 jako přebytkový."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje Střednědobý výhled rozpočtu Bene-Bus na období 2024-2026."),
  vote(V8),

  h5("DSO Týnecko-svazek obcí"),
  p("Starosta seznámil s návrhem Rozpočtu na rok 2023 – vyrovnaný rozpočet. Provozní příspěvek obce Krhanice bude činit 12.595, - Kč."),
  p("Týnecko-svazek obcí předložil také Střednědobý výhled rozpočtu na období 2024-2025."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Rozpočet Týnecko-svazek obcí na rok 2023 jako vyrovnaný."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje Střednědobý výhled rozpočtu Týnecko-svazek obcí na období 2024-2025."),
  vote(V8),

  h5("Posázavský vodovod – dobrovolný svazek obcí"),
  p("Starosta seznámil s návrhem Rozpočtu na rok 2023 – schodkový rozpočet, schodek krytý finančními prostředky z minulých let."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Rozpočet Posázavský vodovod – dobrovolný svazek obcí na rok 2023 jako schodkový, schodek bude krytý finančními prostředky z minulých let."),
  vote(V8),

  h5("Schválení výše provozního příspěvku pro zřízené příspěvkové organizace: Základní škola Krhanice a Mateřská škola Krhanice"),
  p("Návrh Rozpočtu a Návrh Střednědobého výhledu rozpočtu příspěvkových organizací zřízených obcí Krhanice byl v řádném termínu vyvěšen. Návrhy rozpočtů odrážejí zejména nejistou situaci v energiích a inflaci (navyšování cen služeb, materiálu,…) – navýšení příspěvků oproti r. 2022."),
  p("Návrh provozního příspěvku pro příspěvkové organizace pro rok 2023:"),
  ...ul([
    "Mateřská škola Krhanice, okres Benešov: 604.850,- Kč",
    "Základní škola Krhanice, okres Benešov: 3.463.093,- Kč",
    "v tom:",
    "Středisko Základní škola: 2.609.914,- Kč",
    "Středisko Školní jídelna: 856.179,- Kč",
  ]),

  h5("Fond obnovy vodovodů obcí Krhanice a Prosečnice"),
  p("Návrh Rozpočtu Fondu obnovy vodovodů obcí Krhanice a Prosečnice byl v řádném termínu vyvěšen. Návrh Rozpočtu Fondu reaguje na získání dotace na Rekonstrukci hlavního vodovodního přivaděče do obce Krhanice. Příjmy – zaslání prostředků dotačních a částečné spoluúčasti obce, Výdaje – zapojení těchto prostředků + zapojení finančních prostředků z let minulých."),
  h5("Návrh"),
  p("ZO schvaluje Rozpočet Fondu financování obnovy vodovodů obcí Krhanice a Prosečnice pro rok 2023 jako schodkový, schodek bude krytý finančními prostředky z minulých let."),
  vote(V8),

  h5("Rozpočet obce Krhanice na rok 2023"),
  p("Návrh Rozpočtu obce Krhanice na rok 2023 byl v řádném termínu vyvěšen na úřední desce a elektronické úřední desce. Příloha Rozpočtu obce Krhanice na rok 2023 byla v řádném termínu vyvěšena na elektronické úřední desce, vzhledem ke kapacitě úřední desky a dle zákona."),
  p("Rozpočet byl koncipován s těmito prioritami:"),
  ...nl(["realizace investičních projektů", "podpora služeb pro obyvatelstvo"]),
  p("V Návrhu Rozpočtu obce pro rok 2023 příjmy rozpočtu tvoří zejména:"),
  h5("OBLAST PŘÍJMŮ"),
  p("Daňové příjmy:"),
  ...ul([
    "výnosy daní nebo podíly na nich (rozpočtové určení daní),",
    "příjmy z vlastní správní činnosti včetně příjmů z výkonů státní správy,",
    "příjmy z místních poplatků.",
  ]),
  p("Nedaňové příjmy:"),
  ...ul([
    "příjmy z vlastního majetku a majetkových práv,",
    "příjmy z výsledků vlastní činnosti,",
  ]),
  p("Kapitálové příjmy:"),
  ...ul(["nerozpočtováno, nejsou uzavřeny žádné smlouvy v této oblasti v tuto dobu."]),
  p("Přijaté dotace:"),
  ...ul([
    "dotace ze státního rozpočtu a ze státních fondů,",
    "dotace z rozpočtu kraje.",
  ]),
  h5("OBLAST VÝDAJŮ"),
  p("Dle zákona se z rozpočtu obce a s ohledem na naši obec (její velikost, činnost, charakter,…) hradí zejména:"),
  ...ul([
    "závazky vyplývající pro obec z plnění povinností uložených jí zákony,",
    "výdaje na vlastní činnost obce v její samostatné působnosti, zejména výdaje spojené s péčí o vlastní majetek a jeho rozvoj,",
    "výdaje spojené s výkonem státní správy, ke které je obec pověřena zákonem,",
    "závazky vyplývající pro obec z uzavřených smluvních vztahů v jejím hospodaření a ze smluvních vztahů vlastních organizací, jestliže k nim přistoupila,",
    "závazky přijaté v rámci spolupráce s jinými obcemi nebo s dalšími subjekty, včetně příspěvků na společnou činnost,",
    "úhrada úroků z přijatých půjček a úvěrů,",
    "výdaje na podporu subjektů provádějících veřejně prospěšné činnosti,",
    "jiné výdaje uskutečněné v rámci působnosti obce, včetně darů a příspěvků na sociální nebo jiné humanitární účely.",
  ]),

  h5("Pravidla pro Občanský návrhový projektový rozpočet"),
  p("Starosta seznámil s pravidly Občanského návrhového rozpočtu. Potřeba pravidel vznikla z důvodu transparentnosti a jednoznačnosti pro předkládání projektových návrhů ze strany občanů."),
  p("Předložený projekt musí být realizován na majetku obce. Občané navrhují projekty k realizaci. Podmínkou je předložení popisu projektu a návrhu rozpočtu projektu. Zastupitelé vybírají z předložených návrhů občanů a obec realizuje. Předložení návrhů do 28.2.2023."),
  p("Navrhují tato Pravidla pro Občanský návrhový projektový rozpočet:"),
  ...nl([
    "Majetek obce je definován: a) nový majetek (např. pořízení nového majetku – pořízení květinových truhlíků na náves a osazení květinami, …); b) nevyužívaný majetek (např. pozemek, který není pronajímán a je dosud nevyužívaný, projekt počítá s umístěním lavičky, …); c) v případě používaného majetku, neměnit jeho účel používání (např. klubovna, sklad, knihovna, zasedací místnost, místní komunikace, … – zachovat stávající použití)",
    "Předložení popisu projektu a návrhu rozpočtu projektu – projekt musí obsahovat: a) název: Občanský návrhový projektový rozpočet 2023; b) kdo předkládá – občan s trvalým pobytem v obci Krhanice ke dni podání projektu; c) popis projektu, účel projektu a jeho cíle; d) předpokládaný návrh rozpočtu projektu (položkový rozpočet); e) jméno a příjmení občana, adresa, kontakt, datum vyhotovení a podpis předkladatele projektu",
    "Konečný termín předložení projektů je 28.2.2023, do 12:00 hodin na Obecní úřad Krhanice – osobně, datovou schránkou, e-mailem (starosta@obeckrhanice.cz).",
    "Hodnocení předložených projektů bude především směrováno na realizovatelnost, majetkoprávní vztahy a náklady projektů. Zastupitelstvo si vyhrazuje právo žádný z předložených projektů nevybrat/nerealizovat, pokud realizovatelnost, majetkoprávní vztahy nebo náklady projektu nebudou reálné nebo nebudou v souladu s posláním obce. Hodnocení: 1. kolo – projekty s přihlédnutím na realizovatelnost, majetkoprávní vztahy a náklady projektu, které splňují všechny podmínky a získají hlasy více než poloviny zastupitelů (5 a více hlasů, 1 zastupitel = 1 hlas) postupují do hodnocení ve 2.kole. 2. kolo – z vybraných projektů se s přihlédnutím na realizovatelnost, majetkoprávní vztahy a náklady projektu budou vybírat/hodnotit projekt/projekty tak, aby součet nákladů nepřesáhl celkový limit 100.000,- Kč. Bude vybrán projekt/projekty, které získají nejvyšší počet hlasů zastupitelů (1 zastupitel = 1 hlas). Zodpovědná osoba: starosta obce. Postup: zastupitelé ve dvou kolech budou hodnotit; na nejbližším zasedání zastupitelstva budou občané seznámeni s výsledky; v případě vybrání projektu/projektů starosta obce zajistí vyhotovení rozpočtového opatření pro jednání zastupitelstva obce – rozpuštění rezervy na Občanský návrhový projektový rozpočet s přihlédnutím k charakteru vybraných jednotlivých vítězných projektů/projektů.",
  ]),

  h4("Změna v navrženém rozpočtu 2023"),
  p("Na základě rozpisu státního rozpočtu obdrženého dne 21.12.2022 dojde k úpravě položky 4112 Neinvestiční přijaté transfery ze státního rozpočtu – souhrnný dotační vztah:"),
  p("Navýšení je o 11,30 tisíc Kč. Tedy:"),
  p("Příjmy (v tis. Kč): TŘÍDA 4 - PŘIJATÉ DOTACE: Rozpočet 2023: 5798,29; Schválený rozpočet 2022: 437,34; Upravený rozpočet 2022 (předpokládaná výše plnění): 4738,11. Neinv.transfery ze SR v rámci souhrnného dotačního vztahu (Návrh rozpočtu): 275,30 / 274,30 / 275,30; Změna – plánováno v rozpočtu: 286,60 / 274,30 / 275,30."),
  p("Výdaje (v tis. Kč): 6171 Činnost místní správy (Návrh rozpočtu): 2106 / 1912 / 1951; Změna – plánováno v rozpočtu: 2117,30 / 1912 / 1951."),
  p("Tím dojde k úpravě: CELKEM PŘÍJMY: Rozpočet 2023: 26 865,15; Schválený rozpočet 2022: 18 417,08; Upravený rozpočet 2022 (předpokládaná výše plnění): 26 578,87. CELKEM VÝDAJE: 34 697,03 / 37 425,46 / 47 024,25. V tom: VÝDAJE TŘÍDY 6 - KAPITÁLOVÉ VÝDAJE: 14 020,00 / 21 511,80 / 29 624,98; VÝDAJE TŘÍDY 5 - BĚŽNÉ VÝDAJE: 20 677,03 / 15 913,96 / 17 554,27. Ostatní beze změny."),
  h5("Rozprava"),
  p("I.Dvořák: Dotaz na investiční akce, na kdy je plánováno ukončení realizace v roce 2023? Starosta: Rekonstrukce návsi a okolních chodníků do 30.6.2023; Rekonstrukce základní školy do 31.7.2023; Rekonstrukce hlavního vodovodního přivaděče do 30.6.2023; Kruhový objezd u viaduktu včetně chodníku kolem okružní křižovatky – chodník bude financován z rozpočtu obce, ostatní financuje Středočeský kraj, realizace podle Středočeského kraje."),
  p("I.Dvořák: Návrh na zvýšení příjmů – zvýšení cen za pronájem obecních pozemků. Starosta – je třeba udělat revize; Pronájem klubovny – více využívat; Veřejné osvětlení – jakou by přineslo úsporu jeho vypínání? Starosta: Už se zpracovávají podklady – možnost zapínat o 15 minut později a vypínat o 15 minut dříve anebo možnost vypínat v noci od 0:00 hod. do 03:00 hod.; Odpady – zrušit dary pro občany. Místostarosta: Dar je v podstatě částka, kterou dostaneme od EKO-KOMu a vidíme to jako motivaci pro občany z hlediska třídění; Čtrnáctidenní svoz popelnic. Místostarosta: Zhodnotil množství a četnost svozů. Každoročně řešíme změny na TS Benešov, schůzka je již naplánována. Proběhla všeobecná diskuse o odpadovém hospodářství; Výsadbu zeleně by organizovaly místní spolky, o zeleň by se i staraly."),
  p("L.Maršíková: Navrhla bezodpadové akce. Starosta: Všechny akce jsou odpadové. Obec by mohla dodat nádoby na tříděný odpad."),
  p("L.Maršíková: Jaká rezerva zůstane v rozpočtu, pokud je rozpočet schodkový? Starosta: Cca 11 milionů, ale z hlediska investičních akcí ji nelze přesně vyčíslit."),
  p("L.Maršíková: Dotaz na Komisi pro obnovu a rozvoj obce. Jakým způsobem navrhuje, co se bude v obci dělat. T.Kratochvíl: Z pozice předsedy seznámil, jak komise funguje. Lze se na něj obrátit s návrhy."),
  p("Starosta seznámil přítomné s pravidly pro Občanský návrhový projektový rozpočet. Proběhla diskuse."),
  p("Starosta seznámil s pravidly SENIOR TAXI a REHABILITACE TAXI. I.Dvořák: Dotaz na zveřejnění. Starosta: Máme připraveny dopisy pro občany, kterých se to bude týkat. Informace budou i na webových stránkách obce."),
  p("L.Maršíková: Dotazy k příloze rozpočtu: Částka 19 tisíc pro SDH Krhanice na materiální podporu. T.Kratochvíl: Příspěvek na akce, aby byly bez vstupného; Dotaz na právní služby – máme uzavřenou nějakou smlouvu? Starosta: Ne; Dotaz na částku 135 tisíc pro TJ Sokol. Starosta: Na provoz budovy – voda, elektřina a jímka; Částka pro kulturní komisi. Starosta: Na podporu akcí pořádaných obcí a kulturní komisí, např. divadla, výlet; Neúčelové finanční dary pro TJ Sokol a SDH. T.Kratochvíl: Na svačiny pro mladé fotbalisty a mladé hasiče."),
  h5("Návrh"),
  p("ZO schvaluje Pravidla pro Občanský návrhový projektový rozpočet na rok 2023."),
  vote("PRO ( 6 ) – PROTI ( 2 – Maršíková, Dvořák ) – ZDRŽEL SE ( 0 )"),
  h5("Návrh"),
  p("ZO schvaluje Přílohu Rozpočtu obce Krhanice na rok 2023."),
  vote("PRO ( 6 ) – PROTI ( 2 – Maršíková, Dvořák ) – ZDRŽEL SE ( 0 )"),
  h5("Návrh"),
  p("ZO schvaluje Rozpočet obce Krhanice na rok 2023 včetně změny jako schodkový. Schodek bude hrazen finančními prostředky z minulých let a smluvně zabezpečenou půjčkou v souvislosti s projekty „Zateplení, výměna zdroje tepla v ZŠ v obci Krhanice“ a „Pořízení centrální vzduchotechniky do ZŠ Krhanice“."),
  vote("PRO ( 6 ) – PROTI ( 2 – Maršíková, Dvořák ) – ZDRŽEL SE ( 0 )"),

  h3("7) Koupě, prodej, pronájem"),
  ...ul(["prodat díl „a“ z pozemku parc.č. 346/2 k.ú. Krhanice o výměře 176 m² dle geometrického plánu č. 1065-139/2021 za cenu 110,- Kč/1 m²"]),
  p("Informace starosty: Jedná se o pozemek navazující na pozemek místního lomu, který je přístupem k lomu."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje prodej dílu „a“ z pozemku parc.č. 346/2 k.ú. Krhanice o výměře 176 m² dle geometrického plánu č. 1065-139/2021 za cenu 110,- Kč/1 m² firmě NATY TERRA, s. r. o., IČO: 09462741, Žitavského 1178, 156 00 Praha 5 - Zbraslav."),
  vote(V8),
  ...ul(["prodat díl „b“ z pozemku parc.č. 1981/1 k.ú. Krhanice o výměře 85 m² dle geometrického plánu č. 1065-139/2021 za cenu 110,- Kč/1m²"]),
  p("Informace starosty: Jedná se o pozemek navazující na pozemek místního lomu, který je přístupem k lomu."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje prodej dílu „b“ z pozemku parc.č. 1981/1 k.ú. Krhanice o výměře 85 m² dle geometrického plánu č. 1065-139/2021 za cenu 110,- Kč/1 m² firmě NATY TERRA, s. r. o., IČO: 09462741, Žitavského 1178, 156 00 Praha 5 - Zbraslav."),
  vote(V8),
  ...ul(["prodat pozemek parc.č. 1985/5 k.ú. Krhanice o výměře 77 m² a pozemek parc.č. 132/9 k.ú. Krhanice o výměře 60 m² za cenu 900,- Kč/1 m²"]),
  p("Informace starosty: Jedná se dva pozemky navazující na pozemek manželů Platilových v oblasti Svatovice."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje prodej pozemku parc.č. 1985/5 k.ú. Krhanice o výměře 77 m² a pozemku parc.č. 132/9 k.ú. Krhanice o výměře 60 m² za cenu 900,- Kč/1 m². Olze Platilové a Vladimíru Platilovi, Krhanice č.p. 191, 257 42 Krhanice."),
  vote("PRO ( 7 ) – PROTI ( 1 – Maršíková ) – ZDRŽEL SE ( 0 )"),
  ...ul(["uzavření smlouvy o zřízení věcného břemene – uložení vodovodní přípojky pro pozemek parc.č. 272/7 k.ú. Krhanice na pozemku parc.č. 1981/1 k.ú. Krhanice na dobu neurčitou za cenu 3.000,- Kč"]),
  p("Informace starosty: Jedná se o pozemek navazující na komunikaci k lomu. Majitel pozemku si zhotovil vodovodní přípojku, která vede z obecního pozemku."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření smlouvy o zřízení věcného břemene – uložení vodovodní přípojky pro pozemek parc.č. 272/7 k.ú. Krhanice na pozemku parc.č. 1981/1 k.ú. Krhanice dle geometrického plánu č. 1100-140/2022 na dobu neurčitou za cenu 3.000,- Kč s Bc. Tomášem Rukavičkou, Matěchova 1034/6, 140 00 Praha 4."),
  vote(V8),
  ...ul(["uzavření smlouvy o zřízení věcného břemene – uložení vodovodní přípojky pro pozemek parc.č. 272/8 k.ú. Krhanice na pozemku parc.č. 1981/1 k.ú. Krhanice na dobu neurčitou za cenu 3.000,- Kč"]),
  p("Informace starosty: Jedná se pozemek navazující na komunikaci k lomu. Majitelka pozemku si zhotovila vodovodní přípojku, která vede z obecního pozemku."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření smlouvy o zřízení věcného břemene – uložení vodovodní přípojky pro pozemek parc.č. 272/7 k.ú. Krhanice na pozemku parc.č. 1981/1 k.ú. Krhanice dle geometrického plánu č. 1099-139/2022 na dobu neurčitou za cenu 3.000,- Kč s Ing. Michalou Havlínovou, Za Váhou 772, 277 11 Libiš."),
  vote(V8),
  ...ul(["prodat pozemek parc.č. 224/95 k.ú. Krhanice o výměře 20 m², který vznikne dle geometrického plánu č. 1104-150/2022 oddělením z pozemku parc.č. 224/65 za cenu 500,- Kč/1 m²"]),
  p("Informace starosty: Jedná se o pozemek navazující na pozemek manželů Viktorových. Chtějí si oplotit pozemek."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje prodej pozemku parc. č. 224/95 k.ú. Krhanice o výměře 20 m², který vznikne dle geometrického plánu č. 1104-150/2022 oddělením z pozemku parc. č. 224/65 za cenu 500,- Kč/1 m² Svatavě Viktorové a Janu Viktorovi, Krhanice č.p. 303, 257 42 Krhanice."),
  vote("PRO ( 7 ) – PROTI ( 1 - Maršíková ) – ZDRŽEL SE ( 0 )"),

  h3("8) Různé"),
  h4("Zápis z dílčího přezkoumání hospodaření obce Krhanice"),
  p("Starosta seznámil se Zápisem z dílčího přezkoumání hospodaření obce ze dne 1.12.2022 s výsledkem nebyly zjištěny chyby a nedostatky – kontrolu provedl Krajský úřad Středočeského kraje, Odbor interního auditu a kontroly."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí Zápis z dílčího přezkoumání hospodaření obce ze dne 1.12.2022."),

  h4("Souhlas se vznikem pracovněprávních vztahů zastupitelů"),
  p("Dle zákona č. 128/2000 Sb., o obcích, § 84 odst. 2 písm. p) je zastupitelstvu obce vyhrazeno vyslovovat souhlas se vznikem pracovněprávního vztahu mezi obcí a členem zastupitelstva obce. Protože takové pracovně právní vztahy jsou reálné, následuje jejich výčet:"),
  ...ul(["oblast Činnosti knihovnické: Bc. Petr Dub."]),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje a souhlasí se vznikem pracovněprávních vztahů mezi obcí a členem zastupitelstva obce s platností od 1.1.2023 do 31.12.2023, a to oblast Činnosti knihovnické: Bc. Petr Dub. Dohody budou uzavírány v průběhu roku 2023 dle konkrétních potřeb obce."),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 1 - Dub )"),

  h4("Obecní knihovna Krhanice"),
  p("Informace starosty: Návrh v pokračování v roce 2023 s osvobozením od placení registračního poplatku."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Dodatek č. 13 k Příloze č. 1 Knihovního řádu Obecní knihovny Krhanice Výpůjční řád."),
  vote(V8),

  h4("ČEZ Distribuce - smlouva o zřízení části pozemní komunikace"),
  p("Informace starosty: Přístupová komunikace k elektrárně je ve značně poškozeném a nezpevněném stavu. Část provozu na komunikaci souvisí s umístěním zázemí ČEZ Distribuce. Proběhlo jednání, na kterém se ČEZ Distribuce a obec Krhanice dohodly, že se rekonstrukce komunikace provede společně. Uzavřeme smlouvu s ČEZ Distribuce."),
  h5("Rozprava"),
  p("I.Dvořák: Dotaz, zda brána na konci této komunikace bývá otevřená? Starosta: Měla by být. Řešili jsme několikrát její uzavírání. Budeme opět řešit."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o zřízení části pozemní komunikace na pozemku parc.č. st. 42/3 a parc.č. 1980 k.ú. Krhanice."),
  vote(V8),

  h3("9) Diskuse"),
  ...ul([
    "I.Dvořák: Poděkování za zveřejnění kontaktu na sociální pracovnici na webu obce.",
    "I.Dvořák: Informace k zavážení lomu Doubí – činnost bude přerušena či ukončena. Starosta: Jednal jsem s majitelem. Platné povolení mají. Současná technologie na zpracování odpadu z těžební činnosti je taková, že to v podstatě nepotřebují.",
    "I.Dvořák: Poděkoval panu Strnadovi – zajistil, že jeho známý připravil nějaké řešení příchodu na železniční stanici. Starosta: Mám domluveno osobní jednání na Správě železnic.",
    "L.Maršíková: Dotaz, zda se neuvažuje vykoupení pozemku pod sv. Josefem? Starosta: František Mikoláš to nechtěl, respektuji jeho přání.",
    "L.Maršíková: Dotaz na informace o spojení pozemků na vybudování čistírny odpadních vod pro více domácností. Starosta: Měl jsem jednání na MěÚ Benešov. Dotazovateli bude zaslán dopis. Přečištěné odpadní vody by musely být svedeny do vodoteče.",
    "L.Maršíková: Dotaz k úpravě přístupové komunikace k novým parcelám u lomu, zda jsou nové informace. Starosta: Běží řízení – úprava neodpovídá předložené dokumentaci, řeší Silniční správní úřad MěÚ Benešov. Proběhla diskuse.",
    "I. Vatechová: Poděkovala za podporu obce v roce 2022 za SDH Krhanice.",
    "M.Jiřička: Přečetl dopis od spolku Naše Krhanice – poděkování za podporu.",
  ]),
  p("Starosta: Popřál všem k vánočním svátkům a do nového roku 2023."),

  h3("10) Usnesení a závěr"),
  p("a. Starosta se zeptal Návrhové komise na doplnění nebo změnu usnesení z jednání. Nebylo vzneseno žádné doplnění či změna."),
  p("Proběhla diskuse o správnosti hlasování se závěrem, že hlasování proběhne."),
  p("b. Hlasování o předložených návrzích Návrhové komise."),
  vote("PRO ( 6 ) – PROTI ( 0 ) – ZDRŽEL SE ( 2 – Maršíková, Dvořák )"),
  p("c. Závěr: Zastupitelstvo obce bylo ukončeno v 18:30 hod."),

  p("Datum pořízení zápisu: 29.12.2022"),
  p("Ověřovatelé zápisu a starosta obce, podepsáno v listinné podobě."),
  h4("Přílohy"),
  ...nl(["Svolání zastupitelstva obce", "Prezenční listina zastupitelů", "Prezenční listina občanů"]),
];

async function run() {
  const r = await publishZapis({
    cislo: "7",
    rok: "2022",
    isoDate: "2022-12-22",
    dateLabel: "22. 12. 2022",
    fullDateDot: "22.12.2022",
    pdfPath: "scripts/zapisy-pdf/zapis-2022-7.pdf",
    transcript,
  });
  console.log("OK", r.docId, "blocks", r.blocks);
}
run().catch((e) => { console.error(e); process.exit(1); });
