/* eslint-disable no-console */
import { h3, h4, h5, p, vote, nl, ul, publishZapis, type Block } from "../zapis-lib";

const V8 = "PRO ( 8 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )";

const transcript: Block[] = [
  h4("Přítomni"),
  p("Aleš Papoušek, Jaroslav Mixa, Tomáš Kratochvíl, Jana Laboutková, Petr Dub, Martin Jiřička, Lucie Maršíková, Šárka Dušová"),
  h4("Omluveni"),
  p("Aleš Kozel"),

  h3("1) Zahájení, přivítání přítomných, konstatování přítomnosti"),
  p("Starosta konstatoval, že zasedání bylo svoláno dne 11.7.2024, bylo vyvěšeno na úřední desce obecního úřadu, tj. tedy nejméně 7 dní před zasedáním. Bylo tedy svoláno řádně a včas v souladu se zákonem o obcích v platném znění. Starosta konstatoval, že podle prezenční listiny je přítomno 8 členů zastupitelstva, tedy nadpoloviční většina členů zastupitelstva. K předchozímu zápisu nebyly vzneseny námitky."),
  h5("Určení zapisovatele"),
  p("Zápisem zasedání zastupitelstva obce byla pověřena Ing. Alena Kratochvílová."),

  h3("2) Volba návrhové komise a ověřovatelů zápisu"),
  p("Starosta přednesl návrh návrhové komise a ověřovatelů zápisu."),
  h5("Návrh"),
  p("ZO schvaluje návrhovou komisi ve složení: Jana Laboutková, Jaroslav Mixa."),
  h5("Návrh"),
  p("ZO schvaluje ověřovatele zápisu ve složení: Martin Jiřička, Petr Dub."),
  vote(V8),

  h3("3) Schválení programu"),
  p("Starosta oznámil změnu programu."),
  p("Za bod Rozpočtové opatření:"),
  ...ul([
    "Bude zrušen bod Jednací řád Zastupitelstva obce Krhanice.",
    "Budou doplněny body Obecně závazná vyhláška obce o nočním klidu a dále další bod Obecně závazná vyhláška obce o místním koeficientu obce (pro daň z nemovitosti), následující body se posunou v programu o jeden níže.",
  ]),
  p("Starosta přečetl program"),
  ...nl([
    "Zahájení",
    "Volba návrhové komise a ověřovatelů zápisu",
    "Schválení programu",
    "Stavba Krhanice - chodník podél silnice III/1066 - 2.etapa",
    "Rozpočtové opatření",
    "Obecně závazná vyhláška obce o nočním klidu",
    "Obecně závazná vyhláška obce o místním koeficientu obce (pro daň z nemovitosti)",
    "Různé",
    "Diskuse",
    "Závěr",
  ]),
  p("Starosta: Má někdo návrh na změnu nebo doplnění programu?"),
  h5("Rozprava"),
  p("P.Bydžovský: Dotaz, zda tuto změnu programu nevěděli zastupitelé dříve, konkrétně koeficient daně z nemovitosti, na webu obce nebyly žádné podklady. I.Dvořák sdělil P.Bydžovskému, že podklady k tomuto bodu jsou na webu obce u podkladů pro zastupitelstvo, ne na úřední desce."),
  h5("Návrh"),
  p("ZO schvaluje program zasedání zastupitelstva obce."),
  vote(V8),

  h3("4) Stavba Krhanice - chodník podél silnice III/1066 - 2.etapa"),
  p("Starosta seznámil se stavbou chodníku podél silnice III/1066 1. a 2.etapa"),
  p("Dodatek č.1 ke smlouvě s panem Žabou na chodník podél silnice III/1066 na základě rozpočtu vyhotoveného firmou Lucida s.r.o. dle skutečného provedení."),
  p("Úspora byla:"),
  ...ul([
    "montáž a demontáž - dočasné dopravní značky - kompletní dopravně inženýrské opatření (tohle byla velká úspora cca 300 tisíc bez DPH, neboť se využila uzavírka křižovatky)",
    "nedělaly se obloučky do Dlážděnky",
    "nedělaly se asfalty a související práce nad kanalizací, která měla přecházet silnici na druhou stranu",
    "dešťové potrubí bylo kratší - nepřecházelo se s dešťovou kanalizací na druhou stranu",
    "nedělal se inženýrsko-geologický průzkum a rozbor zemin aktivní zóny - v minulosti se v daném místě dělal vodovod a pokládal nový kabel elektrického vedení",
    "nedělaly se průzkumné, geologické a projekční práce-archeologický průzkum - v minulosti se v daném místě dělal vodovod",
    "nedělala se výrobní dokumentace (kladecí plány šachet, úhly apod.) - pan Žaba realizoval dílo bez této dokumentace",
  ]),
  p("Cena díla dle smlouvy byla 6 593 311,41 Kč s DPH. Skutečné provedení je 5 634 600,06 Kč. Cena stavby je snížena o 958 711,35 Kč."),
  p("Stavba: KRHANICE - CHODNÍK PODÉL SILNICE III/1066"),
  p("Smlouva o dílo:"),
  p("KRHANICE - CHODNÍK PODÉL SILNICE III/1066 - 2.etapa"),
  p("Lucida – běžná cena"),
  h5("Rozprava"),
  p("L.Maršíková: Dotaz na 1.etapu chodníku, na kontrolu vyčíslení snížené částky, zda správnost výpočtů kontroloval jen sám starosta? Starosta: Něco s panem Sommerem a hlavně s firmou, co zhotovila rozpočet na stavbu."),
  p("L.Maršíková: Připomínka ke smlouvě na 2.etapu, zůstala tam pasáž z předchozí smlouvy. Starosta: Upravil text smlouvy. Odsouhlaseno L.Maršíkovou."),
  p("I.Dvořák: Požádal o upřesnění, odkud kam vede chodník 2.etapa. Starosta: Ukázal na mapě."),
  p("D.Nováková: Dotaz na to, jak bude vypadat střed kruhového objezdu. Starosta: Uprostřed zeleň."),
  p("L.Durčoková: Dotaz, zda se bude někdy řešit přístup k nádraží. Starosta: Ukázal na mapě, kudy by měl v budoucnu vést oficiální přístup."),
  p("Š.Dušová: Dotaz, zda budou na okružní křižovatce 4 přechody, konkrétně zda bude přechod za kruhovým objezdem směrem na Týnec. Starosta: V tomto místě přechod nebude. Podél hlavní silnice není chodník, chodci by neměli kam přecházet."),
  p("Proběhla diskuse, zda by nebylo vhodné udělat přechod od nádraží směrem k autobusové zastávce na Týnec. Závěr: Starosta tento přechod zapíše jako bod do místního šetření s dopravními požadavky."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Dodatku č. 1 ke smlouvě o dílo č. SoD/02/2024 ze dne 2.4.2024 na akci „Krhanice – chodník podél silnice III/1066“ s firmou Jaroslav Žaba, IČO: 86934431, Pecerady 69, 257 41 Týnec nad Sázavou na celkovou částku 5 634 600,06 Kč s DPH."),
  vote(V8),
  h5("Návrh"),
  p("ZO pověřuje starostu obce uzavřením a podpisem Dodatku č. 1 ke smlouvě o dílo č. SoD/02/2024 ze dne 2.4.2024 na akci „Krhanice – chodník podél silnice III/1066“ s firmou Jaroslav Žaba, IČO 86934431, Pecerady 69, 257 41 Týnec nad Sázavou."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje uzavření smlouvy o dílo na akci „Krhanice – chodník podél silnice III/1066 – 2.etapa“ s firmou Jaroslav Žaba, IČO 86934431, Pecerady 69, 257 41 Týnec nad Sázavou na celkovou částku 1 381 516,02 Kč s DPH."),
  vote(V8),
  h5("Návrh"),
  p("ZO pověřuje starostu obce uzavřením a podpisem smlouvy o dílo na akci „Krhanice – chodník podél silnice III/1066 – 2.etapa“ s firmou Jaroslav Žaba, IČO 86934431, Pecerady 69, 257 41 Týnec nad Sázavou."),
  vote(V8),

  h3("5) Rozpočtové opatření"),
  p("Předseda finančního výboru Petr Dub seznámil s rozpočtovým opatřením obce č. 6/2024 a č. 1/2024 pro Fond obnovy vodovodů obcí Krhanice a Prosečnice."),
  h5("Rozprava"),
  p("Starosta rozebral podrobněji hlavní body rozpočtového opatření. Proběhla diskuse o zpomalovacích prazích na komunikaci u mateřské školy, základní školy a u víceúčelového hřiště."),
  p("Dále proběhla diskuse o oplocení kontejnerového stání u základní školy se závěrem: Oplocení částečně uzavřít směrem k mateřské škole. S realizační firmou projednat, zda by bylo možné vynechat zadní stranu podél budovy základní školy."),
  p("I.Dvořák: Požádal o vysvětlení daru za vodu. Starosta: Peníze byly zaplaceny v hotovosti. Přes rozpočtové opatření budou převedeny do Fondu obnovy vodovodů obcí Krhanice a Prosečnice."),
  h5("Návrh"),
  p("ZO schvaluje navýšení provozního příspěvku Mateřské školy Krhanice ve výši 100 000,- Kč na opravu vrat a branek u školky."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje rozpočtové opatření Fondu financování obnovy vodovodů obcí Krhanice a Prosečnice č. 1/2024."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje rozpočtové opatření obce Krhanice č. 6/2024."),
  vote(V8),

  h3("6) Obecně závazná vyhláška obce o nočním klidu"),
  p("Informace místostarosty o návrhu vyhlášky."),
  p("Informace starosty: Již několik let obec schvaluje obecně závazné vyhlášky o nočním klidu, ve kterých jsou stanoveny výjimečné případy, při nichž je doba nočního klidu vymezena dobou kratší nebo při nichž nemusí být doba nočního klidu dodržována. Jedná se o např. o noc z 31. prosince na 1. ledna z důvodu konání oslav příchodu nového roku nebo akce v obci, které se konaly na veřejných prostranstvích."),
  p("Nyní došlo k situaci, že určité kulturní akce v roce 2024 byly původně nahlášeny s místem konání na veřejném prostranství. Termíny této akce byly povoleny v obecně závazné vyhlášce obce o nočním klidu na zastupitelstvu 6.6.2024."),
  p("Nyní bylo na obecní úřad oznámeno konání těchto akcí uvedených ve vyhlášce. U jedné akce bylo zachováno veřejné prostranství a druhá kulturní akce má nahlášeno pořádání na soukromém pozemku."),
  p("Zákonem o obcích č. 128/2000 Sb., o obcích, § 34 jsou veřejným prostranstvím všechna náměstí, ulice, tržiště, chodníky, veřejná zeleň, parky a další prostory přístupné každému bez omezení, tedy sloužící obecnému užívání, a to bez ohledu na vlastnictví k tomuto prostoru."),
  p("Pořadatel akce samovolně změnil místo konání jedné akce z veřejného prostoru na soukromý pozemek. Otázkou je, zda tuto akci na soukromém pozemku ponechat v obecně závazné vyhlášce o nočním klidu?"),
  h5("Rozprava"),
  p("I.Dvořák Nevidí důvod, proč by se nemohla akce konat na soukromém pozemku. Spolek nemá dostatečné prostředky na obě akce."),
  p("Proběhla diskuse o akci, kde by mohla být, … zástavba, zveřejnění akce, e-mail, … a přešlo se k hlasování, zda tuto akci, která byla původně nahlášena na tréninkovém hřišti a schválena ve vyhlášce na zastupitelstvu 6.6.2024, ve vyhlášce ponechat."),
  h5("Návrh"),
  p("ZO schvaluje odstranit v Článku 3 bod 4 v Obecně závazné vyhlášce obce Krhanice o nočním klidu."),
  vote("PRO ( 6 ) – PROTI ( 0 ) – ZDRŽEL SE ( 2 – Maršíková, Bc. Dušová )"),
  h5("Návrh"),
  p("ZO schvaluje Obecně závaznou vyhlášku obce Krhanice o nočním klidu."),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 1 – Bc. Dušová )"),

  h3("7) Obecně závazná vyhláška obce o místním koeficientu obce (pro daň z nemovitosti)"),
  p("Informace starosty o návrhu vyhlášky. Starosta ukázal propočty očekávaných daní v návaznosti na vyhlášky včetně vyhlášky č. 2/2012 (ruší se k 31.12.2024). Smyslem schválení navýšení koeficientu z 2,0 na 2,5 je nesnížení příjmů z daně z nemovitosti."),
  p("Návrh koeficientu: 2,5 místo 2, což je 12,5%."),
  h5("Rozprava"),
  p("L.Maršíková: Popsala svůj návrh a návrh paní Dušové na změnu koeficientu. Chtěla slyšet zpětnou vazbu od ostatních zastupitelů. Ti to vzali na vědomí."),
  p("I.Dvořák: Navrhl zvýšit daň z nemovitosti rekreantům nebo z Zvýšit daň z nemovitosti konkrétním firmám."),
  p("Proběhla diskuse bez přijatého závěru."),
  p("Diskuse byla ukončena. Přešlo se k hlasování."),
  h5("Návrh"),
  p("ZO schvaluje Obecně závaznou vyhlášku obce Krhanice o stanovení místního koeficientu pro obec."),
  vote("PRO ( 6 ) – PROTI ( 2 – Maršíková, Bc. Dušová ) – ZDRŽEL SE ( 0 )"),
  p("L.Maršíková chtěla znovu otevřít diskusi. Starosta nechal hlasovat, zda diskusi otevřít. 6 zastupitelů bylo proti otevření diskuse."),

  h3("8) Různé"),
  ...ul([
    "Dodatek č.3 ke Smlouvě o přenechání VO na území obce Krhanice do nájmu, o jeho provozování a správě",
  ]),
  p("Informace starosty k dodatku a snížení nákladů na osvětlení:"),
  p("Celkem náklady za VO: Dodatek č.3 449 659,00 Kč, Stávající náklady 780 758,70 Kč, snížení - 331 099,70 Kč, snížení v % 42,41%."),
  p("Platba za elektrickou energii: Dodatek č.3 174 948,00 Kč, Stávající náklady 437 369,20 Kč, snížení - 262 421,20 Kč, snížení v % 60,00%."),
  p("Provoz, správa, údržba a opravy: Dodatek č.3 274 712,00 Kč, Stávající náklady 343 389,50 Kč, snížení - 68 677,50 Kč, snížení v % 20,00%."),
  h5("Rozprava"),
  p("P.Bydžovský: Navrhl snížení nákladů tím, že se přestane svítit v noci."),
  p("P.Bydžovský: Vznesl požadavek na přezkoumání osvětlení v ulici Na Žlabech, aby je neobtěžoval světelný smog. Celou noc jim svítí světlo do ložnice."),
  p("Š.Dušová: Má podobný problém. Podle ní by stačila změna sklonu na výložníku. Starosta: Zjistím."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Dodatku č.3 ke Smlouvě o přenechání VO na území obce Krhanice do nájmu, o jeho provozování a správě s Osvětlení Týnec, k.s., IČO: 26140781, K Náklí 404, 257 41 Týnec nad Sázavou."),
  vote(V8),

  h3("9) Diskuse"),
  ...ul([
    "L.Maršíková: Prosba, aby v SMS, které dostávají občané, bylo více informací. Starosta: V SMS je základ, do e-mailu a do aplikace v mobilu většinou chodí více informací.",
    "L.Maršíková: Konstatování, že WhatsAppem není možné starostovi odsouhlasit podpis smlouvy.",
    "L.Maršíková: Pan Santler věnoval obci doménu krhanice.cz. Co s ní obec zamýšlí? Starosta: Řešili jsme s panem místostarostou.",
    "L.Durčoková: Stížnost na to, jak rychle jezdí někteří řidiči od zatáčky nad úřadem na konec Krhanic. U odbočení na Rafandu chybí doplňková značka křižovatky ke značce hlavní silnice. Starosta: Dám do podnětu na dopravní místní šetření.",
  ]),

  h3("10) Závěr"),
  p("Zastupitelstvo obce bylo ukončeno v 19:52 hod."),

  p("Datum pořízení zápisu: 29.7.2024"),
  p("Ověřovatelé zápisu a starosta obce, podepsáno v listinné podobě."),
  h4("Přílohy"),
  ...nl(["Svolání zastupitelstva obce", "Prezenční listina zastupitelů", "Prezenční listina občanů"]),
];

async function run() {
  const r = await publishZapis({
    cislo: "3",
    rok: "2024",
    isoDate: "2024-07-22",
    dateLabel: "22. 7. 2024",
    fullDateDot: "22.7.2024",
    pdfPath: "scripts/zapisy-pdf/zapis-2024-3.pdf",
    transcript,
  });
  console.log("OK", r.docId, "blocks", r.blocks);
}
run().catch((e) => { console.error(e); process.exit(1); });
