/* eslint-disable no-console */
// One-off: faithful transcript of Zápis č. 5/2021 (10.12.2021), transcribed
// visually (page by page) from the official PDF. Structure per AGENT-SPEC.md
// and the approved golden sample scripts/build-zapis-2026-1.ts.
import { h3, h4, h5, p, vote, nl, ul, publishZapis, type Block } from "../zapis-lib";

const V8 = "PRO ( 8 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )";

const transcript: Block[] = [
  h4("Přítomni"),
  p("Aleš Papoušek, Jaroslav Mixa, Bohuslav Kadeřábek, Tomáš Kratochvíl, Martin Jiřička, Václav Zíta, Petr Dub, Jana Laboutková"),
  h4("Omluveni"),
  p("Edita Jarošová"),

  h3("1) Zahájení, přivítání přítomných, konstatování přítomnosti"),
  p("Starosta konstatoval, že zasedání bylo svoláno dne 3.12.2021, bylo vyvěšeno na úřední desce obecního úřadu, tj. tedy nejméně 7 dní před zasedáním. Bylo tedy svoláno řádně a včas v souladu se zákonem o obcích v platném znění. Starosta konstatoval, že podle prezenční listiny je přítomno 8 členů zastupitelstva, tedy nadpoloviční většina členů zastupitelstva. K předchozímu zápisu nebyly vzneseny námitky."),
  h5("Určení zapisovatele"),
  p("Zápisem zasedání zastupitelstva obce byla pověřena Ing. Alena Kratochvílová."),
  p("Starosta přečetl program."),
  ...nl([
    "Zahájení",
    "Volba návrhové komise a ověřovatelů zápisu",
    "Zpráva finančního výboru o kontrole hospodaření obce Krhanice v roce 2021; Zpráva o výsledcích veřejnosprávních kontrol hospodaření Mateřské školy Krhanice a Základní školy Krhanice v roce 2021",
    "Rozpočtová opatření",
    "Střednědobý výhled rozpočtu obce Krhanice na období 2022 – 2025; Rozpočet obce Krhanice na rok 2022",
    "Obecně závazné vyhlášky obce Krhanice – odpady",
    "Vydání změny č. 1 územního plánu Krhanice",
    "Koupě, prodej, pronájem",
    "Různé",
    "Diskuse",
  ]),
  p("Proběhlo hlasování o programu."),
  h5("Návrh"),
  p("ZO schvaluje program zasedání zastupitelstva obce."),
  vote(V8),

  h3("2) Volba návrhové komise a ověřovatelů zápisu"),
  p("Starosta přednesl návrh návrhové komise a ověřovatelů zápisu."),
  h5("Návrh"),
  p("ZO schvaluje návrhovou komisi ve složení Jaroslav Mixa, Jana Laboutková."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje ověřovatele zápisu Tomáš Kratochvíl, Bohuslav Kadeřábek."),
  vote(V8),

  h3("3) Zpráva finančního výboru o kontrole hospodaření obce Krhanice v roce 2021; Zpráva o výsledcích veřejnosprávních kontrol hospodaření Mateřské školy Krhanice a Základní školy Krhanice v roce 2021"),
  p("Bohuslav Kadeřábek seznámil s kontrolou hospodaření obce Krhanice v roce 2021. A dále seznámil s proběhlými veřejnosprávními kontrolami hospodaření příspěvkových organizací Mateřské školy Krhanice a Základní školy Krhanice v roce 2021. Kontroly proběhly dne 25.10.2021."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí zprávu finančního výboru o kontrole hospodaření obce Krhanice v roce 2021 ze dne 25.10.2021."),
  h5("Návrh"),
  p("ZO bere na vědomí protokoly o průběhu a výsledcích veřejnosprávních kontrol příspěvkových organizací Základní škola Krhanice a Mateřská škola Krhanice v roce 2021 ze dne 25.10.2021."),

  h3("4) Rozpočtová opatření"),
  h4("Rozpočtové opatření č. 6/2021, 7/2021, 8/2021"),
  p("Informace starosty: U všech rozpočtových opatření se jednalo o příjem a zapojení dotačních prostředků."),
  p("Rozpočtové opatření č. 6/2021: dotace na volby do Poslanecké sněmovny v částce 62.000, - Kč."),
  p("Rozpočtové opatření č. 7/2021: dotace z programu Národní program životního prostředí (sázení nových stromů na Sokolce) v částce 30.830, - Kč."),
  p("Rozpočtové opatření č. 8/2021: průtokovou dotaci pro mateřskou školu – Zjednodušené projekty Šablony – v částce 271.250, - Kč."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí a schvaluje rozpočtové opatření č. 6/2021, 7/2021 a 8/2021."),
  vote(V8),

  h4("Rozpočtové opatření č. 9/2021"),
  p("Jana Laboutková přečetla dopis ředitelky školky s návrhem na zvýšení provozního příspěvku – telekomunikační služby (používání SMS brány)."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje zvýšení provozního příspěvku Mateřské škole Krhanice o 10.000, - Kč (telekomunikační služby)."),
  vote(V8),
  p("Starosta seznámil přítomné s odvodem z Fondu investic Základní školy Krhanice ve výši 300.000,- Kč do rozpočtu zřizovatele – obce. Fond se vytváří z peněz na odpisy majetku školy. Odvod proběhne nejpozději do 31.12.2021. A dále seznámil s dopisem – návrh snížení provozního příspěvku za nespotřebované energie v částce 210.000,- Kč."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje odvod z Fondu investic Základní školy Krhanice ve výši 300.000,- Kč do rozpočtu obce Krhanice."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje snížení a vratku provozního příspěvku Základní školy Krhanice ve výši 210.000,- Kč do rozpočtu obce Krhanice do konce roku 2021. Jedná se o snížení položky energií."),
  vote(V8),
  p("Předseda finančního výboru Bohuslav Kadeřábek seznámil s rozpočtovým opatřením č. 9/2021."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje rozpočtové opatření č. 9/2021."),
  vote(V8),

  h3("5) Střednědobý výhled rozpočtu obce Krhanice na období 2022 – 2025; Rozpočet obce Krhanice na rok 2022"),
  h4("Střednědobý výhled rozpočtu 2022 – 2025"),
  p("Informace starosty: Starosta seznámil přítomné se Střednědobým výhledem rozpočtu na období 2022 – 2025. Obec reaguje střednědobým výhledem rozpočtu na aktuální stav rozpočtu obce. Hospodaření obce (výhled a rozpočet) bude v r. 2022 ovlivňovat probíhající realizace akce Zateplení, výměna zdroje tepla v ZŠ v obci Krhanice a Pořízení centrální vzduchotechniky do ZŠ Krhanice, která bude financována z dotačních prostředků, vlastních zdrojů a podpory ze SFŽP formou zápůjčky. Tyto akce mají prioritu a od nich se odvíjí financování, a tedy i střednědobý výhled a dále rozpočet obce"),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Střednědobý výhled rozpočtu na období 2022 – 2025."),
  vote(V8),

  h4("Rozpočet obce Krhanice na rok 2022"),
  h5("Informace starosty – oblast přípravy rozpočtu 2022"),
  p("Informace starosty: Rozpočet obce Krhanice byl vytvořen standardním způsobem, kdy žadatelé předkládali požadavky. Komise pro sestavení rozpočtu na rok 2022 všechny požadavky posoudila, a to zejména s ohledem na celkové hospodaření a financování priority obce pro rok 2022 - akce Zateplení, výměna zdroje tepla v ZŠ v obci Krhanice a Pořízení centrální vzduchotechniky do ZŠ Krhanice. Komise doporučuje, zastupitelstvo schvaluje."),
  h5("ROZPOČET 2022"),
  h4("Fond obnovy vodovodů obcí Krhanice a Prosečnice"),
  p("Místostarosta přečetl návrh Rozpočtu financování obnovy vodovodů obcí Krhanice a Prosečnice."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Rozpočet Fondu financování obnovy vodovodů obcí Krhanice a Prosečnice pro rok 2022."),
  vote(V8),
  p("Odhadované příjmy rozpočtu obce pro rok 2022 přednesl předseda finančního výboru."),
  p("Výdaje rozpočtu obce Krhanice přednesl starosta. Seznámil přítomné s jednáním v Komisi pro sestavení rozpočtu obce na rok 2022."),
  p("Rozpočet z hlediska příjmu a výdajů je navržen jako schodkový. Schodek bude krytý finančními prostředky minulých let."),

  h4("Dobrovolné-svazky obcí: Bene-Bus, Týnecko-svazek obcí"),
  h5("DSO Bene-Bus"),
  p("Starosta seznámil s Rozpočtem na rok 2022 – schodkový, kryto finanční rezervou minulých let. Provozní příspěvek obce Krhanice bude činit 270.045,- Kč."),
  p("Bene-Bus předložil také Střednědobý výhled rozpočtu na období 2023-2025."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Rozpočet Bene-Bus na rok 2022 jako schodkový, schodek bude kryt finančními prostředky z minulých let."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje Střednědobý výhled rozpočtu Bene-Bus na období 2023-2025."),
  vote(V8),

  h5("DSO Týnecko-svazek obcí"),
  p("Starosta seznámil s návrhem Rozpočtu na rok 2022 – vyrovnaný rozpočet. Provozní příspěvek obce Krhanice bude činit 12.595,- Kč."),
  p("Týnecko-svazek obcí předložil také Střednědobý výhled rozpočtu na období 2023-2024."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Rozpočet Týnecko-svazek obcí na rok 2022 jako vyrovnaný."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje Střednědobý výhled rozpočtu Týnecko-svazek obcí na období 2023-2024."),
  vote(V8),

  h4("Schválení výše provozního příspěvku pro zřízené příspěvkové organizace"),
  p("Informace starosty o předložených rozpočtech jednotlivých příspěvkových organizací a jejich projednávání v Komisi pro sestavení rozpočtu na rok 2022."),
  p("Návrh provozního příspěvku pro příspěvkové organizace pro rok 2022:"),
  ...ul([
    "Mateřská škola Krhanice, okres Benešov: 508 850,- Kč",
    "Základní škola Krhanice, okres Benešov: 2 756 756,- Kč",
  ]),
  p("v tom:"),
  ...ul([
    "Středisko Základní škola: 2 077 876,- Kč",
    "Středisko Školní jídelna: 678 880,- Kč",
  ]),

  h4("Pravidla pro rozpočet obce"),
  p("Starosta přednesl informace o Příloze č. 1, Příloze č. 2, Příloze č. 3."),
  ...ul([
    "Příloha č. 1 definuje pravidla a závazné ukazatele pro příspěvky pro MŠ Krhanice a ZŠ Krhanice, pro finanční dary pro narozené děti a pravidla pro poskytování finančních prostředků na kulturu, kulturní a společenské akce a zapojení obce k projektu spolku v obci.",
    "Příloha č. 2 definuje poskytování dotací a uzavírání veřejnoprávních smluv a poskytování darů.",
    "Příloha č. 3 určuje pravidla pro provádění rozpočtových opatření a rozpisu rozpočtu obce Krhanice starostou obce.",
  ]),
  p("Místostarosta přečetl Přílohu č. 1."),
  p("Starosta přečetl Přílohu č. 2."),
  p("Petr Dub přečetl Přílohu č. 3."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Přílohu č. 1 Rozpočtu obce Krhanice na rok 2022: Závazné ukazatele a pravidla pro poskytování prostředků z rozpočtu obce Krhanice."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje Přílohu č. 2 Rozpočtu obce Krhanice na rok 2022: Poskytování dotací – veřejnoprávní smlouvy a poskytování neúčelových finančních darů – darovací smlouvy."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje Přílohu č. 3 Rozpočtu obce Krhanice na rok 2022: Pravidla pro provádění rozpočtových opatření a rozpisu rozpočtu obce Krhanice."),
  vote(V8),
  h5("Rozprava k rozpočtu obce na rok 2022"),
  ...ul([
    "L.Maršíková: Dotaz na příčinu navýšení částky na odpady. Starosta: Skládka v Přibyšicích je uzavřena. Odpad se vozí do Votic. Navýšení jsme spočítali na 38%.",
    "L.Maršíková: Nenabízí se otázka motivace občanů, aby odpadů bylo méně. Nestálo by za úvahu domácí třídění? Starosta: Byl jsem na zkušené v Jílovém u Prahy. Systém ukládání tříděných odpadů je nákladný pro město. Museli zakoupit 2 multikáry, jsou potřeba pracovníci a také sběrný dvůr. Platí se systém, čtečky kódů, tisk kódů, … Pro menší obce to není ekonomicky únosné.",
    "J.Bydžovská: Rozpočet bude schodkový. Pokud bude škola hrazena z rezervy, zbyde tam ještě nějaká částka? Starosta: 2 - 3 miliony. Ještě mohou přijít peníze koncem roku (daně, EKOKOM) a příjmy na rok 2022 jsou podhodnocené.",
  ]),
  h5("Návrh"),
  p("ZO schvaluje Rozpočet obce Krhanice na rok 2022 jako schodkový. Schodek bude kryt finančními prostředky z minulých let."),
  vote(V8),

  h3("6) Obecně závazné vyhlášky obce Krhanice – odpady"),
  h4("Obecně závazná vyhláška obce Krhanice č. 2/2021, o stanovení obecního systému odpadového hospodářství"),
  p("Vyhláška musí reagovat na změnu zákona o odpadech. Obsahově je stejná. Část týkající se stavebních odpadů tato vyhláška již neobsahuje. Stavební odpad nebyl a nebude zařazen v našem systému odpadového hospodářství. Likvidaci si provádí občané na vlastní náklady."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Obecně závaznou vyhlášku obce Krhanice č. 2/2021, o stanovení obecního systému odpadového hospodářství."),
  vote(V8),
  h4("Obecně závazná vyhláška obce Krhanice č. 3/2021, o místním poplatku za obecní systém odpadového hospodářství"),
  p("Se změnou zákona o odpadech se mění celá logika poplatku za odpady. Dále došlo k uzavření skládky v Přibyšicích. Odpad se vozí do Votic. Náklady vzrostly o 38 %."),
  p("Je jedna částka poplatku pro všechny poplatníky, a to je 1000,- Kč. Děti do jednoho roku jsou osvobozeny od poplatku. Úlevu mají děti 2 – 18 let, osoby starší 60 let a osoby s průkazem ZP/ZTP, a to ve výši 200,- Kč. Občan s trvalým pobytem může požádat o poskytnutí finančního daru na snížení dopadu navýšeného poplatku za odpady, a to ve výši 250,- Kč na občana, a to vždy až po zaplacení příslušného poplatku."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Obecně závaznou vyhlášku obce Krhanice č. 3/2021, o místním poplatku za obecní systém odpadového hospodářství."),
  vote(V8),

  h3("7) Vydání změny č. 1 územního plánu Krhanice"),
  p("Informace starosty: Jsme před vydáním změny č. 1 územního plánu Krhanice. Odůvodnění: Obecní úřad Krhanice, který pořizoval změnu č. 1 územního plánu Krhanice ve smyslu ustanovení § 6 odst. 2 zákona č. 183/2006 Sb., o územním plánování a stavebním řádu, ve znění pozdějších předpisů (dále jen stavební zákon) na základě zadání schváleného zastupitelstvem obce Krhanice, dokončil práce na pořízení změny č. 1 územního plánu. V souladu s ustanovením § 55b odst. 10 ve spojení s § 54 odst. 1 stavebního zákona Obecní úřad Krhanice předkládá Zastupitelstvu obce Krhanice návrh na vydání změny č. 1 územního plánu Krhanice s jeho odůvodněním."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh usnesení o vydání změny č. 1 územního plánu Krhanice"),
  p("Zastupitelstvo obce"),
  p("I. bere na vědomí „Předkládací zprávu ke změně č. 1 územního plánu (dále též „ÚP“) Krhanice“;"),
  p("II. ověřilo soulad s ustanovením § 54 odst. 2 zákona č. 183/2006 Sb., o územním plánování a stavebním řádu (stavební zákon) v platném znění, že zpracovaná dokumentace není v rozporu:"),
  ...nl([
    "s Politikou územního rozvoje ČR, ve znění Aktualizací,",
    "s územně plánovací dokumentací vydanou krajem – se Zásadami územního rozvoje Středočeského kraje, ve znění Aktualizací,",
    "s výsledkem řešení rozporů (nebyly řešeny),",
    "se stanovisky dotčených orgánů,",
    "se stanoviskem krajského úřadu ze dne 3.11.2021;",
  ]),
  p("III. rozhodlo o námitkách v souladu s kap. 15. odůvodnění změny;"),
  p("IV. vydává změnu č. 1 územního plánu Krhanice podle ustanovení § 6 odst. 5 písm. c) stavebního zákona formou opatření obecné povahy;"),
  p("V. ukládá pořizovateli:"),
  ...nl([
    "zajistit po nabytí účinnosti změny č. 1 ÚP Krhanice povinnosti vyplývající z ustanovení § 165 stavebního zákona a z § 14 vyhlášky č. 500/2006 Sb., o územně analytických podkladech, územně plánovací dokumentace a způsobu evidence územně plánovací činnosti,",
    "zaslat registrační list Krajskému úřadu Středočeského kraje ve smyslu ustanovení § 162 stavebního zákona.",
  ]),
  vote(V8),

  h3("8) Koupě, prodej, pronájem"),
  ...ul(["pronajmout pozemek parc. č. 59/1 k. ú. Krhanice o výměře 1223 m² od 1.1.2022 do 31.12.2022 za cenu 10,- Kč/1 m²/rok za účelem zřízení zahrádky."]),
  p("Informace starosty: Jedná se o žádost Jana a Jaroslavy Klapáčových. Smlouva je uzavírána na 1 rok."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronájem pozemku parc. č. 59/1 k. ú. Krhanice o výměře 1223 m² od 1.1.2022 do 31.12.2022 za cenu 10,- Kč/1 m²/rok za účelem zřízení zahrádky Janu a Jaroslavě Klapáčovým, Hennerova 3229, 150 00 Praha 5."),
  vote(V8),
  ...ul(["pronajmout část pozemku parc. č. 509/16 k. ú. Krhanice o výměře 92 m² a část pozemku parc. č. 510/4 k. ú. Krhanice o výměře 58 m² od 1.1.2022 do 31.12.2022 za cenu 5,- Kč/1 m²/rok za účelem zřízení zahrádky."]),
  p("Informace starosty: Jedná se o žádost Petra Radosty. Smlouva je uzavírána na 1 rok."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronájem části pozemku parc. č. 509/16 k. ú. Krhanice o výměře 92 m² a část pozemku parc. č. 510/4 k. ú. Krhanice o výměře 58 m² od 1.1.2022 do 31.12.2022 za cenu 5,- Kč/1 m²/rok za účelem zřízení zahrádky Petrovi Radostovi, Krhanice č.ev. 156, 257 42 Krhanice."),
  vote(V8),
  ...ul(["pronajmout část pozemku parc.č. 312/19 k.ú. Krhanice o výměře 105 m² od 1.1.2022 do 31.12.2025 za cenu 5,- Kč/1 m2/rok za účelem zřízení zahrádky."]),
  p("Informace starosty: Jedná se o žádost Jaroslava Mixy. Podal výpověď z jiné části pozemku parc. č. 312/19, tato část pozemku je blíže k jeho bydlišti."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronájem části pozemku parc.č. 312/19 k.ú. Krhanice o výměře 105 m² za účelem zřízení zahrádky na dobu 4 let za cenu 5,- Kč/1 m2/rok od 1.1.2022 Jaroslavu Mixovi, Krhanice 72, 257 42 Krhanice."),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 1 – Mixa )"),
  ...ul(["pronajmout část pozemku parc. č. 312/8 k.ú. Krhanice o výměře 18 m² za účelem umístění vozíku za auto na dobu 4 let za cenu 5,- Kč/1 m²/rok od 1.3.2022."]),
  p("Informace starosty: Jedná se o žádost Petra Pospíšila. Měl již pronajato."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronájem části pozemku parc. č. 312/8 k.ú. Krhanice o výměře 18 m² za účelem umístění vozíku za auto na dobu 4 let za cenu 5,- Kč/1 m²/rok od 1.3.2022 Petrovi Pospíšilovi, Krhanice 216, 257 42 Krhanice."),
  vote(V8),
  ...ul(["pronajmout část pozemku parc. č. 110/1 k.ú. Krhanice o výměře 150 m² za účelem dočasného zřízení zahrádky na dobu 4 let za cenu 5,- Kč/1 m²/rok od 1.3.2022."]),
  p("Informace starosty: Jedná se o žádost Jiřího Bažanta. Měl již pronajato."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronájem části pozemku parc. č. 110/1 k.ú. Krhanice o výměře 150 m² za účelem dočasného zřízení zahrádky na dobu 4 let za cenu 5,- Kč/1 m²/rok od 1.3.2022 Jiřímu Bažantovi, Krhanice 48, 257 42 Krhanice."),
  vote(V8),
  ...ul(["koupit oddělenou část pozemku parc.č. 1953/9 k.ú. Krhanice o výměře 89 m² za cenu 55,- Kč/1 m²."]),
  p("Informace starosty: Jedná se cestičku u silnice II/106 v obci Prosečnice navazující na plochu vedle bývalého obchodu směrem k vlakovému nádraží a bytovým domům využívanou pěšími. Obec v budoucnu bude budovat chodníček na této oddělené části. Celkem: 4.895,- Kč."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje koupi oddělené části pozemku parc.č. 1953/9 k.ú. Krhanice o výměře 89 m² za cenu 55,- Kč/1m² od Altstaedter Investments a.s., Radlická 180/20, 150 00 Praha 5. Náklady na geodetické oddělení a náklady na vklad do katastru nemovitostí hradí kupující."),
  vote(V8),
  ...ul(["uzavřít Smlouvu o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby na pozemku parc. č. 1944/4 k.ú. Krhanice s ČEZ Distribuce, a.s., IČ 24729035, DIČ CZ24729035, se sídlem Děčín IV-Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 7.200,- Kč na kabelové vedení NN."]),
  p("Informace starosty: Jedná se o stavební pozemek u obce Prosečnice. Jde o jeho zasíťování elektrickou energií."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby na pozemku parc. č. 1944/4 k.ú. Krhanice s ČEZ Distribuce, a.s., IČ 24729035, DIČ CZ24729035, se sídlem Děčín IV-Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 7.200,- Kč na kabelové vedení NN."),
  vote(V8),

  h3("9) Různé"),
  h4("CZ.05.5.18/0.0/0.0/19_121/0010073 Zateplení, výměna zdroje tepla v ZŠ v obci Krhanice a CZ.05.5.18/0.0/0.0/19_121/0010072 Pořízení centrální vzduchotechniky do ZŠ Krhanice"),
  p("Informace starosty: Obdrželi jsme změnové Rozhodnutí o poskytnutí dotace na projekt Zateplení, výměna zdroje tepla v ZŠ v obci Krhanice a na projekt Pořízení centrální vzduchotechniky do ZŠ Krhanice. Na základě Rozhodnutí č. 19000735 o poskytnutí finančních prostředků ze Státního fondu životního prostředí ČR je dále zapotřebí doložit následující podklady ke smlouvě, a tudíž musíme schválit záležitosti jako trvalý příkaz na splátku jistiny a souhlas s inkasem z našeho účtu v max. výši součtu prvních tří splátek úroků podle splátkového kalendáře. Budeme platit od 25.3.2023 do 31.12.2032 161.827,04 Kč měsíčně (zateplení) a 20 754,32 Kč měsíčně (vzduchotechnika) a Státní fond si bude z našeho účtu strhávat úroky – proměnlivé snižující se částky. Celkově bude půjčka 6.473.081,50 Kč s celkovým úrokem 142.003,23 Kč pro zateplení a výměnu zdroje tepla. Pro vzduchotechniku je to půjčka 401.619,30 Kč s celkovým úrokem 8.810,52 Kč."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí Rozhodnutí o poskytnutí dotace (změna) pro projekt CZ.05.5.18/0.0/0.0/19_121/0010073 Zateplení, výměna zdroje tepla v ZŠ v obci Krhanice a Rozhodnutí o poskytnutí dotace (změna) pro projekt CZ.05.5.18/0.0/0.0/19_121/0010072 Pořízení centrální vzduchotechniky do ZŠ Krhanice."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pro projekt CZ.05.5.18/0.0/0.0/19_121/0010073 Zateplení, výměna zdroje tepla v ZŠ v obci Krhanice splátkový kalendář."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje pro projekt CZ.05.5.18/0.0/0.0/19_121/0010072 Pořízení centrální vzduchotechniky do ZŠ Krhanice splátkový kalendář."),
  vote(V8),
  h5("1.projekt: Zateplení, výměna zdroje tepla v ZŠ v obci Krhanice"),
  h5("Návrh"),
  p("ZO schvaluje pro projekt CZ.05.5.18/0.0/0.0/19_121/0010073 Zateplení, výměna zdroje tepla v ZŠ v obci Krhanice zřízení trvalého příkazu z bankovního účtu obce č.ú. 320094309/0800 vedeného u ČS a.s. ve prospěch Státního fondu životního prostředí na splátku jistiny od 25.3.2023 do 31.12.2032 ve výši 161.827,04 Kč, bankovní spojení Fondu: č.ú. 30007-9025001/0710, variabilní symbol: 19000735 (číslo Smlouvy projektu), specifický symbol: 21 dle splátkového kalendáře."),
  vote(V8),
  h5("Návrh"),
  p("ZO pověřuje starostu obce pro projekt CZ.05.5.18/0.0/0.0/19_121/0010073 Zateplení, výměna zdroje tepla v ZŠ v obci Krhanice zřízením trvalého příkazu z bankovního účtu obce č.ú. 320094309/0800 vedeného u ČS a.s. ve prospěch Státního fondu životního prostředí na splátku jistiny od 25.3.2023 do 31.12.2032 ve výši 161.827,04 Kč, bankovní spojení Fondu: č.ú. 30007-9025001/0710, variabilní symbol: 19000735 (číslo Smlouvy projektu), specifický symbol: 21 dle splátkového kalendáře."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje pro projekt CZ.05.5.18/0.0/0.0/19_121/0010073 Zateplení, výměna zdroje tepla v ZŠ v obci Krhanice souhlas s inkasem z bankovního účtu obce č.ú. 320094309/0800 vedeného u ČS a.s. ve prospěch Státního fondu životního prostředí v max. výši součtu prvních tří splátek úroků, tj. 20 754,32 Kč od 30.6.2023 do 31.1.2033, bankovní spojení Fondu: č.ú. 30007-9025001/0710, variabilní symbol: 19000735 (číslo Smlouvy projektu), specifický symbol: 23 dle splátkového kalendáře."),
  vote(V8),
  h5("Návrh"),
  p("ZO pověřuje starostu obce pro projekt CZ.05.5.18/0.0/0.0/19_121/0010073 Zateplení, výměna zdroje tepla v ZŠ v obci Krhanice zajištěním souhlasu s inkasem z bankovního účtu obce č.ú. 320094309/0800 vedeného u ČS a.s. ve prospěch Státního fondu životního prostředí v max. výši součtu prvních tří splátek úroků, tj. 20 754,32 Kč od 30.6.2023 do 31.1.2033, bankovní spojení Fondu: č.ú. 30007-9025001/0710, variabilní symbol: 19000735 (číslo Smlouvy projektu), specifický symbol: 23 dle splátkového kalendáře."),
  vote(V8),
  h5("2.projekt: Pořízení centrální vzduchotechniky do ZŠ Krhanice"),
  h5("Návrh"),
  p("ZO schvaluje pro projekt CZ.05.5.18/0.0/0.0/19_121/0010072 Pořízení centrální vzduchotechniky do ZŠ Krhanice zřízení trvalého příkazu z bankovního účtu obce č.ú. 320094309/0800 vedeného u ČS a.s. ve prospěch Státního fondu životního prostředí na splátku jistiny od 25.3.2023 do 31.12.2032 ve výši 10.040,48 Kč, bankovní spojení Fondu: č.ú. 30007-9025001/0710, variabilní symbol: 19000745 (číslo Smlouvy projektu), specifický symbol: 21."),
  vote(V8),
  h5("Návrh"),
  p("ZO pověřuje starostu obce pro projekt CZ.05.5.18/0.0/0.0/19_121/0010072 Pořízení centrální vzduchotechniky do ZŠ Krhanice zřízením trvalého příkazu z bankovního účtu obce č.ú. 320094309/0800 vedeného u ČS a.s. ve prospěch Státního fondu životního prostředí na splátku jistiny od 25.3.2023 do 31.12.2032 ve výši 10.040,48 Kč, bankovní spojení Fondu: č.ú. 30007-9025001/0710, variabilní symbol: 19000745 (číslo Smlouvy projektu), specifický symbol: 21."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje pro projekt CZ.05.5.18/0.0/0.0/19_121/0010072 Pořízení centrální vzduchotechniky do ZŠ Krhanice souhlas s inkasem z bankovního účtu obce č.ú. 320094309/0800 vedeného u ČS a.s. ve prospěch Státního fondu životního prostředí v max. výši součtu prvních tří splátek úroků, tj. 1.287,70 Kč od 30.6.2023 do 31.1.2033, bankovní spojení Fondu: č.ú. 30007-9025001/0710, variabilní symbol: 19000745 (číslo Smlouvy projektu), specifický symbol: 23."),
  vote(V8),
  h5("Návrh"),
  p("ZO pověřuje starostu obce pro projekt CZ.05.5.18/0.0/0.0/19_121/0010072 Pořízení centrální vzduchotechniky do ZŠ Krhanice zajištěním souhlasu s inkasem z bankovního účtu obce č.ú. 320094309/0800 vedeného u ČS a.s. ve prospěch Státního fondu životního prostředí v max. výši součtu prvních tří splátek úroků, tj. 1.287,70 Kč od 30.6.2023 do 31.1.2033, bankovní spojení Fondu: č.ú. 30007-9025001/0710, variabilní symbol: 19000745 (číslo Smlouvy projektu), specifický symbol: 23."),
  vote(V8),

  h4("Schválení příkazní smlouvy na BOZP projektu Zateplení, výměna zdroje tepla v ZŠ v obci Krhanice a projektu Pořízení centrální vzduchotechniky do ZŠ Krhanice"),
  p("Na rekonstrukci ZŠ Krhanice musíme mít technika BOZP. Spolupracujeme s Martinem Michálkem. Předložil příkazní smlouvu. Ceny odpovídají běžným cenám. Protože se jedná o dotační projekt, smlouvu musí schválit zastupitelstvo obce."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření příkazní smlouvy na činnost koordinátora BOZP v rámci akce „Krhanice – revitalizace a VZT budovy ZŠ“ v maximální výši 45.000,- Kč s Martinem Michálkem, IČO: 42567980, se sídlem Senohrabská 2943/10, 141 00 Praha 4."),
  vote(V8),

  h4("Zápis z dílčího přezkoumání hospodaření obce Krhanice"),
  p("Starosta seznámil se Zápisem z dílčího přezkoumání hospodaření obce ze dne 1.12.2021 s výsledkem nebyly zjištěny chyby a nedostatky – kontrolu provedl Krajský úřad Středočeského kraje, Odbor interního auditu a kontroly."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí Zápis z dílčího přezkoumání hospodaření obce ze dne 1.12.2021."),

  h4("Přísedící u Okresního soudu Benešov"),
  p("Starosta seznámil s návrhem kandidáta na funkci přísedícího u Okresního soudu Benešov: Ing. Dany Novákové, trvale bytem Krhanice 297, 257 42 Krhanice."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje zvolení kandidáta na funkci přísedícího u Okresního soudu Benešov: Ing. Dana Nováková, dle zákona č. 6/2000 Sb., o soudech a soudcích, v platném znění."),
  vote(V8),

  h4("Souhlas se vznikem pracovněprávních vztahů zastupitelů"),
  p("Informace starosty: Dle zákona č. 128/2000 Sb., o obcích, § 84 odst. 2 písm. p) je zastupitelstvu obce vyhrazeno vyslovovat souhlas se vznikem pracovněprávního vztahu mezi obcí a členem zastupitelstva obce. Protože takové pracovně právní vztahy jsou reálné, provedeme výčet pracovních oblastí a zastupitelů."),
  p("Oblast požární ochrana: Ing. Tomáš Kratochvíl, Ing. Martin Jiřička"),
  p("Oblast veřejná zeleň: Ing. Bohuslav Kadeřábek, Ing. Tomáš Kratochvíl"),
  p("Oblast komunální služby: Ing. Bohuslav Kadeřábek, Ing. Tomáš Kratochvíl"),
  p("Oblast lesní hospodářství: Ing. Bohuslav Kadeřábek, Ing. Tomáš Kratochvíl"),
  p("Oblast Činnosti knihovnické: Bc. Petr Dub"),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje a souhlasí se vznikem pracovněprávních vztahů mezi obcí a členem zastupitelstva obce s platností od 1.1.2022 do 31.12.2022, a to Oblast požární ochrana: Ing. Tomáš Kratochvíl, Ing. Martin Jiřička; Oblast veřejná zeleň: Ing. Bohuslav Kadeřábek, Ing. Tomáš Kratochvíl; Oblast komunální služby: Ing. Bohuslav Kadeřábek, Ing. Tomáš Kratochvíl; Oblast lesní hospodářství: Ing. Bohuslav Kadeřábek, Ing. Tomáš Kratochvíl; Oblast Činnosti knihovnické: Bc. Petr Dub. Dohody budou uzavírány v průběhu roku 2022 dle konkrétních potřeb obce."),
  vote(V8),

  h4("Navýšení vodného na rok 2022"),
  p("Informace starosty: Zdražování se promítne i do ceny pitné vody. Z důvodu navýšení vody z Posázavského vodovodu, zdražení elektrické energie a zdražení materiálu bude cena pitné vody navýšena o 4,50 Kč bez DPH (4,95 s DPH). V roce 2021 byla cena vody s DPH 55,45 Kč. Pro rok 2022 bude cena vody 60,40 Kč s DPH."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje cenu vodného pro rok 2022 ve výši 60,40 Kč s DPH/1 m³."),
  vote(V8),

  h4("Ceník dřeva od 1.1.2022"),
  p("Informace starosty: Zvedáme ceny za palivové dřevo o 50,- Kč za 1 m³. Ceník palivového dřeva bude od 1.1.2022:"),
  p("Cena v Kč/1 m³ (1 prm = 1 prostorový metr rovnaný; polena rovnaná do krychle 1x1x1 metr). Kód nomenklatury celního sazebníku: 4401."),
  p("Měkké dřevo, palivové dřevo v polenech: BOROVICE 400 Kč, SMRK 300 Kč, BŘÍZA 300 Kč. Tvrdé dřevo, palivové dřevo v polenech: DUB 900 Kč, BUK 800 Kč, AKÁT 900 Kč."),
  p("Měkké dřevo, palivové dřevo ve větvích, otepích a podobných tvarech: BOROVICE 50 Kč, SMRK 30 Kč, BŘÍZA 20 Kč. Tvrdé dřevo, palivové dřevo ve větvích, otepích a podobných tvarech: DUB 100 Kč, BUK 80 Kč, AKÁT 100 Kč."),
  p("V případě, že se obec stane plátcem DPH, bude k této ceně připočtena příslušná sazba DPH dle aktuální výše."),
  h5("Návrh"),
  p("ZO schvaluje ceník palivového dřeva od 1.1.2022."),
  vote(V8),
  p("Poznámka pro zastupitele: Pronájmy ostatní včetně pronájmu klubovny na víceúčelovém hřišti – samostatné pracovní sezení zastupitelů."),

  h4("Rekonstrukce hrobu rudoarmějců na hřbitově v Krhanicích"),
  p("Informace starosty: Na hřbitově v Krhanicích je hrob rudoarmějců. Hrob je potřeba rekonstruovat. Písmo je zašlé, túje jsou přerostlé, plochu kolem hrobu je třeba zrekonstruovat. Je možnost požádat o dotaci z programu Zachování a obnova historických hodnot I – Ministerstvo obrany."),
  p("Odhadovaná částka rekonstrukce je (původně 186.000,- Kč), 241.800,- Kč (navýšení o 30%)."),
  p("Z programu: IV. Výzva k podání žádosti o dotaci na zabezpečení péče o válečné hroby (čj. MO 278239/2021-7460). Poskytovatel programu 107290 – Zachování a obnova historických hodnot I, Česká republika – Ministerstvo obrany vyhlašuje výzvu k podávání žádostí o poskytnutí dotace na zabezpečení péče o válečné hroby."),
  p("Věcné zaměření výzvy: Dotace je určena na účelové udržování válečných hrobů a pietních míst v důstojném stavu či na jejich výstavbu a zachování památky vojáků a ostatních osob, které zahynuly v boji nebo v důsledku aktivní účasti ve válečném konfliktu."),
  p("Dotace ministerstva na realizaci konkrétní akce činí 80 % z celkových uznatelných skutečně vynaložených nákladů na stavební část realizace akce. Minimální výše poskytované dotace je 50,0 tis. Kč."),
  p("Termín k elektronickému podání žádostí je stanoven od 1. 11. 2021 do 31. 1. 2022."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje podání žádosti o dotaci na Rekonstrukci hrobu rudoarmějců na hřbitově v Krhanicích z programu 107290 – Zachování a obnova historických hodnot I, Česká republika – Ministerstvo obrany v rámci IV. Výzvy k podání žádosti o dotaci na zabezpečení péče o válečné hroby (čj. MO 278239/2021-7460)."),
  vote(V8),

  h4("Dotace chodník k viaduktu"),
  p("Informace starosty: Chodník, který bude napojen na chodník u nové silnice od základní a mateřské školy až k odbočení na Vlčí důl směrem k viaduktu je stavebně povolen. Byla vypsána dotace a v návaznosti na ní byl vyhotoven rozpočet celé akce rozdělený na uznatelné a neuznatelné náklady. Do neuznatelných nákladů patří dešťová kanalizace, která souvisí s chodníkem a veřejné osvětlení podél chodníku. Z uznatelných nákladů je dotace ve výši až 85%. Je na zvážení podání žádosti o dotaci a získání finančních prostředků na neuznatelné náklady z jiných dotačních zdrojů. Pokud jiné dotační tituly nebudou, tak dle výsledku jednání zastupitelů se rozhodneme podat žádost o dotaci. Nyní je shoda na záměru pro žádost. Pokud budeme připravovat žádost, budeme na ní spolupracovat s Posázavím, o.p.s. za cenu 20.000,- Kč bez DPH."),
  p("Uznatelné náklady: 2 639 608,01 Kč"),
  p("Neuznatelné náklady: 3 870 168,37 Kč"),
  p("Celkem (cena vč. DPH): 6 509 776,38 Kč"),
  p("Dotační titul: Státní fond dopravní infrastruktury: opatření ke zvýšení bezpečnosti nebo plynulosti dopravy nebo opatření ke zpřístupňování dopravy osobám s omezenou schopností pohybu nebo orientace pro rok 2022."),
  p("Akce oblast I. Příspěvek lze poskytnout na Akce investičního charakteru a) podél silnic I., II. nebo III. třídy, nebo b) podél místních komunikací (mimo místních komunikací IV. třídy, na kterých je umožněn smíšený provoz), ležících na trase, která musí být odsouhlasená v rámci NRPM s doloženou průměrnou intenzitou dopravy vyšší než 500 vozidel/24hodin. Věcná orientace Akcí: o výstavba, rekonstrukce nebo úpravy chodníků; o výstavba, rekonstrukce nebo bezbariérové úpravy nástupišť linkových spojů a veřejné hromadné dopravy (MHD, integrované dopravy, atd.) podél autobusových zastávek;"),
  h5("Rozprava"),
  ...ul([
    "P.Bydžovský: Nešlo by oddělit osvětlení od projektu na chodník a využít jinou dotaci? Starosta: Pokud ano, uděláme to, ale pokud ne, bude to obec muset zaplatit jako neuznatelný náklad.",
    "R.Novotný: Dotaz, zda by nešlo umístit lampy na sloupy ČEZu a osvětlení by se nemuselo vůbec řešit. Starosta: Dostali jsme dopis, že naše veřejné osvětlení na sloupech ČEZu nesmí být.",
    "P.Bydžovský: V Netvořicích vyměnili všechna světla a sloupy veřejného osvětlení. Nestálo by za to zjistit, zda využili dotaci a jakou? Starosta: Zavolám starostce Netvořic. Proběhla diskuse o úsporách na provozu osvětlení: zkrácení doby svícení, postupné rozsvěcování, po půlnoci nižší svítivost.",
  ]),
  h5("Návrh"),
  p("ZO schvaluje podání žádosti o dotaci na Státní fond dopravní infrastruktury na opatření ke zvýšení bezpečnosti nebo plynulosti dopravy pro rok 2022 pro projekt Krhanice – chodník podél silnice III/1066."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje spolupráci s Posázavím o.p.s., Zámek Jemniště 1, 257 01 Postupice, IČO: 27129772 při vyhotovení a podání žádosti o dotaci (20.000,- kč bez DPH) a pro zajištění poradenství při realizaci výběrového řízení (15.000,- Kč) na Státní fond dopravní infrastruktury – opatření ke zvýšení bezpečnosti nebo plynulosti dopravy pro rok 2022 pro projekt Krhanice – chodník podél silnice III/1066."),
  vote(V8),

  h4("Obecní knihovna Krhanice"),
  p("Informace starosty: Návrh v pokračování v roce 2022 s osvobozením od placení registračního poplatku."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Dodatek č. 12 k Příloze č. 1 Knihovního řádu Obecní knihovny Krhanice Výpůjční řád."),
  vote(V8),

  h4("Několika větami"),
  p("Přečetl starosta."),

  h3("10) Diskuse"),
  ...ul([
    "L.Maršíková: Kde se bude konat obecní ples? Starosta: V Týnci nad Sázavou. Vše bude záležet na aktuálních opatřeních.",
    "L.Maršíková: Neplánujete vybudování nějakého prostoru na podobné akce, např. kulturní dům? Starosta: Určitě ne. Máme v plánu tělocvičnu.",
    "L.Maršíková: Nešlo by využít prostor u víceúčelového hřiště, nebo je to omezeno podmínkami dotace? Starosta: Je to klubovna, a tak je i zkolaudovaná. Musíme se zastupiteli určit pravidla využívání.",
    "L.Maršíková: Jaká je kapacita klubovny? Starosta: 36 lidí, max. 40.",
    "I. Vatechová: Poděkovala za Sbor dobrovolných hasičů Krhanice za spolupráci v roce 2021.",
    "R.Novotný: Dotaz, zda budou nějaká omezení na konci roku? Starosta: Záleží na opatřeních vlády. Za sebe bych byl rád, kdyby lidé po sobě na obecních pozemcích uklízeli po zábavní pyrotechnice.",
  ]),
  p("Starosta: Popřál všem k vánočním svátkům a do nového roku 2022."),

  h3("11) Usnesení a závěr"),
  p("a. Návrhová komise přečetla usnesení zastupitelstva obce."),
  vote(V8),
  p("b. Závěr: Zastupitelstvo obce bylo ukončeno v 17:23 hod."),

  p("Datum pořízení zápisu: 20.12.2021"),
  p("Ověřovatelé zápisu a starosta obce, podepsáno v listinné podobě."),
  h4("Přílohy"),
  ...nl(["Svolání zastupitelstva obce", "Prezenční listina zastupitelů", "Prezenční listina občanů"]),
];

async function run() {
  const r = await publishZapis({
    cislo: "5",
    rok: "2021",
    isoDate: "2021-12-10",
    dateLabel: "10. 12. 2021",
    fullDateDot: "10.12.2021",
    pdfPath: "scripts/zapisy-pdf/zapis-2021-5.pdf",
    transcript,
  });
  console.log("OK", r.docId, "blocks", r.blocks);
}
run().catch((e) => { console.error(e); process.exit(1); });
