/* eslint-disable no-console */
// Faithful transcript of Zápis č. 5/2024 (24.10.2024), transcribed VISUALLY
// from the official PDF (7 pages). Structure per scripts/build-zapis-2026-1.ts.
import { h3, h4, h5, p, vote, nl, ul, publishZapis, type Block } from "../zapis-lib";

const V8 = "PRO ( 8 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )";

const transcript: Block[] = [
  h4("Přítomni"),
  p("Aleš Papoušek, Jaroslav Mixa, Tomáš Kratochvíl, Jana Laboutková, Petr Dub, Lucie Maršíková, Šárka Dušová, Aleš Kozel"),
  h4("Omluveni"),
  p("Martin Jiřička"),

  h3("1) Zahájení, přivítání přítomných, konstatování přítomnosti"),
  p("Starosta konstatoval, že zasedání bylo svoláno dne 16.10.2024 bylo vyvěšeno na úřední desce obecního úřadu, tj. tedy nejméně 7 dní před zasedáním. Bylo tedy svoláno řádně a včas v souladu se zákonem o obcích v platném znění. Starosta konstatoval, že podle prezenční listiny je přítomno 8 členů zastupitelstva, tedy nadpoloviční většina členů zastupitelstva. K předchozímu zápisu nebyly vzneseny námitky."),
  h5("Určení zapisovatele"),
  p("Zápisem zasedání zastupitelstva obce byla pověřena Ing. Alena Kratochvílová."),

  h3("2) Volba návrhové komise a ověřovatelů zápisu"),
  p("Starosta přednesl návrh návrhové komise a ověřovatelů zápisu."),
  h5("Návrh"),
  p("ZO schvaluje návrhovou komisi ve složení: Jana Laboutková, Jaroslav Mixa."),
  h5("Návrh"),
  p("ZO schvaluje ověřovatele zápisu ve složení: Šárka Dušová, Lucie Maršíková."),
  vote(V8),

  h3("3) Schválení programu"),
  p("Starosta přečetl program"),
  ...nl([
    "Zahájení",
    "Volba návrhové komise a ověřovatelů zápisu",
    "Schválení programu",
    "Zpráva Finančního výboru",
    "Rozpočtové opatření",
    "Koupě, prodej, pronájem",
    "Různé",
    "Diskuse",
    "Závěr",
  ]),
  p("Starosta: Má někdo návrh na změnu nebo doplnění programu?"),
  h5("Návrh"),
  p("ZO schvaluje program zasedání zastupitelstva obce."),
  vote(V8),

  h3("4) Zpráva finančního výboru o kontrole hospodaření obce Krhanice za rok 2024; Zpráva o výsledcích veřejnosprávních kontrol hospodaření Mateřské školy Krhanice a Základní školy Krhanice za rok 2024"),
  p("Předseda finančního výboru Petr Dub seznámil s kontrolou hospodaření obce Krhanice za rok 2024 ze dne 22.10.2024. A dále seznámil s proběhlými veřejnosprávními kontrolami hospodaření příspěvkových organizací Mateřské školy Krhanice a Základní školy Krhanice. Kontroly proběhly dne 21.10.2024."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí protokoly o průběhu a výsledcích veřejnosprávních kontrol příspěvkových organizací Základní škola Krhanice a Mateřská škola Krhanice za rok 2024 ze dne 21.10.2024."),
  h5("Návrh"),
  p("ZO bere na vědomí zprávu finančního výboru o kontrole hospodaření obce Krhanice za rok 2024 ze dne 22.10.2024."),

  h3("5) Rozpočtové opatření"),
  h4("Rozpočtové opatření č. 10/2024"),
  p("Tomáš Kratochvíl informoval o aktualizaci vozového parku JSDHO Krhanice (zásahová jednotka hasičů). Dále informoval o nutnosti přístavby hasičské zbrojnice."),
  p("Starosta ukázal studii a video o přístavbě hasičské zbrojnice."),
  p("Předseda finančního výboru seznámil s rozpočtovým opatřením č. 10/2024."),
  h5("Rozprava"),
  p("P.Bydžovský: Dotaz, zda by přístavba nebyla lepší širší a delší, kdyby se do budoucna pořizovala nová cisterna? T.Krhatochvíl: Řešili jsme to s projektantem. Přístavba je připravena velikostně na větší automobilovou cisternu."),
  p("Š.Dušová: Dotaz, zda se vedle přístavby vejdou kontejnery na papír? Starosta: Ano, mezi plotem a přístavbou budou necelé čtyři metry."),
  p("L.Maršíková: Kdy by měla být realizace? Starosta: Příští rok."),
  p("Š.Dušová: Budou při stavbě omezeny autobusy? Starosta: Ne."),
  p("A.Kozel: Dotaz na obálkovou dražbu. Jakým způsobem bude probíhat? Starosta: Stejně jako při prodeji předchozí cisterny (trambusu)."),
  p("Š.Dušová: Kdo bude nabídky vyhodnocovat? Starosta: Starosta, místostarosta a T.Kratochvíl."),
  p("Š.Dušová: Obálková metoda se týká jen hasičských sborů nebo kohokoliv: Starosta: Může se přihlásit kdokoliv."),
  p("J.Bydžovská: Dotaz na přestříkání hasičského vozidla. Kterého se to týká? T.Kratochvíl: Vozidla, které stojí vedle hasičárny, má zelenou barvu."),
  p("Proběhla diskuse o označení, vybavení a počtu míst k sezení u přestříkaného hasičského auta."),
  p("P.Bydžovský: Dotaz na částku za přístavbu. Starosta: Mám hrubý odhad. Po kompletním dokončení projektové dokumentace bude udělán kvalifikovaný odhad nákladů přístavby."),
  p("L.Maršíková: Dotaz, zda se jednalo s majiteli sousedního pozemku, který mají od obce v pronájmu? Starosta: S panem Klapáčem jsem jednal ještě před jednáním s projektantem. Neměl s přístavbou žádný problém."),
  p("L.Maršíková: Dotaz, jak se bude v budoucnu užívat zahrada, kterou mají nyní v pronájmu Klapáčovi? Starosta: Pozemek bude pro hasiče. Je to dohoda z roku cca 2008. T.Kratochvíl: Byl to dříve pozemek hasičů. Po skončení pronájmu by ho chtěli opět využívat hasiči."),
  p("Proběhla diskuse o tom, zda bude jednou žádoucí, aby pozemek za hasičárnou využívali pouze hasiči a zda by se zelená plocha nedala využít jinak."),
  p("D.Nováková: Dotaz, zda v minulosti byly v Krhanicích i jiné spolky než volejbalisté a fotbalisté? Byla tady tělocvična? Starosta: V minulosti byli v obci hasiči a sokolové. Tělocvičnu jsme měli v bývalém Posádkovém domě armády, kam chodila cvičit i škola."),
  h5("Návrh"),
  p("ZO pověřuje starostu obce zajištěním prodeje automobilu Volkswagen Multivan s registrační značkou 8A5 7153 obálkovou metodou s minimální požadovanou cenou 100 000,- Kč."),
  vote(V8),
  h5("Návrh"),
  p("ZO pověřuje starostu obce zajištěním prodeje automobilu Volkswagen Transporter s registrační značkou 2SB 9433 obálkovou metodou s minimální požadovanou cenou 1 000,- Kč."),
  vote(V8),
  h5("Návrh"),
  p("ZO pověřuje starostu obce zajištěním prodeje dopravního automobilu Avia A30 K s registrační značkou BNA 0541 obálkovou metodou s minimální požadovanou cenou 1,- Kč."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje rozpočtové opatření obce Krhanice č. 10/2024."),
  vote(V8),

  h3("6) Koupě, prodej, pronájem"),
  ...ul(["uzavřít Smlouvu o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby č. IZ-12-6003886 na pozemcích parc. č. 1942/9 a 1956/33 k.ú. Krhanice s ČEZ Distribuce, a.s., IČO 24729035, DIČ CZ24729035, se sídlem Děčín IV-Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 8 390,- Kč na umístění zařízení distribuční soustavy – kabelové vedení + pojistková skříň."]),
  p("Informace starosty: Jedná se o kabelové vedení a pojistková skříň v Prosečnici."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby č. IZ-12-6003886 na pozemcích parc. č. 1942/9 a 1956/33 k.ú. Krhanice s ČEZ Distribuce, a.s., IČO 24729035, DIČ CZ24729035, se sídlem Děčín IV Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 8 390,- Kč na umístění zařízení distribuční soustavy – kabelové vedení + pojistková skříň."),
  vote(V8),
  ...ul(["uzavřít Smlouvu o zřízení věcného břemene - služebnosti č. IV-12-6016747/VB/001 „Krhanice – kNN – p.č. 102/48“ na pozemku parc.č. 102/38 k.ú. Krhanice s ČEZ Distribuce, a.s., IČO 24729035, DIČ CZ24729035, se sídlem Děčín IV-Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 2 000,- Kč na umístění zařízení distribuční soustavy – kabelové vedení."]),
  p("Informace starosty: Jedná se o kabelové vedení v Krhanicích v lokalitě Na Žlabech."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o zřízení věcného břemene - služebnosti č. IV-12-6016747/VB/001 „Krhanice – kNN – p.č. 102/48“ na pozemku parc.č. 102/38 k.ú. Krhanice s ČEZ Distribuce, a.s., IČO 24729035, DIČ CZ24729035, se sídlem Děčín IV-Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 2 000,- Kč na umístění zařízení distribuční soustavy – kabelové vedení."),
  vote(V8),
  ...ul(["pronajmout část pozemku parc. č. 224/4 k.ú. Krhanice o výměře 12 m² k umístění a provozování samoobslužné schránky určené pro vyzvednutí/vrácení/odeslání zásilek za cenu 1 000 Kč/1 měsíc na dobu neurčitou."]),
  p("Informace starosty: Jedná se o AlzaBox, který bude umístěn na rohu od budovy základní školy směrem k mateřské škole."),
  h5("Rozprava"),
  p("L.Maršíková: Připomínka k lokalitě, nepřipadá mi to jako šťastné řešení – podle mého se zvýší doprava v lokalitě, kde se pohybuje největší množství dětí, ať dopravou balíků do boxu, tak jejich vyzvedáváním. Nelíbí se mi i některé smluvní podmínky, např. délka smlouvy (3 roky) a výpovědní lhůta."),
  p("T.Kratochvíl: Shrnul všechny vytipované lokality pro Alzabox. Tato splňovala všechny potřebné podmínky."),
  p("Š.Dušová: Proč je Alzabox našikmo? Starosta: Ten větší Alzabox se tam rovně nevejde. Museli bychom vykácet jeden strom."),
  p("Proběhla diskuse o možnosti narovnání AlzaBoxu v budoucnu, až strom nebude - nebude to možné kvůli ukotvení boxu."),
  h5("Návrh"),
  p("ZO schvaluje pronájem části pozemku parc. č. 224/4 k.ú. Krhanice o výměře 12 m² k umístění a provozování samoobslužné schránky určené pro vyzvednutí/vrácení/odeslání zásilek za cenu 1 000 Kč/1 měsíc na dobu neurčitou firmě Alza.cz a.s., IČO: 27082440, se sídlem: Jankovcova 1522/53, 170 00 Praha 7 – Holešovice."),
  vote("PRO ( 5 ) – PROTI ( 1 - Maršíková ) – ZDRŽEL SE ( 2 – Bc.Dušová, Kozel )"),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o nájmu prostor pro umístění a provozování AlzaBoxu, tj. samoobslužné schránky určené mj. pro vyzvednutí/vrácení/odeslání zásilek na pozemku parc. č. 224/4 k.ú. Krhanice s firmou Alza.cz a.s., IČO: 27082440, se sídlem: Jankovcova 1522/53, 170 00 Praha 7 – Holešovice."),
  vote("PRO ( 6 ) – PROTI ( 1 - Maršíková ) – ZDRŽEL SE ( 1 – Bc.Dušová )"),
  h5("Návrh"),
  p("ZO pověřuje starostu obce uzavřením Smlouvy o nájmu prostor pro umístění a provozování AlzaBoxu, tj. samoobslužné schránky určené mj. pro vyzvednutí/vrácení/odeslání zásilek na pozemku parc. č. 224/4 k.ú. Krhanice s firmou Alza.cz a.s., IČO: 27082440, se sídlem: Jankovcova 1522/53, 170 00 Praha 7 – Holešovice."),
  vote("PRO ( 6 ) – PROTI ( 1 - Maršíková ) – ZDRŽEL SE ( 1 – Bc.Dušová )"),

  h3("7) Různé"),
  h4("A. INFORMACE STAROSTY OBCE – MĚSTSKÁ POLICIE JÍLOVÉ U PRAHY"),
  p("Jednání ohledně veřejnoprávní smlouvy – městská policie."),
  p("Musím vám bohužel oznámit, že Rada města Jílového u Prahy prozatím nesouhlasí s uzavřením Veřejnoprávní smlouvy o činnosti MP s obcí Krhanice, a to z odůvodněním, že katastrálně jsou Krhanice až za katastrem obce Kamenný Přívoz, tudíž by strážníci museli přejíždět přes obec se kterou prozatím nemají uzavřenou veřejnoprávní smlouvu. Pokud v budoucnu dojde k uzavření veřejnoprávní smlouvy s obcí Kamenný Přívoz tak můžeme obnovit jednání o veřejnoprávní smlouvě s městem Jílové u Prahy."),
  p("Zaměříme se tudíž v rámci zvyšování bezpečnosti na radary s ukazatelem rychlosti a SPZ."),
  h5("Rozprava"),
  p("P.Bydžovský: Navrhl by přesunout radar od chodníku k viaduktu, kde už je pro chodce bezpečněji, do jiné lokality. Starosta: Přesun a zakoupení nového radaru plánujeme."),

  h4("B. INFORMACE – UZAVÍRKA ČAKOVICE"),
  p("Starosta informoval o uzavírce Čakovice – Kamenice a dále o omezení semafory na Týnec nad Sázavou."),

  h4("C. INFORMACE – AUTOBUSOVÁ ZASTÁVKA U ŠKOLY"),
  p("Informace starosty:"),
  p("Negativní jev: Vandalismus v naší obci"),
  p("Byla poničena autobusová zastávka u školy – došlo ke zcizení 8 našroubovaných úchytů, které pro zloděje nemají žádný význam. Budu muset objednat nové."),

  h4("D. INFORMACE – HERNÍ PRVKY DĚTSKÁ HŘIŠTĚ V KRHANICÍCH A V PROSEČNICI"),
  p("Starosta: Jsem rád, že mohu informovat, že začátkem měsíce října byly nainstalovány nové herní prvky na dětská hřiště v Krhanicích a v Prosečnici. Na přípravě herních prvků se podílela Komise pro obnovu a rozvoj obce. Na výběru herních prvků se podíleli občané prostřednictvím ankety. A nyní již tyto další herní prvky mohou naše děti využívat."),
  h5("Rozprava"),
  p("D.Nováková: Dotaz, zda jsou nové prvky pojištěné? Starosta: Obec má pojištění na veškerý majetek obce."),
  p("L.Maršíková: Dotaz na kreslící tabuli na dětském hřišti v Krhanicích, zda bude uklizena nebo znovu umístěna? Místostarosta: Bude zabudována. Kvůli nemoci jsem to nestihl."),
  p("L.Maršíková: Dotaz, zda se vyřazují rozbité dětské hračky na pískovišti? T.Kratochvíl: Hračky byly přebrané v době instalace nových dětských prvků. Starosta: Má zaměstnankyně provádí průběžně likvidaci nevyhovujících hraček."),
  p("Š.Dušová: Dotaz na plachtu nad pískovištěm. T.Kratochvíl: Je to stínící síťovina na letní období. Jinak samotné pískoviště bude zakryto plachtou."),

  h3("8) Diskuse"),
  p("D.Nováková: U šatního kontejneru byla spousta věcí okolo. Kdy bude vyvezen? Starosta: Informoval jsem Diakonii Broumov. Oděvy kolem kontejneru jsme napytlovali. Bohužel druhý den pytle někdo vysypal."),
  p("D.Nováková: Do kdy budou hnědé kontejnery? Starosta: Do konce listopadu."),
  p("J.Bydžovská: Dotaz na doplňkovou činnost ve školce, zda by nemohla být smlouva stejná jako v základní škole?"),
  p("Starosta: Ředitelka mateřské školy řešila doplňkovou činnost dle zřizovací listiny, doplňková činnost musí být zisková. Starosta dohledal pravidla pronájmu pro základní školu z roku 2017. Musím se podívat do zřizovací listiny základní školy, zda jsou v souladu se zřizovací listinou."),
  p("P.Bydžovský: Pochválil, že se vyčistila plakátovací plocha u obchodu. Podělil se o svoji špatnou zkušenost s přelepováním aktuálních plakátů."),
  p("Proběhla všeobecná diskuse o plakátování, starostou připravených pravidlech, odstraňování velkoformátových plakátů, zda by nebylo vhodné za vyvěšení platit jako v Týnci."),

  h3("9) Závěr"),
  p("Zastupitelstvo obce bylo ukončeno v 19:42 hod."),

  p("Datum pořízení zápisu: 30.10.2024"),
  p("Ověřovatelé zápisu a starosta obce, podepsáno v listinné podobě."),
  h4("Přílohy"),
  ...nl(["Svolání zastupitelstva obce", "Prezenční listina zastupitelů", "Prezenční listina občanů"]),
];

async function run() {
  const r = await publishZapis({
    cislo: "5",
    rok: "2024",
    isoDate: "2024-10-24",
    dateLabel: "24. 10. 2024",
    fullDateDot: "24.10.2024",
    pdfPath: "scripts/zapisy-pdf/zapis-2024-5.pdf",
    transcript,
  });
  console.log("OK", r.docId, "blocks", r.blocks);
}
run().catch((e) => { console.error(e); process.exit(1); });
