/* eslint-disable no-console */
// Faithful, visually-transcribed minutes of Zápis č. 4/2024 (24.9.2024).
// Read page-by-page from the official PDF images (the PDF text layer is corrupt).
import { h3, h4, h5, p, vote, nl, ul, publishZapis, type Block } from "../zapis-lib";

const V9 = "PRO ( 9 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )";

const transcript: Block[] = [
  h4("Přítomni"),
  p("Aleš Papoušek, Jaroslav Mixa, Tomáš Kratochvíl, Jana Laboutková, Petr Dub, Martin Jiřička, Lucie Maršíková, Šárka Dušová, Aleš Kozel"),

  h3("1) Zahájení, přivítání přítomných, konstatování přítomnosti"),
  p("Starosta konstatoval, že zasedání bylo svoláno dne 12.9.2024, bylo vyvěšeno na úřední desce obecního úřadu, tj. tedy nejméně 7 dní před zasedáním. Bylo tedy svoláno řádně a včas v souladu se zákonem o obcích v platném znění. Starosta konstatoval, že podle prezenční listiny je přítomno 9 členů zastupitelstva, tedy nadpoloviční většina členů zastupitelstva. K předchozímu zápisu nebyly vzneseny námitky."),
  h5("Určení zapisovatele"),
  p("Zápisem zasedání zastupitelstva obce byla pověřena Ing. Alena Kratochvílová."),

  h3("2) Volba návrhové komise a ověřovatelů zápisu"),
  p("Starosta přednesl návrh návrhové komise a ověřovatelů zápisu."),
  h5("Návrh"),
  p("ZO schvaluje návrhovou komisi ve složení: Jana Laboutková, Jaroslav Mixa."),
  h5("Návrh"),
  p("ZO schvaluje ověřovatele zápisu ve složení: Petr Dub, Aleš Kozel."),
  vote(V9),

  h3("3) Schválení programu"),
  p("Starosta přečetl program"),
  ...nl([
    "Zahájení",
    "Volba návrhové komise a ověřovatelů zápisu",
    "Schválení programu",
    "Zpráva Kontrolního výboru",
    "Koupě, prodej, pronájem",
    "Pořízení Zprávy o uplatňování územního plánu Krhanice",
    "Společná voda d.s.o. – vstup obce Krhanice do dobrovolného svazku obcí",
    "Rozpočtová opatření",
    "Různé",
    "Diskuse",
    "Závěr",
  ]),
  p("Starosta: Má někdo návrh na změnu nebo doplnění programu?"),
  h5("Návrh"),
  p("ZO schvaluje program zasedání zastupitelstva obce."),
  vote(V9),

  h3("4) Zpráva Kontrolního výboru"),
  p("Předseda kontrolního výboru seznámil s kontrolou proběhlou dne 2.9.2024."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí Zápis z jednání Kontrolního výboru Zastupitelstva obce Krhanice dne 2.9.2024."),

  h3("5) Koupě, prodej, pronájem"),

  ...ul(["pronajmout část pozemku parc. č. 312/19 k.ú. Krhanice o výměře 101 m² ke zřízení dočasné zahrádky za cenu 10,- Kč/1 m²/rok od 1.10.2024 na dobu 4 let."]),
  p("Informace starosty: Jedná se o žádost Jaroslava Mixy, končí platnost dosavadní smlouvy na pronájem."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronájem části pozemku parc. č. 312/19 k.ú. Krhanice o výměře 101 m² ke zřízení dočasné zahrádky za cenu 10,- Kč/1 m²/rok od 1.10.2024 na dobu 4 let Jaroslavu Mixovi, Krhanice č.p. 72, 257 42 Krhanice."),
  vote("PRO ( 8 ) – PROTI ( 0 ) – ZDRŽEL SE ( 1 - Mixa )"),

  ...ul(["pronajmout část pozemku parc. č. 312/8 k.ú. Krhanice o výměře 10 m² k umístění vozíku za auto pro účely podnikání za cenu 20,- Kč/1 m²/rok od 1.10.2024 na dobu 4 let."]),
  p("Informace starosty: Jedná se o žádost Miroslava Rötha, končí platnost dosavadní smlouvy na pronájem."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronájem části pozemku parc. č. 312/8 k.ú. Krhanice o výměře 10 m² k umístění vozíku za auto pro účely podnikání za cenu 20,- Kč/1 m²/rok od 1.10.2024 na dobu 4 let Miroslavu Röthovi, Krhanice č.p. 16, 257 42 Krhanice."),
  vote(V9),

  ...ul(["pronajmout nebytové prostory – místnost v přízemí budovy Obecního úřadu Krhanice o výměře 15 m² k uskladnění malířských potřeb za cenu 250,- Kč/1 m²/rok od 1.1.2025 na dobu 4 let."]),
  p("Informace starosty: Jedná se o žádost Pavla Fišera, končí platnost dosavadní smlouvy na pronájem nebytových prostor."),
  h5("Rozprava"),
  p("L.Maršíková: Dotaz k bodům 1-3. Jedná se o pokračování smluv? Starosta: Ano."),
  p("I.Dvořák: Doporučil by uzavírat smlouvy pouze na rok. A započítávat inflační doložku. Obec by získala větší příjmy. Starosta: Lidé se o pozemky starají. Ušetří obci práci při sekání trávy."),
  p("Proběhla diskuse o očekávaném efektu zvýšení cen za pronájem obecních pozemků."),
  h5("Návrh"),
  p("ZO schvaluje pronájem nebytových prostor – místnost v přízemí budovy Obecního úřadu Krhanice o výměře 15 m² k uskladnění malířských potřeb za cenu 250,- Kč/1 m²/rok od 1.1.2025 na dobu 4 let Pavlu Fišerovi, Krhanice č.p. 78, 257 42 Krhanice."),
  vote(V9),

  ...ul(["pronajmout část pozemku parc. č. 1941/21 o výměře 1028 m² a pozemek parc.č. 1943/1 pro hospodaření v zemědělství za cenu 4% z ceny půdy úředně stanovené průměrné ceny pozemků v katastrálním území Krhanice dle vyhlášky č. 298/2014 Sb. o stanovení seznamu katastrálních území s přiřazenými průměrnými základními cenami zemědělských pozemků, v platném znění, na dobu 4 let od 1.11.2024."]),
  p("Informace starosty: Jedná se o žádost AG AGROPRIM, s.r.o., končí platnost dosavadní smlouvy na pronájem. Z důvodu, že se jedná o hospodaření v zemědělství, předkládám návrh ceny 4% z ceny půdy úředně stanovené průměrné ceny pozemků v katastrálním území Krhanice dle vyhlášky č. 298/2014 Sb. o stanovení seznamu katastrálních území s přiřazenými průměrnými základními cenami zemědělských pozemků, v platném znění."),
  h5("Rozprava"),
  p("P.Bydžovský: Dotaz na cenu za pronájem zemědělské půdy. Starosta: Dohledám ve vyhlášce a pošlu SMS."),
  h5("Návrh"),
  p("ZO schvaluje pronájem části pozemku parc. č. 1941/21 o výměře 1028 m² a pozemek parc.č. 1943/1 pro hospodaření v zemědělství za cenu 4% z ceny půdy úředně stanovené průměrné ceny pozemků v katastrálním území Krhanice dle vyhlášky č. 298/2014 Sb. o stanovení seznamu katastrálních území s přiřazenými průměrnými základními cenami zemědělských pozemků, v platném znění, na dobu 4 let od 1.11.2024 AG AGROPRIM, s.r.o., IČO 256 49 213, Netvořicec.p. 300, 257 44 Netvořice."),
  vote(V9),

  ...ul(["uzavřít Smlouvu o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby č. IV-12-6035207 na pozemcích parc. č. 2053/5, 1956/68, 2053/8 k.ú. Krhanice s ČEZ Distribuce, a.s., IČO 24729035, DIČ CZ24729035, se sídlem Děčín IV-Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 11 300,- Kč na umístění zařízení distribuční soustavy – kabelové vedení."]),
  p("Informace starosty: Jedná se o pozemek na kraji obce Prosečnice, nalevo od Krhanic. ČEZ bude budovat elektrickou přípojku ke stavebnímu pozemku parc.č. 1944/2 k.ú. Krhanice."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby č. IV-12-6035207 na pozemcích parc. č. 2053/5, 1956/68, 2053/8 k.ú. Krhanice s ČEZ Distribuce, a.s., IČO 24729035, DIČ CZ24729035, se sídlem Děčín IV-Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 11 300,- Kč na umístění zařízení distribuční soustavy – kabelové vedení."),
  vote(V9),

  ...ul(["uzavřít Dodatek č.1 ke Smlouvě o budoucí smlouvě o zřízení věcného břemene a dohodě o umístění stavby č. IV-12-6034244/VB/6 na pozemcích parc. č. 1972/1, 1977 a 35 k.ú. Krhanice s ČEZ Distribuce, a.s., IČO 24729035, DIČ CZ24729035, se sídlem Děčín IV Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou na umístění zařízení distribuční soustavy – kabelové vedení a podpěrný bod – betonový sloup."]),
  p("Informace starosty: Již jsme schvalovali – lokalita návsi U Lípy. ČEZ opomněl jeden pozemek parc.č. 35 k.ú. Krhanice. Budeme uzavírat Dodatek č.1."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Dodatku č.1 ke Smlouvě o budoucí smlouvě o zřízení věcného břemene a dohodě o umístění stavby č. IV-12-6034244/VB/6 na pozemcích parc. č. 1972/1, 1977 a 35 k.ú. Krhanice s ČEZ Distribuce, a.s., IČO 24729035, DIČ CZ24729035, se sídlem Děčín IV Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou na umístění zařízení distribuční soustavy – kabelové vedení a podpěrný bod – betonový sloup."),
  vote(V9),

  ...ul(["uzavřít Smlouvu o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby č. IV-12-6035376/VB/1 K_BN-KRHANICE-KNN-PARC.Č. 132/9 na pozemku parc.č. 132/5 k.ú. Krhanice s ČEZ Distribuce, a.s., IČO 24729035, DIČ CZ24729035, se sídlem Děčín IV-Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 2 000,- Kč na umístění zařízení distribuční soustavy – kabelové vedení."]),
  p("Informace starosty: Jedná se o pozemek za nádrží Gabčíkovo směrem k Palečníku. ČEZ bude budovat elektrickou přípojku k rekreačnímu pozemku."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby č. IV-12-6035376/VB/1 K_BN-KRHANICE-KNN-PARC.Č. 132/9 na pozemku parc.č. 132/5 k.ú. Krhanice s ČEZ Distribuce, a.s., IČO 24729035, DIČ CZ24729035, se sídlem Děčín IV-Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 2 000,- Kč na umístění zařízení distribuční soustavy – kabelové vedení."),
  vote(V9),

  h4("Střelecký klub Krhanice projevil zájem o koupi pozemku."),
  p("Informace starosty: Je na posouzení zastupitelstva, zda záměr prodeje ANO/NE. A dále stanovení ceny."),
  h5("Rozprava"),
  p("L.Maršíková: Dotaz, zda mají střelci pozemek v nájmu. Starosta: Ne."),
  p("L.Maršíková: Neprodávala by pozemek. V budoucnu by možná došlo k propojení Prosečnice a Krhanic. Vede tudy cesta podle vody."),
  p("A.Kozel: Pozemek nezasahuje do cesty."),
  p("Starosta: Propojení by bylo velice problematické. Cesta u vody bývá někdy zaplavena a v některých místech vede přes soukromé pozemky. A ne všichni majitelé těchto pozemků již nyní souhlasí s tím, aby se přes ně chodilo. Jedna majitelka pozemku navrhla obci, že obci celý pozemek prodá, ne pouze část pro případnou cestu."),
  p("Proběhla diskuse se závěrem, že starosta osloví střelecký klub a zjistí jaký má s pozemkem záměr."),

  h4("Věcné břemeno obce na cizím pozemku"),
  p("Informace starosty: Jedná se o kabely veřejného osvětlení ve vlastnictví obce na pozemku manželů Sedlákových. Jednalo by se o uzavření smlouvy na věcné břemeno, obec by byla smluvní stranou oprávněnou. Cena věcného břemene 3.000,- Kč/1 zatížený pozemek."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o věcném břemeni – služebnosti pro kabely veřejného osvětlení na pozemcích parc.č. 100/3 a 1439/9 k.ú. Krhanice za cenu 6.000,- Kč s vlastníky pozemku (strana povinná) Ing. Štěpán Sedlák, Zahrádecká 371/2, 142 00 Praha 4, Ludmila Sedláková, Na okruhu 389/13, 142 00 Praha 4. Vklad na katastrálním úřadě bude hradit Obec Krhanice jako strana oprávněná."),
  vote(V9),
  p("Z diskusí vyplynul závěr, že starosta svolá pracovní sezení zastupitelů, na kterém se budou řešit pronájmy a prodeje či koupě pozemků ze strany obce."),

  h3("6) Schválení pořízení Zprávy o uplatňování územního plánu Krhanice"),
  p("Informace starosty: Výzva pro rok 2025 by měla být vypsána ke konci tohoto roku. Uzavřeli bychom dvě smlouvy o dílo s Pavlou Bechyňovou a Ing. arch. Zuzanou Hrochovou."),
  p("PODPORA ÚZEMNĚ PLÁNOVACÍCH ČINNOSTÍ OBCÍ"),
  p("Cílem programu je podpořit zpracování územních plánů a jejich transformace do jednotného standardu, přispět ke koncepčnímu územnímu rozvoji prostřednictvím systémové dotace na zpracování územních plánů a jejich změn a tím i zkvalitnění rozhodování veřejné správy o území a zkvalitnění územní přípravy investic. Jednotný standard je součástí projektu na digitalizaci stavebního řízení a územního plánování. Jednotně zpracované části územních plánů přispějí k efektivnějšímu výkonu agend stavebního práva a koordinaci rozvoje území. Povinnost zpracovávat vybrané části územně plánovací dokumentace v jednotném standardu vychází z platného stavebního zákona."),
  h5("Rozprava"),
  p("Bc.Dušová: Kdo jsou tyto dámy a proč zrovna ony? Starosta: Při pořizování územního plánu proběhlo výběrové řízení a tyto dvě (Bechyňová, Hrochová) byly vybrány."),
  p("L.Maršíková: Není mi jasné, proč platíme dva lidi? Starosta: Každá z nich pracuje na svoje IČO. Je tedy třeba uzavřít s každou z nich smlouvu zvlášť."),
  p("I.Dvořák: Zpráva souvisí se stavebním zákonem. Nebyla už vypracována po schválení územního plánu? Starosta: Nebyla."),
  p("Proběhla diskuse bez přijetí závěrů."),
  h5("Návrh"),
  p("ZO schvaluje tyto body usnesení týkající se pořízení Zprávy o uplatňování územního plánu Krhanice"),
  p("I. Zastupitelstvo obce rozhodlo o pořízení zprávy o uplatňování územního plánu Krhanice;"),
  p("II. Zastupitelstvo obce schvaluje"),
  ...ul([
    "pořízení zprávy o uplatňování územního plánu Krhanice prostřednictvím Obecního úřadu Krhanice postupem podle § 46 odst. 2, písm. c) zákona č. 283/2021 Sb., stavební zákon, v platném znění,",
    "uzavření smlouvy s osobou splňující předpoklady pro výkon územně plánovací činnosti Pavlou Bechyňovou,",
    "uzavření smlouvy s projektantem Ing. arch. Zuzanou Hrochovou, ČKA 00 773, na technickou pomoc při zpracování zprávy;",
  ]),
  p("IV. Zastupitelstvo obce určilo"),
  ...ul(["Mgr. Aleše Papouška, člena zastupitelstva obce, který bude spolupracovat s pořizovatelem při pořizování územně plánovací dokumentace pro zbytek volebního období;"]),
  p("V. Zastupitelstvo obce pověřilo starostu obce"),
  ...ul([
    "zajistit naplnění požadavku vyplývajícího z ustanovení § 47 odst. 1 stavebního zákona,",
    "uzavřením smluv s Ing. arch Zuzanou Hrochovou a po obdržení potvrzení dle bodu a) se zástupcem pořizovatele, Pavlou Bechyňovou,",
    "předat po obdržení potvrzení zástupci pořizovatele podněty na změny územního plánu uložené v zásobníku žádostí od vydání změny č. 1 a další podněty obce.",
  ]),
  vote(V9),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o dílo na pořízení zprávy o uplatňování územního plánu pro obec Krhanice s Pavlou Bechyňovou, IČO: 70789444, Pražského povstání 2266, 256 01 Benešov."),
  vote(V9),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o dílo na technickou pomoc při zpracování Zprávy o uplatňování Územního plánu Krhanice s Ing. arch. Zuzanou Hrochovou, IČO: 47147334, Matoušova 18, 150 00 Praha 5."),
  vote(V9),

  h3("7) Společná voda d.s.o. – vstup obce Krhanice do dobrovolného svazku obcí"),
  p("Informace starosty: Posázavský vodovod – dobrovolný svazek obcí, jehož jsme členy a který sdružuje obce, město a městys, které zejména vlastní Posázavský vodovod vedoucí od Vestce do Chrástu nad Sázavou rozhodl o fúzi se Společná voda d.s.o."),
  p("Obec Krhanice se musí rozhodnout, zda zůstane sama, nebo zda bude souhlasit s fúzí a dále zda se stane členem Společná voda d.s.o."),
  p("Vstupní vklad bude cca 540 tisíc Kč (18,- kč krát počet odebraných m3 vody)."),
  p("Pokud vstup do Společná voda d.s.o.:"),
  p("Na základě Nájemní smlouvy z VHS Benešov ze dne 21.1.1999 uzavřené na dobu neurčitou, kdy VHS Benešov provozuje vodovod v obci Krhanice, bude třeba uzavřít Dodatek č. 1 k této smlouvě."),
  p("Časový horizont – předpokládaný vstup do Společná voda d.s.o. v roce 2025 – od 2.čtvrtletí."),
  h5("Rozprava"),
  p("L.Maršíková: Myslím si, že je lepší zůstat ve spolku."),
  p("I.Dvořák: Příspěvek bude sloužit i k opravám, nebo si případné opravy budeme platit sami? Starosta: Příspěvek je v návaznosti na koupi 50% VHS Benešov. Obec má fond, ze kterého hradíme např. modernizaci. Např. havárii v Prosečnici jsme neplatili."),
  p("I.Dvořák: Plánuje se zvýšení podílu ve VHS Benešov? Starosta: Francouzští majitelé nechtějí měnit poměr 50:50."),
  p("J.Bydžovská: Dotaz na dělení zisku. Starosta: Dobrovolný spolek vznikl před rokem. Zatím nevím výsledek."),
  p("Bc.Dušová: Vstupní příspěvek obcí je stejný? Máme všichni stejný hlas? Starosta: Vstupní příspěvek je podle množství pitné a splaškové vody. Hlas máme všichni stejný."),
  p("Proběhla diskuse bez přijetí závěrů."),
  h5("Návrh"),
  p("ZO schvaluje záměr vstupu obce Krhanice do dobrovolného svazku obcí Společná voda d.s.o., IČO:17408288, se sídlem Černoleská 1600, 256 01 Benešov, a to na základě Smlouvy o fúzi sloučením svazků Posázavský vodovod – dobrovolný svazek obcí, IČO: 14117223, se sídlem Masarykovo náměstí 194, 254 01 Jílové u Prahy a Společná voda d.s.o., IČO:17408288, se sídlem Černoleská 1600, 256 01 Benešov k rozhodnému dni."),
  vote(V9),
  h5("Návrh"),
  p("ZO pověřuje starostu k zajištění činností směřujících ke vstupu obce Krhanice do dobrovolného svazku obcí Společná voda d.s.o., IČO:17408288, se sídlem Černoleská 1600, 256 01 Benešov."),
  vote(V9),
  h5("Návrh"),
  p("ZO schvaluje uzavření Dodatku č. 1 k Nájemní smlouvě ze dne 21.1.1999 s Vodohospodářská společnost Benešov a.s., IČO: 47535865, se sídlem Černoleská 1600, 256 01 Benešov."),
  vote(V9),

  h3("8) Rozpočtová opatření"),
  h4("Rozpočtové opatření č. 7/2024 a 8/2024"),
  p("Starosta obce seznámil s rozpočtovými opatřeními č. 7/2024 a 8/2024 provedenými v souladu se schválenými pravidly ze dne 15.12.2023."),
  p("Č.7/2024: dotace ve výši 300 tisíc Kč od Středočeského kraje – Pořízení nového dopravního automobilu pro JSDHO (příjmy a výdaje)."),
  p("Č.8/2024: dotace Volby do zastupitelstva Stč. kraje a 1/3 Senátu Parlamentu ČR – dotace ze státního rozpočtu v částce 96 tisíc Kč (příjmy a výdaje)."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí rozpočtové opatření č. 7/2024 a č. 8/2024."),

  p("Informace starosty: pomoc obcím postiženým povodněmi. Stejný princip jako při tornádu v roce 2021 na jižní Moravě."),
  p("INFORMACE A PODĚKOVÁNÍ V SOUVISLOSTI S MIMOŘÁDNOU UDÁLOSTÍ OČEKÁVANÝCH VYDATNÝCH SRÁŽEK OD PÁTKU 13.9.2024 DO PONDĚLÍ 16.9.2024"),
  p("Rád bych Vás seznámil nejen s tím, jak probíhala příprava na mimořádnou událost v souvislosti s očekávanými vydatnými srážkami v naší obci, ale také bych rád poděkoval a ocenil nabídky pomoci."),
  p("V pátek v dopoledních hodinách byly nakoupeny pohonné hmoty do elektrocentrál a kalových čerpadel. Dále byli telefonicky nebo osobně kontaktováni majitelé nemovitostí nejvíce zasažených povodněmi v roce 2013. Byla jim nabídnuta případná pomoc při přípravě pozemku – odstranění věcí a materiálu v blízkosti koryta levobřežního přítoku Palečnického potoka – lokalita kolem nádrže u vrby v Krhanicích. Byl zajištěn případný výdej písku v jakoukoliv denní či noční dobu."),
  p("V pátek v odpoledních hodinách byla provedena kontrola technických prostředků pro čerpání vod, odstraňování padlých stromů, čištění dešťových kanalizací a příkopů a propustků kolem silnic a u Gabčíkova."),
  p("Na základě výzvy starosty, jako předsedy Protipovodňové komise se sešla většina členů komise a členové zásahové jednotky hasičů k přípravě výjezdových aut se všemi potřebnými technickými prostředky a pohonnými hmotami. Byla dohodnuta kontrola kritických míst na vodních tocích a dešťové kanalizaci a dále kontrola dalších míst. Byly určeny termíny a časy pro vyhodnocení akcí, stavů a kontrol."),
  p("O víkendu a v pondělí zásahová jednotka hasičů provedla odstraňování padlých nebo nakloněných stromů."),
  p("I ze strany občanů přišly nabídky pomoci při případném odstraňování následků povodňových škod. To velmi oceňuji a velmi děkuji."),
  p("Chtěl bych pochválit profesionální přístup členů zásahové jednotky hasičů, jak po stránce přípravy na případné mimořádné události, tak i za všechny činnosti, jejichž cílem je ochrana obyvatel a majetku."),
  p("Dobrou zprávou je, že v obci Krhanice a v obci Prosečnici nakonec nedošlo k žádným mimořádným událostem v souvislosti s vydatnými dešti a také silným větrem."),
  p("Bohužel na řadě míst v republice, a to zejména na severní Moravě, byly povodně tragické. Stejně jako při tornádu v roce 2021 na jižní Moravě, kdy naše obec finančně přispěla některým nejvíce postiženým obcím, budeme i v případě těchto povodní 2024 postupovat stejně, tj. poskytneme finanční dary některým nejvíce postiženým obcím."),
  h5("Návrhy"),
  p("Starosta: je mnoho zasažených obcí povodněmi, např. Mikulovice, Bohdíkov, Žulová a Brantice. Další obce: Česká Ves, Jeseník, Písečná, Lipová-lázně, Velké Albrechtice, Malé Hoštice, Nová Ves,… a třeba i Plav v jižních Čechách."),
  p("Návrh vybrat 4 obce a dát finanční dar 20 tisíc Kč/1 obec, nejlépe přes transparentní účty obcí."),
  p("obec Bohdíkov, IČO: 00302376, se sídlem Bohdíkov 163, 789 64 Bohdíkov"),
  p("město Žulová, IČO: 00303682, se sídlem Hlavní 36, 790 65 Žulová"),
  p("obec Brantice, IČO: 00295884, se sídlem Brantice 121, 793 93 Brantice"),
  p("město Vidnava, IČO: 00303585, se sídlem Mírové náměstí 80, 790 55 Vidnava"),
  p("Předseda finančního výboru seznámil s rozpočtovým opatřením č. 9/2024."),
  h5("Rozprava"),
  p("L.Maršíková: Dotaz na částku 190 tisíc na zpevněnou plochu na kontejner. Z jakého bude materiálu? Starosta: Stavební komise navrhla asfalt."),
  p("L.Maršíková: Jakou plochu jste navrhoval Vy? Starosta: Zatravňovací dlaždice."),
  p("I.Dvořák: Navrhoval by jiné místo na umístění – v areálu školy od hlavní silnice. Starosta: Připomněl historii, kdy všichni (kauza kontejnerů na návsi U lípy) s umístěním kontejnerů u víceúčelového hřiště souhlasili."),
  p("J.Bydžovská: Jak velké bude místo pod kontejnerem? Starosta: 3 x 14 metrů."),
  p("Starosta: Místo pod kontejner na bioodpad se bude využívat 2x ročně. Mimo toto období bude sloužit pro parkování, neboť např. u mateřské školy se díky chodníku prostor k parkování zmenšil. Počítáme i s AlzaBoxem, takže ubyde další parkovací místo."),
  p("Proběhla diskuse se závěrem, že toto nové místo má smysl a bude přínosné. Kontejnery na bioodpad zůstanou na stávajícím místě."),
  p("L.Maršíková: Dotaz na částku 25 tisíc na péči o vzhled obcí. Co se bude sázet? Starosta: Jde pouze o účetní operaci."),
  h5("Návrh"),
  p("ZO schvaluje poskytnutí finančních prostředků v rámci ostatní správy v oblasti hospodářských opatření pro krizové stavy takto: 20.000,- Kč jednotlivě pro obec Bohdíkov, IČO: 00302376, se sídlem Bohdíkov 163, 789 64 Bohdíkov; pro město Žulová, IČO: 00303682, se sídlem Hlavní 36, 790 65 Žulová; pro obec Brantice, IČO: 00295884, se sídlem Brantice 121, 793 93 Brantice a pro město Vidnava, IČO: 00303585, se sídlem Mírové náměstí 80, 790 55 Vidnava."),
  vote(V9),
  h5("Návrh"),
  p("ZO schvaluje rozpočtové opatření obce Krhanice č. 9/2024."),
  vote(V9),

  h3("9) Různé"),

  h4("A. INFORMACE STAROSTY OBCE"),
  p("Co se v roce 2024 již podařilo zrealizovat a co nás čeká dále?"),
  p("Letošní rok v naší obci bychom mohli nazvat „rokem chodníků“. Podařilo se nám zrealizovat chodník k viaduktu po odbočení na Vlčím důle, dále chodník kolem okružní křižovatky až ke schodům k Hodkovu včetně tří přechodů, tzv. propojovací chodník mezi chodníkem k viaduktu a chodníkem kolem okružní křižovatky. Zahájili jsme budování chodníku pod strání, který bude základem pro přístup k vlakové zastávce. Na tento chodník bude navazovat upravený přístup z zadní části pozemku vlakového nádraží. Tento chodník a přístup bude včetně osvětlení."),
  p("Jaký je současný stav ohledně čistírny vod Krhanice a splaškových řadů v obci Krhanice v návaznosti na to, co se již udělalo:"),
  p("Pro nové umístění čistírny odpadních vod jsme získali bezúplatně pozemek od pozemkového fondu pod hlavní silnicí směrem na Prosečnici u elektrárny."),
  p("Na základě inženýrsko-geologických průzkumů se stanovilo nové umístění ČOV."),
  p("Byla zhotovena projektová dokumentace k novému umístění ČOV a bylo získáno územní rozhodnutí na toto umístění."),
  p("Dále byla zhotovena elektrická přípojka pro ČOV Krhanice. Do nového územního plánu obce byl zapracován koridor pro splaškové řady."),
  p("Na začátku letošního roku jsem jednal s Ing. Matuškou ohledně čistírny vod Krhanice a splaškových řadů v obci Krhanice. Výsledkem jednání je vytvoření Zprávy, kterou Vám přečtu."),
  p("Jaký je cílový stav?"),
  p("Získání územního rozhodnutí a stavebního povolení (společné povolení) pro ČOV Krhanice a splaškové řady Krhanice."),
  p("Zhotovení prováděcí dokumentace, ze které bude stanovena celková cena zhotovení ČOV a splaškových řadů."),
  p("Informování občanů o nákladech na ČOV a splaškové řady, odhad nákladů za 1 m³ splaškových vod, a odhad všech souvisejících nákladů ze strany občanů."),
  p("Časově – 2. polovina roku 2025 při získání všech potřebných pozemků a získání souhlasu všech majitelů dotčených pozemků s uložením splaškové kanalizace."),
  h5("Rizika"),
  ...ul([
    "Rizikem může být neodkoupení potřebných pozemků a nezískání souhlasu všech majitelů dotčených pozemků s uložením splaškové kanalizace.",
    "Rizikem může být nemožnost umístění splaškového řadu s ohledem na již položené inženýrské sítě v úzkých místních komunikacích.",
    "Rizikem může být nedostupnost finančních prostředků – nezískání případného úvěru, půjčky, návratné finanční výpomoci, …",
    "Je třeba počítat, že v případě realizace bude mít obec omezené finanční prostředky na další rozvoj obce. Bude potřeba vždy zajistit provozní chod: škola, školka, veřejné osvětlení, odpadové hospodářství, zastupitelstvo a obecní úřad, zeleň, komunální služby, provoz kanalizace, požární ochranu, ……",
  ]),
  p("V letošním roce budeme vyhodnocovat současný Strategický plán obce a bude připravován nový strategický plán. Občané budou opět osloveni formou dotazníku. Předpokládám, že ČOV pro občany Krhanic bude priorita."),
  h5("Rozprava"),
  p("L.Maršíková: Kdo bude zpracovávat strategický plán? Starosta: Poptáme občany. Vyhodnotíme stávající strategický plán. Vše aktualizujeme."),
  p("L.Maršíková: Jakým způsobem poptáme občany? Starosta: Dotazník, nebo anketa."),
  p("L.Maršíková: Středočeský kraj vypisuje dotaci na vypracování strategického plánu. Nebylo by lepší využít odborníky? Starosta: Myslím si, že by to nebylo pro nás ….. Za mě jsem pro tabulku s projekty, financováním, předpokládanou dobou realizace, …"),
  p("I.Dvořák: Navrhl přerušit práce na centrální čističce pro obec, zaměřit se a podpořit lokální čistírny, vybudovat čistírnu pro mateřskou a základní školu. Mám připomínku k omezení v územním plánu pro domácí čistírny odpadních vod – 1000 m2 nezastavěných ploch. Starosta: S firmou Projekty Vodam budeme řešit nákladovost vybudování ČOV a splaškových řadů. Provedeme odhad nákladů za 1 m3 splaškových vod vypouštěných na ČOV, … Občané budou s výsledky seznámeni. Podmínku územního plánu zrušíme. Povolení má jiný charakter než v minulosti. Už to bude o sousedech, zda udělí souhlas. A také o hydrogeologickém posudku."),
  p("L.Maršíková: Požadavek: Firmě, která bude zpracovávat analýzu nákladů stanovit termín na dodání této zprávy. Starosta: Dáme jí 2 měsíce."),

  h4("B. ŽABA – DODATEK KE SMLOUVĚ"),
  p("Starosta seznámil se stavbou propojovacího chodníku pod železničním viaduktem směrem k odbočení na Vlčí důl. Realizace byla provedena ze strany pana Žaby. Vícepráce nebyly, méněpráce ano."),
  p("Smlouva o dílo 1 381 516,02 Kč"),
  p("Fakturováno 1 215 648,01 Kč"),
  p("Rozdíl 165 868,01 Kč"),
  p("Úspora:"),
  ...ul([
    "Asfaltování – 61 tisíc Kč",
    "Trubní vedení a kanalizační vpusť – 64 tisíc Kč",
    "Čištění propust a čištění vozovek – 15 tisíc Kč",
    "Dopravní značení – 23 tisíc Kč",
    "Projednání DIO – 3 tisíce Kč",
  ]),
  p("Uzavřeme Dodatek č.1 k této Smlouvě o dílo."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Dodatku č. 1 ke smlouvě o dílo č. SoD/02/2024 ze dne 24.7.2024 na akci „Krhanice – chodník podél silnice III/1066 – 2.etapa“ s firmou Jaroslav Žaba, IČO: 86934431, Pecerady 69, 257 41 Týnec nad Sázavou na celkovou částku 1 215 648,01 Kč s DPH."),
  vote(V9),
  h5("Návrh"),
  p("ZO pověřuje starostu obce uzavřením a podpisem Dodatku č. 1 ke smlouvě o dílo č. SoD/03/2024 ze dne 2.4.2024 na akci „Krhanice – chodník podél silnice III/1066 – 2.etapa“ s firmou Jaroslav Žaba, IČO 86934431, Pecerady 69, 257 41 Týnec nad Sázavou."),
  vote(V9),

  h4("C. VEŘEJNOPRÁVNÍ SMLOUVA S MĚSTEM JÍLOVÉ U PRAHY – VÝKON OBECNÍ POLICIE"),
  p("Informace starosty: Jedná se o uzavření veřejnoprávní smlouvy s městem Jílové u Prahy na výkon obecní/městské policie. Smlouvu po uzavření musí schválit Středočeský kraj."),
  p("Městská policie by vykonávala na území obce Krhanice všechny úkoly stanovené zákonem o obecní policii, nebo zvláštními zákony, a to s výjimkou odchytu toulavých, opuštěných a volně se pohybujících se psů a jiných zvířat, toto si obec Krhanice bude i po podpisu této smlouvy realizovat samostatně."),
  p("Městská policie bude na území obce Krhanice vykonávat zejména dozor nad dodržováním právních předpisů v dopravě a dále tuto činnost:"),
  ...ul([
    "přispívat k ochraně a bezpečnosti osob a majetku,",
    "dohlížet na dodržování pravidel občanského soužití,",
    "dohlížet na dodržování obecně závazných vyhlášek a nařízení obce Krhanice,",
    "podílet se v rozsahu stanoveném tímto nebo zvláštním zákonem na dohledu na bezpečnost a plynulost provozu na pozemních komunikacích,",
    "podílet se na dodržování právních předpisů o ochraně veřejného pořádku a v rozsahu svých povinností a oprávnění stanovených tímto nebo zvláštním zákonem činí opatření k jeho obnovení,",
    "podílet se na prevenci kriminality v obci Krhanice,",
    "provádět dohled nad dodržováním čistoty na veřejných prostranstvích v obci Krhanice,",
    "odhalovat přestupky a jiné správní delikty, jejichž projednávání je v působnosti obce Krhanice,",
    "poskytovat za účelem zpracování statistických údajů Ministerstvu vnitra České republiky na požádání údaje o obecní policii.",
  ]),
  p("Příjem z pokut uložených městskou policií na území obce Krhanice je vždy příjmem do rozpočtu města Jílové u Prahy."),
  p("Jaký rozsah hodin měsíčně pro výkon policie formou pěších hlídek a autohlídek stanovit? Návrh : 6 hodin."),
  p("V tuto chvíli jsou:"),
  p("Návrh nákladů spojených s plněním úkolů městské policie na území obce Krhanice je v tuto chvíli stanovený takto: paušální částka v celkové výši 1 300 Kč/hodinu vykonávání úkolů městské policie na území obce Krhanice,"),
  p("Město Jílové u Prahy může každoročně upravovat výši paušálních nákladů a částky za náklady za mimořádnou činnost v souladu s mírou inflace vyjádřenou přírůstkem průměrného ročního indexu spotřebitelských cen za uplynulý kalendářní rok, publikované Českým statistickým úřadem, a to po zveřejnění výše uvedeného indexu ČSÚ. Oznámení bude mít formu písemného oznámení odeslané obci Krhanice."),
  p("Mimořádná činnost, nad rámec smluvních hodin : částka 650 Kč za každou započatou hodinu činnosti každého jednotlivého zasahujícího strážníka městské policie."),
  h5("Rozprava"),
  p("P.Bydžovský: Nebylo by lepší na místo spolupráce s městskou policií nainstalovat na kritická místa radary jako u silnice k viaduktu? Stálo by to méně peněz a možná by to mělo lepší efekt."),
  p("A.Kozel: V podkladech četl, že by se městská policie dala využít i jinak – špatné parkování, rušení nočního klidu, …"),
  p("Starosta: Dnes jsem vás seznámil s možností spolupráce s městskou policií. Budeme to řešit na pracovním sezení zastupitelů a rozhodneme na zastupitelstvu v prosinci."),

  h4("D. PLÁN INVENTUR NA ROK 2024"),
  p("Informace starosty: Standardním způsobem provedeme inventarizaci. Schválíme Plán inventur na rok 2024 včetně přílohy č. 1 – Seznamu inventurních soupisů s konkrétním postupem pro provedení inventarizace majetku a závazků obce. Jsou zde uvedeny konkrétní osoby, termíny a úkoly. Pro rok 2024 se zřizuje jedna inventarizační komise pro střediska – Obecní úřad Krhanice, Knihovna, Hasičská zbrojnice ve složení: Aleš Papoušek, Jana Cachová, Lenka Termerová, Jaroslav Mixa a Petr Dub. Stav majetku a závazků bude zjišťován k datu 31. 12. 2024. Inventurní soupisy bude inventarizační komise vyhotovovat průběžně v měsíci lednu 2025. Inventarizační komise vyhotoví Inventarizační zprávu nejpozději do 6. 2. 2025."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Plán inventur 2024."),
  vote(V9),

  h4("E. KOMISE PRO SESTAVENÍ ROZPOČTU PRO ROK 2025"),
  p("Informace starosty: V souladu se směrnicí č. 2/2017 Metodika sestavení rozpočtu obce Krhanice bude zřízena Komise pro sestavení rozpočtu pro rok 2025 v počtu 6 členů. Komise pro sestavení rozpočtu zpracovává jednotlivé požadavky žadatelů, jedná s některými žadateli a dotazuje se na předkládané materiály. Vyhotovuje písemnou zprávu pro jednání zastupitelstva o rozpočtu pro rok 2025. Sezení komise bude naplánováno na měsíc listopad 2024."),
  p("Z hlediska Rozpočtu pro rok 2025 bude dále opět otevřen, ve formě Ankety, „Zásobník námětů občanů“ – kde budou moci občané zasílat své náměty do rozpočtu pro rok 2025."),
  p("Sešly se nám tyto návrhy členů Komise pro sestavení rozpočtu pro rok 2025: Starosta jako předseda Komise navrhl tyto členy: Aleš Papoušek, Jana Laboutková, Petr Dub, Alena Kratochvílová, Markéta Vaňková a Jana Cachová."),
  p("Zastupitelka Lucie Maršíková navrhla do Komise pro sestavení rozpočtu Petru Dvořákovou."),
  p("Postup: Budeme schvalovat nejprve návrh předsedy Komise pro sestavení rozpočtu. Vybral jsem si konkrétní lidi."),
  h5("Rozprava"),
  p("L.Maršíková: Navrhla do komise novou členku paní Dvořákovou, která by byla podle ní přínosem. Nechápu, proč nechce starosta měnit složení nebo navýšit počet členů."),
  p("Proběhla diskuse o složení komise, počtu členů komise, o volbách členů komise ze strany jejího předsedy, možnosti změny podle návrhu L. Maršíkové, …"),
  h5("Návrh"),
  p("ZO schvaluje složení Komise pro sestavení rozpočtu pro rok 2025: Aleš Papoušek, Jana Laboutková, Petr Dub, Alena Kratochvílová, Markéta Vaňková a Jana Cachová."),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 2 – Maršíková, Bc. Dušová )"),

  h4("F. ZÍSKÁNÍ DOTACE OD GŘ HZS STŘEDOČESKÉHO KRAJE NA NOVÝ DOPRAVNÍ AUTOMOBIL JSDHO KRHANICE"),
  p("Informace starosty: Získali jsme dotaci ve výši 450 tisíc Kč na nový dopravní automobil od Ministerstva vnitra. Dotace bude poskytnuta v příštím roce. Starosta vstoupí v jednání s vedením Zásahové jednotky hasičů na optimalizaci aut v návaznosti na získání nového dopravního automobilu pro zásahovou jednotku hasičů."),
  h5("Návrh"),
  p("ZO bere na vědomí získání dotace ve výši 450 tisíc Kč na nový dopravní automobil od Ministerstva vnitra ČR pro JSDHO Krhanice."),

  h4("G. TERMÍNY PRACÍ A UZAVÍRKY KOMUNIKACE II/107"),
  p("Předběžně: v termínu od 7.10.2024 do 25.11.2024 bude uzavírka komunikace II/107. Investor je KSÚS Středočeského kraje a zhotovitel Skanska a.s., Praha 8. Bude zveřejněno na webu obce. Obec byla informována pouze e-mailem. Na jednání na MěÚ Týnec nad Sázavou jsme nebyli pozváni. Napsal jsem nesouhlas a požadoval jsem zajištění průjezdnosti na Prahu. Odpověď:"),
  p("Dobrý den, dotčené orgány státní správy se k předloženému vyjádřili kladně. Viz příloha. Dopravní značení v Krhanicích je umístěno na komunikacích II/106 a III/1066, které jsou ve správě KSUSKy. Stavba zahájí práce od Kamenice, v tu dobu bude křižovatka Čakovice x Krhanice průjezdná. Poté se stavba přesune za křižovatku směr Týnec nad Sázavou, provoz bude řízen SSZ a tím pádem bude křižovatka Čakovice x Krhanice uzavřena. Jakmile stavba bude vědět, že se přesouvá za křižovatku směr Týnec nad Sázavou, jsme schopni vám nahlásit termín plné uzavírky křižovatky Čakovice x Krhanice."),
  p("Proběhla diskuse o uzavírce a špatné koordinaci v návaznosti na automobilovou dopravu z Krhanic."),

  h3("10) Diskuse"),
  ...ul([
    "T.Strnad: Dotaz ke škole. Vrací obci dost velké peníze. Proč nemůže přispívat na učebnice dětí, nebo alespoň sociálně slabším? Starosta: Škola má závazné ukazatele. Obec přispívá na učební pomůcky, ale ne na pracovní sešity. Je třeba případně přesvědčit paní učitelku, aby změnila způsob výuky a nepoužívala pracovní sešity, které platí rodiče.",
    "T.Strnad: Na třídní schůzce byl ve třídě špatný vzduch. Domnívá se, že vzduchotechnika nefunguje, jak by měla. Starosta: Projednám to s ředitelkou školy. Školník byl proškolen, je to v jeho kompetenci.",
  ]),

  h3("11) Závěr"),
  p("Zastupitelstvo obce bylo ukončeno v 20:36 hod."),

  p("Datum pořízení zápisu: 30.9.2024"),
  p("Ověřovatelé zápisu a starosta obce, podepsáno v listinné podobě."),
  h4("Přílohy"),
  ...nl(["Svolání zastupitelstva obce", "Prezenční listina zastupitelů", "Prezenční listina občanů"]),
];

async function run() {
  const r = await publishZapis({
    cislo: "4",
    rok: "2024",
    isoDate: "2024-09-24",
    dateLabel: "24. 9. 2024",
    fullDateDot: "24.9.2024",
    pdfPath: "scripts/zapisy-pdf/zapis-2024-4.pdf",
    transcript,
  });
  console.log("OK", r.docId, "blocks", r.blocks);
}
run().catch((e) => { console.error(e); process.exit(1); });
