/* eslint-disable no-console */
// One-off: faithful visual transcript of Zápis č. 1/2021 (17.3.2021),
// transcribed page-by-page from the official PDF. Structure per AGENT-SPEC.md
// and the approved golden example scripts/build-zapis-2026-1.ts.
import { h3, h4, h5, p, vote, nl, ul, publishZapis, type Block } from "../zapis-lib";

const V8 = "PRO ( 8 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )";

const transcript: Block[] = [
  h4("Přítomni"),
  p("Aleš Papoušek, Jaroslav Mixa, Bohuslav Kadeřábek, Tomáš Kratochvíl, Václav Zíta, Petr Dub, Martin Jiřička, Edita Jarošová"),
  h4("Omluveni"),
  p("Jana Laboutková"),

  h3("1) Zahájení, přivítání přítomných, konstatování přítomnosti"),
  p("Starosta konstatoval, že zasedání bylo svoláno dne 9.3.2021 bylo vyvěšeno na úřední desce obecního úřadu, tj. tedy nejméně 7 dní před zasedáním. Bylo tedy svoláno řádně a včas v souladu se zákonem o obcích v platném znění. Starosta konstatoval, že podle prezenční listiny je přítomno 8 členů zastupitelstva, tedy nadpoloviční většina členů zastupitelstva. K předchozímu zápisu nebyly vzneseny námitky."),
  h5("Určení zapisovatele"),
  p("Zápisem zasedání zastupitelstva obce byla pověřena Ing. Alena Kratochvílová."),
  p("Starosta přečetl program."),
  ...nl([
    "Zahájení",
    "Volba návrhové komise a ověřovatelů zápisu",
    "Projekty a akce na rok 2021",
    "Rozpočtová opatření",
    "Koupě, prodej, pronájem",
    "Různé",
    "Diskuse",
    "Usnesení a závěr",
  ]),
  h5("Návrh"),
  p("ZO schvaluje program zasedání zastupitelstva obce."),
  vote(V8),

  h3("2) Volba návrhové komise a ověřovatelů zápisu"),
  p("Starosta přednesl návrh návrhové komise a ověřovatelů zápisu."),
  h5("Návrh"),
  p("ZO schvaluje návrhovou komisi ve složení Jaroslav Mixa, Petr Dub"),
  h5("Návrh"),
  p("ZO schvaluje ověřovatele zápisu ve složení Tomáš Kratochvíl, Martin Jiřička"),
  vote(V8),

  h3("3) Projekty a akce na rok 2021"),
  p("V letošním roce proběhla již dvě pracovní jednání zastupitelstva, jejichž výsledkem je výběr projektů a akcí s charakterem rekonstrukce, dodělání rozpracovaných akcí a akce a projekty menšího rozsahu, které se provádí každý rok, a to s ohledem na aktuální situaci a na finanční situaci obce. Jediný velký projekt a priorita obce je rekonstrukce oken, rekonstrukce topení, výměna kotlů, zateplení fasády a zhotovení vzduchotechniky budovy základní školy. Nyní probíhá výběrové řízení na zhotovitele. Předpokládaná rozpočet této stavební akce je 19 miliónů Kč. Na akci budeme čerpat dotaci, půjčku SFŽP a dále využijeme finanční prostředky minulých let, které pro tuto akci vytvoříme. Vše se bude odvíjet od konečné ceny stavebních prací z výběrového řízení."),
  p("Pro rok 2021 byly vybrány následující akce a projekty:"),
  ...ul([
    "Silnice: Vyasfaltování nájezdu z vedlejší komunikace na hlavní silnici II/106 vedle autobusové zastávky v Prosečnici",
    "Ostatní záležitosti pozemních komunikací: Zhotovení rozpočtu chodníku a dešťové kanalizace směrem k viaduktu",
    "Provoz veřejné silniční dopravy: Rekonstrukce podesty autobusové zastávky v Prosečnici směrem na Krhanice",
    "Pitná voda: Průtlak vodovodního řadu pod silnicí II/106 u zastávky v Prosečnici",
    "Pitná voda: Zhotovení vodovodní přípojky s větší dimenzí do základní školy",
    "Pitná voda: FOND : Přesun opravy a udržování ve Fondu na Posázavák",
    "Odvádění a čistění odpadních vod: Obstarání souhlasů majitelů pozemků na změnu umístění řadů splaškové kanalizace v obci Krhanice pro územní rozhodnutí",
    "Úpravy drobných vodních toků: Vyčištění koryta Palečnického potoka pod nádrží u hasičárny",
    "Základní školy: Rekonstrukce zateplení, topení a zhotovení vzduchotechniky budovy základní školy",
    "Pořízení, zachování, obnova hodnot místního kulturního povědomí: Zhotovení kamene k položení květin a následný přesun pamětního kamene 17.listopadu mimo zeleň",
    "Sportovní zařízení v majetku obce: Vytvoření zpevněné plochy navazující na stávající zpevněnou plochu před budovou v areálu TJ Sokol Krhanice",
    "Využití volného času dětí a mládeže: Dokončení dětského hřiště v Prosečnici",
    "Využití volného času dětí a mládeže: Dokončení zázemí víceúčelového hřiště u základní školy",
    "Využití volného času dětí a mládeže: Doplnění areálu zázemí víceúčelového hřiště",
    "Využití volného času dětí a mládeže: Zhotovení přístřešku a dřevěných zábran na Indiánskou stráň mateřské školy",
    "Nebytové hospodářství: Demolice prostředních skladů u Hodkova",
    "Nebytové hospodářství: Vytvoření zpevněné plochy pro umístění obecních garáží u Hodkova",
    "Veřejné osvětlení: Výměna LED osvětlení veřejného osvětlení",
    "Pohřebnictví: Vytvoření zpevněné plochy ke kontejneru na směsný odpad na hřbitově",
    "Pohřebnictví: Terénní úpravy a vytvoření nové uličky na hřbitově",
    "Komunální služby a územní rozvoj: Rekonstrukce schodů k Hodkovu v Krhanicích",
    "Komunální služby a územní rozvoj: Zhotovení zábradlí u pěšiny souběžně se silnicí od bývalého obchodu v Prosečnici směrem na Kamenný Přívoz",
    "Komunální služby a územní rozvoj: Terénní úpravy veřejného prostranství v Prosečnici za autobusovou zastávkou + vysazení stromu",
    "Komunální služby a územní rozvoj: Terénní úpravy vedle chatové oblasti Sádek",
    "Komunální služby a územní rozvoj: Zpevnění příjezdové plochy u Hodkova v Krhanicích",
    "Komunální služby a územní rozvoj: Zhotovení rozpočtu k rekonstrukci návsi u obchodu a vybudování chodníků",
    "Komunální služby a územní rozvoj: Nákup strategických pozemků pro obec Krhanice",
    "Využívání a zneškodňování komunálních odpadů: Zhotovení plotu kolem kontejnerů u Hodkova v Krhanicích",
    "Využívání a zneškodňování komunálních odpadů: Zhotovení panelové podesty pro velkoobjemový kontejner za brodem pod Gabčíkovem v Krhanicích",
    "Využívání a zneškodňování komunálních odpadů: Vyasfaltování podesty pod kontejnery v Kozině u brodu v Krhanicích",
    "Péče o vzhled obcí a veřejnou zeleň: Osazení keři zelené plochy u komunikace u mateřské školy a u základní školy",
    "Péče o vzhled obcí a veřejnou zeleň: Osazení ovocných stromů na školní zahradu základní školy",
    "Péče o vzhled obcí a veřejnou zeleň: Odstranění náletových keřů vedle chatové oblasti Sádek",
    "Péče o vzhled obcí a veřejnou zeleň: Výsadba zeleně na Indiánskou stráň mateřské školy",
    "PO - dobrovolná část: Nákup tabletu, software a datové karty do auta VW Transporter pro zásahovou jednotku hasičů (JSDHO Krhanice)",
  ]),
  h5("Rozprava"),
  p("L.Maršíková: Dotaz na oplocení hřiště u školy, jaká část bude oplocena? Starosta: Záměrem je přístup z jednoho místa do celého areálu víceúčelového hřiště."),
  p("J.Bydžovská: V kterých místech by měla být nová ulička? Starosta: Ulička by měla být k řadě nově vznikajících urnových hrobů."),
  p("J.Bydžovská: Poděkovala za vyklestění v okolí hřbitovní zdi."),

  h3("4) Rozpočtová opatření"),
  h4("Rozpočtové opatření č.1/2021"),
  p("Informace starosty: Obdrželi jsme průtokovou dotaci pro základní školu – Zjednodušené projekty Šablony – v částce 217.702,- Kč. Zahrnuto do příjmů i do výdajů."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí a schvaluje rozpočtové opatření č. 1/2021."),
  vote(V8),
  h4("Rozpočtové opatření č. 2/2021"),
  p("Martin Jiřička přečetl dopis ředitelky mateřské školy s žádostí o navýšení provozního příspěvku o 30 tisíc Kč na nákup počítače s operačním systémem Windows 10 Pro a Office 2019."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje navýšení provozního příspěvku Mateřské škole Krhanice o 30.000,- Kč na nákup počítače s operačním systémem Windows 10 Pro a Office 2019."),
  vote(V8),
  p("Informace předsedy finančního výboru Bohuslava Kadeřábka k rozpočtovému opatření č. 2/2021."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje rozpočtové opatření č. 2/2021."),
  vote(V8),

  h3("5) Koupě, prodej, pronájem"),
  ...ul([
    "uzavřít Smlouvu o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby č. IP-12-6019047/VB/2, Krhanice-kNN-č.parc. 277/2 na pozemcích parc. č. 326/2 a 1979/3 k.ú. Krhanice s ČEZ Distribuce, a.s., IČ 24729035, DIČ CZ24729035, se sídlem Děčín IV-Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 6.000,- Kč na umístění kabelového vedení NN",
  ]),
  p("Informace starosty: Jedná se o pozemek nedaleko železničního přejezdu u komunikace k lomu. Bude k němu vybudována elektrická přípojka."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby č. IP-12-6019047/VB/2, Krhanice-kNN-č.parc. 277/2 na pozemcích parc. č. 326/2 a 1979/3 k.ú. Krhanice s ČEZ Distribuce, a.s., IČ 24729035, DIČ CZ24729035, se sídlem Děčín IV-Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 6.000,- Kč na umístění kabelového vedení NN."),
  vote(V8),
  ...ul([
    "prodat pozemek parc.č. 312/1 k.ú. Krhanice o výměře 84 m² za cenu 500 Kč/1 m²",
  ]),
  p("Informace starosty: Jedná se o žádost Jiřího Švehly – narovnání historického stavu, kdy plot a část stavby garáže je na obecním pozemku. Vše bylo vybudováno v šedesátých letech 20.století."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje prodej pozemku parc.č. 312/1 k.ú. Krhanice o výměře 84 m2 za cenu 500 Kč/1 m² JUDr. Jiřímu Švehlovi, Krhanice 192, 257 42 Krhanice. Náklady na vklad do katastru nemovitostí hradí kupující."),
  vote(V8),
  ...ul([
    "pronajmout část pozemku st. p. 675 k.ú. Krhanice o výměře 17,5 m² k umístění plechové garáže k podnikání za cenu 20 Kč/m²/rok od 1.9.2021 na dobu 10 let",
  ]),
  p("Informace starosty: Jedná se o žádost Jiřího Mlejnka. Žadatel si pro podnikání chce pořídit plechovou garáž a tu umístit na pronajatý pozemek. Doba pronájmu bude 10 let."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronájem části pozemku st. p. 675 k.ú. Krhanice o výměře 17,5 m² k umístění plechové garáže k podnikání za cenu 20 Kč/m²/rok od 1.9.2021 na dobu 10 let Jiřímu Mlejnkovi, Krhanice 215, 257 42 Krhanice."),
  vote(V8),
  ...ul([
    "uzavřít Smlouvu o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby č. IV-12-6027954/VB/016, Krhanice-kNN-p.č.272/11,10,6,5 na pozemcích parc. č. 1981/1, 272/1 k.ú. Krhanice s ČEZ Distribuce, a.s., IČ 24729035, DIČ CZ24729035, se sídlem Děčín IV-Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 26.700,- Kč na umístění kabelového vedení NN",
  ]),
  p("Informace starosty: Jedná se o lokalitu s novými parcelami (8 parcel) u komunikace směrem k lomu. Jde o zasíťování parcel elektrickými přípojkami."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby č. IV-12-6027954/VB/016, Krhanice-kNN-p.č.272/11,10,6,5 na pozemcích parc. č. 1981/1, 272/1 k.ú. Krhanice s ČEZ Distribuce, a.s., IČ 24729035, DIČ CZ24729035, se sídlem Děčín IV-Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 26.700,- Kč na umístění kabelového vedení NN."),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 1 - Kadeřábek )"),
  ...ul([
    "prodat z pozemku parc. č. 1972/1 k.ú. Krhanice oddělenou část 1972/10 o výměře 6 m², která vznikne na základě geometrického plánu č. 926-46/2018 za cenu 500 Kč/1m².",
  ]),
  p("Informace starosty: Jedná se o prodej části pozemku před garáží, kdy obec od majitelů kupuje část pozemku pro chodník směrem k pítku u parčíku s památníkem obětí 1.světové války."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje prodej oddělené části 1972/10 o výměře 6 m² z pozemku parc. č. 1972/1 k.ú. Krhanice, která vznikne na základě geometrického plánu č. 926-46/2018 za cenu 500 Kč/1 m² Jitce a Petru Babánkovi, Krhanice č.p. 65, 257 42 Krhanice. Náklady na vklad do katastru nemovitostí hradí kupující."),
  vote(V8),
  ...ul([
    "HODKOV – PRODEJ NEBYTOVÝCH PROSTOR A POZEMKU",
  ]),
  p("dle schváleného záměru prodat stávajícím dlouhodobým nájemcům nebytových prostor u Hodkova poměrné části stavebního pozemku st.p. 674 k.ú. Krhanice včetně souvisejících nebytových prostor na pozemku st.p. 674 k.ú. Krhanice: poměry 16,67% za cenu 17206 Kč (pozemek 7150 Kč, stavba 10056 Kč) a poměry 16,67% za cenu 14128 Kč (pozemek 7150 Kč, stavba 6978 Kč) poměrné části stavebního pozemku st.p. 676 k.ú. Krhanice včetně souvisejících nebytových prostor na pozemku st.p. 676 k.ú. Krhanice: poměry 24,49% za cenu 9371 Kč (pozemek 5460 Kč, stavba 3911 Kč), 23,76% za cenu 9092 Kč (pozemek 5298 Kč, stavba 3794 Kč), 25,60% za cenu 9796 Kč (pozemek 5708 Kč, stavba 4088 Kč) a 26,15% za cenu 10006 Kč (pozemek 5830 Kč, stavba 4176 Kč) na základě znaleckého posudku. Návrhy na vklad a právní služby si hradí jednotliví kupující,"),
  p("Informace starosty: Jedná se o realizaci prodeje skladů a pozemků pod nimi dle schváleného záměru stávajícím nájemcům. Sklady, které nebudou prodány zůstanou v majetku obce a nebudou pronajímány."),
  h5("poměrné části stavebního pozemku st.p. 674 k.ú. Krhanice včetně souvisejících nebytových prostor na pozemku st.p. 674 k.ú. Krhanice:"),
  p("poměry :"),
  ...ul([
    "16,67% za cenu 17206 Kč (pozemek 7150 Kč, stavba 10056 Kč) – Jaroslav Mixa, Krhanice 72, 257 42 Krhanice",
    "16,67% za cenu 17206 Kč (pozemek 7150 Kč, stavba 10056 Kč) – Jaroslav Mixa, Krhanice 72, 257 42 Krhanice",
  ]),
  p("Na těchto skladech je nutná celková oprava střechy. Realizaci opravy provede kupující."),
  ...ul([
    "16,67% za cenu 14128 Kč (pozemek 7150 Kč, stavba 6978 Kč) – Vladimír Smolík, Komenského 506, 257 41 Týnec nad Sázavou",
    "16,67% za cenu 14128 Kč (pozemek 7150 Kč, stavba 6978 Kč) – David Modřanský, Krhanice 72, 257 42 Krhanice",
  ]),
  h5("poměrné části stavebního pozemku st.p. 676 k.ú. Krhanice včetně souvisejících nebytových prostor na pozemku st.p. 676 k.ú. Krhanice:"),
  p("poměry:"),
  ...ul([
    "24,49% za cenu 9371 Kč (pozemek 5460 Kč, stavba 3911 Kč) – František Brabec, Krhanice 72, 257 42 Krhanice",
    "23,76% za cenu 9092 Kč (pozemek 5298 Kč, stavba 3794 Kč) – Jozef Steinhübel, Krhanice 72, 257 42 Krhanice",
    "25,60% za cenu 9796 Kč (pozemek 5708 Kč, stavba 4088 Kč) – David Richtr, Krhanice 71, 257 42 Krhanice",
    "26,15% za cenu 10006 Kč (pozemek 5830 Kč, stavba 4176 Kč) – Zdeňka Klabíková, Krhanice 71, 257 42 Krhanice",
  ]),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje prodej poměrné části stavebního pozemku st.p. 674 k.ú. Krhanice včetně souvisejících nebytových prostor na pozemku st.p. 674 k.ú. Krhanice:"),
  ...ul([
    "poměr 16,67% za cenu 17206 Kč (pozemek 7150 Kč, stavba 10056 Kč) – Jaroslavu Mixovi, Krhanice 72, 257 42 Krhanice",
    "poměr 16,67% za cenu 17206 Kč (pozemek 7150 Kč, stavba 10056 Kč) – Jaroslavu Mixovi, Krhanice 72, 257 42 Krhanice",
    "poměr 16,67% za cenu 14128 Kč (pozemek 7150 Kč, stavba 6978 Kč) – Vladimíru Smolíkovi, Komenského 506, 257 41 Týnec nad Sázavou",
    "poměr 16,67% za cenu 14128 Kč (pozemek 7150 Kč, stavba 6978 Kč) – Davidu Modřanskému, Krhanice 72, 257 42 Krhanice",
  ]),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 1 - Mixa )"),
  h5("Návrh"),
  p("ZO schvaluje prodej poměrné části stavebního pozemku st.p. 676 k.ú. Krhanice včetně souvisejících nebytových prostor na pozemku st.p. 676 k.ú. Krhanice:"),
  ...ul([
    "poměr 24,49% za cenu 9371 Kč (pozemek 5460 Kč, stavba 3911 Kč) – Františku Brabcovi, Krhanice 72, 257 42 Krhanice",
    "poměr 23,76% za cenu 9092 Kč (pozemek 5298 Kč, stavba 3794 Kč) – Jozefu Steinhüblovi, Krhanice 72, 257 42 Krhanice",
    "poměr 25,60% za cenu 9796 Kč (pozemek 5708 Kč, stavba 4088 Kč) – Davidu Richtrovi, Krhanice 71, 257 42 Krhanice",
    "poměr 26,15% za cenu 10006 Kč (pozemek 5830 Kč, stavba 4176 Kč) – Zdeňce Klabíkové, Krhanice 71, 257 42 Krhanice",
  ]),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 1 - Papoušek )"),
  ...ul([
    "koupit pozemek parc.č. 148/6 k.ú. Krhanice o výměře 660 m² za cenu 55 Kč/1m².",
  ]),
  p("Informace starosty: Jedná se o nákup pozemku, na kterém má částečně obec Krhanice panely pro kontejnery na bioodpad. Ty ještě zasahují do sousedního pozemku parc.č. 148/32 k.ú. Krhanice. Obec chce vykoupit ještě pozemek parc.č 148/45. Na sousedních pozemcích 148/6 a 148/32 k.ú. Krhanice chce obec vysázet stromy a keře, popř. umístit lavičku. V současnosti jsou to neudržované pozemky."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje koupi pozemku parc.č. 148/6 k.ú. Krhanice o výměře 660 m² za cenu 55 Kč//1 m² od Ing. Bohuslava Kadeřábka a Jana Kadeřábka, Krhanice č.p. 1, 257 42 Krhanice. Náklady na vklad do katastru nemovitostí hradí kupující."),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 1 - Kadeřábek )"),
  ...ul([
    "záměr koupit část pozemku parc.č. 148/32 k.ú. Krhanice o výměře cca 260 m² za cenu 55 Kč/1m².",
  ]),
  p("Informace starosty: Jedná se o nákup části pozemku, do které zasahují panely pro kontejnery na bioodpad. Proto část pozemku o pozemek parc.č. 148/6 k.ú. Krhanice jsou pro obec tedy důležité i z hlediska budoucnosti např. pro rozšíření svozu tříděného odpadu."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje záměr koupit část pozemku parc.č. 148/32 k.ú. Krhanice o výměře cca 260 m² za cenu 55 Kč/1 m² od Ing. Bohuslava Kadeřábka a Jana Kadeřábka, Krhanice č.p. 1, 257 42 Krhanice. Náklady na zhotovení geometrického plánu na dělení a náklady na vklad do katastru nemovitostí hradí kupující."),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 1 - Kadeřábek )"),
  ...ul([
    "koupit pozemek parc.č. 148/45 k.ú. Krhanice o výměře 295 m² za cenu 55 Kč/1m².",
  ]),
  p("Informace starosty: Jedná se o nákup pozemku v lokalitě na Rafandě, kde má obec záměr odkoupit pozemek parc.č. 148/6 k.ú. Krhanice. Tento pozemek na něj navazuje. Oba pozemky chce obec osázet stromy."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje koupi pozemku parc.č. 148/45 k.ú. Krhanice o výměře 295 m² za cenu 55 Kč/1 m² od Jitky Doležalové, Trojdílná 481/15, Košíře, 150 00 Praha 5. Náklady na vklad do katastru nemovitostí hradí kupující."),
  vote(V8),
  ...ul([
    "koupit oddělenou část z pozemku 1435/42 k.ú. Krhanice díl a o výměře 42 m², který vznikne na základě geometrického plánu č. 1036-5065/2020 za cenu 500 Kč/1m².",
  ]),
  p("Informace starosty: Jedná se o nákup části pozemku v lokalitě na Rafandě, kdy stávající cesta vedoucí směrem k lesu zasahuje do pozemku. Po odkoupení povede cesta po obecních pozemcích. Bude nutná úprava povrchu nalevo směrem k lesu."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje koupi oddělené části z pozemku 1435/42 k.ú. Krhanice díl a o výměře 42 m², který vznikne na základě geometrického plánu č. 1036-5065/2020 za cenu 500 Kč/1m² od Petra Semeckého, Kamenný Přívoz 86, 252 82 Kamenný Přívoz. Geometrický plán a náklady na vklad do katastru nemovitostí hradí kupující."),
  vote(V8),
  ...ul([
    "záměr prodat oddělenou část z pozemku 346/2 k.ú. Krhanice o výměře cca 185 m² za cenu 110 Kč/1m² a oddělenou část z pozemku 1881/1/1 k.ú. Krhanice o výměře cca 110 m² za cenu 110 Kč/1m².",
  ]),
  p("Informace starosty: Jedná se o záměr odprodeje části pozemku ve stráni směrem k železnici a vedle železnice nalevo od cesty vedoucí do lomu a část pozemku napravo vedoucího vedle cesty do lomu. Po vypracování geometrického plánu by byl záměr znovu projednán. Geometrický plán bude financovat Dobet spol. s r.o., Nádražní 946, 687 22 Ostrožská Nová Ves. Na pozemcích váznou věcným břemenem inženýrské sítě a kanál z lomu."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje záměr prodat oddělenou část z pozemku 346/2 k.ú. Krhanice o výměře cca 185 m² za cenu 110 Kč/1m² a oddělenou část z pozemku 1881/1 k.ú. Krhanice o výměře cca 110 m² za cenu 110 Kč/1m², a to včetně inženýrských sítí. Po vyhotovení geometrického plánu bude záměr prodeje s konkrétními výměrami znovu projednán."),
  vote(V8),

  h3("6) Různé"),
  h4("Několika větami"),
  p("Zpráva starosty, co proběhlo, … v obci v posledních týdnech."),
  h5("Rozprava"),
  p("L.Maršíková: Ve Svatovicích v obecním lese je navážka, možná skládka. Viděla jsem tam nový odpad. Starosta: Dojedu se tam podívat."),
  h4("Výroční zpráva o poskytování informací za rok 2020"),
  p("Informace starosty: Starosta seznámil s výroční zprávou za rok 2020 o činnosti v oblasti poskytování informací podle zákona č. 106/1999 o svobodném přístupu k informacím, v platném znění, kdy v roce 2020 nebyla podána žádná žádost o poskytnutí informací."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí a schvaluje výroční zprávu za rok 2020 o činnosti v oblasti poskytování informací."),
  vote(V8),
  h4("Dotace na stromy do areálu TJ Sokol Krhanice"),
  p("Informace starosty: Státní fond životního prostředí nám zatím e-mailem potvrdil obdržení dotace na stromy do areálu TJ Sokol Krhanice. Budou vysazeny souběžně s plotem směrem k základní škole. Veřejnost bude zapojena podle aktuálních epidemiologických opatření."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí akceptaci dotace Nové stromy na Sokolce v Krhanicích od Státní fond životního prostředí."),
  h4("Inventarizační zpráva obce Krhanice za rok 2020"),
  p("Předseda inventarizační komise Aleš Papoušek přečetl inventarizační zprávu o proběhlé inventarizaci za rok 2020."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Inventarizační zprávu obce Krhanice za rok 2020."),
  vote(V8),
  h4("Aktivní Krhanice – souhlas s umístěním lavičky"),
  p("Obec Krhanice byla oslovena spolkem Aktivní Krhanice ohledně osazení okolí Krhanic lavičkami. Starosta obce vyhotovil dokument podporující danou aktivitu. Z hlediska pozemků obce se jedná zatím o pozemek parc.č. 312/12 k.ú. Krhanice – mezi náhonem a řekou Sázavou. Přesné umístění na obecním pozemku musí být odsouhlaseno starostou obce. Je to jediný pozemek ve vlastnictví obce."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje předběžný souhlas s umístěním lavičky na pozemku parc.č. 312/12 k.ú. Krhanice projektu „Lavičky do krajiny“ pro Aktivní Krhanice, z.s., IČO: 09017429, Krhanice 35, 257 42 Krhanice."),
  vote(V8),
  h4("Objížďka – uzavírka silnice do Prosečnice"),
  p("Je povolena. Termín: od 1.4.2021 do 30.7.2021. Budou zrekonstruovány 2 mostky přes vodoteče. Autobusová doprava nebude do Prosečnice zajíždět. Proces schvalování ještě není ukončen. Předpokládá se schválení navrženého období. Od 1.4.2021 do cca 31.5.2021 se bude dělat od propustku včetně propustku od teplárny v Prosečnici až k odbočení k lomu. Cca 1.6.2021 do 30.7.2021 je bude pracovat od odbočení k lomu až po křižovatku včetně propustku nad Palečnickým potokem."),
  h4("Žádost o dotaci z fondu sportu a volného času Středočeského kraje na rekonstrukci tréninkového hřiště před základní školou"),
  p("Maximální výše dotace 300 tisíc Kč, u nákupu dlouhodobého hmotného majetku maximálně 100 tisíc Kč. Míra podpory až 70 %. Termín podání 6.4. – 20.4.2021. Podpora investičních projektů zaměřených na modernizaci stávajících tělovýchovných a volnočasových zařízení souvisejících se sportovní a volnočasovou činností dětí a mládeže. Záměrem je vyměnit stávající sloupy na sítě, vyměnit sítě za nové, zrekonstruovat zapínání osvětlení, zhotovit jedno nové světlo a zakoupit dvě nové hliníkové brány se sítí na fotbal, provést úpravy terénu a doseti travním semenem. Přítomni byli seznámeni s předběžným rozpočtem."),
  h5("Rozprava"),
  p("L.Maršíková: Dotaz na výši částky. Zdá se jí příliš vysoká na výměnu sloupů."),
  p("Proběhla všeobecná diskuse o zpevněné ploše a její využívání."),
  h5("Návrh"),
  p("ZO schvaluje podání žádosti o dotaci z Fondu sportu a volného času Středočeského kraje pro rok 2021 na rekonstrukci tréninkového hřiště před základní školou a souhlasí s podmínkami žádosti včetně finanční spoluúčasti."),
  vote(V8),

  h3("7) Diskuse"),
  p("J.Bydžovská: Dotaz na památník u viaduktu, který je zarostlý a není ze silnice téměř vidět. Starosta: Chceme ho přemístit před stávající keře."),
  p("R.Novotný: Nebude lepší počkat, až bude kruhový objezd, aby se s ním nemuselo znovu hýbat. Starosta: Chceme ho posunout pouze o cca metr."),
  p("J.Bečkovský: Dotaz na keltský kámen, který se má přesunout od lomu. Kdo vybíral nové místo. Starosta: Přesun kamene jsem konzultoval s Mílou Padevětem. Vymyslí i informační ceduli."),
  p("J.Bečkovský: Navrhl obci dle jeho názoru výhodnou výměnu svého pozemku za obecní. Starosta ví, o jaké pozemky se jednalo. Starosta: Návrh případné směny se musí projednat se zastupiteli. Uděláme místní šetření."),

  h3("8) Usnesení a závěr"),
  p("a. Návrhová komise přečetla usnesení zastupitelstva obce."),
  vote(V8),
  p("b. Závěr: Zastupitelstvo obce bylo ukončeno v 18:45 hod."),
  h4("Přílohy"),
  ...nl([
    "Svolání zastupitelstva obce",
    "Prezenční listina zastupitelů",
    "Prezenční listina občanů",
  ]),
];

async function run() {
  const r = await publishZapis({
    cislo: "1",
    rok: "2021",
    isoDate: "2021-03-17",
    dateLabel: "17. 3. 2021",
    fullDateDot: "17.3.2021",
    pdfPath: "scripts/zapisy-pdf/zapis-2021-1.pdf",
    transcript,
  });
  console.log("OK", r.docId, "blocks", r.blocks);
}
run().catch((e) => { console.error(e); process.exit(1); });
