/* eslint-disable no-console */
// Faithful visual transcript of Zápis č. 3/2025 (25.6.2025), transcribed
// page-by-page from the official PDF images. Structure per AGENT-SPEC.md and the
// golden example scripts/build-zapis-2026-1.ts.
import { h3, h4, h5, p, vote, nl, ul, publishZapis, type Block } from "../zapis-lib";

const V8 = "PRO ( 8 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )";

const transcript: Block[] = [
  h4("Přítomni"),
  p("Aleš Papoušek, Jaroslav Mixa, Tomáš Kratochvíl, Jana Laboutková, Petr Dub, Martin Jiřička, Lucie Maršíková, Šárka Dušová"),
  h4("Omluveni"),
  p("Aleš Kozel"),

  h3("1) Zahájení, přivítání přítomných, konstatování přítomnosti"),
  p("Starosta konstatoval, že zasedání bylo svoláno dne 17.6.2025, bylo vyvěšeno na úřední desce obecního úřadu, tj. tedy nejméně 7 dní před zasedáním. Bylo tedy svoláno řádně a včas v souladu se zákonem o obcích v platném znění. Starosta konstatoval, že podle prezenční listiny je přítomno 8 členů zastupitelstva, tedy nadpoloviční většina členů zastupitelstva. U předchozího zápisu zastupitelstva obce nebyla shoda na zápisu u jednotlivých ověřovatelů zápisu. Vznikly dva zápisy – T.Kratochvíla a L.Maršíkové. Proto o konečné verzi zápisu musí rozhodnout zastupitelstvo svým usnesením."),
  h5("Rozprava"),
  p("L.Maršíková: Uvedla své důvody, proč chce, aby zápis obsahoval v některých pasážích podrobnější diskusi."),
  p("T.Kratochvíl: Citoval článek VIII jednacího řádu Zastupitelstva obce, který se týká zápisu a toho se při pořizování zápisu držel."),
  p("Š.Dušová: Vyjádřila se k zápisu už na pracovním sezení zastupitelů."),
  p("Místostarosta: Seznámil se s oběma verzemi zápisu a v zápisu paní Maršíkové byly věci, které se týkaly jeho a byly zapsány jinak, než byly řečeny."),
  p("Starosta: Četl jsem zápis paní Maršíkové a v některých věcech neodpovídal skutečnosti, co jsem řekl. Proběhla diskuse bez přijetí závěrů."),
  h5("Návrh"),
  p("ZO schvaluje Zápis č.2/2025 zastupitelstva obce Krhanice ze dne 16.04.2025 (viz příloha)."),
  vote("PRO ( 6 ) – PROTI ( 2 – Dušová, Maršíková ) – ZDRŽEL SE ( 0 )"),
  h5("Určení zapisovatele"),
  p("Zápisem zasedání zastupitelstva obce byla pověřena Ing. Alena Kratochvílová."),

  h3("2) Volba návrhové komise a ověřovatelů zápisu"),
  p("Starosta přednesl návrh návrhové komise a ověřovatelů zápisu."),
  h5("Návrh"),
  p("ZO schvaluje návrhovou komisi ve složení: Jana Laboutková, Jaroslav Mixa."),
  h5("Návrh"),
  p("ZO schvaluje ověřovatele zápisu ve složení Martin Jiřička, Petr Dub."),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 1 - Dušová )"),

  h3("3) Schválení programu"),
  p("Starosta přečetl program."),
  ...nl([
    "Zahájení",
    "Volba návrhové komise a ověřovatelů zápisu",
    "Schválení programu",
    "Závěrečný účet obce Krhanice pro rok 2024 a Závěrečné účty svazku obcí",
    "Zpráva finančního výboru o kontrole hospodaření obce Krhanice za rok 2024; Zpráva o výsledcích veřejnosprávních kontrol hospodaření Mateřské školy Krhanice a Základní školy Krhanice za rok 2024",
    "Schválení účetní závěrky obce Krhanice za rok 2024; Schválení účetní závěrky Mateřské školy Krhanice a Základní školy Krhanice za rok 2024",
    "Rozpočtové opatření",
    "Koupě, prodej, pronájem",
    "Obecně závazné vyhlášky: noční klid; zabezpečení místních záležitostí veřejného pořádku",
    "Vodohospodářský majetek: Společná voda d.s.o., Dohoda vlastníků (Týnec nad Sázavou)",
    "Různé",
    "Diskuse",
    "Závěr",
  ]),
  p("Starosta: Má někdo návrh na změnu nebo doplnění programu? L.Maršíková: Navrhuje do programu žádost paní Ledecké o odstranění kontejnerů od hasičské zbrojnice. Starosta: Tato žádost je zařazena v bodu Různé."),
  p("Hlasování o návrhu L.Maršíkové:"),
  vote("PRO ( 2 – Dušová, Maršíková) – PROTI ( 6 ) – ZDRŽEL SE ( 0 )"),
  h5("Návrh"),
  p("ZO schvaluje program zasedání zastupitelstva obce."),
  vote(V8),

  h3("4) Závěrečný účet obce Krhanice pro rok 2024 a Závěrečné účty svazku obcí"),
  p("Starosta seznámil se Závěrečným účtem obce Krhanice pro rok 2024, jakým způsobem se sestavuje a co obsahuje."),
  h5("Rozprava"),
  p("L.Maršíková: Dotaz, zda je součástí závěrečného účtu i příloha o střednědobém výhledu? Starosta: Všechny podklady zastupitelé dostali."),
  h5("Návrh"),
  p("ZO schvaluje Závěrečný účet obce Krhanice za rok 2024 a dává souhlas s celoročním hospodařením, a to bez výhrad."),
  vote("PRO ( 6 ) – PROTI ( 2 – Dušová, Maršíková ) – ZDRŽEL SE ( 0 )"),

  h4("Závěrečné účty svazku obcí"),
  h5("DSO BENE-BUS; TÝNECKO-SVAZEK OBCÍ; POSÁZAVSKÝ VODOVOD – dobrovolný svazek obcí"),
  p("Informace starosty:"),
  p("DSO BENE-BUS: Byl nám předložen návrh Závěrečného účtu za rok 2024 a Zpráva o výsledku přezkoumání hospodaření za rok 2024. Vyvěšeno dne 23.4.2025 Schvalující orgán – valná hromada svazku."),
  p("TÝNECKO-SVAZEK OBCÍ: Byl nám předložen návrh Závěrečného účtu za rok 2024 a Zpráva o výsledku přezkoumání hospodaření za rok 2024. Vyvěšeno dne 31.3.2025. Schvalující orgán – valná hromada svazku."),
  p("POSÁZAVSKÝ VODOVOD – dobrovolný svazek obcí: Byl nám předložen návrh Závěrečného účtu za rok 2024 a Zpráva o výsledku přezkoumání hospodaření za rok 2024. Vyvěšeno dne 26.3.2025. Schvalující orgán – správní rada členů."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí Závěrečný účet dobrovolného svazku obcí BENE-BUS za rok 2024 a Zprávu o výsledku přezkoumání hospodaření za rok 2024 dobrovolného svazku obcí BENE-BUS."),
  h5("Návrh"),
  p("ZO bere na vědomí Závěrečný účet Týnecko-svazek obcí za rok 2024 a Zprávu o výsledku přezkoumání hospodaření za rok 2024 Týnecko – svazek obcí."),
  h5("Návrh"),
  p("ZO bere na vědomí Závěrečný účet Posázavský vodovod – dobrovolný svazek obcí za rok 2024 a Zprávu o výsledku přezkoumání hospodaření za rok 2024 Posázavský vodovod – dobrovolný svazek obcí."),

  h3("5) Zpráva finančního výboru o kontrole hospodaření obce Krhanice za rok 2024; Zpráva o výsledcích veřejnosprávních kontrol hospodaření Mateřské školy Krhanice a Základní školy Krhanice za rok 2024"),
  p("Předseda finančního výboru Petr Dub seznámil s kontrolou hospodaření obce Krhanice za rok 2024 ze dne 19.5.2025. A dále seznámil s proběhlými veřejnosprávními kontrolami hospodaření příspěvkových organizací Mateřské školy Krhanice a Základní školy Krhanice. Kontroly proběhly dne 19.5.2025."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí zprávu finančního výboru o kontrole hospodaření obce Krhanice za rok 2024 ze dne 19.5.2025."),
  h5("Návrh"),
  p("ZO bere na vědomí protokoly o průběhu a výsledcích veřejnosprávních kontrol příspěvkových organizací Základní škola Krhanice a Mateřská škola Krhanice za rok 2024 ze dne 19.5.2025."),

  h3("6) Schválení účetní závěrky obce Krhanice za rok 2024; Schválení účetní závěrky Mateřské školy Krhanice a Základní školy Krhanice za rok 2024"),
  p("Starosta seznámil s průběhem procesu schvalování účetní závěrky a dále přečetl Protokoly o schvalování účetní závěrky za rok 2024 pro obec Krhanice, pro Mateřskou školu Krhanice a Základní školu Krhanice."),
  p("Starosta přečetl „Protokol o schvalování účetní závěrky za rok 2024 obce Krhanice“."),
  p("Starosta přečetl „Protokol o schvalování účetní závěrky za rok 2024 příspěvkové organizace Mateřská škola Krhanice, okres Benešov“."),
  p("Starosta přečetl „Protokol o schvalování účetní závěrky za rok 2024 příspěvkové organizace Základní škola Krhanice, okres Benešov“."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Schválení účetní závěrky"),
  h5("Návrh"),
  p("ZO schvaluje účetní závěrku obce Krhanice za rok 2024; schvalovaná účetní závěrka poskytuje věrný a poctivý obraz předmětu účetnictví a finanční situace účetní jednotky."),
  vote("PRO ( 6 ) – PROTI ( 0 ) – ZDRŽEL SE ( 2 – Dušová, Maršíková )"),
  h5("Návrh"),
  p("ZO schvaluje účetní závěrku příspěvkové organizace Mateřská škola Krhanice, okres Benešov za rok 2024; schvalovaná účetní závěrka poskytuje věrný a poctivý obraz předmětu účetnictví a finanční situace účetní jednotky."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje účetní závěrku příspěvkové organizace Základní škola Krhanice, okres Benešov za rok 2024; schvalovaná účetní závěrka poskytuje věrný a poctivý obraz předmětu účetnictví a finanční situace účetní jednotky."),
  vote(V8),
  h5("Rozdělení výsledku hospodaření"),
  h5("Návrh"),
  p("ZO schvaluje výsledek hospodaření ve schvalovacím řízení za rok 2024 obce Krhanice ve výši 13 778 928,05 Kč a jeho převod na účet 432 výsledek hospodaření předchozích účetních období."),
  vote("PRO ( 6 ) – PROTI ( 0 ) – ZDRŽEL SE ( 2 – Dušová, Maršíková )"),
  h5("Návrh"),
  p("ZO schvaluje hospodářský výsledek příspěvkové organizace Základní škola Krhanice za rok 2024 ve výši 39 296,43 Kč a jeho příděl do rezervního fondu."),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 1 - Dušová )"),
  h5("Návrh"),
  p("ZO schvaluje Protokol o schvalování účetní závěrky za rok 2024 obce Krhanice."),
  vote("PRO ( 6 ) – PROTI ( 0 ) – ZDRŽEL SE ( 2 – Dušová, Maršíková )"),
  h5("Návrh"),
  p("ZO schvaluje Protokol o schvalování účetní závěrky za rok 2024 příspěvkové organizace Mateřská škola Krhanice, okres Benešov."),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 1 - Dušová )"),
  h5("Návrh"),
  p("ZO schvaluje Protokol o schvalování účetní závěrky za rok 2024 příspěvkové organizace Základní škola Krhanice, okres Benešov."),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 1 - Dušová )"),

  h3("7) Rozpočtové opatření"),
  h4("Rozpočtové opatření č. 3/2025"),
  p("Předseda finančního výboru Petr Dub seznámil s rozpočtovým opatřením č.3/2025."),
  h5("Rozprava"),
  p("Š.Dušová: Dotaz na cestu k lomu, zda v době rekonstrukce bude doprava omezena úplně, nebo bude cesta částečně průjezdná. Starosta: Podle aktuální situace. Obyvatelé, kterých se to bude týkat, budou průběžně informováni."),
  p("Š.Dušová: Budou na cestě místa k vyhnutí dvou aut? Starosta: Ne, je to obytná zóna."),
  p("L.Maršíková: Zůstanou zachována tři místa, kde se auta mohou vyhnout? Starosta. Ano."),
  p("Starosta: V jedné části dojde k zúžení kvůli obrubníkům, neboť je tam „uskočený“ plot."),
  p("L.Maršíková: Nešlo by z této komunikace udělat jednosměrku? Starosta: Je tam cyklostezka. Zkusím zjistit, zda je to vůbec možné."),
  p("I.Dvořák: Jakým způsobem bude komunikace odvodněna? Starosta: Část vody se odvede směrem k lomu, část vody směrem k trafostanici."),
  p("I.Dvořák: Je už podepsaná smlouva s firmou BES? Starosta: Ne."),
  p("L.Maršíková: Dotaz na garáž u Sokolky. O jakou budovu se jedná? Starosta: Jedná se o budovu za autobusovou zastávkou."),
  p("Š.Dušová: Kdy se plánuje realizace chodníku nad úřadem? Starosta: Pan Žaba bude kapacitně mít čas na podzim."),
  h5("Návrh"),
  p("ZO schvaluje rozpočtové opatření č. 3/2025."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje Smlouvu o dílo číslo SoD/1/2025 na zhotovení díla Krhanice přípolož veřejného osvětlení – dodání a montáž technologie, zemní práce s Elmoz Czech, s.r.o., IČO: 47544929, Černoleská 2326, 256 01 Benešov v částce 248 413,- Kč bez DPH."),
  vote(V8),
  h5("Návrh"),
  p("ZO pověřuje starostu obce uzavřením Smlouvy o dílo číslo SoD/1/2025 na zhotovení díla Krhanice přípolož veřejného osvětlení – dodání a montáž technologie, zemní práce s Elmoz Czech, s.r.o., IČO: 47544929, Černoleská 2326, 256 01 Benešov."),
  vote(V8),

  h4("DSO BENE-BUS"),
  p("Informace starosty. Bylo nám předloženo Rozpočtové opatření, které se vztahuje ke schválenému rozpočtu na rok 2025."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí Rozpočtové opatření č. 1/2025 DSO BENE-BUS."),

  h3("8) Koupě, prodej, pronájem"),
  ...ul(["uzavřít Smlouvu o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby č. IV-12-6036731/VB/4 BN_Krhanice-trafo,kNN-č.parc. 373/5 na pozemcích parc.č. 1981/1, 1983/1, 1983/2, 346/2, 272/1 a 363 k.ú. Krhanice s ČEZ Distribuce, a.s., IČO 24729035, DIČ CZ24729035, se sídlem Děčín IV Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 5 900,- Kč na umístění zařízení distribuční soustavy – kabelové vedení NN."]),
  p("Informace starosty: Jedná se o natažení kabelu elektrického vedení od transformátoru až k pozemkům lokality Na splazích."),
  h5("Rozprava"),
  p("L.Maršíková: Kabely budou zasahovat do rekonstrukce komunikace. Tyto práce by se měly realizovat dřív. Starosta: Firma o tom ví. Důležité bude udělat alespoň překop u transformátoru."),
  h5("Návrh"),
  p("ZO schvaluje zřízení věcného břemene na pozemcích parc.č. 1981/1, 1983/1, 1983/2, 346/2, 272/1 a 363 k.ú. Krhanice a schvaluje uzavření Smlouvy o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby č. IV-12-6036731/VB/4 BN_Krhanice-trafo,kNN-č.parc. 373/5 na pozemcích parc.č. 1981/1, 1983/1, 1983/2, 346/2, 272/1 a 363 k.ú. Krhanice s ČEZ Distribuce, a.s., IČO 24729035, DIČ CZ24729035, se sídlem Děčín IV Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 5 900,- Kč na umístění zařízení distribuční soustavy – kabelové vedení NN."),
  vote(V8),
  ...ul(["uzavřít pachtovní smlouvu pro část pozemku parc.č. 1420/8 k.ú. Krhanice o výměře 2416 m², část pozemku parc. č.1978/2 k.ú. Krhanice o výměře 761 m² a část pozemku parc.č. 1420/2 k.ú. Krhanice o výměře 278 m² pro hospodaření v zemědělství za cenu 4 % z ceny půdy úředně stanovené průměrné ceny pozemků v katastrálním území Krhanice dle vyhlášky č. 298/2014 Sb. o stanovení seznamu katastrálních území s přiřazenými průměrnými základními cenami zemědělských pozemků, v platném znění, na dobu 4 let od 26.6.2025."]),
  p("Informace starosty: Ukázal na mapě dotčené pozemky k zemědělské výrobě."),
  h5("Rozprava"),
  p("Š.Dušová: Dotaz na cestu k Boroví, zda tam zůstane, když se pozemky pronajmou. Starosta: Ano."),
  p("Š.Dušová: Dotaz, zda by šlo cestu zpevnit, aby byla vhodná i pro kočárky? Starosta: Ne, oprava cesty by stála miliony."),
  p("L.Maršíková: Kolik jsou 4% z ceny půdy? Starosta: Nevím přesné číslo. Pošlu e-mailem."),
  h5("Návrh"),
  p("ZO schvaluje propachtování části pozemku parc.č. 1420/8 k.ú. Krhanice o výměře 2416 m², části pozemku parc. č.1978/2 k.ú. Krhanice o výměře 761 m² a části pozemku parc.č. 1420/2 k.ú. Krhanice o výměře 278 m² a schvaluje uzavření pachtovní smlouvy pro část pozemku parc.č. 1420/8 k.ú. Krhanice o výměře 2416 m², část pozemku parc.č. 1978/2 k.ú. Krhanice o výměře 761 m² a část pozemku parc.č. 1420/2 k.ú. Krhanice o výměře 278 m² pro hospodaření v zemědělství za cenu 4 % z ceny půdy úředně stanovené průměrné ceny pozemků v katastrálním území Krhanice dle vyhlášky č. 298/2014 Sb. o stanovení seznamu katastrálních území s přiřazenými průměrnými základními cenami zemědělských pozemků, v platném znění, na dobu 4 let od 26.6.2025 se STATEK POŽÁRY s.r.o., IČO: 05933498, Římská 1276/36, 120 00, zastoupený Mgr. Janem Cilínkem."),
  vote(V8),
  ...ul(["uzavřít Smlouvu o zřízení věcného břemene – uložení vodovodní přípojky pro pozemek 1435/22 k.ú. Krhanice na pozemku parc.č. 2086/1 k.ú. Krhanice dle geometrického plánu č. 1196-12/2025 na dobu neurčitou za cenu 3 000,- Kč."]),
  p("Informace starosty: Ukázal na mapě, kde se vodovodní přípojka nachází."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje zřídit věcné břemeno na pozemku parc.č. 2086/1 k.ú. Krhanice dle geometrického plánu č. 1196-12/2025 a schvaluje uzavření Smlouvy o zřízení věcného břemene – uložení vodovodní přípojky pro pozemek 1435/22 k.ú. Krhanice na pozemku parc.č. 2086/1 k.ú. Krhanice dle geometrického plánu č. 1196-12/2025 na dobu neurčitou za cenu 3 000,- Kč s MUDr. Kateřinou Bartošovou, Krhanice č.p. 70, 257 42 Krhanice a Janem Bartošem, Krhanice č.p. 70, 257 42 Krhanice."),
  vote(V8),
  ...ul(["uzavřít Dohodu o zrušení věcného břemene chůze a jízdy, kdy dojde ke zrušení věcného břemene pro Oprávněnou stranu z věcného břemene paní Marcelu Norkovou a Povinnou stranu Obec Krhanice v tomto rozsahu: ruší se Věcné břemeno chůze a jízdy – oprávnění pro Parcela: 102/4, povinnost k Parcela: 102/20, Parcela: 102/38, Parcela 102/39, Parcela 1439/10, vše obec a k.ú. Krhanice, část obce Krhanice."]),
  p("Informace starosty: Věcné břemeno pozbylo smyslu."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Dohody o zrušení věcného břemene chůze a jízdy, kdy dojde ke zrušení věcného břemene pro Oprávněnou stranu z věcného břemene Marcelu Norkovou a Povinnou stranu Obec Krhanice v tomto rozsahu: ruší se věcné břemeno chůze a jízdy – oprávnění pro parcelu č.102/4, povinnost k parcele č.102/20, parcele č.102/38, parcele č.102/39 a parcele č.1439/10 vše k.ú. Krhanice."),
  vote(V8),

  h3("9) Obecně závazná vyhlášky: noční klid; zabezpečení místních záležitostí veřejného pořádku"),
  p("Informace místostarosty o návrhu vyhlášek."),
  p("Noční klid – aktualizace akcí a doplnění jedné akce."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Obecně závaznou vyhlášku obce Krhanice o nočním klidu."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje Obecně závaznou vyhlášku obce Krhanice o regulaci hlučných činností."),
  vote(V8),

  h3("10) Vodohospodářský majetek: Společná voda d.s.o., Dohoda vlastníků (Týnec nad Sázavou)"),
  h4("Společná voda"),
  p("Informace starosty: Jde o dokončení procesu vstupu obce Krhanice do Společné vody."),
  ...ul([
    "Zápis č.4/2024 ze zasedání zastupitelstva obce Krhanice konaného dne 24.9.2024: Společná voda d.s.o. – vstup obce Krhanice do dobrovolného svazku obcí",
    "Zápis č.6/2024 ze zasedání zastupitelstva obce Krhanice konaného dne 13.12.2024: vzájemná Dohodu vlastníků provozně souvisejících vodovodů s Posázavský vodovod – dobrovolný svazek obcí.",
    "Zápis č.1/2025 ze zasedání zastupitelstva obce Krhanice konaného dne 11.3.2025: smlouvu o fúzi svazku Posázavský vodovod – dobrovolný svazek obcí sloučením se svazkem Společná voda d.s.o. k 1. 7. 2025; vstup do dobrovolného svazku Společná voda d.s.o. ke dni 1. 7. 2025; souhlas s účastí ve svazku Společná voda d.s.o. a s podmínkami smlouvy o vytvoření dobrovolného svazku obcí a se stanovami svazku Společná voda d.s.o.; dohoda o úpravě majetkových poměrů o bezúplatném převodu části Posázavského vodovodu na svazek Společná voda d.s.o.",
  ]),
  h5("Rozprava"),
  p("I.Dvořák: V případě poruchy, kdo bude vodovod opravovat a opravy platit? Starosta: Společná voda."),
  h5("Návrhy"),
  p("A.1) Zastupitelstvo obce schvaluje vložení majetku tvořícího vodovody a kanalizace pro veřejnou potřebu ve vlastnictví Obce Krhanice, IČO: 00232025, Krhanice č.p. 46, 257 42 Krhanice specifikovaného v příloze Příloha č. 1 - Specifikace vodohospodářského majetku (dále jen „Vložený majetek“) do hospodaření dle ustanovení § 38 zákona č. 250/2000 Sb., o rozpočtových pravidlech územních rozpočtů, ve znění pozdějších předpisů dobrovolného svazku obcí Společná voda d.s.o., IČO: 17408288, se sídlem Černoleská 1600, 256 01 Benešov (dále jen „Společná voda“);"),
  p("A.2) Zastupitelstvo obce schvaluje uzavření smlouvy mezi Obcí Krhanice, IČO: 00232025, Krhanice č.p. 46, 257 42 Krhanice a Společnou vodou d.s.o., IČO: 17408288, se sídlem Černoleská 1600, 256 01 Benešov, na jejímž základě dojde k vložení Vloženého majetku dle předchozího bodu do hospodaření Společné vody a přenesení majetkových práv k Vloženému majetku na Společnou vodu v rozsahu dle stanov Společné vody;"),
  p("A.3) Zastupitelstvo obce pověřuje Mgr. Aleše Papouška, starostu Obce Krhanice zabezpečit provedení potřebných úkonů k realizaci bodů A.1) a A.2) tohoto usnesení;"),
  p("A.4) Zastupitelstvo obce pověřuje Mgr. Aleše Papouška, starostu Obce Krhanice uzavřením Smlouvy dle bodu A.2)."),
  p("B.1) Zastupitelstvo obce schvaluje uzavření smlouvy o přenechání vodohospodářské infrastruktury do užívání za účelem zajištění jejího provozu mezi Obcí Krhanice, IČO: 00232025, Krhanice č.p. 46, 257 42 Krhanice a dobrovolného svazku obcí Společná voda d.s.o., IČO: 17408288, se sídlem Černoleská 1600, 256 01 Benešov (dále jen „Společná voda“), na základě níž dojde k přenechání do užívání majetku tvořícího vodovody a kanalizace pro veřejnou potřebu ve vlastnictví Obce Krhanice specifikovaného v příloze Příloha č.1 - Specifikace svěřeného majetku včetně protokolu o převzetí (dále jen „Svěřený majetek“) Společné vodě za účelem zajištění provozování Svěřeného majetku Společnou vodou;"),
  p("B.2) Zastupitelstvo obce pověřuje Mgr. Aleše Papouška, starostu Obce Krhanice zabezpečit provedení potřebných úkonů k realizaci bodu B.1) tohoto usnesení."),
  p("B.3) Zastupitelstvo obce pověřuje Mgr. Aleše Papouška, starostu Obce Krhanice uzavřením Smlouvy dle bodu B.1)."),
  vote(V8),

  h4("Dohoda vlastníků (Týnec nad Sázavou)"),
  p("Informace starosty: Z vodovodního řadu obce Krhanice byl udělán vodovodní řad k novým nemovitostem v Chrástu nad Sázavou. Musíme uzavřít dohodu vlastníků provozně souvisejících vodovodů na předávání pitné vody."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Dohody vlastníků provozně souvisejících vodovodů dle zákona o vodovodech a kanalizacích mezi Obcí Krhanice a Městem Týnec nad Sázavou, IČO: 00232904, K Náklí 404, 257 41 Týnec nad Sázavou."),
  vote(V8),

  h3("11) Různé"),
  h4("Kanalizace – další postup"),
  p("Z pracovního sezení zastupitelů (11.6.2025): Z hlediska obce by se jednalo o vybudování ČOV a částečně kanalizace – spodek Krhanic až ke škole."),
  p("Je třeba rozhodnout, zda obec půjde cestou postupného budování splaškové kanalizace v Krhanicích po etapách, NEBO vybudování tělocvičny s jazykovou učebnou a budování chodníků u hlavní silnice. Rozhodovat se budou občané 18+ obce Krhanice a obce Prosečnice. Rozhodovat se budou formou dotazníku se dvěma variantami. Dotazníky se budou odevzdávat při podzimních volbách v budově základní školy a do schránky obecního úřadu."),
  h5("Rozprava"),
  p("L.Maršíková: Myslím si, že by bylo vhodné veřejné setkání s občany, aby se mohli doptávat na podrobnosti. Starosta: Zásadní je důkladně připravit dotazníky, podklady."),
  p("I.Dvořák: Jak dalece se budou zastupitelé řídit rozhodnutím občanů? Je možné, že jejich rozhodnutí nebude souhlasit s tím, jak by se rozhodli zastupitelé. Starosta: Pro mě jako starostu bude názor občanů závazný."),
  p("V.Duša: Dotaz na částky první a druhé varianty. Starosta: Částky musí vypracovat odborníci. Proběhla diskuse, např. o stanovení množství odevzdaných dotazníků – relevantnost odpovědí."),

  h4("Změna cen pronájmů"),
  p("Informace starosty: Na pracovní sezení zastupitelů byl odsouhlasen postup, že navyšování nájmů má přímou souvislost s inflací. Výsledné ceny – viz prezentace."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje ceny pronájmu pozemků a nebytových prostor s účinností od 1.7.2025 dle následující tabulky:"),
  ...ul([
    "Pronájem pozemku nebo jeho části: občan 15,00 Kč m²/rok; podnikání 30,00 Kč m²/rok; spolky, pobočné spolky a zájmová sdružení 1,00 Kč m²/rok",
    "Dlouhodobý (nad 30 dnů) pronájem nebytových prostor nebo jejich části vyjma klubovny zázemí víceúčelového hřiště: občan 70,00 Kč m²/rok; podnikání 330,00 Kč m²/rok",
    "Krátkodobý (do 30 dnů) pronájem nebytových prostor nebo jejich části vyjma klubovny zázemí víceúčelového hřiště: občan 15,00 Kč m²/den; podnikání 30,00 Kč m²/den",
    "Pronájem pozemku nebo jeho části pro užitný objem pod pronajímaným pozemkem nebo jeho části: občan 15,00 Kč m³/rok; podnikání 135,00 Kč m³/rok",
  ]),
  vote(V8),

  h4("Dopis JUDr. Ledecké"),
  p("Starosta: Přečetl dopis JUDr. Ledecké. Proběhla diskuse se závěrem, že JUDr. Ledecké odpoví na její žádost o odstranění kontejnerů místostarosta, který má na starosti odpadové hospodářství obce."),

  h4("Tréninkové hřiště před základní školou"),
  p("Starosta: Informoval, že kolíky na tréninkovém hřišti jsou z geodetického vytýčení. Sokolové by chtěli umístit hřiště s umělou trávou o velikosti 22 x 40 metrů na tréninkové hřiště. Ještě je třeba zjistit finance. Potom se uvidí, zda řešit jako záměr."),
  p("L.Maršíková: V prosinci se hřiště schválilo. Starosta: V prosinci se schválily pouze peníze na záměr, ne realizaci. Ještě je třeba zjistit rozpočet. Potom se uvidí."),
  p("I.Zahrádková: Dotaz, zda škola o tom ví? Využívá travnatou plochu před školou každý den. Starosta: Ředitelka školy se k záměru vyjádřila. Proběhla diskuse bez přijetí závěrů."),

  h3("12) Diskuse"),
  p("R.Novotný: Doporučil rozšířit mezeru mezi keři v parku nad úřadem z důvodu dopravní přehlednosti. Starosta: Podívám se, zda je to možné realizovat."),

  h3("13) Závěr"),
  p("Zastupitelstvo obce bylo ukončeno v 20:31 hod."),
  p("Datum pořízení zápisu: 30.6.2025"),
  p("Ověřovatelé zápisu a starosta obce, podepsáno v listinné podobě."),
  h4("Přílohy"),
  ...nl([
    "Svolání zastupitelstva obce",
    "Prezenční listina zastupitelů",
    "Prezenční listina občanů",
    "Zápis č.2/2025 zastupitelstva obce Krhanice ze dne 16.04.2025",
  ]),
];

async function run() {
  const r = await publishZapis({
    cislo: "3",
    rok: "2025",
    isoDate: "2025-06-25",
    dateLabel: "25. 6. 2025",
    fullDateDot: "25.6.2025",
    pdfPath: "scripts/zapisy-pdf/zapis-2025-3.pdf",
    transcript,
  });
  console.log("OK", r.docId, "blocks", r.blocks);
}
run().catch((e) => { console.error(e); process.exit(1); });
