/* eslint-disable no-console */
// Faithful, visually transcribed minutes - Zápis č. 4/2023 (19.10.2023).
import { h3, h4, h5, p, vote, nl, ul, publishZapis, type Block } from "../zapis-lib";

const transcript: Block[] = [
  h4("Přítomni"),
  p("Aleš Papoušek, Jaroslav Mixa, Tomáš Kratochvíl, Jana Laboutková, Petr Dub, Lucie Maršíková, Hana Strnadová, Martin Jiřička"),
  h4("Omluveni"),
  p("Aleš Kozel"),

  h3("1) Zahájení, přivítání přítomných, konstatování přítomnosti"),
  p("Starosta konstatoval, že zasedání bylo svoláno dne 5.10.2023, bylo vyvěšeno na úřední desce obecního úřadu, tj. tedy nejméně 7 dní před zasedáním. Bylo tedy svoláno řádně a včas v souladu se zákonem o obcích v platném znění. Starosta konstatoval, že podle prezenční listiny je přítomno 8 členů zastupitelstva, tedy nadpoloviční většina členů zastupitelstva. K předchozímu zápisu nebyly vzneseny námitky."),
  h5("Určení zapisovatele"),
  p("Zápisem zasedání zastupitelstva obce byla pověřena Ing. Alena Kratochvílová."),

  h3("2) Volba návrhové komise a ověřovatelů zápisu"),
  p("Starosta přednesl návrh návrhové komise a ověřovatelů zápisu."),
  h5("Návrh"),
  p("ZO schvaluje návrhovou komisi ve složení: Jaroslav Mixa, Jana Laboutková."),
  h5("Návrh"),
  p("ZO schvaluje ověřovatele zápisu ve složení Martin Jiřička, Lucie Maršíková."),
  vote("PRO ( 8 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )"),

  h3("3) Schválení programu"),
  p("Starosta přečetl program."),
  ...nl(["Zahájení", "Volba návrhové komise a ověřovatelů zápisu", "Schválení programu", "Zpráva Kontrolního výboru", "Rozpočtová opatření", "Koupě, prodej, pronájem", "Různé", "Diskuse", "Usnesení a závěr"]),
  p("Starosta: Má někdo návrh na změnu nebo doplnění programu?"),
  h5("Návrh"),
  p("ZO schvaluje program zasedání zastupitelstva obce."),
  vote("PRO ( 8 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )"),

  h3("4) Zpráva kontrolního výboru"),
  p("Martin Jiřička seznámil se zprávou kontrolního výboru ze dne 24.8.2023."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí Zprávu kontrolního výboru ze dne 24.8.2023."),

  h3("5) Rozpočtové opatření"),
  h4("Rozpočtové opatření č. 8/2023"),
  p("V souladu se schválenými pravidly provedl starosta obce. Jednalo se o přijetí a přeposlání průtokové dotace pro Mateřskou školu Krhanice – operační program Jan Amos Komenský v částce 443,42 tisíc Kč."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí rozpočtové opatření č. 8/2023."),
  p("Předseda finančního výboru Petr Dub seznámil s rozpočtovým opatřením č. 9/2023."),
  h5("Rozprava"),
  p("P.Jettmar: Dotaz na kapitálové výdaje – snížení o 4,5 milionu. Starosta: Jsou to výdaje na výstavbu chodníku kolem okružní křižovatky, který se nakonec bude realizovat v příštím roce."),
  h5("Návrh"),
  p("ZO schvaluje rozpočtové opatření č. 9/2023."),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 1 - Strnadová )"),

  h3("6) Koupě, prodej, pronájem"),
  ...ul(["prodat část pozemku díl „a“ z parc.č. 59/1 k.ú. Krhanice o výměře 17 m² za cenu 750,- Kč/1m². Geometrický plán na oddělení části pozemku a vklad na katastr bude hradit kupující."]),
  p("Informace starosty: Jde o přikoupení části obecního pozemku k trojúhelníkovému pozemku pana Hnídka, aby na tomto pozemku mohl parkovat a v budoucnu si ukládat stavební materiál pro zamýšlenou stavbu rodinného domu, bude si tam parkovat a tento veřejný prostor za hasičárnou nebude využívat a nebude v kolizi s hasičskými akcemi."),
  h5("Rozprava"),
  p("L.Maršíková: Původní záměr byl 14 m², proč nyní 17 m²? Starosta: Zpřesnění bylo na základě geodetického zaměření."),
  p("Proběhla diskuse o tom, proč chce pan Hnídek zvětšit místo na parkování, zda už má stavební povolení, jak funguje pronájem pozemku parc.č. 59/1 k.ú. Krhanice, o přístupu k jímce za hasičskou zbrojnicí, o konání akcí u hasičské zbrojnice, o ceně pozemku, odkupu hráze od manželů Hnídkových, o vjezdu z veřejného prostranství, … T. Kratochvíl: Za hasiče nechceme, aby u hasičské zbrojnice někdo parkoval. Tímto se vyřeší, že p. Hnídek bude parkovat za bránou na svém pozemku. S panem Hnídkem máme dobré vztahy a ústní dohodu ohledně výjezdu z pozemku a neblokování přístupu, když máme akci. Nevidíme důvod, proč toto podkládat písemně. Výbor hasičů se shodl na tom, že dá souhlasné stanovisko s prodejem, a s p. Hnídkem jsme se na místě taky dohodli."),
  p("Starosta: Cena je cena dohodnutá, je stejná, za jakou jsme získali 6 m² hráze. Pan Hnídek nám vyšel vstříc, jde o reciprocitu a korektní jednání. Prodej od 1. 1. 2024."),
  p("L.Maršíková předložila protinávrh usnesení:"),
  h5("Návrh"),
  p("ZO schvaluje záměr pronajmout část pozemku o výměře 17 m2 z parc.č. 59/1 k.ú. Krhanice za cenu 10,- Kč/1m2/rok na dobu 1 roku Jaromíru Hnídkovi, Krhanice č.p. 28, 257 42 Krhanice."),
  vote("PRO ( 2 – Maršíková, Strnadová ) – PROTI ( 6 ) – ZDRŽEL SE ( 0 )"),
  h5("Návrh"),
  p("ZO schvaluje prodej části pozemku díl „a“ z parc.č. 59/1 k.ú. Krhanice o výměře 17 m² za cenu 750,- Kč/1m² Jaromíru Hnídkovi, Krhanice č.p. 28, 257 42 Krhanice. Geometrický plán na oddělení části pozemku a vklad na katastr nemovitostí bude hradit kupující."),
  vote("PRO ( 6 ) – PROTI ( 2 – Maršíková, Strnadová ) – ZDRŽEL SE ( 0 )"),

  h3("7) Různé"),
  h4("Posázavský vodovod – rozpočtové opatření č. 2/2023"),
  p("Informace starosty: Bylo nám předloženo rozpočtové opatření č. 2/2023."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí Rozpočtové opatření č. 2/2023 Posázavský vodovod – dobrovolný svazek obcí."),

  h4("Plán inventur na rok 2023"),
  p("Informace starosty: Standardním způsobem provedeme inventarizaci. Schválíme Plán inventur na rok 2023 včetně přílohy č. 1 – Seznamu inventurních soupisů s konkrétním postupem pro provedení inventarizace majetku a závazků obce. Jsou zde uvedeny konkrétní osoby, termíny a úkoly. Pro rok 2023 se zřizuje jedna inventarizační komise pro střediska – Obecní úřad Krhanice, Knihovna, Hasičská zbrojnice ve složení: Aleš Papoušek, Jana Cachová, Lenka Termerová, Jaroslav Mixa a Petr Dub."),
  p("Stav majetku a závazků bude zjišťován k datu 31. 12. 2023. Inventurní soupisy bude inventarizační komise vyhotovovat průběžně v měsíci lednu 2024. Inventarizační komise vyhotoví Inventarizační zprávu nejpozději do 6. 2. 2024."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Plán inventur 2023."),
  vote("PRO ( 8 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )"),

  h4("Komise pro sestavení rozpočtu pro rok 2024"),
  p("Informace starosty: V souladu se směrnicí č. 2/2017 Metodika sestavení rozpočtu obce Krhanice bude zřízena Komise pro sestavení rozpočtu pro rok 2024: Aleš Papoušek, Jana Laboutková, Petr Dub, Alena Kratochvílová, Markéta Vaňková a Jana Cachová."),
  p("Jednotliví žadatelé – základní škola, mateřská škola, Komise pro obnovu a rozvoj obce, Kulturní komise, SDH Krhanice, JSDHO Krhanice, TJ Sokol Krhanice, některé spolky a zájmové organizace již byli osloveni a vyzváni k předložení požadavků na rozpočet na rok 2024."),
  p("Sezení komise bude naplánováno na měsíc listopad 2023."),
  p("Komise pro sestavení rozpočtu zpracovává jednotlivé požadavky žadatelů, jedná s některými žadateli a dotazuje se na předkládané materiály. Vyhotovuje písemnou zprávu pro jednání zastupitelstva o rozpočtu pro rok 2024."),
  h5("Rozprava"),
  p("L.Maršíková: Na koho se obracet, pokud budu chtít informace k rozpočtu? Starosta: Na starostu, komise je podpůrná."),
  p("L.Maršíková: Návrh na nového člena komise: Petra Dvořáková. Starosta: Komise má 6 členů, musel by se někdo vyměnit. Přítomní navržení členové komise byli vyzváni k vyjádření. Nikdo se svého místa v komisi vzdát nechtěl. L. Maršíková: Nebyli jsme osloveni, abychom podali návrh na člena. Starosta: Můžete příští rok navrhnout, schvaluje se zpravidla na říjnovém zastupitelstvu. Dopředu Vám to řeknu."),
  h5("Návrh"),
  p("ZO schvaluje složení Komise pro sestavení rozpočtu pro rok 2024: Aleš Papoušek, Jana Laboutková, Petr Dub, Alena Kratochvílová, Markéta Vaňková a Jana Cachová."),
  vote("PRO ( 6 ) – PROTI ( 2 – Maršíková, Strnadová ) – ZDRŽEL SE ( 0 )"),

  h4("Dílčí kontrola hospodaření obce Krhanice ze strany Středočeského kraje"),
  p("Informace starosty: Dne 19.9.2023 provedl Odbor kontroly Středočeského kraje dílčí kontrolu hospodaření obce Krhanice za rok 2023. Výsledek – bez chyb a nedostatků."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí Zápis z dílčího přezkoumání hospodaření obce Krhanice ze dne 19.9.2023."),

  h4("Projekt Krhanice – rekonstrukce veřejného osvětlení"),
  p("Dotace: Byla nám schválena žádost o dotaci na projekt „Krhanice – rekonstrukce veřejného osvětlení“ z dotačního titulu Ministerstva průmyslu a obchodu ČR: výzva č. NPO 1/2022 Národní plán obnovy; Rekonstrukce veřejného osvětlení – Komponenta 2.2.2. V projektu se plánuje výměna 161 světel, výměna výložníků, některých sloupů, …"),
  p("Akceptace/rezervovány finanční prostředky ve výši: 925.290,- Kč."),
  p("Předpokládaný rozpočet projektu: 2.880.383 Kč."),
  p("Dalšími kroky jsou: výběrové řízení na projekt, schválení dodavatele, schválení dotace, uzavření veřejnoprávní smlouvy."),
  h5("Rozprava"),
  p("H.Strnadová: Nedostali jsme soupis firem, které budou osloveny. Starosta: Firmy jsem dopisoval až dnes."),
  p("L. Maršíková: Žádala jsem opakovaně o zaslání podkladů k projektu, dostala jsem je až dnes odpoledne, neměla jsem tedy možnost si je projít a zodpovědně hlasovat. Ostatní zastupitelé je dostali? Nejsem proti rekonstrukci veřejného osvětlení, ale chci o tom něco vědět, než se bude hlasovat. Starosta: Parametry odpovídají dotaci, dotace je schválená. Už na tom není co měnit, co odkládat. Dnes řešíme jen výběrové řízení."),
  p("L.Maršíková předložila protinávrh usnesení."),
  h5("Návrh"),
  p("ZO schvaluje odložit hlasování o všech bodech týkajících se rekonstrukce veřejného osvětlení (níže uvedené body, body č. 8, 9 a 10 a pověření bod č.1)."),
  vote("PRO ( 2 – Maršíková, Strnadová ) – PROTI ( 6 ) – ZDRŽEL SE ( 0 )"),
  h5("Návrh"),
  p("ZO schvaluje vypsání výběrového řízení na dodavatele stavby pro projekt „Krhanice – rekonstrukce veřejného osvětlení“."),
  vote("PRO ( 6 ) – PROTI ( 0 ) – ZDRŽEL SE ( 2 – Maršíková, Strnadová )"),
  h5("Návrh"),
  p("ZO schvaluje oslovení 3 firem pro výzvu k podání nabídky pro projekt „Krhanice-rekonstrukce veřejného osvětlení“:"),
  ...ul([
    "DĚDIC-Elektromontáže s.r.o., IČO: 02623650, Ostrava, Moravská Ostrava a Přívoz, Cihelní 1191/95",
    "ELTODO OSVĚTLENÍ, s.r.o., IČO: 25751018, Praha 4, Lhotka, Novodvorská 1010/14",
    "Yunex, s.r.o., IČO: 09962638, Praha 11, Chodov, V parku 2308/8",
  ]),
  vote("PRO ( 6 ) – PROTI ( 0 ) – ZDRŽEL SE ( 2 – Maršíková, Strnadová )"),
  h5("Návrh"),
  p("ZO pověřuje starostu obce realizací výběrového řízení na dodavatele stavby pro projekt „Krhanice – rekonstrukce veřejného osvětlení“."),
  vote("PRO ( 6 ) – PROTI ( 0 ) – ZDRŽEL SE ( 2 – Maršíková, Strnadová )"),
  h5("Návrh"),
  p("ZO schvaluje spolupráci s Posázavím o.p.s., Zámek Jemniště 1, 257 01 Postupice, IČO 27129772 při zajištění poradenství při realizaci výběrového řízení pro projekt „Krhanice – rekonstrukce veřejného osvětlení“."),
  vote("PRO ( 6 ) – PROTI ( 0 ) – ZDRŽEL SE ( 2 – Maršíková, Strnadová )"),

  h4("Kalkulace vodného pro rok 2024"),
  p("Informace starosty: Byla nám předložena kalkulace cen pro vodné pro rok 2024 od VHS Benešov. Navyšuje se cena vody předávané z hlavního přivaděče Posázavský vodovod o 2,95 Kč/m³, dále se navyšuje cena za výměnu vodoměrů, náklady na údržbu, mzdy pro odečty a také se očekává nižší spotřeba vody."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje navýšení ceny vodného na 62,72 Kč bez DPH od 1.1.2024."),
  vote("PRO ( 8 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )"),

  h4("Tělocvična"),
  p("Informace starosty: Máme povolenou stavbu tělocvičny a stavbu jazykové budovy jako přístavbu základní školy. Národní sportovní agentura vypsala dotaci na výstavbu sportovní infrastruktury primárně určené pro sportovně zaměřené spolky a sekundárně využívané školou (Regionální sportovní infrastruktura 2023 - investice nad 10 mil. Kč – výzva 12/2023). Rozpočet je 46 841 543,90 Kč a maximální výše dotace na akci může být 30 000 000 Kč."),
  h5("Rozprava"),
  p("P.Bydžovský: Jak bude přístavba vypadat? Takto se k té budově nehodí. Starosta: Seznámil přítomné s hledáním vhodného umístění tělocvičny (nebylo moc možností), s podmínkami získání dotace, …"),
  p("H.Strnadová: Tělocvična je až etapa č.2. Jak se to napojí na stávající stavbu. Nemělo by se myslet i na odborné učebny, které škola potřebuje?"),
  p("Starosta: Jazyková učebna (etapa č. 1) má dle projektu vstup z druhého patra. Na vlastní náklady bychom museli vybudovat spodní část, krček. Nejsem schopen říct, jak to technicky bude. V plánu je odborná učebna pro dílny v prostorách družiny, až se pro družinu uvolní prostory ve škole. Toto by pomohla řešit jazyková učebna (což je vize hodně daleko)."),
  p("H. Strnadová: Máte bilanci, kolik bude budova následně stát, když se postaví? Budova nesplňuje kritéria pasivní budovy, nepracuje s využitím dešťové vody, zelenou střechou."),
  p("Starosta: Ne, nemám. Projekt se dělal tři roky. Pokud dotaci nedostaneme, budeme o projektu jednat a diskutovat dál."),
  p("P. Bydžovský: Teď je doba, kdy projekt není schválený, není schválená dotace, tak by se mělo o projektu bavit, o využití, o ekologických parametrech, o následných nákladech..."),
  p("Starosta: Národní sportovní agentura vypsala program 1. října pro podání žádostí je v podstatě jen měsíc, do konce října."),
  p("J. Bydžovská: Kdy se projekt tvořil a byla možnost se do toho zapojit a vyjádřit se k němu?"),
  p("Starosta: Před třemi roky. Pro projektanta byl vůbec problém tuto budovu vymyslet a napojit na stávající budovu. Pokud projekt neprojde dotací, můžeme se o něm dál bavit, předělat ho apod. pro využití tělocvičny širší veřejností."),
  p("I. Dvořák: Nevidím důvod, proč projekt nebyl zveřejněn dřív. Přimlouvám se za to, dát projekt na stránky a okomentovat. Dotaz, zda bude budova využitelná i pro ostatní veřejnost vyjma školy, sokolů, hasičů?"),
  p("Starosta: Ano. Je to předčasné, ale bude rozpis, jsem pro využití tělocvičny veřejností."),
  p("P. Bydžovský: Jakmile dotaci podáte, již s projektem nebudete moct hnout. Nebylo by vhodné ho aktualizovat, aby energetická náročnost v budoucnu nebyla veliká?"),
  p("Starosta: Energetické náklady budou vždycky vyšší."),
  p("Pokud dotaci nezískáme, můžeme se začít bavit o tom, jak budovu povýšit. Projektant ale projekt nepředělá na pasivní budovu. Tělocvična nikdy nebude pasivní budova."),
  p("L. Maršíková: Co znamená položka Hnojení umělým hnojivem v rovině v částce 921 milionů a položka retenční nádrž v částce 759 tis. Není specifikovaná. Jak bude velká?"),
  p("Starosta: Nevím. Nejsem rozpočtář, tyto položky mohu zjistit. Nevšiml jsem si toho."),
  p("Proběhla diskuse, zda se bude moci tělocvična využívat na společenské akce, jak upravit projekt tak, aby splňoval podmínky pasivní stavby, o jazykové učebně, o zmenšení zahrady pro žáky, o vzhledu budovy, kdo bude žadatelem dotace - obec, o dalším možném využívání tělocvičny, …"),
  h5("Návrh"),
  p("ZO schvaluje podání žádosti o dotaci pro projekt „Tělocvična obce Krhanice“ na výstavbu tělocvičny u Národní sportovní agentury – Regionální sportovní infrastruktura 2023 - investice nad 10 mil. Kč – výzva 12/2023."),
  vote("PRO ( 6 ) – PROTI ( 1 – Maršíková ) – ZDRŽEL SE ( 1 – Strnadová )"),
  h5("Návrh"),
  p("ZO schvaluje použití finančních prostředků z rozpočtu obce pro dofinancování podílu nejméně 30 % celkových způsobilých výdajů projektu „Tělocvična obce Krhanice“."),
  vote("PRO ( 6 ) – PROTI ( 1 – Maršíková ) – ZDRŽEL SE ( 1 – Strnadová )"),
  h5("Návrh"),
  p("ZO schvaluje spolupráci s Posázavím o.p.s., Zámek Jemniště 1, 257 01 Postupice, IČO 27129772 při zajištění poradenství pro podání dotace pro projekt „Tělocvična obce Krhanice“."),
  vote("PRO ( 6 ) – PROTI ( 1 – Maršíková ) – ZDRŽEL SE ( 1 – Strnadová )"),

  h4("Informace starosty: Anketa o celonočním provozu veřejného osvětlení"),
  p("Anketa: Koncem měsíce září 2023 proběhla Anketa s dotazem, zda má být obnoven celonoční provoz veřejného osvětlení."),
  p("Výsledek ankety: 86% ANO, 14% NE. Celonoční svícení bylo zavedeno."),

  h4("Informace starosty: Uzavírka okružní křižovatka"),
  p("Krajská správa a údržba silnic Středočeského kraje oznámila přesunutí realizace stavby okružní křižovatky s chodníkem na začátek stavební sezóny 2024."),

  h4("Odpadové hospodářství – změny r. 2024"),
  p("Informace místostarosty: Dojde ke změnám ve svozu popelnic. A dojde ke změnám ve svozu papíru a plastů."),
  p("Od roku 2024 bude pouze čtrnáctidenní svoz popelnic."),
  p("Tento týden jsme začali rozesílat domácnostem s týdenním a kombinovaným svozem popelnic Dotazník. Tyto domácnosti v něm budou volit velikost popelnice pro rok 2024. Dále domácnosti, které topí v kamnech (uhlím, dřevem) mají možnost zvolit další popelnici pro popel v topné sezóně. Zpětná vazba – termín do 31.10.2023."),
  p("Důležité bude jednání 6.11.2023 na Technických službách Benešov. Naše obec a další obce zapojené do projektu čtrnáctidenního svozu budou domlouvat další postup a termíny s Technickými službami Benešov. Poté budou informováni občané - např. jak bude probíhat výměna popelnicových nádob, jak bude probíhat pytlový svoz papíru a plastů, …."),

  h4("Informace starosty: Poděkování JSDHO Krhanice – zásah statek"),
  p("Chtěl bych poděkovat naší zásahové jednotce hasičů, která zasahovala dne 20. srpna 2023 při požáru na statku farmy Mikoláš v Krhanicích. Jsem rád, že obec Krhanice má plně funkční a aktivní hasičskou zásahovou jednotku, ale i také velmi dobře fungující Sbor dobrovolných hasičů Krhanice."),

  h4("Informace starosty: Divoká prasata"),
  p("V poslední době začala v obci hodně řádit divoká prasata, a to zejména ve dvou lokalitách – Prosečnice a Krhanice (zejména Na Vlčím důle)."),
  p("Jednal jsem s Ing. Jankovským, ředitelem Lesního závodu Konopiště Lesů České republiky a myslivcem. Problematika je špatně řešitelná, neboť by se jednalo o střelbu v zastavěné oblasti. Je to riziko střílejícího a na jeho zodpovědnost. 6.listopadu provedou LČR odstřel divočáků v lesích nad Krhanicemi."),
  p("S některými občany, jejichž nemovitosti jsou zasaženy řáděním divokých prasat jsem již konzultoval postup ke zmírnění následků působení divokých prasat. Obec má objednané prostředky – pachové odpuzovače (antifer roztok a PACHO-LEK na černou zvěř), které by měly v určité míře odpuzovat divoká prasata. Po domluvě s majiteli nemovitostí dotčených řáděním divokých prasat v Krhanicích a Prosečnici budou tyto prostředky aplikovány v okolí jejich nemovitostí."),
  p("P.Bydžovský: Poznámka, zda by nebylo při honu vhodné divočáky vyhánět z obce směrem k lesu? Starosta: Nabízel jsem, zatím p. ředitel Jankovský nechce, začnou nejprve u lomu. Nabídnu znovu. Je to složité, jsou v místech zástavby, kde dřív nebyly. Po 6. 11. se s panem ředitelem spojím, vyhodnotíme, jestli se to zlepšilo."),
  p("M. Maršík: Lidé by se o odstřelu prasat ve vsi měli informovat. Starosta: Není to v zástavbě, ale na louce pod palouky."),
  p("Proběhla diskuse o odstřelech, o nejvíce postižených lokalitách, …"),

  h3("8) Diskuse"),
  p("I.Dvořák: Dotaz, kdy bude jasné, jaká dopravní omezení budou v době výstavby okružní křižovatky? Starosta: Zatím nepřišly oficiální informace. Do dubna má být všechno připravené a schválené MěÚ Benešov. Kraj je neústupný."),
  p("P.Jettmar: Proč bude stavět kruhový objezd? Starosta: Kvůli bezpečnosti řidičů a chodců, dějí se tam opakovaně nehody, které mají obdobný charakter."),
  p("I.Dvořák: Dotaz, zda bude chodník od Dlážděnky až k viaduktu? Starosta: K viaduktu ne, k poslednímu odbočení vpravo. Zbylá část se bude dořešovat, předběžně jsme s majiteli přilehlých nemovitostí dohodnutí. Pod viaduktem by měl být zúžený chodník 1,25 m a musí se tam předělat dešťová kanalizace, která se zanáší."),
  p("P.Bydžovský: Vláda odsouhlasila úsporný balíček a 1,8 násobek základu daně z nemovitosti. Dávám podnět k zamyšlení, protože obec letos schvalovala zvýšení daně z nemovitosti na trojnásobek. Není to zvýšení o pár set korun, ale o 2,7násobek stávající daně z nemovitosti. Je to velké zatížení. Starosta: Mám zapsáno, podíváme se na to."),
  p("P.Jettmar: Dotaz na bezpečný příchod k nádraží zejména při budování okružní křižovatky. Jak se dostanu jako chodec na nádraží, aniž bych musel uskakovat do příkopu? Bude tam chodník? Starosta: V tuto chvíli vše záleží na Agentuře logistiky Armády České republiky. Proběhne jednání. Podle výsledku bude jasné, zda lze chodník vůbec vybudovat. Pokud ano, bude následovat jednání se Správou železnic."),
  p("L.Maršíková: Za zahradou pana Mixy jsem si všimla stržené ornice na obecním pozemku, z jakého důvodu? Starosta: Tato zemina byla potřeba pro dokončení pumptrackové dráhy."),
  p("L.Maršíková: Dotaz na dokončení pumptrackové dráhy a limitu 100 tisíc dráhy a následnou údržu. Starosta: V budoucnu tam bude řešit komunikace, obratiště. Dráha je hotová, používá se a v příštím roce realizátoři provedou finální úpravy. Limit nebyl překročen. Udržovat bude obec."),
  p("P.Bydžovský: Dotaz na terénní úpravy, aby kolem svého plotu projel sekačkou. Starosta: Obec seká trávu 2x ročně. Pan místostarosta se dojde podívat na místo."),

  h3("9) Usnesení a závěr"),
  p("Zastupitelstvo obce bylo ukončeno v 20:05 hod."),

  p("Datum pořízení zápisu: 24.10.2023"),
  p("Ověřovatelé zápisu a starosta obce, podepsáno v listinné podobě."),
  h4("Přílohy"),
  ...nl(["Svolání zastupitelstva obce", "Prezenční listina zastupitelů", "Prezenční listina občanů"]),
];

async function run() {
  const r = await publishZapis({
    cislo: "4",
    rok: "2023",
    isoDate: "2023-10-19",
    dateLabel: "19. 10. 2023",
    fullDateDot: "19.10.2023",
    pdfPath: "scripts/zapisy-pdf/zapis-2023-4.pdf",
    transcript,
  });
  console.log("OK", r.docId, "blocks", r.blocks);
}
run().catch((e) => { console.error(e); process.exit(1); });
