/* eslint-disable no-console */
import { h3, h4, h5, p, vote, nl, ul, publishZapis, type Block } from "../zapis-lib";

const V8 = "PRO ( 8 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )";

const transcript: Block[] = [
  h4("Přítomni"),
  p("Aleš Papoušek, Jaroslav Mixa, Tomáš Kratochvíl, Václav Zíta, Petr Dub, Martin Jiřička, Jana Laboutková, Edita Jarošová"),
  h4("Omluveni"),
  p("Bohuslav Kadeřábek"),

  h3("1) Zahájení, přivítání přítomných, konstatování přítomnosti"),
  p("Starosta konstatoval, že zasedání bylo svoláno dne 14.2.2022, bylo vyvěšeno na úřední desce obecního úřadu, tj. tedy nejméně 7 dní před zasedáním. Bylo tedy svoláno řádně a včas v souladu se zákonem o obcích v platném znění. Starosta konstatoval, že podle prezenční listiny je přítomno 8 členů zastupitelstva, tedy nadpoloviční většina členů zastupitelstva. K předchozímu zápisu nebyly vzneseny námitky."),
  h5("Určení zapisovatele"),
  p("Zápisem zasedání zastupitelstva obce byla pověřena Ing. Alena Kratochvílová."),
  p("Starosta přečetl program."),
  ...nl(["Zahájení", "Volba návrhové komise a ověřovatelů zápisu", "Zpráva kontrolního výboru", "Rozpočtová opatření", "Rekonstrukce hlavního vodovodního přivaděče pod viaduktem v Krhanicích", "Koupě, prodej, pronájem", "Různé", "Diskuse"]),
  h5("Návrh"),
  p("ZO schvaluje program zasedání zastupitelstva obce."),
  vote(V8),

  h3("2) Volba návrhové komise a ověřovatelů zápisu"),
  p("Starosta přednesl návrh návrhové komise a ověřovatelů zápisu."),
  h5("Návrh"),
  p("ZO schvaluje návrhovou komisi ve složení Jaroslav Mixa, Jana Laboutková."),
  h5("Návrh"),
  p("ZO schvaluje ověřovatele zápisu ve složení Petr Dub, Václav Zíta."),
  vote(V8),

  h3("3) Zpráva kontrolního výboru"),
  p("Předseda kontrolního výboru Martin Jiřička seznámil se zprávou o kontrole ze dne 22.12.2022."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí Zprávu kontrolního výboru ze dne 22.12.2022."),

  h3("4) Rozpočtová opatření"),
  h4("Rozpočtové opatření č.10/2021"),
  p("Informace starosty: Obdrželi jsme na základě žádosti o platbu v roce 2021, a to na základě zaplacených faktur poměrnou část dotace na zateplení ZŠ v částce 815,81 tisíc Kč. Tato dotace byla zahrnuta do příjmů a výdajů, k finančním prostředkům souvisejícím s dotací byl dále přiřazen Nástroj a zdroj."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí a schvaluje rozpočtové opatření č. 10/2021."),
  vote(V8),
  h4("Rozpočtové opatření č. 1/2022"),
  p("Informace člena Finančního výboru Petra Duba k rozpočtovému opatření č. 2/2022."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje rozpočtové opatření č. 1/2022."),
  vote(V8),

  h3("5) Rekonstrukce hlavního vodovodního přivaděče pod viaduktem v Krhanicích"),
  p("Informace starosty: Podali jsme žádost o dotaci na chodník k viaduktu. Zároveň je potřebné vyřešit rekonstrukci hlavního přivaděče pitné vody do obce Krhanice pod křižovatkou směrem pod viaduktem až do odbočení k Dlážděnce. Finanční nákladovost akce je cca 3 116 tisíc Kč. Vhodná dotace je na Středočeském kraji: Program 2022 pro poskytování dotací z rozpočtu Středočeského kraje ze Středočeského Infrastrukturního fondu v rámci Tematického zadání Drobné vodohospodářské projekty"),
  p("Budeme žádat o maximální částku a to je 1 mil. Kč."),
  h5("Rozprava"),
  p("R.Novotný: Dotaz, jak dlouho se bude vodovod dělat, aby to neomezilo zásobování Krhanic? Starosta: Nyní je předčasné se o tom bavit. Zatím jsme požádali jenom o dotaci."),
  h5("Návrh"),
  p("ZO schvaluje podání žádosti o dotaci na Středočeský kraj v rámci programu Program 2022 pro poskytování dotací z rozpočtu Středočeského kraje ze Středočeského Infrastrukturního fondu v rámci Tematického zadání Drobné vodohospodářské projekty pro projekt Rekonstrukce hlavního vodovodního přivaděče do obce Krhanice a souhlasí s podmínkami dotace a finanční spoluúčastí obce."),
  vote(V8),

  h3("6) Koupě, prodej, pronájem"),
  ...ul(["pronajmout část pozemku parc.č. 224/4 k.ú. Krhanice o výměře 1 m² od 1.3.2022 do 28.2.2026 za cenu 1,- Kč/1 m2/rok za účelem propagace činnosti spolku."]),
  p("Informace starosty: Jedná se o žádost Unie rodičů při ZŠ Krhanice, která na vývěsce u základní školy chce propagovat svoji činnost. Předchozí nájemce OSANN ukončil pronájem."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronajmout část pozemku parc.č. 224/4 k.ú. Krhanice o výměře 1 m² od 1.3.2022 do 28.2.2026 za cenu 1,- Kč/1 m2/rok za účelem propagace činnosti Unie rodičů ZŠ Krhanice, z.s., Krhanice 149, 257 42 Krhanice, IČO: 22877177."),
  vote(V8),
  ...ul(["uzavření smlouvy o zřízení věcného břemene – uložení vodovodní přípojky pro pozemek parc.č. 127/7 k.ú. Krhanice na pozemcích parc.č. 128/9 a 127/8 Krhanice na dobu neurčitou za cenu 6.000,- Kč"]),
  p("Informace starosty: Jedná se věcná břemeno na vodovodní přípojku k nemovitosti Krhanice č.ev. 177."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření smlouvy o zřízení věcného břemene – uložení vodovodní přípojky pro pozemek parc.č. 127/7 k.ú. Krhanice na pozemcích parc.č. 128/9 a 127/8 Krhanice na dobu neurčitou za cenu 6.000,- Kč s Monikou Víškovou, Jílovská 261, 257 41 Týnec nad Sázavou."),
  vote(V8),
  ...ul(["odkup části pozemku místní komunikace – parc.č. 109/8 k.ú. Krhanice"]),
  p("Informace starosty: Obec Krhanice odkoupí část pozemku přístupové komunikace k nemovitostem ke Štěpánům a ke Kozlům, třetí odbočení vlevo z hlavní silnice nad obecním úřadem. Oddělená část pozemku má 103 m². Nabídková cena je 450 Kč za 1 m². Celkem 46.350,- Kč."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje odkoupení pozemku parc.č. 109/13 k.ú. Krhanice, který vznikne oddělením z pozemku parc.č. 109/8 k.ú. Krhanice na základě geometrického plánu č. 1040-22969/2020 o výměře 103 m² za cenu 450,- Kč/1 m² od Aleše Kozla, Krhanice 88, 257 42 Krhanice."),
  vote(V8),
  ...ul(["předkupní právo ke koupi nemovitosti Krhanice č.ev. 34 na obecním pozemku parc.č. st.p. 474"]),
  p("Informace starosty: Obec Krhanice vlastní stavební pozemek, na kterém stojí chata číslo evidenční 34. Majitelka chce chatu prodat a ze zákona ji musí přednostně nabídnout obci Krhanice. Obec Krhanice toto předkupní právo nevyužije."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje vzdání se předkupního práva ke koupi nemovitosti Krhanice č. ev. 34 na pozemku parc.č. st.p. 474 k.ú. Krhanice ve vlastnictví obce Krhanice."),
  vote(V8),

  h3("7) Různé"),
  h4("Automobily od Policie ČR – Ministerstva vnitra České republiky, se sídlem Nad Štolou 936/3, 170 34 Praha 7, zastoupeného Správou logistického zabezpečení Policejního prezidia ČR pro JSDHO Krhanice"),
  p("Informace T.Kratochvíla (zastupitel a zároveň člen zásahové jednotky): Jedná se o automobily Renault Trafic a VW Transporter od Ministerstva vnitra ČR – Policejního prezidia – pro zásahovou jednotku hasičů Krhanice (JSDHO) – obměna a doplnění. Požádali jsme o dva. Nevíme, zda je dostaneme oba nebo alespoň jeden."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje bezúplatný převod majetku (Renault Trafic a VW Transporter) pro JSDHO Krhanice od Ministerstva vnitra České republiky, se sídlem Nad Štolou 936/3, 170 34 Praha 7, zastoupeného Správou logistického zabezpečení Policejního prezidia ČR."),
  vote(V8),
  h4("Podmínky pronájmu klubovny zázemí víceúčelového hřiště na jednorázové akce nepravidelného charakteru"),
  p("Informace starosty: Klubovna je primárně pro základní školu, mateřskou školu a obecní úřad. V klubovně jsou pro místní spolky možné akce charakteru kulturního, besedy a přednášky. Pronájem je za symbolickou 1 korunu českou a náklady za elektrickou energii, vodu a splaškové vody. Starosta přečetl podmínky."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Podmínky krátkodobého jednorázového pronájmu klubovny zázemí víceúčelového hřiště."),
  vote(V8),
  h4("Několika větami"),
  p("Zpráva starosty, co proběhlo, …"),
  h4("Dotace „Rekonstrukce hrobu rudoarmějců na hřbitově v Krhanicích“"),
  p("Informace starosty: K podání žádosti o dotaci na Rekonstrukci hrobu rudoarmějců na hřbitově v Krhanicích, kterou jsme schválili v prosinci 2021, je třeba dle požadavku poskytovatele dotace schválit, že se jedná o investiční akci."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje investiční záměr realizace akce Rekonstrukci hrobu rudoarmějců na hřbitově v Krhanicích při podání žádosti o dotaci na Rekonstrukci hrobu rudoarmějců na hřbitově v Krhanicích z programu 107290 – Zachování a obnova historických hodnot I, Česká republika – Ministerstvo obrany v rámci IV. Výzvy k podání žádosti o dotaci na zabezpečení péče o válečné hroby (čj. MO 278239/2021-7460)."),
  vote(V8),
  h4("Výroční zpráva o Poskytování informací podle zákona č.10611999 Sb., o svobodném přístupu k informacím za rok 2021"),
  p("Informace starosty: V roce 2021 nebyla podána žádná žádost o informace dle zákona č. 106/1999 Sb."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí Zprávu o poskytování informací podle zákona č.10611999 Sb., o svobodném přístupu k informacím za rok 2021."),
  h4("Inventarizační zpráva obce Krhanice za rok 2021"),
  p("Předseda inventarizační komise Aleš Papoušek přečetl inventarizační zprávu o proběhlé inventarizaci za rok 2021."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Inventarizační zprávu obce Krhanice za rok 2021."),
  vote(V8),
  h4("Zpráva Obecní knihovny Krhanice za rok 2021"),
  p("Informace: Starosta seznámil se zprávou obecní knihovny Krhanice za rok 2021."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí Zprávu Obecní knihovny Krhanice za rok 2021."),
  h4("Kontrola poskytnutí dotace na Zázemí víceúčelového hřiště ze strany Středočeského kraje"),
  p("Informace starosty: Dne 19.1.2022 proběhla kontrola hospodaření s veřejnými prostředky z poskytnuté dotace na akci Zázemí víceúčelového hřiště Krhanice ze strany Středočeského kraje s výsledkem – bez zjištěných nedostatků."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí kontrolu hospodaření s veřejnými prostředky z poskytnuté dotace na akci Zázemí víceúčelového hřiště Krhanice ze strany Středočeského kraje s výsledkem – bez zjištěných nedostatků."),
  h4("Posázavský vodovod – dobrovolný svazek obcí"),
  p("Posázavský vodovod – DSO je novým dobrovolným svazkem obcí, vytvořeným v r. 2022, kterého jsme členy. Byl nám předložen návrh rozpočtu pro rok 2022 a návrh Střednědobého výhledu rozpočtu 2023-2025. Standardní postup – schválíme jako i ostatní obce."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje rozpočet Posázavského vodovodu – dobrovolného svazku obcí, Masarykovo náměstí 194,254 01 Jílové u Prahy, IČ: 14117223 pro rok 2022, jako přebytkový."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje Střednědobý výhled rozpočtu 2023-2025 Posázavského vodovodu – dobrovolného svazku obcí, Masarykovo náměstí 194,254 01 Jílové u Prahy, IČ: 14117223."),
  vote(V8),
  h4("Úřad práce – veřejně prospěšné práce"),
  p("Informace starosty: V minulosti jsme využívali nezaměstnané z úřadu práce. Pokud tato možnost bude i letos, zaměstnali bychom opět 2 lidi z obce Krhanice v rámci veřejně prospěšných prací."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí a souhlasí s účastí obce Krhanice v rámci aktivní politiky zaměstnanosti (veřejně prospěšné práce)."),
  vote(V8),

  h3("8) Diskuse"),
  ...ul([
    "R.Novotný: Dotaz, zda se budou opravovat díry na silnici? Starosta: Nahlášeno to je. Oprava proběhne v příznivých klimatických podmínkách.",
    "P.Bydžovský: Dotaz na navýšení zeleně u areálu TJ Sokol Krhanice. O co se jedná? Starosta: Jedná se o úsek podél silnice po zatáčku. Na levé straně se vysadí podle nabídky ovocné stromy.",
    "P.Bydžovský: Částka na výsadbu je vysoká. Stromy by šly určitě pořídit levněji. Starosta: Bude se jednat o vzrostlejší stromy. Respektujeme odbornost firmy, která má dobré reference.",
    "J.Stibůrek: Dotaz na stromy. Je vhodné vysazovat ovocné stromy? Starosta: Ovocné stromy tam byly, proto je tam chceme vysadit znovu.",
    "P.Bydžovský: Budou se dělat i jiné práce než výsadba stromů? Starosta: Vyřezání a probírka porostů po obou stranách silnice. Informace byla doplněna o plánovanou realizaci vrat v zadní části areálu TJ Sokol Krhanice.",
    "J.Bydžovská: Jaký je stav obecních financí? Starosta: Počítáme s rezervou 2-3 miliony.",
    "J.Stibůrek: Jak se vyplácí solární panely na škole? Starosta: Majitel panelů platí obci za pronájem střechy.",
    "J.Stibůrek: Poznámka k Panské skále. Zda by nestálo za to zajistit vyřezání stromů kvůli výhledu. Starosta: Nevím, jak vypadá vyhlídka v současné době. Zjistím.",
    "R.Novotný: Návrh na zkultivování plochy na stání aut u lesa nad statkem. Dost lidí, kteří míří na Panskou skálu, zde parkují. Starosta: To není pozemek obce, ale Lesů ČR.",
  ]),

  h3("9) Usnesení a závěr"),
  p("Návrhová komise přečetla usnesení zastupitelstva obce."),
  vote(V8),
  p("Závěr: Zastupitelstvo obce bylo ukončeno v 18:40 hod."),

  p("Datum pořízení zápisu: 28.2.2022"),
  p("Ověřovatelé zápisu a starosta obce, podepsáno v listinné podobě."),
  h4("Přílohy"),
  ...nl(["Svolání zastupitelstva obce", "Prezenční listina zastupitelů", "Prezenční listina občanů", "Záměry"]),
];

async function run() {
  const r = await publishZapis({
    cislo: "1",
    rok: "2022",
    isoDate: "2022-02-21",
    dateLabel: "21. 2. 2022",
    fullDateDot: "21.2.2022",
    pdfPath: "scripts/zapisy-pdf/zapis-2022-1.pdf",
    transcript,
  });
  console.log("OK", r.docId, "blocks", r.blocks);
}
run().catch((e) => { console.error(e); process.exit(1); });
