/* eslint-disable no-console */
// One-off: faithful, visually-transcribed import of Zápis č. 5/2023 (15.12.2023).
import { h3, h4, h5, p, vote, nl, ul, publishZapis, type Block } from "../zapis-lib";

const V9 = "PRO ( 9 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )";

const transcript: Block[] = [
  h4("Přítomni"),
  p("Aleš Papoušek, Jaroslav Mixa, Tomáš Kratochvíl, Martin Jiřička, Jana Laboutková, Petr Dub, Aleš Kozel, Lucie Maršíková, Hana Strnadová"),

  h3("1) Zahájení, přivítání přítomných, konstatování přítomnosti"),
  p("Starosta konstatoval, že zasedání bylo svoláno dne 27.11.2023, bylo vyvěšeno na úřední desce obecního úřadu, tj. tedy nejméně 7 dní před zasedáním. Bylo tedy svoláno řádně a včas v souladu se zákonem o obcích v platném znění. Starosta konstatoval, že podle prezenční listiny je přítomno 9 členů zastupitelstva, tedy nadpoloviční většina členů zastupitelstva. K předchozímu zápisu nebyly vzneseny námitky."),
  h5("Určení zapisovatele"),
  p("Zápisem zasedání zastupitelstva obce byla pověřena Ing. Alena Kratochvílová."),

  h3("2) Volba návrhové komise a ověřovatelů zápisu"),
  p("Starosta přednesl návrh návrhové komise a ověřovatelů zápisu."),
  h5("Návrh"),
  p("ZO schvaluje návrhovou komisi ve složení: Jaroslav Mixa, Jana Laboutková."),
  h5("Návrh"),
  p("ZO schvaluje ověřovatele zápisu ve složení Petr Dub, Tomáš Kratochvíl."),
  vote(V9),

  h3("3) Schválení programu"),
  p("Starosta přečetl program."),
  ...nl([
    "Volba návrhové komise a ověřovatelů zápisu",
    "Schválení programu",
    "Střednědobý výhled rozpočtu obce Krhanice na období 2023–2027; Rozpočet obce Krhanice na rok 2024",
    "Rozpočtové opatření",
    "Obecně závazné vyhlášky obce",
    "Zpráva finančního výboru o kontrole hospodaření obce Krhanice v roce 2023; Zpráva o výsledcích veřejnoprávních kontrol hospodaření Mateřské školy Krhanice a Základní školy Krhanice v roce 2023",
    "Koupě, prodej, pronájem",
    "Různé",
    "Diskuse",
    "Závěr",
  ]),
  p("Starosta: Má někdo návrh na změnu nebo doplnění programu?"),
  h5("Návrh"),
  p("ZO schvaluje program zasedání zastupitelstva obce."),
  vote(V9),

  h3("3) Střednědobý výhled rozpočtu obce Krhanice na období 2023 – 2027; Rozpočet obce Krhanice na rok 2024"),

  h4("STŘEDNĚDOBÝ VÝHLED ROZPOČTU 2023 – 2027"),
  p("Informace starosty:"),
  p("Střednědobý výhled rozpočtu je nástrojem sloužícím pro střednědobé finanční plánování rozvoje. Sestavuje se na základě uzavřených smluvních vztahů a přijatých závazků zpravidla na 2 až 5 let následujících po roce, na který se sestavuje roční rozpočet."),
  p("Střednědobý výhled rozpočtu obsahuje souhrnné základní údaje o příjmech a výdajích, o dlouhodobých závazcích a pohledávkách, o finančních zdrojích a potřebách dlouhodobě realizovaných záměrů."),
  p("U dlouhodobých závazků se uvádí dopady na hospodaření územního samosprávného celku po celou dobu trvání závazku (v našem případě splátka zápůjčky)."),
  p("Návrh střednědobého výhledu rozpočtu byl zveřejněn dne 28.11.2023."),
  p("Starosta seznámil přítomné se Střednědobým výhledem rozpočtu na období 2023 – 2027."),
  h5("Rozprava"),
  p("Proběhla diskuse, proč v dalších letech střednědobého výhledu jsou podstatně nižší příjmy a jakým způsobem je zvýšit. Nejpřesnější příjmy jsou aktuální rok a následující rok. Nedá se přesně odhadnout, jaké příjmy budou v posledních dvou letech výhledu."),
  h5("Návrh"),
  p("ZO schvaluje Střednědobý výhled rozpočtu obce Krhanice na období 2023 – 2027."),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 2 – Maršíková, Strnadová )"),

  h4("DOBROVOLNÉ SVAZKY OBCÍ: BENE-BUS, TÝNECKO-SVAZEK OBCÍ, POSÁZAVSKÝ VODOVOD - DSO"),
  p("Informace starosty: Obec je členem následujících dobrovolných svazků obcí. Byly nám zaslány následující dokumenty a v rozpočtu obce 2024 byly vyčleněny následující finanční příspěvky."),

  h4("DSO BENE-BUS"),
  p("Informace starosty: Byl nám předložen návrh Rozpočtu 2024 a návrh Střednědobého výhledu rozpočtu. Vyvěšeno dne 22.11.2023. Orgán určený ke schválení – valná hromada."),
  p("Návrh rozpočtu – přebytkový."),
  p("Příspěvek obce Krhanice pro rok 2024: 308 280,- Kč."),

  h4("TÝNECKO-SVAZEK OBCÍ"),
  p("Informace starosty: Byl nám předložen návrh Rozpočtu 2024 a návrh Střednědobého výhledu rozpočtu. Vyvěšeno dne 14.11.2023. Orgán určený ke schválení – valná hromada."),
  p("Návrh rozpočtu – vyrovnaný."),
  p("Příspěvek obce Krhanice pro rok 2024: 12 595,- Kč."),

  h4("POSÁZAVSKÝ VODOVOD – dobrovolný svazek obcí"),
  p("Informace starosty: Bylo nám předloženo Rozpočtové opatření č. 3/2023, návrh Rozpočtu 2024 a návrh Střednědobého výhledu rozpočtu. Vyvěšeno dne 27.11.2023. Orgán určený ke schválení – správní rada členů."),
  p("Návrh rozpočtu – schodkový, krytý finančními prostředky minulých let."),
  p("Příspěvek obce Krhanice pro rok 2024: bez příspěvku."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí, že Rozpočet Bene-Bus dobrovolný svazek obcí na rok 2024 je přebytkový a bere na vědomí Střednědobý výhled rozpočtu Bene-Bus dobrovolný svazek obcí na období 2025-2027."),
  h5("Návrh"),
  p("ZO bere na vědomí, že Rozpočet 2024 Týnecko-svazek obcí je vyrovnaný a bere na vědomí Střednědobý výhled rozpočtu na období 2023-2026."),
  h5("Návrh"),
  p("ZO bere na vědomí, že Rozpočet 2024 Posázavský vodovod – dobrovolný svazek obcí je schodkový a bude kryt finančními prostředky z minulých let, bere na vědomí Střednědobý výhled rozpočtu Posázavský vodovod – dobrovolný svazek obcí na období 2024-2027 a bere na vědomí Rozpočtové opatření č. 3/2023."),

  h4("ROZPOČET 2024 - FOND OBNOVY VODOVODŮ OBCÍ KRHANICE A PROSEČNICE"),
  p("Informace starosty:"),
  p("Návrh Rozpočtu Fondu obnovy vodovodů obcí Krhanice a Prosečnice byl vyvěšen 28.11.2023. Příjmy tvoří nájemné od VHS Benešov a 0,0025 % z celkové hodnoty majetku vodovodů k 31.12. předchozího kalendářního roku. Použití Fondu je na opravy vodovodů."),
  p("Návrh Rozpočtu Fondu je vyrovnaný."),
  p("Předpoklad konečného zůstatku Fondu k 31.12.2023: 223 tisíc Kč."),
  h5("Rozprava"),
  p("L.Maršíková: Dotaz, zda lze čerpat nějaké prostředky z rozpočtu Posázavský vodovod – dobrovolný svazek obcí. Starosta: Vysvětlil rozdíl mezi Sdružení obcí Posázavský vodovod a nástupnickou Posázavský vodovod – dobrovolný svazek obcí a poskytování financí."),
  h5("Návrh"),
  p("ZO schvaluje Rozpočet Fondu financování obnovy vodovodů obcí Krhanice a Prosečnice pro rok 2024 jako vyrovnaný."),
  vote(V9),

  h4("ROZPOČET OBCE KRHANICE NA ROK 2024"),
  p("Petr Dub přečetl Zápis komise pro sestavení rozpočtu 2024."),
  p("Starosta informoval o procesu sestavení návrhu rozpočtu pro rok 2024."),
  p("Starosta informoval o návrhu rozpočtu pro rok 2024."),
  p("Provozní příspěvek pro zřízené příspěvkové organizace: Základní škola Krhanice a Mateřská škola Krhanice:"),
  p("Návrh Rozpočtu a Návrh Střednědobého výhledu rozpočtu příspěvkových organizací zřízených obcí Krhanice byl vyvěšen 27.11.2023."),
  p("Návrh provozního příspěvku pro příspěvkové organizace pro rok 2024:"),
  ...ul([
    "Mateřská škola Krhanice, okres Benešov: 602 850,- Kč",
    "Základní škola Krhanice, okres Benešov: 3 668 841,- Kč",
    "v tom: Středisko Základní škola: 2 767 453,- Kč",
    "v tom: Středisko Školní jídelna: 901 388,- Kč",
  ]),
  p("Starosta: Součástí Rozpočtu 2024 je Příloha."),
  p("Přílohu Rozpočtu 2024 přečetl Martin Jiřička."),
  h5("Rozprava"),
  p("H.Strnadová: Dotaz na dotace – zda Komise pro sestavení rozpočtu a Komise pro obnovu a rozvoj obce uvažuje i o možnosti získání dotace. T.Kratochvíl: Komise pouze shromažďuje podněty a dává náměty. Starosta: Dotace sledujeme a pracujeme s nimi průběžně."),
  p("H.Strnadová: Projekt tělocvičny neodpovídá moderním parametrům. Starosta: Je požádáno o dotaci."),
  p("L.Maršíková: Dotaz, jak bude probíhat anketa na výběr dětských prvků? T.Kratochvíl: Vysvětlil, jak to mají v komisi vymyšleno."),
  p("Proběhla diskuse, proč pořizovat prvky zrovna pro nejmenší děti."),
  p("H.Strnadová: Dotaz k dotacím na kulturní akce, jakým způsobem se rozhoduje o její výši? Přispěla by obec 60 % i na velmi drahou kapelu? Starosta: Pokud si někdo pozve drahou kapelu, nedostane určitě 60 %. Všichni při žádosti uvádějí veškeré náklady. Každá žádost se zvažuje individuálně."),
  p("M.Maršík: Dotaz, zda by se některým spolkům neměla platit celá požadovaná částka (100 %)? V zahraničí tomu tak je."),
  p("Proběhla všeobecná diskuse o nákladech na akce, …. bez přijetí závěrů."),
  p("I.Dvořák: Dotaz, co je nedotační část chodníku? Starosta: Je to vybudování chodníku nad úřadem ke klempírně – parametrově to není na dotaci."),
  p("I.Dvořák: Dotaz na pitnou vodu? Starosta: Jedná se o projektovou dokumentaci na vodovod v obratišti v Prosečnici. V době sestavení rozpočtu jsme nevěděli, zda bude projektová dokumentace dokončena a vyfakturována ještě v roce 2023, nebo to spadne do roku 2024."),
  p("I.Dvořák: Dotaz na splaškové řady + kanalizaci? Starosta: Jedná se o peníze na výkup pozemků, smlouvy a situace pro majitele pozemků, …"),
  p("Proběhla diskuse o řešení splaškových řadů gravitačně, nebo tlakově."),
  p("I.Dvořák: Dotaz na sportovní zařízení obce? Starosta: Položka obsahuje částku na protihlukový plot a sjezd na hřiště z hlavní silnice."),
  p("I.Dvořák: Dotaz na nebytové prostory? Nájmy nepokryjí ani spotřebu energie. Starosta: Nebytových prostor není tolik – sklad pana Fišera na úřadě a sklad na návsi naproti hasičské zbrojnici – využívá ho obec a hasiči."),
  p("L.Maršíková: Dotaz na místní komunikaci pod lomem, zda se bude dělat i odvod dešťové vody? Starosta: Dešťová kanalizace se budovat nebude, není kam dešťové vody odvést."),
  p("L.Maršíková: Dotaz na pivní sety? Za jakých podmínek se budou poskytovat? Starosta: Hasiči si připraví podmínky zápůjčky a odsouhlasí je s obcí. T.Kratochvíl: Podmínky pronájmu budou řešit hlavně případné poškození."),
  p("L.Maršíková: Odpady, dotaz na 250 Kč jako dar občanům, zda by ho neměli pobírat jen sociálně slabší? Místostarosta: Stávající systém je v pořádku. Starosta: Nemáme přístup k datům, kdo bere sociální příspěvky."),
  p("Proběhla diskuse bez přijetí závěrů."),
  h5("Návrh"),
  p("ZO schvaluje Přílohu Rozpočtu obce Krhanice na rok 2024."),
  vote("PRO ( 7 ) – PROTI ( 2 – Maršíková, Strnadová ) – ZDRŽEL SE ( 0 )"),
  h5("Návrh"),
  p("ZO schvaluje Rozpočet obce Krhanice na rok 2024 jako schodkový. Schodek bude hrazen finančními prostředky z minulých let."),
  vote("PRO ( 7 ) – PROTI ( 2 – Maršíková, Strnadová ) – ZDRŽEL SE ( 0 )"),

  h3("4) Rozpočtové opatření"),
  h4("Rozpočtové opatření č. 10/2023"),
  p("Předseda finančního výboru Petr Dub seznámil s rozpočtovým opatřením č. 10/2023."),
  h5("Rozprava"),
  p("L.Maršíková: Kdo je dárce 100 tisíc a byl dar konkrétně určen zásahové jednotce hasičů? Starosta: Dárcem je Kámen Zbraslav. Darem chtěli poděkovat konkrétně mé osobě za jednání. Záleželo na mě, kam čerpání daru nasměruji, oblasti byly dány smlouvou, rozhodl jsem se pro zásahovou jednotku hasičů."),
  p("T.Kratochvíl: Seznámil přítomné, co vše si zásahová jednotka pořídila."),
  h5("Návrh"),
  p("ZO schvaluje rozpočtové opatření č. 10/2023."),
  vote(V9),

  h3("5) Obecně závazné vyhlášky obce"),
  p("Místostarosta seznámil se všemi vyhláškami."),
  h4("Zrušení OZV – koeficient daň z nemovitostí"),
  p("Bude zrušeno OZV obce Krhanice č. 6/2023 o stanovení místního koeficientu pro výpočet daně z nemovitých věcí schválená zastupitelstvem obce dne 15.6.2023. Je to krok pro lidi, neboť stát v rámci Konsolidačního balíčku navyšuje daň z nemovitostí lidem v průměru o 1,8 násobek. Vyhlášku jsme schvalovali, kdy daň z nemovitosti v konsolidačním balíčku nebyla."),
  h4("Nové OZV – místní poplatky"),
  p("Na základě § 14 zákona č. 565/1990 Sb., o místních poplatcích, ve znění pozdějších předpisů (dále jen „zákon o místních poplatcích“), a v souladu s § 10 písm. d) a § 84 odst. 2 písm. h) zákona č. 128/2000 Sb., o obcích (obecní zřízení), ve znění pozdějších předpisů byly předloženy k projednání tyto obecně závazné vyhlášky:"),
  ...ul([
    "Obecně závazná vyhláška obce Krhanice o místním poplatku ze psů",
    "Obecně závazná vyhláška obce Krhanice o místním poplatku ze vstupného",
    "Obecně závazná vyhláška obce Krhanice o místním poplatku za užívání veřejného prostranství včetně Přílohy č. 1 (Vyhláška + Příloha)",
  ]),
  p("Ve vyhláškách o místním poplatku ze psů, ze vstupného a za užívání veřejného prostranství dochází ke změnám:"),
  p("Poplatek ze psů – zůstává výše poplatku, ohlašovací povinnost, v souladu se změnou zákonů se změnilo „názvosloví“"),
  p("Poplatek vstupné – zůstává výše poplatku, ohlašovací povinnost, v souladu se změnou zákonů se změnilo „názvosloví“"),
  p("Poplatek veřejné prostranství – srovnání sazeb na 10,- Kč/1 m²/1 den a změna příloha č. 1 – aktualizované pozemky a jeden pozemek parc.č. 2051/7 k.ú. Krhanice vyňat."),
  ...ul([
    "Obecně závazná vyhláška obce Krhanice o místním poplatku za obecní systém odpadového hospodářství",
  ]),
  p("Ve vyhlášce o místním poplatku za obecní systém odpadového hospodářství dochází ke změně: Změny ve vyhlášce od 1.1.2024:"),
  ...ul([
    "zvýšení sazby poplatku o 100 Kč na částku 1 150 Kč,",
    "sjednocení částky úlev na částku 300 Kč pro osoby v kategoriích 2–18 let, 65 a více let a poživatel invalidního důchodu nebo držitel průkazu ZTP nebo ZTP/P,",
    "posunutí věkové hranice pro úlevy na věk 65 a více let.",
    "splatnost poplatku: nejpozději do 28. února příslušného kalendářního roku.",
  ]),
  p("Místostarosta obce Jaroslav Mixa seznámil se „Svozem komunálního odpadu v roce 2024“."),
  h5("Rozprava"),
  p("L.Maršíková: Poplatek ze vstupného nepřináší žádné velké peníze, nemohl by být pro spolky zrušen? Starosta: Za mě je v pořádku, protože musí platit pro všechny, spolky zvýhodňujeme jinak – např. zdarma pronájem veřejného prostranství, bezplatné využívání WC, elektrického proudu, …"),
  p("L.Maršíková: Hlásí se akce bez vybírání vstupného? T.Kratochvíl: Nemusí, pokud skončí před desátou hodinou večer."),
  p("J.Bydžovská: Dotaz, zda obec nemá zájem připojit místní podnikatele do svého odpadového hospodářství? Místostarosta: Mají samostatně smlouvy s TS Benešov."),
  p("L.Maršíková: Dotaz na vyhlášku z června 2023, zda platí? Proběhla diskuse se závěrem, že platí předchozí vyhláška, červnová a v tuto chvíli neplatí a od 1.1.2024 ani platit nebude."),
  h5("Návrh"),
  p("ZO schvaluje obecně závaznou vyhlášku obce Krhanice, kterou se zrušuje Obecně závazná vyhláška obce Krhanice č. 6/2023 o stanovení místního koeficientu pro výpočet daně z nemovitých věcí, ze dne 15.6.2023."),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 2 – Maršíková, Strnadová )"),
  h5("Návrh"),
  p("ZO schvaluje Obecně závaznou vyhlášku obce Krhanice o místním poplatku ze psů"),
  vote(V9),
  h5("Návrh"),
  p("ZO schvaluje Obecně závaznou vyhlášku obce Krhanice o místním poplatku ze vstupného"),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 2 – Maršíková, Strnadová )"),
  h5("Návrh"),
  p("ZO schvaluje Obecně závaznou vyhlášku obce Krhanice o místním poplatku za užívání veřejného prostranství"),
  vote("PRO ( 7 ) – PROTI ( 1 – Maršíková ) – ZDRŽEL SE ( 1 – Strnadová )"),
  h5("Návrh"),
  p("ZO schvaluje Obecně závaznou vyhlášku obce Krhanice o místním poplatku za obecní systém odpadového hospodářství"),
  vote("PRO ( 7 ) – PROTI ( 2 – Maršíková, Strnadová ) – ZDRŽEL SE ( 0 )"),
  p("V 18:02 hod. byla vyhlášena pauza do 18:15 hod."),

  h3("6) Zpráva finančního výboru o kontrole hospodaření obce Krhanice v roce 2023; Zpráva o výsledcích veřejnosprávních kontrol hospodaření Mateřské školy Krhanice a Základní školy Krhanice v roce 2023"),
  p("Petr Dub jako předseda kontrolní skupiny seznámil s proběhlými veřejnosprávními kontrolami hospodaření příspěvkových organizací Mateřské školy Krhanice a Základní školy Krhanice v roce 2023, které proběhly dne 30.10.2023."),
  p("Petr Dub jako předseda Finančního výboru obce Krhanice seznámil s kontrolou hospodaření obce Krhanice v roce 2023."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí protokoly o průběhu a výsledcích veřejnosprávních kontrol příspěvkových organizací Základní škola Krhanice a Mateřská škola Krhanice v roce 2023 ze dne 30.10.2023."),
  h5("Návrh"),
  p("ZO bere na vědomí zprávu finančního výboru o kontrole hospodaření obce Krhanice v roce 2023 ze dne 30.10.2023."),
  h5("Návrh"),
  p("ZO bere na vědomí, že spolek Aktivní Krhanice, z.s., se sídlem Krhanice č.p. 35, 257 42 Krhanice, IČO: 09017429 provedl na základě výzvy poskytovatele dotace Obce Krhanice vratku neoprávněně čerpané poměrné části poskytnuté dotace ve výši 6 250 Kč v souladu s uzavřenou veřejnoprávní smlouvou DOTAKCE/2023/04 Aktivní Krhanice – Letní kino 2023–2 produkce v souvislosti s neuskutečněním konání jedné produkce letního kina."),

  h3("7) Koupě, prodej, pronájem"),
  ...ul([
    "pronajmout část pozemku parc. č. 59/1 k.ú. Krhanice o výměře 1206 m² ke zřízení dočasné zahrádky za cenu 10,- Kč/1 m²/rok od 1.1.2024 do 31.12.2024.",
  ]),
  p("Informace starosty: Jedná se o žádost manželů Klapáčových. Pronájem na 1 rok."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronajmout část pozemku parc. č. 59/1 k.ú. Krhanice o výměře 1206 m² ke zřízení dočasné zahrádky za cenu 10,- Kč/1 m²/rok od 1.1.2024 do 31.12.2024 Janu a Jaroslavě Klapáčovým, Hennerova 3/2009, 150 00 Praha 5."),
  vote(V9),
  ...ul([
    "pronajmout část pozemku parc. č. 1957/5 k.ú. Krhanice o výměře 170 m² ke zřízení dočasné zahrádky za cenu 10,- Kč/1 m²/rok od 1.1.2024 na dobu 4 let.",
  ]),
  p("Informace starosty: Jedná se o žádost Chýlkové Aleny."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronajmout část pozemku parc. č. 1957/5 k.ú. Krhanice o výměře 170 m² ke zřízení dočasné zahrádky za cenu 10,- Kč/1 m²/rok od 1.1.2024 na dobu 4 let Aleně Chýlkové, Vinohradská 165, 100 00 Praha 10."),
  vote(V9),
  ...ul([
    "pronajmout část pozemku parc. č. 502 k.ú. Krhanice a část pozemku parc.č. 498 k.ú. Krhanice o výměře 2.700 m² od 21.12.2023 na dobu 4 let, a to k chovu ryb za účelem vsazení do řeky Sázavy za cenu 1,- Kč/1 m²/rok.",
  ]),
  p("Informace starosty: Jedná se o žádost Českého rybářského svazu, místní organizace v Týnci."),
  h5("Rozprava"),
  p("Proběhla diskuse o tom, zda se může pronajmout něco, co v katastru nemovitostí není vedeno jako rybník, ale jako travnatá plocha a o povolení vodní nádrže z roku 1994."),
  h5("Návrh"),
  p("ZO schvaluje pronajmout část pozemku parc. č. 502 k.ú. Krhanice a část pozemku parc.č. 498 k.ú. Krhanice o výměře 2.700 m² od 21.12.2023 na dobu 4 let, a to k chovu ryb za účelem vsazení do řeky Sázavy za cenu 1,- Kč/1 m²/rok Českému rybářskému svazu, z.s., místní organizaci Týnec nad Sázavou, IČO: 45064296, K Náklí 404, 257 41 Týnec nad Sázavou."),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 2 – Maršíková, Strnadová )"),
  ...ul([
    "uzavřít Smlouvu o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby č. IV-12-6034250/VB/2 BN-Krhanice-KNN-parc.č. 152/3,2 na pozemcích parc. č. 142/28 k.ú. Krhanice a parc. č. 148/18 k.ú. Krhanice s ČEZ Distribuce, a.s., IČ 24729035, DIČ CZ24729035, se sídlem Děčín IV-Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 9 300 Kč na umístění zařízení kabelového vedení.",
  ]),
  p("Informace starosty: Jedná se o zhotovení elektrického kiosku pro dvě parcely v lokalitě Na Starém hřišti."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavřít Smlouvu o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby č. IV-12-6034250/VB/2 BN-Krhanice-KNN-parc.č. 152/3,2 na pozemcích parc. č. 142/28 k.ú. Krhanice a parc. č. 148/18 k.ú. Krhanice s ČEZ Distribuce, a.s., IČ 24729035, DIČ CZ24729035, se sídlem Děčín IV-Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 9 300 Kč na umístění zařízení kabelového vedení."),
  vote(V9),
  ...ul([
    "pronajmout část pozemku parc. č. 502 k.ú. Krhanice o výměře 138 m² od 1.1.2024 na dobu 4 let, a to za účelem výstavby a udržování 3 tůní za cenu 1,- Kč/1 m²/rok.",
  ]),
  p("Informace starosty: K dnešnímu dni, 12:00 hod. obec neobdržela upravenou projektovou dokumentaci, ke které se vyjadřuje, není tedy možné řešit navazující Smlouvu o právu o provedení stavby včetně příloh pro projekt Tůně U Gabčíkova v Krhanicích se spolkem Aktivní Krhanice. Přílohou této smlouvy je finální projektová dokumentace a finální vyjádření obce Krhanice k projektové dokumentaci. Smlouva o pronájmu pozemku je podmíněna uzavřením Smlouvy o právu o provedení stavby. Z toho důvodu tento bod záměrů není možné dnes projednat. Starosta obce seznámil přítomné s dopisem č.j. 928/2023 ze dne 15.12.2023 – vyjádření k předloženému upravenému (verze 13.12.2023) projektu „TŮNĚ U GABČÍKOVA V KRHANICÍCH“."),
  h5("Rozprava"),
  p("Proběhla všeobecná diskuse o projektové dokumentaci, jejích úpravách, vyjádření obce k nim, cenách za pronájem pozemku, … Výsledkem diskuse nakonec bylo, že obec udělá vstřícný krok, že dnes proběhne hlasování alespoň o schválení smlouvy o právu provedení stavby, s tím, že bude do doby realizace stavby uzavřena smlouva o pronájmu pozemku nebo zápůjčce. Ze strany paní Maršíkové jako předsedkyně spolku Aktivní Krhanice byly odsouhlaseny změny v projektové dokumentaci na základě požadavků obce, aby mohlo být vydáno souhlasné vyjádření k takto upravené projektové dokumentaci."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o právu o provedení stavby pro projekt Tůně u Gabčíkova v Krhanicích se spolkem Aktivní Krhanice, z.s., se sídlem Krhanice č.p. 35, 257 42 Krhanice, IČO: 09017429."),
  vote("PRO ( 6 ) – PROTI ( 0 ) – ZDRŽEL SE ( 3 – Kratochvíl, Maršíková, Strnadová )"),

  h3("8) Různé"),
  h4("POJIŠTĚNÍ MAJETKU OBCE"),
  p("Starosta obce seznámil s návrh pojistné smlouvy číslo 0111115018, která nahradí původní pojistnou smlouvu číslo 0007419015 včetně všech dodatků. Smlouva má nový formát. Nová pojistná smlouva má obdobné pojistné podmínky a větší rozsah pojištění."),
  p("Výrazně navýšené pojistné částky staveb na 155.680.000 Kč dle metodiky HVP (původní pojistná hodnota staveb byla 32.470.000 Kč). Zachována nulová spoluúčast, vyjma vandalismu a přenosné elektroniky, kde je spoluúčast 1.000 Kč. Dále je navýšen limit pro pojištění Odpovědnosti za škody na 10.000.000 Kč a přidání dalších odpovědnostních pojištění, jako např. regresy zdravotních pojišťoven, odpovědnost zastupitelů."),
  p("Nadstandardní smluvní ujednání RENOMIA, naše pojištění rozšiřuje o vystoupání vody z kanalizace, přepětí, podpětí a nepřímý úder blesku, dále atmosférické srážky, poškození zvířetem nebo hmyzem, dále poškození majetku sprejery, rozšíření místa pojištění na území ČR pro mobilní elektronická zařízení, sesuv půdy, tolerance podpojištění 15 % apod."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Pojistné smlouvy č. 0111115018 náhrada PS č. 0007419015 s Hasičskou vzájemnou pojišťovnou, a.s., IČO : 46973451, se sídlem Praha 2, Římská 45, 120 00, Česká republika"),
  vote(V9),
  h4("SOUHLAS SE VZNIKEM PRACOVNĚPRÁVNÍCH VZTAHŮ ZASTUPITELŮ"),
  p("Dle zákona č. 128/2000 Sb., o obcích, § 84 odst. 2 písm. p) je zastupitelstvu obce vyhrazeno vyslovovat souhlas se vznikem pracovněprávního vztahu mezi obcí a členem zastupitelstva obce. Protože takové pracovně právní vztahy jsou reálné, následuje jejich výčet:"),
  ...ul([
    "oblast Činnosti knihovnické: Bc. Petr Dub.",
  ]),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje a souhlasí se vznikem pracovněprávních vztahů mezi obcí a členem zastupitelstva obce s platností od 1.1.2024 do 31.12.2024, a to oblast Činnosti knihovnické: Bc. Petr Dub. Dohody budou uzavírány v průběhu roku 2024 dle konkrétních potřeb obce."),
  vote("PRO ( 8 ) – PROTI ( 0 ) – ZDRŽEL SE ( 1 - Dub )"),
  h4("KRHANICE – REKONSTRUKCE VEŘEJNÉHO OSVĚTLENÍ"),
  p("Informace starosty: Výběrové řízení bylo realizováno s Posázaví o.p.s. Dle dotačních podmínek byly osloveny tři firmy. Výběrové řízení proběhlo v pondělí 11.12.2023. Nabídku podaly dvě firmy. Hodnotícím kritériem byla nejnižší nabídková cena."),
  p("Výsledek:"),
  ...ul([
    "1. Yunex, s.r.o., IČ/RČ 09962638, nabídková cena v Kč bez DPH: 2 142 361,00",
    "2. DĚDIC-Elektromontáže s.r.o., IČ/RČ 02623650, nabídková cena v Kč bez DPH: 2 240 659,00",
  ]),
  p("Nejvhodnější nabídkou, tj. nabídkou nejlépe splňující kritérium stanovené zadavatelem v textu zadávací dokumentace pro zakázku malého rozsahu mimo režim zákona č. 134/2016 Sb., o zadávání veřejných zakázek k zakázce „Krhanice – rekonstrukce veřejného osvětlení“ je nabídka účastníka:"),
  p("obchodní firma/jméno: Yunex, s.r.o., , se sídlem"),
  p("sídlo / místo podnikání: V parku 2308/8, 148 00 Praha 11 – Chodov"),
  p("IČO: 09962638"),
  p("Nabídková cena bez DPH: 2 142 361,00 Kč"),
  p("DPH: 449 896,00 Kč"),
  p("Nabídková cena s DPH: 2 592 256,00 Kč"),
  p("Úspora 138 tisíc Kč oproti dotačnímu rozpočtu."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření smlouvy o dílo na akci Krhanice – rekonstrukce veřejného osvětlení s firmou Yunex, s.r.o., IČO: 09962638, se sídlem V parku 2308/8, 148 00 Praha 11 – Chodov na celkovou částku 2.592.256 Kč s DPH."),
  vote(V9),
  h5("Návrh"),
  p("ZO pověřuje starostu obce uzavřením a podpisem smlouvy o dílo na akci Krhanice – rekonstrukce veřejného osvětlení s firmou Yunex, s.r.o., IČO: 09962638, se sídlem V parku 2308/8, 148 00 Praha 11 – Chodov."),
  vote(V9),
  h4("CHODNÍK – VÝBĚROVÉ ŘÍZENÍ"),
  p("Informace starosty: V souvislosti se stavbou chodníku k viaduktu ještě nevíme, zda v žádosti o dotaci na Státním fondu dopravní infrastruktury jsme uspěli či neuspěli. Pokud ne, budeme realizovat chodník z rozpočtu obce. K tomu využijeme plánované uzavření křižovatky duben – červenec 2024. Bude to i dobře z hlediska bezpečnosti chodců, neboť při chůzi ke školce, škole, na sportoviště či fotbalové hřiště budou moci jít po pravé straně směrem od viaduktu."),
  p("Připravíme výběrové řízení poptávkou po čtyřech firmách, které v obci dlouhodobě působí a máme s nimi bezproblémové zkušenosti."),
  p("Rozpočet je z podané žádosti o dotaci. Rozpočtář zhotovil rozpočet přes celou akci. Výsledná částka za dílo cca 6 mil. 710 tisíc. Pokud nedojde k nějakým zásadním změnám na v oblasti stavebnictví, cen pohonných hmot, … vysoutěženou částku předpokládáme nižší. Výběrové řízení je již bez veřejného osvětlení, které je již realizováno."),
  p("Výběrové řízení vypíšeme tak, abychom na dalším zastupitelstvu mohli schvalovat vítěznou firmu."),
  p("Poptávané firmy:"),
  ...ul([
    "1) Rudolf Pospíšil, Havlíčkova 1563, 258 01 Vlašim, IČO: 63827735",
    "2) LAROS s.r.o., Jana Nohy 1285, 256 01 Benešov, IČO: 49826514",
    "3) Zdeněk Makovíni, Krhanice 193, 257 42 Krhanice, IČO: 74225740",
    "4) Jaroslav Žaba, Pecerady 69, 257 41 Týnec nad Sázavou, IČO: 86934431",
  ]),
  p("Spolupracovat na výběrovém řízení budeme s Posázaví, o.p.s."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO pověřuje starostu obce realizací výběrového řízení na projekt „Krhanice - chodník podél silnice III/1066“ ve spolupráci s Posázavím o.p.s., Zámek Jemniště 1, 257 01 Postupice, IČO 27129772."),
  vote(V9),
  h4("OBECNÍ KNIHOVNA KRHANICE"),
  p("Informace starosty: Návrh v pokračování v roce 2024 s osvobozením od placení registračního poplatku."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Dodatek č. 14 k Příloze č. 1 Knihovního řádu Obecní knihovny Krhanice Výpůjční řád."),
  vote(V9),

  h3("9) Diskuse"),
  ...ul([
    "R.Novotný: Dotaz, jak to vypadá s krhanickou poštou? Zda bude zrušena. Proběhla diskuse o využívání pošty v Chrástu nad Sázavou a v Týnci nad Sázavou bez přijetí závěrů.",
    "I.Kratochvílová: Za SDH Krhanice poděkovala za podporu ze strany obce. Pokud si spolky vymýšlí různé akce, není povinností obce je financovat.",
    "I.Kratochvílová: Za zásahovou jednotku hasičů poděkovala za podporu ze strany obce a poděkovala za finanční dar pro zásahovou jednotku hasičů.",
    "I.Kratochvílová: Popřála všem krásné vánoční svátky.",
  ]),
  p("Starosta: Přání bylo tak hezké, že už netřeba nic dodávat. Nashledanou v příštím roce."),

  h3("10) Usnesení a závěr"),
  p("Zastupitelstvo obce bylo ukončeno v 19:40 hod."),

  p("Datum pořízení zápisu: 20.12.2023"),
  p("Ověřovatelé zápisu a starosta obce, podepsáno v listinné podobě."),
  h4("Přílohy"),
  ...nl([
    "Svolání zastupitelstva obce",
    "Prezenční listina zastupitelů",
    "Prezenční listina občanů",
  ]),
];

async function run() {
  const r = await publishZapis({
    cislo: "5",
    rok: "2023",
    isoDate: "2023-12-15",
    dateLabel: "15. 12. 2023",
    fullDateDot: "15.12.2023",
    pdfPath: "scripts/zapisy-pdf/zapis-2023-5.pdf",
    transcript,
  });
  console.log("OK", r.docId, "blocks", r.blocks);
}
run().catch((e) => { console.error(e); process.exit(1); });
