/* eslint-disable no-console */
// Faithful, visually transcribed minutes of Zápis č. 2/2023 (15.6.2023),
// 16 pages, read page-by-page from the official PDF (corrupt text layer).
import { h3, h4, h5, p, vote, nl, ul, publishZapis, type Block } from "../zapis-lib";

const V8 = "PRO ( 8 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )";

const transcript: Block[] = [
  h4("Přítomni"),
  p("Aleš Papoušek, Tomáš Kratochvíl, Aleš Kozel, Jana Laboutková, Petr Dub, Lucie Maršíková, Hana Strnadová"),
  h4("Omluveni"),
  p("Jaroslav Mixa, Martin Jiřička – přijde později"),

  h3("1) Zahájení, přivítání přítomných, konstatování přítomnosti"),
  p("Starosta konstatoval, že zasedání bylo svoláno dne 19.5.2023, bylo vyvěšeno na úřední desce obecního úřadu, tj. tedy nejméně 7 dní před zasedáním. Bylo tedy svoláno řádně a včas v souladu se zákonem o obcích v platném znění. Starosta konstatoval, že podle prezenční listiny je přítomno 7 členů zastupitelstva, tedy nadpoloviční většina členů zastupitelstva. K předchozímu zápisu nebyly vzneseny námitky."),
  h5("Určení zapisovatele"),
  p("Zápisem zasedání zastupitelstva obce byla pověřena Ing. Alena Kratochvílová."),

  h3("2) Volba návrhové komise a ověřovatelů zápisu"),
  p("Starosta přednesl návrh návrhové komise a ověřovatelů zápisu."),
  h5("Návrh"),
  p("ZO schvaluje návrhovou komisi ve složení: Jana Laboutková, Petr Dub."),
  h5("Návrh"),
  p("ZO schvaluje ověřovatele zápisu ve složení Aleš Kozel, Tomáš Kratochvíl."),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )"),

  h3("3) Schválení programu"),
  p("Starosta přečetl program."),
  ...nl([
    "Zahájení",
    "Volba návrhové komise a ověřovatelů zápisu",
    "Schválení programu",
    "Složení slibu zastupitele obce Krhanice",
    "Zpráva finančního výboru o kontrole hospodaření obce Krhanice za rok 2022; Zpráva o výsledcích veřejnosprávních kontrol hospodaření Mateřské školy Krhanice a Základní školy Krhanice za rok 2022",
    "Schválení účetní závěrky Mateřské školy Krhanice a Základní školy Krhanice za rok 2022",
    "Schválení účetní závěrky obce Krhanice za rok 2022",
    "Závěrečný účet obce Krhanice pro rok 2022",
    "Rozpočtová opatření",
    "Vyhlášky obce Krhanice",
    "Koupě, prodej, pronájem",
    "Různé",
    "Diskuse",
    "Usnesení a závěr",
  ]),
  p("Starosta: Má někdo návrh na změnu nebo doplnění programu?"),
  h5("Návrh"),
  p("ZO schvaluje program zasedání zastupitelstva obce."),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )"),

  h3("4) Složení slibu zastupitele obce Krhanice"),
  p("Starosta oznámil rezignaci zastupitele Bc. Ivana Dvořáka."),
  p("Starosta přivítal Ing. Hanu Strnadovou, která jako náhradník z kandidátní listiny téže volební strany bude budoucí zastupitelkou obce."),
  h4("Složení slibu člena zastupitelstva"),
  p("Starosta v souladu s § 69 odst. 2 zákona o obcích vyzval Ing. Hanu Strnadovou ke složení slibu. Před složením slibu starosta upozornil, že odmítnutí složit slib nebo složení slibu s výhradou má za následek zánik mandátu (§ 55 zákona č. 491/2001 Sb., o volbách do zastupitelstev obcí a o změně některých zákonů, v platném znění)."),
  p("Složení slibu proběhlo tak, že starosta přečetl slib stanovený v § 69 odst. 2 zákona o obcích:"),
  p("„Slibuji věrnost České republice. Slibuji na svou čest a svědomí, že svoji funkci budu vykonávat svědomitě, v zájmu obce a jejích občanů a řídit se Ústavou a zákony České republiky.“"),
  p("a vyzval Ing. Hanu Strnadovou ke složení slibu pronesením slova „slibuji“ a podpisem na připraveném archu. Ing. Hana Strnadová neodmítla složit slib, ani nesložila slib s výhradou."),
  p("Starosta: Nyní musíme projednat výši a datum vyplácení odměny nové neuvolněné zastupitelce. Nařízení vlády, kterým se mění nařízení vlády č. 318/2017 Sb., o výši odměn členů zastupitelstev územních samosprávných celků, ve znění nařízení vlády č. 202/2018 Sb. Výše odměny 1083,- Kč dle schválených částek odměn na Zastupitelstvu obce č. 6/2022 dne 7.11.2022. Datum navrhuji: od 16.6.2023."),
  h5("Návrh"),
  p("ZO schvaluje v souladu s usnesením Zastupitelstva obce č. 6/2022 ze dne 7.11.2022 výši odměny neuvolněné člence zastupitelstva Haně Strnadové: člen zastupitelstva : 1 083,- Kč, a to s platností od 16.6.2023."),
  vote("PRO ( 6 ) – PROTI ( 0 ) – ZDRŽEL SE ( 1 - Strnadová )"),

  h3("5) Zpráva finančního výboru o kontrole hospodaření obce Krhanice za rok 2022; Zpráva o výsledcích veřejnosprávních kontrol hospodaření Mateřské školy Krhanice a Základní školy Krhanice za rok 2022"),
  p("Přišel zastupitel Martin Jiřička – 18:06 hod."),
  p("Předseda finančního výboru Petr Dub seznámil s kontrolou hospodaření obce Krhanice za rok 2022 ze dne 26.4.2023. A dále seznámil s proběhlými veřejnosprávními kontrolami hospodaření příspěvkových organizací Mateřské školy Krhanice a Základní školy Krhanice. Kontroly proběhly dne 26.4.2023."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí zprávu finančního výboru o kontrole hospodaření obce Krhanice za rok 2022 ze dne 26.4.2023."),
  h5("Návrh"),
  p("ZO bere na vědomí protokoly o průběhu a výsledcích veřejnosprávních kontrol příspěvkových organizací Základní škola Krhanice a Mateřská škola Krhanice za rok 2022 ze dne 26.4.2023."),

  h3("6) Schválení účetní závěrky Mateřské školy Krhanice a Základní školy Krhanice za rok 2022"),
  h4("Mateřská škola Krhanice"),
  p("Starosta (zřizovatel) seznámil přítomné se Zprávou zřizovatele k podkladům pro schválení účetní závěrky příspěvkové organizace Mateřská škola Krhanice, okres Benešov za rok 2022."),
  p("Starosta (zřizovatel) doporučuje na základě této zprávy přijmout tento návrh usnesení zastupitelstva ve věci schválení účetní závěrky Mateřské školy v tomto znění:"),
  p("ZO schvaluje účetní závěrku příspěvkové organizace Mateřská škola Krhanice, okres Benešov za rok 2022; schvalovaná účetní závěrka poskytuje věrný a poctivý obraz předmětu účetnictví a finanční situace účetní jednotky."),
  p("Starosta přečetl „Protokol o schvalování účetní závěrky za rok 2022 příspěvkové organizace Mateřská škola Krhanice, okres Benešov“."),
  p("Ředitelka Mateřské školy Krhanice sdělila, že se k protokolu vyjádří písemně."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje účetní závěrku příspěvkové organizace Mateřská škola Krhanice, okres Benešov za rok 2022; schvalovaná účetní závěrka poskytuje věrný a poctivý obraz předmětu účetnictví a finanční situace účetní jednotky."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje Protokol o schvalování účetní závěrky za rok 2022 příspěvkové organizace Mateřská škola Krhanice, okres Benešov."),
  vote(V8),
  h4("Základní škola Krhanice"),
  p("Starosta (zřizovatel) seznámil přítomné se Zprávou zřizovatele k podkladům pro schválení účetní závěrky příspěvkové organizace Základní škola Krhanice, okres Benešov za rok 2022."),
  p("Starosta (zřizovatel) doporučuje na základě této zprávy přijmout tento návrh usnesení zastupitelstva ve věci schválení účetní závěrky Základní školy v tomto znění:"),
  p("ZO schvaluje účetní závěrku příspěvkové organizace Základní škola Krhanice, okres Benešov za rok 2022; schvalovaná účetní závěrka poskytuje věrný a poctivý obraz předmětu účetnictví a finanční situace účetní jednotky."),
  p("Starosta přečetl „Protokol o schvalování účetní závěrky za rok 2022 příspěvkové organizace Základní škola Krhanice, okres Benešov“."),
  p("Ředitelka Základní školy Krhanice sdělila, že se k protokolu vyjádří písemně."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje účetní závěrku příspěvkové organizace Základní škola Krhanice, okres Benešov za rok 2022; schvalovaná účetní závěrka poskytuje věrný a poctivý obraz předmětu účetnictví a finanční situace účetní jednotky."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje rozdělení hospodářského výsledku příspěvkové organizace Základní škola Krhanice za rok 2022 ve výši 30.480,82 Kč do rezervního fondu."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje Protokol o schvalování účetní závěrky za rok 2022 příspěvkové organizace Základní škola Krhanice, okres Benešov."),
  vote(V8),

  h3("7) Schválení účetní závěrky obce Krhanice za rok 2022"),
  p("Petr Dub seznámil přítomné se Zprávou Finančního výboru obce Krhanice k podkladům pro schválení účetní závěrky obce Krhanice za rok 2022."),
  p("Finanční výbor doporučuje na základě této zprávy přijmout tento návrh usnesení zastupitelstva ve věci schválení účetní závěrky obce Krhanice v tomto znění:"),
  p("ZO schvaluje účetní závěrku obce Krhanice, okres Benešov za rok 2022; schvalovaná účetní závěrka poskytuje věrný a poctivý obraz předmětu účetnictví a finanční situace účetní jednotky."),
  p("Finanční výbor dále doporučuje schválit výsledek hospodaření ve schvalovacím řízení za rok 2022 obce Krhanice v částce + 11 145 494,44 Kč a jeho převod na účet 432 výsledek hospodaření předchozích účetních období."),
  p("Saldo hospodařeníobce za rok 2022: - 3 653 980,69 Kč (příjmy menší než výdaje)"),
  p("Starosta přečetl „Protokol o schvalování účetní závěrky za rok 2022 obce Krhanice“."),
  h5("Rozprava"),
  p("I.Dvořák: Došlo k doplnění nějakých Fondů: Starosta: Pouze Fondu na obnovu vodovodů obcí Prosečnice a Krhanice."),
  h5("Návrh"),
  p("ZO schvaluje účetní závěrku obce Krhanice za rok 2022; schvalovaná účetní závěrka poskytuje věrný a poctivý obraz předmětu účetnictví a finanční situace účetní jednotky."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje výsledek hospodaření ve schvalovacím řízení za rok 2022 obce Krhanice a jeho převod na účet 432 výsledek hospodaření předchozích účetních období."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje Protokol o schvalování účetní závěrky za rok 2022 obce Krhanice."),
  vote(V8),

  h3("8) Závěrečný účet obce Krhanice pro rok 2022"),
  p("Starosta seznámil se Závěrečným účtem obce Krhanice pro rok 2022."),
  p("Návrh Závěrečného účtu včetně příloh byl vyvěšen na úřední desce a elektronické úřední desce dne 3.5.2023. Závěrečný účet obsahuje přehled hospodaření obce za rok 2022, hospodaření zřízených příspěvkových organizací za rok 2022 a Zprávu z celkového přezkoumání hospodaření obce za rok 2022. V Závěrečném účtu jsou obsaženy údaje o plnění rozpočtu příjmů a výdajů v plném členění podle rozpočtové skladby, údaje o hospodaření s majetkem a o dalších finančních operacích, včetně tvorby a použití peněžních fondů. Součástí závěrečného účtu je vyúčtování finančních vztahů ke státnímu rozpočtu, rozpočtům krajů, obcí, státním fondům a jiným rozpočtům a k hospodaření dalších osob."),
  p("Závěrečný účet za rok 2022 bude vyvěšen až do doby schválení nového Závěrečného účtu za rok 2023. Písemné připomínky k závěrečnému účtu nebyly podány."),
  p("Starosta: „Má někdo z přítomných připomínky k závěrečnému účtu obce?“"),
  p("Bez připomínek – přistoupíme k hlasování."),
  h5("Návrh"),
  p("ZO schvaluje Závěrečný účet obce Krhanice za rok 2022 a dává souhlas s celoročním hospodařením, a to bez výhrad."),
  vote(V8),

  h3("9) Rozpočtová opatření"),
  h4("Rozpočtové opatření č. 4/2023 a č. 5/2023"),
  p("Starosta obce seznámil s rozpočtovými opatřeními č. 4/2023 a č. 5/2023 provedenými v souladu se schválenými pravidly ze dne 22.12.2022."),
  p("Č. 4/2023: dotace Rekonstrukce památníku obětem 2.světové války – rozpočtována příjmová položka dotace."),
  p("Č. 5/2023: dotace Operační program Jan Amos Komenský – průtoková dotace pro Základní školu, – rozpočtována příjmová položka dotace a ve výdajích transfer ZŠ. Dotace bude použita na další vzdělávání pedagogických pracovníků a inovativní vzdělávání."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí rozpočtové opatření č. 4/2023 a č. 5/2023."),

  h4("Rozpočtové opatření č. 6/2023"),
  p("Před přednesením rozpočtového opatření Petrem Dubem seznámil starosta s dílčími požadavky na rozpočet:"),

  h5("STAVEBNÍ DOZOR – CHODNÍK OKRUŽNÍ KŘIŽOVATKA"),
  p("Starosta seznámil s nabídkou na výkon technického dozoru pro akci Krhanice – Okružní křižovatka silnic, část 2 – chodníky a další SO předloženou Ing. Jaroslavem Mikynou v částce 65.000,- Kč. Jedná se o cenu obvyklou. S Ing. Mikynou dlouhodobě spolupracujeme, dělá nám stavební dozor na různých stavebních akcích."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Ing. Jaroslava Mikynu jako technický dozor pro akci Krhanice – Okružní křižovatka silnic, část 2 – chodníky a další SO a schvaluje uzavření smlouvy na výkon technického dozoru v částce 65 000,- Kč."),
  vote(V8),

  h5("PRAVIDLA STAROSTA – POSKYTOVÁNÍ NEINVESTIČNÍCH DARŮ"),
  p("Starosta: Obrátili se na mě organizátoři Krhanice Open Air, kteří chtějí podpořit Rytmus Benešov. Byl jsem osloven, zda by obec poskytla Rytmusu Střední Čechy, o.p.s. finanční částku ve výši 5% ze všech prodaných vstupenek. To je možné v případě, že se v rozpočtu vyčlení finanční částka a stanoví se k ní pravidla poskytování, se kterou bude disponovat starosta. Obec každoročně finančně podporuje různé spolky, organizace, obecně prospěšné společnosti, … Rytmus Střední Čechy, o.p.s. obdržel v roce 2023 částku 3.000,- Kč."),
  h5("Rozprava"),
  p("M.Maršík: Dovysvětlil za organizátory akce, jak si svoji podporu představují."),
  p("L.Maršíková: Kam jdou peníze, které obec vybere z prodeje vstupenek na ostatních akcích? Starosta: Na podporu činnosti spolků v obci."),
  p("Starosta seznámil s návrhem pravidel pro poskytování neinvestičních darů. V rozpočtu by byla vyčleněna částka 10 tisíc Kč. Dary by byly poskytovány v souladu se zákonem č. 128/2000 Sb. o obcích."),
  h5("Návrh"),
  p("ZO schvaluje Pravidla pro poskytování finančních darů v roce 2023 – pravomoc starosty."),
  vote("PRO ( 6 ) – PROTI ( 1 - Strnadová ) – ZDRŽEL SE ( 1 - Maršíková )"),

  h5("PRAVIDLA POSKYTOVÁNÍ FINANČNÍCH PŘÍSPĚVKŮ PRO OBČANY S TRVALÝM POBYTEM V OBCI KRHANICE NA POŘÍZENÍ KOMPOSTÉRU V OBCI KRHANICE"),
  p("Starosta: Obecní úřad pomocí dotazníků zjišťoval zájem občanů o kompostéry v rámci případné dotace anebo v rámci finanční spoluúčasti nemovitostí. Z hlediska zájmu to na dotaci není. Tu jsme v minulosti obdrželi. Proto v rámci podpory kompostování předkládám návrh pravidel pro poskytování finančních příspěvků na kompostér nemovitostem s občany s trvalým pobytem v obci Krhanice. V rozpočtu by byla vyčleněna částka 80 tisíc Kč."),
  h5("Rozprava"),
  p("T.Strnad: Jestli to tedy dobře chápu, stačí si pořídit kompostér za 2 tisíce a obec ho proplatí. Jak bude ošetřeno, aby občan používal kompostér na území obce Krhanice? Starosta: Ve smlouvách je, že musí být umožněn přístup ke kontrole kompostéru."),
  p("P.Bydžovský: Jak je definována zahrada? Starosta: Není."),
  h5("Návrh"),
  p("ZO schvaluje Pravidla pro poskytování finančních příspěvků pro občany s trvalým pobytem v obci Krhanice na pořízení kompostéru v obci Krhanice."),
  vote(V8),

  h5("ZÁKLADNÍ ŠKOLA KRHANICE – NAVÝŠENÍ PROVOZNÍHO PŘÍSPĚVKU"),
  p("Starosta seznámil s navýšením provozního příspěvku pro základní školu:"),
  p("a) regionální učebnice : 55 tisíc Kč – grafika 48 182,20 Kč; 15 ks učebnic 5 841,00 Kč"),
  p("b) oprava střechy budovy: 90 tisíc Kč"),
  h5("Rozprava"),
  p("L.Maršíková: Změnilo se něco od doby, kdy se regionální učebnice probírala na předchozím zastupitelstvu? Našel se jiný způsob financování? Starosta: Ředitelka slíbila, že předloží podrobnější informace v září."),
  p("Kratochvíl: Tím, že se zaplatí grafik, škola získá autorská práva."),
  p("Proběhla diskuse bez přijetí závěrů."),
  h5("Návrh"),
  p("ZO schvaluje navýšení provozního příspěvku Základní škole Krhanice, okres Benešov o 145 tisíc Kč (regionální učebnice, oprava střechy budovy)."),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 1 - Strnadová )"),

  h5("INTERMONT – DODATEK Č. 3"),
  p("Informace starosty: Jedná se o vícepráce a méněpráce, které vznikly při rekonstrukci budovy základní školy. Práce byly odsouhlaseny stavebním dozorem a projektantem. Částka je: 223 931,15 bez DPH, 270 956,70 Kč s DPH."),
  h5("Rozprava"),
  p("P.Bydžovský: Dotaz na zádržné. Proč bude vyplaceno nyní? Na ostatních stavbách se praktikuje výplata až poté, když nedojde k žádným reklamacím. Starosta: Spolupracujeme s firmou, která se takovými projekty zabývá. Postupujeme podle jejich doporučení."),
  p("L.Maršíková: Nedostala změnové listy, aby si je mohla předem prostudovat. Požaduje posunutí hlasování na příští zastupitelstvo."),
  h5("Návrh"),
  p("ZO schvaluje posunutí hlasování o uzavření Dodatku č.3 ke Smlouvě o dílo se společností Intermont, Opatrný. s.r.o., IČO: 49900854, Mostecká 1973, 431 11 Jirkov pro stavební práce Krhanice – revitalizace a VZT budovy ZŠ na příští zasedání Zastupitelva obce Krhanice."),
  vote("PRO ( 3 – Maršíková, Strnadová, Papoušek ) – PROTI ( 5 ) – ZDRŽEL SE ( 0 )"),
  h5("Návrh"),
  p("ZO schvaluje uzavření Dodatku č.3 ke Smlouvě o dílo se společností Intermont, Opatrný. s.r.o., IČO: 49900854, Mostecká 1973, 431 11 Jirkov pro stavební práce Krhanice – revitalizace a VZT budovy ZŠ. Cena díla včetně DPH se navyšuje o 270 956,70 Kč."),
  vote("PRO ( 5 ) – PROTI ( 3 – Maršíková, Strnadová, Papoušek ) – ZDRŽEL SE ( 0 )"),
  h5("Návrh"),
  p("ZO pověřuje starostu obce podpisem Dodatku č.3 ke Smlouvě o dílo se společností Intermont, Opatrný. s.r.o., IČO: 49900854, Mostecká 1973, 431 11 Jirkov pro stavební práce Krhanice – revitalizace a VZT budovy ZŠ."),
  vote("PRO ( 6 ) – PROTI ( 2 – Maršíková, Strnadová ) – ZDRŽEL SE ( 0 )"),
  p("Předseda finančního výboru Petr Dub seznámil s rozpočtovým opatřením č. 6/2023."),
  h5("Rozprava"),
  p("I.Dvořák: Dotaz na brigády. Jak funguje spolupráce s úřadem práce. Starosta: Úřad práce přispívá na mzdy zaměstnance a obec platí odvody."),
  p("I.Dvořák: Kolik je částka na opravu automobilu a kolik školení hasičů? Starosta: Částka na školení je 78 tisíc, zbytek pak na automobily (trnsporter, tatra). Proškoleny budou 2/3 členů zásahové jednotky + jeden zaměstnanec, který s motorovou pilou pracuje. Školení je nezbytné kvůli pojištění."),
  p("L.Maršíková: Dotaz na dar k zeleni ve výši 40 tisíc. Kdo je dárce? Starosta: Dotyčný nechce být jmenován."),
  h5("Návrh"),
  p("ZO schvaluje rozpočtové opatření č. 6/2023."),
  vote("PRO ( 6 ) – PROTI ( 2 – Strnadová, Maršíková ) – ZDRŽEL SE ( 0 )"),

  h3("10) Vyhlášky obce Krhanice"),
  h4("Obecně závazná vyhláška obce Krhanice, kterou se stanoví část společného školského obvodu základní školy"),
  p("Starosta obce seznámil s Obecně závaznou vyhláškou obce Krhanice, kterou se stanoví část společného školského obvodu základní školy. Vyhlášku jsme v minulosti schvalovali. Byla v ní chyba v katastrálním území."),
  h5("Rozprava"),
  p("Proběhla diskuse o umisťování dětí do různých škol ze strany rodičů."),
  h5("Návrh"),
  p("ZO schvaluje Obecně závaznou vyhlášku obce, kterou se stanoví část společného školského obvodu základní školy."),
  vote(V8),

  h4("Obecně závazná vyhláška obce Krhanice o nočním klidu"),
  p("Starosta obce seznámil s Obecně závaznou vyhláškou obce Krhanice o nočním klidu."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Obecně závaznou vyhlášku obce o nočním klidu."),
  vote(V8),

  h4("Obecně závazná vyhláška obce Krhanice o stanovení obecního systému odpadového hospodářství"),
  p("Starosta obce seznámil s Obecně závaznou vyhláškou obce Krhanice o stanovení obecního systému odpadového hospodářství, která stanovuje obecní systém odpadového hospodářství na území obce Krhanice."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Obecně závaznou vyhlášku obce Krhanice o stanovení obecního systému odpadového hospodářství."),
  vote(V8),

  h4("Obecně závazná vyhláška – o stanovení místního koeficientu pro výpočet daně z nemovitých věcí"),
  p("Starosta obce seznámil s Obecně závaznou vyhláškou obce Krhanice o stanovení místního koeficientu pro výpočet daně z nemovitých věcí"),
  h5("Rozprava"),
  p("L.Maršíková: Propočítala, že navýšení koeficientu přinese do rozpočtu cca 600 tisíc. H.Strnadová: Víme, co s těmi penězi uděláme? Starosta: Použijeme je na financování plánovaných investičních akcí."),
  p("J.Bydžovská: Je nutné zvyšovat koeficient o tolik (o 50 %)? Starosta: Je možné ho zvýšit až na hodnotu 5. Nyní je 2, teď zvyšujeme na 3."),
  p("Proběhla diskuse o koeficientech v obcích a městech České republiky a k čemu by se získané peníze daly použít."),
  h5("Návrh"),
  p("ZO schvaluje Obecně závaznou vyhlášku obce o stanovení místního koeficientu pro výpočet daně z nemovitých věcí."),
  vote("PRO ( 6 ) – PROTI ( 1 - Maršíková ) – ZDRŽEL SE ( 1 - Strnadová )"),

  h3("11) Koupě, prodej, pronájem"),
  ...ul(["pronajmout část pozemku parc. č. 132/1 k.ú. Krhanice o výměře 430 m² ke zřízení dočasné zahrádky za cenu 10,- Kč/1 m²/rok od 1.7.2023 na dobu 4 let"]),
  p("Informace starosty: Žádost Kubáta Miroslava - jedná se o pokračování nájmu pozemku."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronajmout část pozemku parc. č. 132/1 k.ú. Krhanice o výměře 430 m² ke zřízení dočasné zahrádky za cenu 10,- Kč/1 m²/rok od 1.7.2023 na dobu 4 let Miroslavu Kubátovi, Vackova 1560/10, 155 00 Praha 5."),
  vote(V8),
  ...ul(["pronajmout část pozemku parc. č. 132/1 k.ú. Krhanice o výměře 131 m² ke zřízení dočasné zahrádky za cenu 10,- Kč/1 m²/rok od 1.9.2023 na dobu 4 let"]),
  p("Informace starosty: Žádost Holuba Josefa - jedná se o pokračování nájmu pozemku."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronajmout část pozemku parc. č. 132/1 k.ú. Krhanice o výměře 131 m2 ke zřízení dočasné zahrádky za cenu 10,- Kč/1 m2/rok od 1.9.2023 na dobu 4 let Josefu Holubovi, Kozácká 4, 101 00 Praha 10."),
  vote(V8),
  ...ul(["pronajmout část pozemku parc. č. 1884/2 k.ú. Krhanice o výměře 494 m² ke zřízení dočasné zahrádky za cenu 10,- Kč/1 m²/rok od 14.10.2023 na dobu 4 let"]),
  p("Informace starosty: Žádost Pavláta Pavla - jedná se o pokračování nájmu pozemku."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronajmout část pozemku parc. č. 1884/2 k.ú. Krhanice o výměře 494 m² ke zřízení dočasné zahrádky za cenu 10,- Kč/1 m²/rok od 14.10.2023 na dobu 4 let Pavlu Pavlátovi, Úvalská 41, 100 00 Praha 10."),
  vote(V8),
  ...ul(["pronajmout část pozemku parc. č. 1954/1 k.ú. Krhanice o výměře 24 m² k dočasnému umístění dětských herních prvků a stolů za cenu 10,- Kč/1 m²/rok od 1.10.2023 na dobu 4 let"]),
  p("Informace starosty: Žádost Krejzla Milana - jedná se o pokračování nájmu pozemku."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronajmout část pozemku parc. č. 1954/1 k.ú. Krhanice o výměře 24 m² k dočasnému umístění dětských herních prvků a stolů za cenu 10,- Kč/1 m²/rok od 1.10.2023 na dobu 4 let Milanovi Krejzlovi, Chrást nad Sázavou 217, 257 42 Týnec nad Sázavou."),
  vote(V8),
  ...ul(["uzavřít smlouvu o zřízení věcného břemene – uložení vodovodní přípojky pro pozemek parc.č. 365/1 k.ú. Krhanice na pozemku parc.č. 1983/1 k.ú. Krhanice dle geometrického plánu č. 1094-38/2022 na dobu neurčitou za cenu 3.000,- Kč"]),
  p("Starosta: Jedná se o věcné břemeno na vodovodní přípojku nedaleko lomu. Starosta ukázal na katastrální mapě."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavřít smlouvu o zřízení věcného břemene – uložení vodovodní přípojky pro pozemek parc.č. 365/1 k.ú. Krhanice na pozemku parc.č. 1983/1 k.ú. Krhanice dle geometrického plánu č. 1094-38/2022 na dobu neurčitou za cenu 3.000,- Kč s Marií Maršíkovou, Krhanice 35, 257 42 Krhanice."),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 1 - Maršíková )"),
  ...ul(["uzavřít smlouvu o zřízení věcného břemene – uložení vodovodní přípojky pro pozemek parc.č. 365/2 k.ú. Krhanice na pozemku parc.č. 1981/1 k.ú. Krhanice dle geometrického plánu č. 1115-16/2023 na dobu neurčitou za cenu 3.000,- Kč"]),
  p("Starosta: Jedná se o věcné břemeno na vodovodní přípojku nedaleko lomu. Starosta ukázal na katastrální mapě."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavřít smlouvu o zřízení věcného břemene – uložení vodovodní přípojky pro pozemek parc.č. 365/2 k.ú. Krhanice na pozemku parc.č. 1981/1 k.ú. Krhanice dle geometrického plánu č. 1115-16/2023 na dobu neurčitou za cenu 3.000,- Kč s Lucií Steinhüblovou, Krhanice 313, 257 42 Krhanice."),
  vote(V8),
  ...ul(["uzavřít Smlouvu o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby č. IE-12-6028834/VB/001 Krhanice-kNN-parc.č.336/3 na pozemcích parc. č. 319 k.ú. Krhanice a parc. č. 324/1 k.ú. Krhanice s ČEZ Distribuce, a.s., IČ 24729035, DIČ CZ24729035, se sídlem Děčín IV-Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 16 900 Kč na umístění zařízení kabelového vedení a pojistkové skříně."]),
  p("Starosta: Jedná se vybudování elektrické přípojky k chatě nedaleko střelnice. Starosta ukázal na katastrální mapě."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavřít Smlouvu o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby č. IE-12-6028834/VB/001 Krhanice-kNN-parc.č.336/3 na pozemcích parc. č. 319 k.ú. Krhanice a parc. č. 324/1 k.ú. Krhanice s ČEZ Distribuce, a.s., IČ 24729035, DIČ CZ24729035, se sídlem Děčín IV-Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 16 900 Kč na umístění zařízení kabelového vedení a pojistkové skříně."),
  vote(V8),
  ...ul(["bezúplatné nabytí stavby veřejného osvětlení (v počtu 4 ks Led svítidel) na p.č. 299/1 k.ú. Krhanice zkolaudovaného Městským úřadem Týnec nad Sázavou do vlastnictví obce Krhanice v hodnotě 251 680 Kč od: Borys Moshkola, Iuliia Moshkola, Slunečná 56, 254 01 Jílové u Prahy"]),
  p("Starosta: Jedná se o převzetí zkolaudovaného veřejného osvětlení v lokalitě před Hodkovem v Krhanicích. Starosta ukázal na katastrální mapě."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje bezúplatné nabytí stavby veřejného osvětlení (v počtu 4 ks Led svítidel) na p.č. 299/1 k.ú. Krhanice zkolaudovaného Městským úřadem Týnec nad Sázavou do vlastnictví obce Krhanice v hodnotě 251 680 Kč od Borys Moshkola a Iuliia Moshkola, Slunečná 56, 254 01 Jílové u Prahy."),
  vote(V8),

  h3("12) Různé"),
  h4("DSO BENE-BUS; TÝNECKO-SVAZEK OBCÍ; POSÁZAVSKÝ VODOVOD – dobrovolný svazek obcí"),
  p("Informace starosty:"),
  p("DSO BENE-BUS: Byl nám předložen návrh Závěrečného účtu za rok 2022 a Zpráva o výsledku přezkoumání hospodaření za rok 2022. Vyvěšeno dne 4.5.2023. Valnou hromadou svazku byl závěrečný účet schválený bez výhrad, a to dne 23.5.2023."),
  p("TÝNECKO-SVAZEK OBCÍ: Byl nám předložen návrh Závěrečného účtu za rok 2022 a Zpráva o výsledku přezkoumání hospodaření za rok 2022. Vyvěšeno dne 12.4.2023. Valnou hromadou svazku byl závěrečný účet schválený bez výhrad, a to dne 17.5.2023."),
  p("POSÁZAVSKÝ VODOVOD – dobrovolný svazek obcí: Byl nám předložen návrh Závěrečného účtu za rok 2022 a Zpráva o výsledku přezkoumání hospodaření za rok 2022. Vyvěšeno dne 18.4.2023. Správní radou členů byl závěrečný účet schválený bez výhrad, – dne 4.5.2023."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí Závěrečný účet dobrovolného svazku obcí BENE-BUS za rok 2022 a Zprávu o výsledku přezkoumání hospodaření za rok 2022 dobrovolného svazku obcí BENE-BUS."),
  h5("Návrh"),
  p("ZO bere na vědomí Závěrečný účet Týnecko-svazek obcí za rok 2022 a Zprávu o výsledku přezkoumání hospodaření za rok 2022 Týnecko – svazek obcí."),
  h5("Návrh"),
  p("ZO bere na vědomí Závěrečný účet Posázavský vodovod – dobrovolný svazek obcí za rok 2022 a Zprávu o výsledku přezkoumání hospodaření za rok 2022 Posázavský vodovod – dobrovolný svazek obcí."),

  h4("KALKULACE VODNÉHO OD VHS BENEŠOV – OBEC KRHANICE, POSÁZAVSKÝ VODOVOD"),
  p("Informace starosty: Byly nám předloženy kalkulace vodného za rok 2022 od VHS Benešov pro obec Krhanice a Posázavský vodovod. Vyvěšeny byly dne 28.4.2023."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí Kalkulaci vodného za kalendářní rok 2022 od VHS Benešov a.s. pro obec Krhanice a Posázavský vodovod."),

  h4("LAROS – PRODLOUŽENÍ TERMÍNU REALIZACE AKCE REKONSTRUKCE HLAVNÍHO VODOVODNÍHO PŘIVADĚČE DO OBCE KRHANICE“"),
  p("Firma z kapacitních důvodů žádá o prodloužení termínu realizace do 30.9.2023."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Dodatku č.1 ke Smlouvě o dílo SoD č. 2022/2 se společností LAROS s.r.o., IČO: 49826514, Jana Nohy 1285, 256 01 Benešov pro stavební práce Rekonstrukce hlavního vodovodního přivaděče do obce Krhanice, prodloužení termínu do 30.9.2023."),
  vote(V8),
  h5("Návrh"),
  p("ZO pověřuje starostu obce podpisem Dodatku č.1 ke Smlouvě o dílo SoD č. 2022/2 se poelčností LAROS s.r.o., IČO: 49826514, Jana Nohy 1285, 256 01 Benešov pro stavební práce Rekonstrukce hlavního vodovodního přivaděče do obce Krhanice."),
  vote(V8),

  h4("INFORMACE O DOTACI NA LED OSVĚTLENÍ"),
  p("Informace starosty: Zastupitelstvo obce schválilo 2.5.2022 podání žádosti o dotaci „Krhanice – rekonstrukce veřejného osvětlení“ pro dotační titul na Ministerstvu práce a obchodu: Výzva č. NPO 1/2022 NÁRODNÍ PLÁN OBNOVY; Rekonstrukce veřejného osvětlení - Komponenta 2.2.2. Byl zpracován projekt a veškeré podklady pro podání dotace."),
  p("Jednalo by se o výměnu 161 světel, výměnu výložníků, některých sloupů,… Rozpočet na 2 880 383,- Kč. Dotace by byla cca 900 tisíc Kč."),
  h5("Rozprava"),
  p("T.Strnad: Máme spočítáno, kolik to ušetří ročně? Starosta: Cca 50%."),
  p("P.Bydžovský. Ocenil podání dotace. Uvedl příklad Netvořic."),
  h5("Návrh"),
  p("ZO bere na vědomí informaci o připravovaném podání žádosti o dotaci na projekt „Krhanice – rekonstrukce veřejného osvětlení“."),

  h4("ODPADY"),
  p("Informace starosty o jednání na Technických službách Benešov."),
  p("Obec Krhanice, a několik dalších vybraných obcí, budou v roce 2024 součástí pilotního projektu s Technickými službami Benešov, který přinese změny do svozu popelnic. Svoz popelnic bude od března 2024 již jen čtrnáctidenní. Další změnou, respektive novinkou, na další zlepšení třídění plastů a papíru z domácností budou čtrnáctidenní pytlové svozy plastu a papíru, na které budete dostávat pytle. Protože to bude obnášet změny – např. výměny popelnic, začínáme na tomto projektu pracovat již nyní. Jednotlivé domácnosti s týdenním nebo kombinovaným svozem budou postupně v průběhu září oslovovány. Bude řešena velikost popelnice, a to zachování stávající velikosti popelnice; nebo změna velikosti popelnice; nebo změna počtu popelnic pro domácnost, … Termín zahájení bude 1.března 2024."),
  h5("Rozprava"),
  p("L.Maršíková: Jak velké pytle to budou? Starosta: Zřejmě 120 litrů."),
  p("Proběhla diskuse o odpadovém hospodářství, bez přijetí závěrů."),

  h4("ÚŘAD PRÁCE – VEŘEJNĚ PROSPĚŠNÉ PRÁCE"),
  p("Informace starosty: Úřad práce má program pro podporu nezaměstnaných. Pro osoby se sníženou možností získání zaměstnání jsme schopni vytvořit dočasně 1 pracovní místo."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje a souhlasí s účastí obce Krhanice v rámci projektu Úřadu práce Příbram, pobočka Benešov v zaměstnávání osob se sníženou možností získání zaměstnání – 1 pracovní místo."),
  vote(V8),

  h4("CENA STRAVNÉHO OD 1.9.2023 VE ŠKOLNÍ JÍDELNĚ"),
  p("Starosta seznámil přítomné s dopisem ředitelky základní školy o zvýšení stravného od 1.9.2023."),
  p("Cizí strávníci:"),
  p("Cena obědů od 1. 10. 2021: 78 Kč"),
  p("Od 1.9.2023:"),
  p("Cena obědů od 1. 9. 2023: 81 Kč"),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje cenu oběda pro cizí strávníky Školní jídelny Základní školy Krhanice v částce 81,- Kč od 1.9.2023."),
  vote(V8),

  h4("ČISTÁ ŘEKA SÁZAVA – PODĚKOVÁNÍ"),
  p("Informace starosty: Přišlo nám poděkování od Posázaví o.p.s. za finanční podporu akce Čistá řeka Sázava 2023 a za úklid kolem řeky Sázavy"),
  p("Starosta:"),
  ...ul([
    "Poděkování za úklidové akce Čistíme Krhanice a Prosečnici, Uklízíme Hornopožárské lesy I a II, Čistá řeka Sázava a bezejmenným dobrovolníkům, kteří občas někde něco posbírají.",
    "Poděkování firmě Kámen Zbraslav za finanční dar na Dětský den v Krhanicích.",
    "Rekonstrukce návsi a okolních chodníků finišuje.",
    "Rekonstrukce budovy základní školy a vybudování vzduchotechniky v procesu předání stavby po dokončení.",
    "Ukončena rekonstrukce památníku obětem 2.světové války na hřbitově.",
    "Pumptracková dráha je ve stavu zpracování návrhu vzhledu podle jiné pumptrackové dráhy. Realizace bude v areálu základní školy vedle školní jídelny.",
    "Předpokládané zahájení budování okružní křižovatky s chodníkem v září 2023 na dobu cca 2,5 měsíce. Nyní probíhá výběrové řízení na výběr realizační firmy.",
  ]),

  h3("13) Diskuse"),
  ...ul([
    "L.Maršíková: Kolik byl finanční dar od Kámen Zbraslav? Starosta: 10 000 Kč prostřednictvím SDH. Kratochvíl: Celá částka byla použita na odměny pro děti a na tombolu.",
    "J.Bydžovská: Došlo už ke změně umístění pumptrackové dráhy? Starosta: Ano, původně měla být v areálu TJ Sokol Krhanice, ale byl by k ní přístup jen během otvírací doby Sokolky. Nyní má být umístěna v areálu vedle víceúčelového hřiště s přístupem přes víceúčelové hřiště.",
    "I.Dvořák: V areálu došlo ke kácení. Bude se ještě pokračovat? Starosta:Už ne.",
    "I.Dvořák: Poznámka k nové výsadbě. Zdá se mi, že se vysazují keře a stromky moc blízko plotu. Nebude možná dobrá údržba. Starosta: Výsadbu provádí odborná firma.",
    "I.Dvořák: Dotaz k lomu v Doubí. Zavážení stále pokračuje. Chtěl požádat o vyvěšení na obecních vývěskách – bližší informace k této kauze a připravované petici.",
    "T.Strnad: Bude se rekonstruovat celá střecha školy? Starosta: Pod fotovoltaikou ne.",
    "H.Strnadová: Dotaz na souhlas se zavážením lomu. Jaký je postoj obce a starosty? Starosta: Můj názor zavážení v rozsahu, aby zůstala ta atraktivní část, která je přírodně zajímavá, nezavežena. Ještě budu mít příští týden místní šetření.",
  ]),

  h3("14) Usnesení a závěr"),
  p("Zastupitelstvo obce bylo ukončeno v 20:42 hod."),

  p("Datum pořízení zápisu: 23.6.2023"),
  p("Ověřovatelé zápisu a starosta obce, podepsáno v listinné podobě."),
  h4("Přílohy"),
  ...nl(["Svolání zastupitelstva obce", "Prezenční listina zastupitelů", "Prezenční listina občanů"]),
];

async function run() {
  const r = await publishZapis({
    cislo: "2",
    rok: "2023",
    isoDate: "2023-06-15",
    dateLabel: "15. 6. 2023",
    fullDateDot: "15.6.2023",
    pdfPath: "scripts/zapisy-pdf/zapis-2023-2.pdf",
    transcript,
  });
  console.log("OK", r.docId, "blocks", r.blocks);
}
run().catch((e) => { console.error(e); process.exit(1); });
