/* eslint-disable no-console */
import { h3, h4, h5, p, vote, nl, ul, publishZapis, type Block } from "../zapis-lib";

const V6 = "PRO ( 6 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )";

const transcript: Block[] = [
  h4("Přítomni"),
  p("Aleš Papoušek, Jaroslav Mixa, Tomáš Kratochvíl, Petr Dub, Martin Jiřička, Bohuslav Kadeřábek, Edita Jarošová"),
  h4("Omluveni"),
  p("Jana Laboutková, Václav Zíta, Martin Jiřička (přijde později)"),

  h3("1) Zahájení, přivítání přítomných, konstatování přítomnosti"),
  p("Starosta konstatoval, že zasedání bylo svoláno dne 4.6.2021 bylo vyvěšeno na úřední desce obecního úřadu, tj. tedy nejméně 7 dní před zasedáním. Bylo tedy svoláno řádně a včas v souladu se zákonem o obcích v platném znění. Starosta konstatoval, že podle prezenční listiny je přítomno 6 členů zastupitelstva, tedy nadpoloviční většina členů zastupitelstva. K předchozímu zápisu nebyly vzneseny námitky."),
  h5("Určení zapisovatele"),
  p("Zápisem zasedání zastupitelstva obce byla pověřena Ing. Alena Kratochvílová."),
  p("Starosta přečetl program."),
  ...nl([
    "Zahájení",
    "Volba návrhové komise a ověřovatelů zápisu",
    "Projekt Zateplení a výměna zdroje tepla a pořízení centrální vzduchotechniky v Základní škole Krhanice – oznámení výsledku výběrového řízení, smlouva o dílo, administrativa se SFŽP",
    "Rozpočtové opatření",
    "Koupě, prodej, pronájem",
    "Různé",
    "Diskuse",
    "Usnesení a závěr",
  ]),
  p("Proběhlo hlasování o programu."),
  h5("Návrh"),
  p("ZO schvaluje program zasedání zastupitelstva obce."),
  vote(V6),

  h3("2) Volba návrhové komise a ověřovatelů zápisu"),
  p("Starosta přednesl návrh návrhové komise a ověřovatelů zápisu."),
  h5("Návrh"),
  p("ZO schvaluje návrhovou komisi ve složení Jaroslav Mixa, Petr Dub."),
  h5("Návrh"),
  p("ZO schvaluje ověřovatele zápisu ve složení Edita Jarošová, Tomáš Kratochvíl."),
  vote(V6),

  h3("3) Projekt Zateplení a výměna zdroje tepla a pořízení centrální vzduchotechniky v Základní škole Krhanice – oznámení výsledku výběrového řízení, smlouva o dílo, administrativa se SFŽP"),
  p("Informace starosty: Smlouva o dílo bude sepsána s firmou Intermont, Opatrný, s.r.o., IČO: 49900854, se sídlem: Vrskmaň 74, 431 15 Vrskmaň pro realizaci akce „Krhanice – revitalizace a VZT budovy ZŠ“."),
  p("Cena díla celkem bez DPH 16 987 292 Kč"),
  p("DPH 21 % 3 567 331 Kč"),
  p("Cena celkem včetně DPH 20 554 623 Kč"),
  p("Nyní máme Rozhodnutí o poskytnutí finančních prostředků ze Státního fondu životního prostředí ČR registrační číslo projektu CZ.05.5.18/0.0/0.0/19_121/0010072, název projektu 5.1. b. Pořízení centrální vzduchotechniky do ZŠ Krhanice a Rozhodnutí o poskytnutí finančních prostředků ze Státního fondu životního prostředí ČR registrační číslo projektu CZ.05.5.18/0.0/0.0/19_121/0010073, název projektu 5.1. a. Zateplení, výměna zdroje tepla v ZŠ v obci Krhanice."),
  p("Po uzavření Smlouvy o dílo začne změnové jednání na SFŽP, kdy podle konečné vysoutěžené ceny budou upraveny příslušné dokumenty: dotace, zápůjčky, trvalé příkazy a souhlasy s inkasem, splátkové kalendáře. Obec bude cca 10 let splácet čtvrtletně poskytnuté zápůjčky a dá souhlas k inkasu úroků ze strany SFŽP."),
  h5("Rozprava"),
  p("J.Bydžovský: Dotaz, zda si obec bude brát půjčku? Starosta: Ano, cca 7 miliónů Kč."),
  h5("Návrh"),
  p("ZO schvaluje uzavření smlouvy o dílo na akci „Krhanice – revitalizace a VZT budovy ZŠ“ s firmou Intermont, Opatrný, s.r.o., IČO: 49900854, se sídlem: Vrskmaň 74, 431 15 Vrskmaň ve výši 20.554.623,- Kč."),
  vote(V6),
  h5("Návrh"),
  p("ZO pověřuje starostu uzavřením a podpisem smlouvy o dílo na akci na akci „Krhanice – revitalizace a VZT budovy ZŠ“ s firmou Intermont, Opatrný, s.r.o., IČO: 49900854, se sídlem: Vrskmaň 74, 431 15 Vrskmaň."),
  vote(V6),

  h3("4) Rozpočtové opatření"),
  h4("„Krhanice – revitalizace a VZT budovy ZŠ“ – finanční prostředky"),
  h5("Návrh"),
  p("ZO schvaluje finanční prostředky ve výši 6.900.000,- Kč jako spoluúčast obce Krhanice pro dotaci a na související investiční výdaje na akci „Krhanice – revitalizace a VZT budovy ZŠ“, které budou zapojeny do výdajů rozpočtu na rok 2021 rozpočtovým opatřením č. 4/2021. Finanční prostředky dle Smlouvy o dílo a související investiční výdaje na akci pro další období budou zapojeny v rozpočtu daného období."),
  vote(V6),

  h4("Žádost TJ Sokol – Oslavy 80. let založení fotbalu"),
  p("Informace: Byla předložena žádost TJ Sokol o finanční příspěvek na akci Oslavy 80 let založení fotbalu TJ Sokol Krhanice na částku 61.619, - Kč. Příspěvek by byl použit na skákací hrad a kopací terč pro děti (9.874, - Kč), upomínkové předměty jako jsou čepice, náramky pro dospělé a děti a klíčenky (19.045, - Kč) a na hudební balíček, např. živá hudba, diskotéka pro děti, moderátor, pódium, osvětlení (31.000, - Kč) a poplatek OSA (1.700, - Kč)."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje poskytnutí finančního příspěvku ve výši 60.000, - Kč pro TJ Sokol Krhanice, IČ 61664723, Krhanice 162, 257 42 Krhanice na akci „Oslavy 80 let založení fotbalu TJ Sokol Krhanice“. S organizací bude uzavřena veřejnoprávní smlouva."),
  vote(V6),

  h4("Pomoc obcím – tornádo na Moravě"),
  p("Informace starosty: Zastupitelé se shodli na finanční pomoci po živelné katastrofě tornádem postiženým vybraným čtyřem obcím. Výsledkem je zaslat finanční příspěvek do veřejné sbírky na pomoc obcím na území Jihomoravského kraje zasažené živelní pohromou (tornádem) dne 24.6.2021:"),
  ...ul([
    "Hrušky – 10.000,- Kč",
    "Mikulčice – 10.000,- Kč",
    "Lužice – 10.000,- Kč",
    "Moravská Nová Ves – 10.000,- Kč",
  ]),
  p("Obec Hrušky, číslo účtu: 123-4548350207/0100, Obec Hrušky - Transparentní účet pro finanční pomoc občanům obce Hrušky (hrusky.cz)"),
  p("Obec Mikulčice, číslo účtu: 299222440/0300, Obec Mikulčice - Oficiální stránky obce Mikulčice (mikulcice.cz)"),
  p("Obec Lužice, číslo účtu: 123-3116370277/0100, Úvod - Obec Lužice (luziceuhodonina.cz)"),
  p("Obec Moravská Nová Ves, číslo účtu: 6013203349/0800, TRANSPARENTNÍ ÚČET - TORNÁDO MORAVSKÁ NOVÁ VES / Městys Moravská Nová Ves (mnves.cz)"),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje poskytnutí finančního příspěvku do veřejné sbírky na pomoc obci:"),
  ...ul([
    "Hrušky na území Jihomoravského kraje zasažené živelní pohromou (tornádem) dne 24.6.2021, a to ve výši 10.000, - Kč na transparentní účet – číslo účtu: 123-4548350207/0100",
    "Mikulčice na území Jihomoravského kraje zasažené živelní pohromou (tornádem) dne 24.6.2021, a to ve výši 10.000, - Kč na transparentní účet – číslo účtu: 299222440/0300.",
    "Lužice na území Jihomoravského kraje zasažené živelní pohromou (tornádem) dne 24.6.2021, a to ve výši 10.000, - Kč na transparentní účet – číslo účtu: 123-3116370277/0100.",
    "Moravská Nová Ves na území Jihomoravského kraje zasažené živelní pohromou (tornádem) dne 24.6.2021, a to ve výši 10.000, - Kč na transparentní účet – číslo účtu: 6013203349/0800",
  ]),
  vote(V6),
  p("Člen Finančního výboru Petr Dub přednesl odůvodnění rozpočtového opatření č. 4/2021."),
  h5("Rozprava"),
  p("H.Strnadová: Dotaz na opravu cesty na Borový. Voda poničila cestu tak, že se po ní jezdí špatně na kole. Starosta: V dané lokalitě máme naplánovanou opravu korýtka u Stibůrků u hlavní silnice. Provedeme úpravu navazující části komunikace."),
  h5("Návrh"),
  p("ZO schvaluje rozpočtové opatření č. 4/2021."),
  vote(V6),

  h3("5) Koupě, prodej, pronájem"),
  ...ul([
    "uzavřít Smlouvu o zřízení věcného břemene – služebnosti č. IV-12-6023937/1 na pozemku parc. č. 102/42 k.ú. Krhanice a parc. č. 102/51 k. ú. Krhanice s ČEZ Distribuce, a.s., IČ 24729035, DIČ CZ24729035, se sídlem Děčín IV-Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 6.000,- Kč na umístění zařízení distribuční soustavy – nové kabelové vedení NN, spojka na kabelu, pojistkový pilíř včetně pojistkové skříně, zemnění.",
  ]),
  p("Informace starosty: Jedná se o pozemek Na Žlabech. Jedná se o standardní elektrickou přípojku."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o zřízení věcného břemene – služebnosti č. IV-12-6023937/1 na pozemku parc. č. 102/42 k.ú. Krhanice a parc. č. 102/51 k. ú. Krhanice s ČEZ Distribuce, a.s., IČ 24729035, DIČ CZ24729035, se sídlem Děčín IV-Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 6.000, - Kč na umístění zařízení distribuční soustavy – nové kabelové vedení NN, spojka na kabelu, pojistkový pilíř včetně pojistkové skříně, zemnění."),
  vote(V6),
  p("Zastupitel Martin Jiřička dorazil na jednání zastupitelstva."),

  h4("Dokončení schváleného záměru koupě/odprodeje části pozemku"),
  p("Informace starosty: Na zastupitelstvu č. 1/2021 dne 17.3.2021 jsme odsouhlasili nákup části pozemku parc.č. 148/32 k.ú. Krhanice o výměře cca 260 m² za cenu 55 Kč/1 m² od Ing. Bohuslava Kadeřábka a Jana Kadeřábka, Krhanice č.p. 1, 257 42 Krhanice. Náklady na zhotovení geometrického plánu na dělení a náklady na vklad do katastru nemovitostí hradila obec jako kupující. Nyní již máme vyhotovený geometrický plán č. 1049-5116/2021 a došlo tedy ke zpřesnění části pozemku, který chceme odkoupit. Bude se jednat o pozemek parc.č. 148/51 o výměře 1410 m² za cenu 55 Kč/1 m². Zvětšení kupované plochy souvisí s nemožností udržovat zbytek pozemku zemědělskou technikou. Proto se odkupuje ne lichoběžník, ale obdélník navazující na již odkoupený pozemek parc. č. 148/6 k.ú. Krhanice."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje záměr koupit pozemek parc.č. 148/51 k.ú. Krhanice o výměře cca 1410 m², který vznikne na základě geometrického plánu č. 1049-5116/2021 za cenu 55 Kč/1 m² od Ing. Bohuslava Kadeřábka a Jana Kadeřábka, Krhanice č.p. 1, 257 42 Krhanice."),
  vote("PRO ( 6 ) – PROTI ( 0 ) – ZDRŽEL SE ( 1 - Kadeřábek )"),

  h4("Žádost o koupi pozemků v k.ú. Krhanice – Správa železnic"),
  p("Informace starosty: Obdrželi jsme rozšíření žádosti ze strany Správy železnic o koupi části pozemků parc.č. 2053/2 a parc.č. 1981/1 k.ú. Krhanice. Zastupitelstvo odsouhlasilo prodej části pozemků v dané lokalitě firmě Kámen Zbraslav vlastnící firmu Dobet. Z toho důvodu nebude odsouhlasovat prodej dalšímu subjektu."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO neschvaluje záměr rozšíření prodeje pozemků Správě železnic, státní organizaci, Dlážděná 1003/7, Praha 1, IČO: 70994234 o pozemky: část pozemků parc.č. 2053/2 a parc.č. 1981/1 k.ú. Krhanice."),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )"),

  h3("6) Různé"),
  ...ul([
    "Informace starosty: Dotace na Rekonstrukci a modernizaci volnočasového hřiště v Krhanicích byla Zastupitelstvem Středočeského kraje projednána 28.6.2021, dotace splňovala všechny formální náležitosti, ale objem peněžních prostředků v uvedeném Programu nestačil pro schválení naší dotace.",
    "Poděkování starosty členům JSDHO Krhanice (tzv. zásahová jednotka hasičů) – zásahy v noci z 23.6. na 24.6.2021 - celkem 6 výjezdů a při dalších dvou silnějších bouřkách vždy po 1 výjezdu.",
  ]),

  h3("7) Diskuse"),
  p("H.Strnadová: Připomínka k popadaným stromům mezi Borovím a Březinkou. Celá řada stromů je i nakloněná. Hrozí, že by mohly někoho zranit. Starosta: Není to majetek obce. Vlastníka jsem již písemně upozornil. Jednal jsem i s jejich správcem lesa před cca 1,5 měsícem."),
  p("I.Dvořák: Komu ten les patří? Římskokatolické farnosti v Týnci nad Sázavou vedle ordinace obvodní lékařky vedle hradu."),
  p("H.Strnadová: Dotaz na neonovou ceduli u vchodu na víceúčelové hřiště. Připadá mi, že je to v rozporu se snahou zachovávat vesnický ráz Krhanic. Starosta: Cedule pomáhá řešit situace s mládeží, která se na víceúčelovém hřišti shromažďuje. Pokud svítí nápis ZAVŘENO, je pro mě nebo pana místostarostu snazší je vykázat."),
  p("L.Maršíková: Jaký byl náklad a kolik stála brožura o historických místech Krhanic. Starosta: 430 ks a vydání financovali zastupitelé ze svého."),
  p("L.Maršíková: Na jakém základě jste vybrali místa, která brožura obsahuje? Starosta: vybrali jsme je na základě zkušeností a dle starousedlíků (E.Jarošová). Proběhla diskuse o prostoru před obchodem."),
  p("L.Maršíková: O plakátovací plochu se nikdo nestará. Jsou tam staré informace. Starosta: Beru jako podnět k vyčištění."),
  p("H.Strnadová: Vznesla požadavek na umístění výkresu rekonstrukce návsi u obchodu na web obce. Starosta: Dám tam výkres."),
  p("L.Maršíková: Upozornila na nádrž u vrby (exkrementy) a požadavek na lavičky (H.Strnadová). Starosta: Situace s exkrementy nastala pouze jednou. Lavičky nelze umístit, je tam přístup ke stavebním pozemkům."),

  h3("8) Usnesení a závěr"),
  p("Návrhová komise přečetla usnesení zastupitelstva obce."),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )"),
  h5("Závěr"),
  p("Zastupitelstvo obce bylo ukončeno v 18:30 hod."),
  h4("Přílohy"),
  ...nl(["Svolání zastupitelstva obce", "Prezenční listina zastupitelů", "Prezenční listina občanů"]),
];

async function run() {
  const r = await publishZapis({
    cislo: "3",
    rok: "2021",
    isoDate: "2021-07-12",
    dateLabel: "12. 7. 2021",
    fullDateDot: "12.7.2021",
    pdfPath: "scripts/zapisy-pdf/zapis-2021-3.pdf",
    transcript,
  });
  console.log("OK", r.docId, "blocks", r.blocks);
}
run().catch((e) => { console.error(e); process.exit(1); });
