/* eslint-disable no-console */
import { h3, h4, h5, p, vote, nl, ul, publishZapis, type Block } from "../zapis-lib";

const V8 = "PRO ( 8 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )";
const V7d = "PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 1 – Bc. Dušová )";

const transcript: Block[] = [
  h4("Přítomni"),
  p("Aleš Papoušek, Jaroslav Mixa, Tomáš Kratochvíl, Aleš Kozel, Jana Laboutková, Petr Dub, Lucie Maršíková, Šárka Dušová"),
  h4("Omluveni"),
  p("Martin Jiřička"),

  h3("1) Zahájení, přivítání přítomných, konstatování přítomnosti"),
  p("Starosta konstatoval, že zasedání bylo svoláno dne 20.5.2024, bylo vyvěšeno na úřední desce obecního úřadu, tj. tedy nejméně 7 dní před zasedáním. Bylo tedy svoláno řádně a včas v souladu se zákonem o obcích v platném znění. Starosta konstatoval, že podle prezenční listiny je přítomno 8 členů zastupitelstva, tedy nadpoloviční většina členů zastupitelstva. K předchozímu zápisu nebyly vzneseny námitky."),
  h5("Určení zapisovatele"),
  p("Zápisem zasedání zastupitelstva obce byla pověřena Ing. Alena Kratochvílová."),

  h3("2) Volba návrhové komise a ověřovatelů zápisu"),
  p("Starosta přednesl návrh návrhové komise a ověřovatelů zápisu."),
  h5("Návrh"),
  p("ZO schvaluje návrhovou komisi ve složení: Jana Laboutková, Jaroslav Mixa."),
  h5("Návrh"),
  p("ZO schvaluje ověřovatele zápisu ve složení Lucie Maršíková, Tomáš Kratochvíl."),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )"),

  h3("3) Schválení programu"),
  p("Starosta oznámil, změnu programu. Z důvodu podání rezignace zastupitelky Ing. Hany Strnadové dne 5.6.2024 dojde ke změně programu – doplnění o bod č. 4) Složení slibu zastupitele obce Krhanice, následující body se posunou v programu o jeden níže. Starosta přečetl program."),
  ...nl([
    "Zahájení",
    "Volba návrhové komise a ověřovatelů zápisu",
    "Schválení programu",
    "Složení slibu zastupitele obce Krhanice",
    "Závěrečný účet obce Krhanice pro rok 2023 a Závěrečné účty svazku obcí",
    "Zpráva finančního výboru o kontrole hospodaření obce Krhanice za rok 2023; Zpráva o výsledcích veřejnosprávních kontrol hospodaření Mateřské školy Krhanice a Základní školy Krhanice za rok 2023",
    "Schválení účetní závěrky obce Krhanice za rok 2023; Schválení účetní závěrky Mateřské školy Krhanice a Základní školy Krhanice za rok 2023",
    "Rozpočtová opatření",
    "Koupě, prodej, pronájem",
    "Obecně závazná vyhláška: noční klid; daň z nemovitých věcí (koeficient)",
    "Různé",
    "Diskuse",
    "Závěr",
  ]),
  p("Starosta: Má někdo návrh na změnu nebo doplnění programu?"),
  h5("Návrh"),
  p("ZO schvaluje program zasedání zastupitelstva obce."),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )"),

  h3("4) Složení slibu zastupitele obce Krhanice"),
  p("Starosta oznámil rezignaci zastupitelky Ing. Hany Strnadové. Dále oznámil že pět náhradníků z kandidátní listiny téže volební strany se vzdalo mandátů zastupitele. Budoucí zastupitelkou obce bude náhradnice z kandidátní listiny téže volební strany – Šárka Dušová. Starosta přivítal Šárku Dušovou."),
  h5("Složení slibu člena zastupitelstva"),
  p("Starosta v souladu s § 69 odst. 2 zákona o obcích vyzval Šárku Dušovou ke složení slibu. Před složením slibu starosta upozornil, že odmítnutí složit slib nebo složení slibu s výhradou má za následek zánik mandátu (§ 55 zákona č. 491/2001 Sb., o volbách do zastupitelstev obcí a o změně některých zákonů, v platném znění). Složení slibu proběhlo tak, že starosta přečetl slib stanovený v § 69 odst. 2 zákona o obcích:"),
  p("„Slibuji věrnost České republice. Slibuji na svou čest a svědomí, že svoji funkci budu vykonávat svědomitě, v zájmu obce a jejích občanů a řídit se Ústavou a zákony České republiky.“"),
  p("a vyzval Šárku Dušovou ke složení slibu pronesením slova „slibuji“ a podpisem na připraveném archu. Šárka Dušová neodmítla složit slib, ani nesložila slib s výhradou."),
  p("Starosta: Nyní musíme projednat výši a datum vyplácení odměny nové neuvolněné zastupitelce. Nařízení vlády, kterým se mění nařízení vlády č. 318/2017 Sb., o výši odměn členů zastupitelstev územních samosprávných celků, ve znění nařízení vlády č. 202/2018 Sb. Výše odměny 1083,- Kč dle schválených částek odměn na Zastupitelstvu obce č. 6/2022 dne 7.11.2022. Datum navrhuji: od 7.6.2024."),
  h5("Návrh"),
  p("ZO schvaluje v souladu s usnesením Zastupitelstva obce Krhanice č. 6/2022 ze dne 7.11.2022 výši odměny neuvolněné člence zastupitelstva Šárce Dušové: člen zastupitelstva: 1 083,- Kč, a to s platností od 7.6.2024."),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 1 – Bc. Dušová )"),

  h3("5) Závěrečný účet obce Krhanice pro rok 2023 a Závěrečné účty svazku obcí"),
  p("Starosta seznámil se Závěrečným účtem obce Krhanice pro rok 2023."),
  h5("Rozprava"),
  p("I.Dvořák: Dotaz ke Střednědobému výhledu: Obec má v majetku plynovod ten pronajímá. Chce ho dle výhledu do roku 2027 prodat? Starosta: Plynovod zatím pronajímáme. Neuvažujeme o prodeji. Plynovod opravuje provozovatel."),
  h5("Návrh"),
  p("ZO schvaluje Závěrečný účet obce Krhanice za rok 2023 a dává souhlas s celoročním hospodařením, a to bez výhrad."),
  vote(V7d),

  h4("Závěrečné účty svazku obcí"),
  ...ul(["DSO BENE-BUS; TÝNECKO-SVAZEK OBCÍ; POSÁZAVSKÝ VODOVOD – dobrovolný svazek obcí"]),
  p("Informace starosty:"),
  p("DSO BENE-BUS: Byl nám předložen návrh Závěrečného účtu za rok 2023 a Zpráva o výsledku přezkoumání hospodaření za rok 2023. Vyvěšeno dne 6.5.2024 Schvalující orgán – valná hromada svazku."),
  p("TÝNECKO-SVAZEK OBCÍ: Byl nám předložen návrh Závěrečného účtu za rok 2023 a Zpráva o výsledku přezkoumání hospodaření za rok 2023. Vyvěšeno dne 7.3.2024. Schvalující orgán – valná hromada svazku."),
  p("POSÁZAVSKÝ VODOVOD – dobrovolný svazek obcí: Byl nám předložen návrh Závěrečného účtu za rok 2023 a Zpráva o výsledku přezkoumání hospodaření za rok 2023. Vyvěšeno dne 16.5.2024. Schvalující orgán – správní rada členů."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí Závěrečný účet dobrovolného svazku obcí BENE-BUS za rok 2023 a Zprávu o výsledku přezkoumání hospodaření za rok 2023 dobrovolného svazku obcí BENE-BUS."),
  h5("Návrh"),
  p("ZO bere na vědomí Závěrečný účet Týnecko-svazek obcí za rok 2023 a Zprávu o výsledku přezkoumání hospodaření za rok 2023 Týnecko – svazek obcí."),
  h5("Návrh"),
  p("ZO bere na vědomí Závěrečný účet Posázavský vodovod – dobrovolný svazek obcí za rok 2023 a Zprávu o výsledku přezkoumání hospodaření za rok 2023 Posázavský vodovod – dobrovolný svazek obcí."),

  h3("6) Zpráva finančního výboru o kontrole hospodaření obce Krhanice za rok 2023; Zpráva o výsledcích veřejnosprávních kontrol hospodaření Mateřské školy Krhanice a Základní školy Krhanice za rok 2023"),
  p("Předseda finančního výboru Petr Dub seznámil s kontrolou hospodaření obce Krhanice za rok 2023 ze dne 22.4.2024. A dále seznámil s proběhlými veřejnosprávními kontrolami hospodaření příspěvkových organizací Mateřské školy Krhanice a Základní školy Krhanice. Kontroly proběhly dne 22.4.2024."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí zprávu finančního výboru o kontrole hospodaření obce Krhanice za rok 2023 ze dne 22.4.2024."),
  h5("Návrh"),
  p("ZO bere na vědomí protokoly o průběhu a výsledcích veřejnosprávních kontrol příspěvkových organizací Základní škola Krhanice a Mateřská škola Krhanice za rok 2023 ze dne 22.4.2024."),

  h3("7) Schválení účetní závěrky obce Krhanice za rok 2023; Schválení účetní závěrky Mateřské školy Krhanice a Základní školy Krhanice za rok 2023"),
  p("Starosta seznámil s průběhem procesu schvalování účetní závěrky a dále přečetl Protokoly o schvalování účetní závěrky za rok 2023 pro obec Krhanice, pro Mateřskou školu Krhanice a Základní školu Krhanice."),
  p("Starosta přečetl „Protokol o schvalování účetní závěrky za rok 2023 obce Krhanice“."),
  p("Starosta přečetl „Protokol o schvalování účetní závěrky za rok 2023 příspěvkové organizace Mateřská škola Krhanice, okres Benešov“."),
  p("Starosta přečetl „Protokol o schvalování účetní závěrky za rok 2023 příspěvkové organizace Základní škola Krhanice, okres Benešov“."),
  h5("Rozprava"),
  p("L.Maršíková: Dotaz na hospodářský výsledek základní školy. Převede ho základní škola do rozpočtu obce nebo na rezervní fond? Starosta: Na svůj rezervní fond."),
  h5("Schválení účetní závěrky"),
  h5("Návrh"),
  p("ZO schvaluje účetní závěrku obce Krhanice za rok 2023; schvalovaná účetní závěrka poskytuje věrný a poctivý obraz předmětu účetnictví a finanční situace účetní jednotky."),
  vote(V7d),
  h5("Návrh"),
  p("ZO schvaluje účetní závěrku příspěvkové organizace Mateřská škola Krhanice, okres Benešov za rok 2023; schvalovaná účetní závěrka poskytuje věrný a poctivý obraz předmětu účetnictví a finanční situace účetní jednotky."),
  vote(V7d),
  h5("Návrh"),
  p("ZO schvaluje účetní závěrku příspěvkové organizace Základní škola Krhanice, okres Benešov za rok 2023; schvalovaná účetní závěrka poskytuje věrný a poctivý obraz předmětu účetnictví a finanční situace účetní jednotky."),
  vote(V7d),
  h5("Rozdělení výsledku hospodaření"),
  h5("Návrh"),
  p("ZO schvaluje výsledek hospodaření ve schvalovacím řízení za rok 2023 obce Krhanice ve výši 14 004 512,41 Kč a jeho převod na účet 432 výsledek hospodaření předchozích účetních období."),
  vote(V7d),
  h5("Návrh"),
  p("ZO schvaluje hospodářský výsledek příspěvkové organizace Základní škola Krhanice za rok 2023 ve výši 43.114,60 Kč a jeho příděl do rezervního fondu."),
  vote(V7d),
  h5("Návrh"),
  p("ZO schvaluje Protokol o schvalování účetní závěrky za rok 2023 obce Krhanice."),
  vote(V7d),
  h5("Návrh"),
  p("ZO schvaluje Protokol o schvalování účetní závěrky za rok 2023 příspěvkové organizace Mateřská škola Krhanice, okres Benešov."),
  vote(V7d),
  h5("Návrh"),
  p("ZO schvaluje Protokol o schvalování účetní závěrky za rok 2023 příspěvkové organizace Základní škola Krhanice, okres Benešov."),
  vote(V7d),

  h3("8) Rozpočtová opatření"),
  h4("Rozpočtové opatření č. 2/2024, 3/2024, 4/2024 a č. 5/2024"),
  p("Starosta obce seznámil s rozpočtovými opatřeními č. 2/2024, 3/2024 a 4/2024 provedenými v souladu se schválenými pravidly ze dne 15.12.2023."),
  p("Č.2/2024: dotace Krhanice – rekonstrukce veřejného osvětlení – dotace z Evropské unie v částce 925,29 tisíc Kč."),
  p("Č.3/2024: dotace Operační program Zaměstnanost plus – dotace z úřadu práce na veřejně prospěšné práce v částce 88,2 tisíc Kč."),
  p("Č.4/2024: dotace Volby do Evropského parlamentu – dotace ze státního rozpočtu v částce 64 tisíc Kč."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí rozpočtové opatření č. 2/2024, 3/2024 a č. 4/2024."),
  h4("Rozpočtové opatření č. 5/2024"),
  p("Předseda finančního výboru Petr Dub seznámil s rozpočtovým opatřením č.5/2024."),
  p("Starosta seznámil se stavebními akcemi:"),
  ...ul([
    "Silnice: navýšení o 1600 tisíc Kč (místní komunikace na Žlabech)",
    "Ostatní záležitosti pozemních komunikací: navýšení o 2400 tisíc Kč (propojovací chodník pod železničním viaduktem, chodník pod strání u železničního viaduktu, technický dozor a BOZP – chodník k okružní křižovatce, společné povolení stavby a další související výdaje)",
    "Pitná voda: navýšení o 950 tisíc Kč (vodovodní řad H9-1 Prosečnice)",
    "Veřejné osvětlení: navýšení o 570 tisíc Kč (oprava spínacího bodu u transformátoru směrem ke statku, osvětlení 1x nové světlo u Hodkova (Za Mezírkou); osvětlení Na Žlabech; rekonstrukce kabelu u Hodkova)",
  ]),
  h5("Rozprava"),
  p("L.Maršíková: Dotaz, o jakou část komunikace Na Žlabech se jedná? Starosta: Ukázal na mapě rozsah nové místní komunikace."),
  p("J.Bydžovská: Dotaz na parametry nové komunikace. Starosta přečetl ze situace jednotlivé parametry nové komunikace. Povrch bude buď ze štěrkodrti nebo asfaltového recyklátu."),
  p("L.Maršíková: Bude obec dělat další část komunikace směrem k Havlíkům a dál? Starosta: V září proběhne místní šetření ohledně prašnosti na této komunikaci."),
  p("L.Maršíková: Proč se celá lokalita neřeší najednou? Starosta: Tato část je na projektovou dokumentaci. Budeme muset řešit problém s odvedením dešťových vod."),
  p("L.Maršíková: Dotaz na obecní pozemek v dané lokalitě? Jsou s ním nějaké plány? Starosta: Zatím ne."),
  p("A.Kozel: Je už dáno, že propojovací chodník bude dělat pan Žaba? Starosta: Bude záležet na zastupitelích, zda oslovíme jen pana Žabu nebo ještě oslovíme další firmy."),
  p("P.Bydžovský: Jak velká je to investice? Starosta: 1 a půl milionu dle rozpočtu."),
  p("L.Maršíková: Dotaz na povrch chodníku. Starosta: Zámková dlažba."),
  p("L.Maršíková: Dotaz na další část přístupové cesty k nádraží (chodník pod strání). Starosta vysvětlil chodníky v celé lokalitě, vlastnictví jednotlivých pozemků, budoucí koupi pozemku od Českých drah pod železničním viaduktem, pronájem části pozemku od Českých drah na nádraží, …"),
  p("Proběhla diskuse."),
  p("L.Maršíková: Probíhá nějaký stavební dozor na stavbě chodníku směrem k železničnímu viaduktu? Starosta: Dozor provádí pan Sommer ze Stavební komise a na stavbu jezdím každý den já. Ne všechny položky z rozpočtu byly plněny, např. nebylo potřeba využít semafory."),
  p("I.Dvořák: Dotaz k vodovodu na Prosečnici, kde se napojí 3 nové nemovitosti, zda nevybírat od majitelů nějaké částky za zhodnocení jejich pozemků. Starosta: Majitelé budou platit za připojení."),
  p("Proběhla diskuse k vybavení nového dopravního automobilu pro Zásahovou jednotku hasičů o typech podvozku a možnosti připojit přívěs."),
  p("L.Maršíková: Dotaz na herní prvky na dětském hřišti v Prosečnici. Pokud se bude budovat hřiště na jiném místě, má cenu dávat nové prvky na to stávající? Starosta: Nové hřiště se bude řešit až po změně územního plánu."),
  p("Proběhla diskuse o propojovacím chodníku pod železničním viaduktem, zda poptáme pouze pana Žabu a jeho nabídka bude následně porovnána s odhadem projektantské firmy, nebo budou osloveny i jiné firmy. Proběhla diskuse zda výběr firmy podle nejnižší ceny zaručí i kvalitu provedení,… Výsledkem diskuse bylo usnesení:"),
  h5("Návrh"),
  p("ZO schvaluje oslovení firmy Jaroslav Žaba k předložení nabídky na realizaci projektu Chodník podél silnice III/1066 – 2.etapa."),
  vote("PRO ( 6 ) – PROTI ( 2 – Maršíková, Bc. Dušová ) – ZDRŽEL SE ( 0 )"),
  h5("Návrh"),
  p("ZO schvaluje navýšení provozního příspěvku Mateřské školy Krhanice ve výši 40.000,- Kč na nákup drobného majetku."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje uzavření veřejnoprávní smlouvy o poskytnutí individuální dotace ve výši 23 560,- Kč na vertikulaci fotbalového hřiště s Tělocvičnou jednotou Sokol Krhanice, IČO: 61664723, 257 42 Krhanice č.p. 162."),
  vote(V7d),
  h5("Návrh"),
  p("ZO schvaluje rozpočtové opatření č. 5/2024."),
  vote("PRO ( 6 ) – PROTI ( 1 – Maršíková ) – ZDRŽEL SE ( 1 – Bc. Dušová )"),
  h4("Posázavský vodovod – dobrovolný svazek obcí"),
  p("POSÁZAVSKÝ VODOVOD – dobrovolný svazek obcí: Bylo nám předloženo Rozpočtové opatření č. 1/2024. Snížení očekávaných příjmů – pachtovné od VHS Benešov, snížení daní a zapojení finančních prostředků minulých let."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí Rozpočtové opatření č. 1/2024 Posázavského vodovodu – dobrovolného svazku obcí."),

  h3("9) Koupě, prodej, pronájem"),
  ...ul(["uzavřít Smlouvu o budoucí smlouvě o zřízení služebnosti na pozemku parc. č. 111/2 k.ú. Krhanice s CETIN a.s., IČO: 04084063, se sídlem: Českomoravská 2510/19, 190 00 Praha 9, na dobu neurčitou za cenu 13000 Kč na podzemní kabelové vedení a pilíř elektroměrového rozvaděče."]),
  p("Informace starosty: Jedná se o pozemek parku nad obecním úřadem."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o budoucí smlouvě o zřízení služebnosti na pozemku parc. č. 111/2 k.ú. Krhanice s CETIN a.s., IČO: 04084063, se sídlem: Českomoravská 2510/19, 190 00 Praha 9, na dobu neurčitou za cenu 13000 Kč na podzemní kabelové vedení a pilíř elektroměrového rozvaděče."),
  vote(V7d),
  ...ul(["uzavřít smlouvu o zřízení věcného břemene – uložení vodovodní přípojky pro pozemek parc.č. 1439/9 k.ú. Krhanice na pozemcích parc.č. 1978/13 a 1439/10 k.ú. Krhanice dle geometrického plánu č. 1145-3/2024 na dobu neurčitou za cenu 6.000,- Kč."]),
  p("Informace starosty: Jedná se o pozemky na návsi U Lípy."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření smlouvy o zřízení věcného břemene – uložení vodovodní přípojky pro pozemek parc.č. 1439/9 k.ú. Krhanice na pozemcích parc.č. 1978/13 a 1439/10 k.ú. Krhanice dle geometrického plánu č. 1145-3/2024 na dobu neurčitou za cenu 6.000,- Kč s Ing. Štěpánem Sedlákem, Zahrádecká 371/2, 142 00 Praha 4 a Ludmilou Sedlákovou, Na okruhu 389/13, 142 00 Praha 4."),
  vote(V7d),
  ...ul(["uzavřít Smlouvu o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby č. IV-12-6036043 na pozemku parc. č. 312/61 k.ú. Krhanice s ČEZ Distribuce, a.s., IČO 24729035, DIČ CZ24729035, se sídlem Děčín IV-Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 7700,- Kč na umístění zařízení distribuční soustavy – kabelové vedení."]),
  p("Informace starosty: Jedná se o pozemek v lokalitě u Slunečního domu."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby č. IV-12-6036043 na pozemku parc. č. 312/61 k.ú. Krhanice s ČEZ Distribuce, a.s., IČO 24729035, DIČ CZ24729035, se sídlem Děčín IV Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 7700,- Kč na umístění zařízení distribuční soustavy – kabelové vedení."),
  vote(V7d),
  ...ul(["uzavřít Smlouvu o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby č. IV-12-6034244/VB/6 na pozemcích parc. č. 1972/1 a 1977 k.ú. Krhanice s ČEZ Distribuce, a.s., IČO 24729035, DIČ CZ24729035, se sídlem Děčín IV-Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 13300,- Kč na umístění zařízení distribuční soustavy – kabelové vedení a podpěrný bod – betonový sloup."]),
  p("Informace starosty: Jedná se o pozemky na návsi U Lípy."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby č. IV-12-6034244/VB/6 na pozemcích parc. č. 1972/1 a 1977 k.ú. Krhanice s ČEZ Distribuce, a.s., IČO 24729035, DIČ CZ24729035, se sídlem Děčín IV Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 13300,- Kč na umístění zařízení distribuční soustavy – kabelové vedení a podpěrný bod – betonový sloup."),
  vote(V7d),
  ...ul(["uzavřít Smlouvu o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby č. IV-12-6033714/VB/1 na pozemcích parc. č. 35, 1972/1 a 38/6 k.ú. Krhanice s ČEZ Distribuce, a.s., IČO 24729035, DIČ CZ24729035, se sídlem Děčín IV-Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 74400,- Kč na umístění zařízení distribuční soustavy – kabelové vedení a rozpojovací skříně."]),
  p("Informace starosty: Jedná se o pozemky na návsi U Lípy a navazující pozemky."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby č. IV-12-6033714/VB/1 na pozemcích parc. č. 35, 1972/1 a 38/6 k.ú. Krhanice s ČEZ Distribuce, a.s., IČO 24729035, DIČ CZ24729035, se sídlem Děčín IV Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 74400,- Kč na umístění zařízení distribuční soustavy – kabelové vedení a rozpojovací skříně."),
  vote(V7d),
  ...ul(["uzavřít Smlouvu o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby č. IV-12-6033714/VB/4 na pozemku parc. č. 35 k.ú. Krhanice s Marií Jandákovou, Krhanice č.p. 4, 257 42 Krhanice a Františkem Brožkem, Husova 823, 271 01 Nové Strašecí, na dobu neurčitou za cenu 2000,- Kč na umístění zařízení distribuční soustavy – kabelové vedení a rozpojovací skříně. Investorem akce bude ČEZ Distribuce, a.s., IČO 24729035, DIČ CZ24729035, se sídlem Děčín IV-Podmokly, Teplická 874/8, 405 02 Děčín."]),
  p("Informace starosty: Jedná se o pozemky na návsi U Lípy."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby č. IV-12-6033714/VB/4 na pozemku parc.č. 35 k.ú. Krhanice s Marií Jandákovou, Krhanice č.p. 4, 257 42 Krhanice a Františkem Brožkem, Husova 823, 271 01 Nové Strašecí, na dobu neurčitou za cenu 2000,- Kč na umístění zařízení distribuční soustavy – kabelové vedení a rozpojovací skříně. Investorem akce bude ČEZ Distribuce, a.s., IČO 24729035, DIČ CZ24729035, se sídlem Děčín IV Podmokly, Teplická 874/8, 405 02 Děčín."),
  vote(V7d),
  ...ul(["uzavřít Smlouvu o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby č. IV-12-6033714/VB/6 na pozemku parc. č. 1972/1 k.ú. Krhanice s Martinem Schmidtem, Krhanice č.p. 45, na dobu neurčitou za cenu 2000,- Kč na umístění zařízení distribuční soustavy – kabelové vedení a rozpojovací skříně. Investorem akce bude ČEZ Distribuce, a.s., IČO 24729035, DIČ CZ24729035, se sídlem Děčín IV-Podmokly, Teplická 874/8, 405 02 Děčín."]),
  p("Informace starosty: Jedná se o pozemek na návsi U Lípy."),
  h5("Rozprava"),
  p("L.Maršíková: Dotaz na cestu k vratům nemovitosti Krhanice č.p. 5. Ještě není na katastru zapsán nový majitel. Starosta: Pozemek je veden jako cesta a nelze část oplotit. Oplocení lze provést po změně územního plánu."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby č. IV-12-6033714/VB/6 na pozemku parc. č. 1972/1 k.ú. Krhanice s Martinem Schmidtem, Krhanice č.p. 45, na dobu neurčitou za cenu 2000,- Kč na umístění zařízení distribuční soustavy – kabelové vedení a rozpojovací skříně. Investorem akce bude ČEZ Distribuce, a.s., IČO 24729035, DIČ CZ24729035, se sídlem Děčín IV Podmokly, Teplická 874/8, 405 02 Děčín."),
  vote(V7d),
  ...ul(["prodat z pozemku parc. č. 1439/10 k.ú. Krhanice část o výměře cca 110 m² za cenu 900,- Kč/1 m²."]),
  p("Informace starosty: Sedlákovi a pozemek pro přechod s ostrůvkem – ukázal na mapě."),
  p("Záměr:. prodat z pozemku parc. č. 1439/10 k.ú. Krhanice část o výměře cca 110 m² za cenu 900,- Kč/1 m². Obec by kupovala: 8 m² na přechod pro chodce s ostrůvkem"),
  h5("Rozprava"),
  p("L.Maršíková: Dotaz na hranice pozemků, zda je potok na obecním pozemku? Starosta: Částečně až u hlavní silnice."),
  p("Š.Dušová: Kdy bude chodník po druhé straně ke škole? Starosta: Je to v pořadí. Nyní řešíme jiné lokality."),
  h5("Návrh"),
  p("ZO schvaluje záměr prodeje části pozemku z pozemku parc. č. 1439/10 k.ú. Krhanice o výměře 110 m² za cenu 900,- Kč/1 m² a schvaluje záměr koupit část pozemku z pozemku parc.č. 186/26 k.ú. Krhanice o výměře cca 8 m² za cenu 900,- Kč/1 m²."),
  vote(V8),
  h4("České dráhy – nájemní smlouva"),
  p("Informace starosty: Starosta seznámil se záměrem pronajmout si část pozemku Českých drah, kde by chodili občané na vlakové nádraží – ve smlouvě „dočasný zábor k používání veřejností jako chodník“, nájemné ve výši 39.960,- Kč + DPH."),
  h5("Rozprava"),
  p("Starosta: Ve smlouvě chyběla výpovědní lhůta pro obec. Doplněno na 1 měsíc."),
  p("Proběhla diskuse o tom, zda je nutné smlouvu uzavírat a platit nájem."),
  h5("Návrh"),
  p("ZO schvaluje uzavření nájemní smlouvy o nájmu části pozemku parc. č. 2070/3 o výměře 333 m² – „dočasný zábor k používání veřejností jako chodník“ s firmou: České dráhy, a.s., sídlo: Praha 1, Nábřeží L. Svobody 1222, PSČ 110 15, IČO: 70994226."),
  vote("PRO ( 6 ) – PROTI ( 0 ) – ZDRŽEL SE ( 2 – Maršíková, Bc. Dušová )"),

  h3("10) Obecně závazná vyhlášky: noční klid; daň z nemovitých věcí (koeficient)"),
  p("Informace místostarosty o návrhu vyhlášky o nočním klidu."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Obecně závaznou vyhlášku obce Krhanice o nočním klidu."),
  vote(V8),
  p("Místostarosta obce seznámil s návrhem vyhlášky o místním koeficientu daně z nemovitostí a o skončení vyhlášky č.2/2012 o stanovení koeficientu pro výpočet daně z nemovitosti. Starosta seznámil s dopisem a hovorem s osobou z Finančního úřadu pro Středočeský kraj. Doporučeno zvýšit místní koeficient z 2 na 3, aby nedošlo k propadu daně z nemovitosti. Proběhla všeobecná diskuse, ze které vyplynulo, že starosta zjistí podrobnější informace výpočtu a jaký bude přínos do příjmů obce. Starosta informace dodá zastupitelům, na vyžádání také p.Bydžovské."),

  h3("11) Různé"),
  h4("Mateřská škola – konkursní řízení ředitel/ka"),
  p("Starosta seznámil s výběrovým řízením na ředitele/ředitelku Mateřské školy. Do konkursního řízení se přihlásily 3 uchazečky. Výběrové řízení bylo dvoukolové. Konkurzní komise byla složena z:"),
  ...ul([
    "2 členové za zřizovatele",
    "člen určený Krajským úřadem Středočeského kraje",
    "člen, který je odborníkem na organizaci a řízení ve školství podle druhu a typu příslušné školy nebo školského zařízení určený Českou školní inspekcí",
    "člen, který je odborník v oblasti státní správy, určený Českou školní inspekcí",
    "člen, který je pedagogický pracovník příslušné právnické osoby vykonávající činnost školy nebo školského zařízení",
    "člen, který je školní inspektor České školní inspekce",
  ]),
  p("V 1.kole konkursní komise posuzovala, zda:"),
  ...nl([
    "jednotlivé obálky přihlášek do konkursu byly doručeny v termínu",
    "jednotlivé obálky přihlášek do konkursu byly v neporušeném stavu",
    "požadované dokumenty měly formální správnost a byly úplné",
  ]),
  p("Všechny tři uchazečky splnily všechny požadavky. Byly pozvány na vlastní konkursní řízení, které proběhlo formou řízeného rozhovoru."),
  p("Na vlastním konkursním řízení byly uchazečkám kladeny zejména dotazy z oblastí školské problematiky a další dotazy prokazující jejich přehled, znalosti, … Uchazečky byly podrobeny doplňkovému hodnocení."),
  p("Jednotliví členové komise posuzovali vhodnost jednotlivých uchazeček na pozici ředitelky mateřské školy, všechny uspěly. Poté členové konkurzní komise stanovili jednotlivé pořadí uchazeček. Na prvním místě se umístila Barbora Tejčková Poldová. Tato uchazečka byla doporučena zřizovateli jako nejlepší uchazečka na pozici ředitelky Mateřské školy Krhanice."),
  p("Zřizovatel, starosta obce Krhanice, jmenoval ředitelkou Mateřské školy Krhanice Barboru Tejčkovou Poldovou. Starosta představil paní budoucí ředitelku Barboru Tejčkovou Poldovou."),
  h5("Rozprava"),
  p("L.Maršíková: Dotaz na koncepci budoucí paní ředitelky z výběrového řízení. B.Tejčková Poldová: Po zapracování se začne věnovat představené koncepci mateřské školy."),
  h5("Návrh"),
  p("ZO bere na vědomí jmenování Barbory Tejčkové Poldové ředitelkou Mateřské školy Krhanice, okres Benešov s účinností od 1.7.2024."),

  h4("Dopravní automobil pro Zásahovou jednotku hasičů"),
  p("Informace T.Kratochvíla: Proběhlo výběrové řízení na „Dopravní automobil pro JSDHO Krhanice“. Byly osloveny čtyři firmy. Výběrové řízení proběhlo v pondělí 3.6.2024. Nabídku podala jedna firma. Hodnotícím kritériem byla nejnižší nabídková cena."),
  p("Výsledek: Číslo doručené nabídky 1. – EMBEFOR s.r.o., Korunní 2569/108, 101 00 Praha 10 - Vinohrady, IČ/RČ 06138900, nabídková cena 1 413 000 Kč bez DPH."),
  p("Nabídková cena bez DPH: 1 413 000,00 Kč. DPH: 296 730,00 Kč. Nabídková cena s DPH: 1 709 730,00 Kč."),
  p("Kromě dotace 300 tisíc Kč od Středočeského kraje je přislíbena na pořízení automobilu také dotace 450 tisíc Kč od Generálního ředitelství Hasičského záchranného sboru České republiky."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření smlouvy o dílo na „Dopravní automobil pro JSDHO Krhanice“ (EDS: 014D262004192) s firmou EMBEFOR s.r.o., IČO: 06138900, se sídlem Korunní 2569/108, 101 00 Praha 10 na celkovou částku 1 709 730,- Kč s DPH."),
  vote(V7d),
  h5("Návrh"),
  p("ZO pověřuje starostu obce uzavřením a podpisem smlouvy o dílo na akci „Dopravní automobil pro JSDHO Krhanice“ (EDS: 014D262004192) s firmou EMBEFOR s.r.o., IČO: 06138900, se sídlem Korunní 2569/108, 101 00 Praha 10."),
  vote(V7d),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje přijetí dotace ve výši 300 000,- Kč z rozpočtu Středočeského kraje ze Středočeského Fondu podpory dobrovolných hasičů a složek IZS a schvaluje uzavření veřejnoprávní smlouvy o poskytnutí dotace na akci „Dopravní automobil pro JSDHO Krhanice“."),
  vote(V8),
  h5("Návrh"),
  p("ZO pověřuje starostu obce uzavřením a podpisem veřejnoprávní smlouvy o poskytnutí dotace na akci „Dopravní automobil pro JSDHO Krhanice“ se Středočeským krajem."),
  vote(V8),

  h4("Kalkulace vodného od VHS Benešov"),
  p("Informace starosty: Byla nám předložena kalkulace cen pro vodné pro kalendářní rok 2024. Vyhláškou se musí dělat další rozbory pitné vody, tím se zvýšily náklady."),
  h5("Rozprava"),
  p("P.Bydžovský: Rozbory jsou četnější nebo podrobnější? Starosta: Dle kalkulace podrobnější."),
  h5("Návrh"),
  p("ZO schvaluje cenu vodného 73,16 Kč s DPH/1 m³ s účinností od 1.6.2024."),
  vote("PRO ( 7 ) – PROTI ( 1 – Bc. Dušová ) – ZDRŽEL SE ( 0 )"),

  h4("Smlouva o poskytování služeb – DTM ČR"),
  p("Informace starosty: Byl nám předložena Smlouva o poskytování služeb – DTM ČR od VHS Benešov. Půjde o činnosti pro skupiny technické infrastruktury – vodovodu, který je předmětem provozní smlouvy Obec – VHS."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o poskytování služeb – DTM ČR s firmou Vodohospodářská společnost Benešov, a.s., Černoleská 1600, 256 13 Benešov u Prahy, IČO: 47535865."),
  vote(V7d),

  h4("Jmenování do školské rady Základní školy Krhanice za obec"),
  p("Informace starosty: Jako zřizovatel příspěvkové organizace Základní školy Krhanice, okres Benešov, jsem do školské rady Základní školy Krhanice jmenoval na další funkční období stávající členy školské rady: Aleš Papoušek, Jaroslav Mixa, Jana Laboutková."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí jmenování členů Školské rady Základní školy Krhanice: Aleš Papoušek, Jaroslav Mixa, Jana Laboutková na další tříleté funkční období za zřizovatele."),

  h4("Výsledky ankety prvky dětská hřiště"),
  p("Tomáš Kratochvíl seznámil s anketou na doplnění dětských prvků na dětské hřiště v Prosečnici a v Krhanicích."),
  p("V anketě hlasovalo celkem: Prosečnice: 20 osob, Krhanice: 53 osob."),
  p("PROSEČNICE - VARIANTA 1P - 16 hlasů. PROSEČNICE - VARIANTA 2P - 4 hlasy."),
  p("KRHANICE - VARIANTA 1K - 26 hlasů. KRHANICE - VARIANTA 2K - 25 hlasů. KRHANICE - VARIANTA 3K - 2 hlasy."),
  h5("Rozprava"),
  p("L.Maršíková: Kdy bude realizace? Starosta: V podstatě zítra může KORO začít vytvářet poptávku."),

  h4("Informace o chodnících, okružní křižovatce, …"),
  p("Informace starosty: Starosta stručně seznámil s akcemi: Chodník podél silnice III/1066, okružní křižovatka, chodník kolem okružní křižovatky, chodník pod strání u železničního viaduktu, propojovací chodník pod železničním viaduktem. Informace o předpokládaném termínu ukončení výstavby okružní křižovatky s chodníkem. 16.8.2024."),

  h3("12) Diskuse"),
  ...ul([
    "M.Maršík: Dotaz na lokalitu Vlčí rokle nad Prosečnicí, je tam nedodělaná rekonstrukce rybníku. Starosta: Lesy ČR udělaly výběrové řízení. Vyhrála firma, která neodvedla kvalitní práci. Lesy ČR řeší oslovení jiné firmy.",
    "I.Dvořák: Dotaz na částku na software v mateřské škole. Starosta: Končí stávající mzdová účetní. Mateřská škola si zakoupí nový software na mzdy.",
    "P.Bydžovský: Návrh – zpoplatnil bych např. parkování nákladních aut na obecních pozemcích.",
  ]),

  h3("13) Závěr"),
  p("Zastupitelstvo obce bylo ukončeno v 20:35 hod."),

  p("Datum pořízení zápisu: 13.6.2024"),
  h4("Přílohy"),
  ...nl(["Svolání zastupitelstva obce", "Prezenční listina zastupitelů", "Prezenční listina občanů"]),
];

async function run() {
  const r = await publishZapis({
    cislo: "2",
    rok: "2024",
    isoDate: "2024-06-06",
    dateLabel: "6. 6. 2024",
    fullDateDot: "6.6.2024",
    pdfPath: "scripts/zapisy-pdf/zapis-2024-2.pdf",
    transcript,
  });
  console.log("OK", r.docId, "blocks", r.blocks);
}
run().catch((e) => { console.error(e); process.exit(1); });
