/* eslint-disable no-console */
import { h3, h4, h5, p, vote, nl, ul, publishZapis, type Block } from "../zapis-lib";

const transcript: Block[] = [
  h4("Přítomni"),
  p("Aleš Papoušek, Jaroslav Mixa, Tomáš Kratochvíl, Jana Laboutková, Petr Dub, Aleš Kozel, Lucie Maršíková, Šárka Dušová"),
  h4("Omluveni"),
  p("Martin Jiřička"),

  h3("1) Zahájení, přivítání přítomných, konstatování přítomnosti"),
  p("Starosta konstatoval, že zasedání bylo svoláno dne 5.12.2024, bylo vyvěšeno na úřední desce obecního úřadu, tj. tedy nejméně 7 dní před zasedáním. Bylo tedy svoláno řádně a včas v souladu se zákonem o obcích v platném znění. Starosta konstatoval, že podle prezenční listiny je přítomno 8 členů zastupitelstva, tedy nadpoloviční většina členů zastupitelstva. K předchozímu zápisu nebyly vzneseny námitky."),
  h5("Určení zapisovatele"),
  p("Zápisem zasedání zastupitelstva obce byla pověřena Ing. Alena Kratochvílová."),

  h3("2) Volba návrhové komise a ověřovatelů zápisu"),
  p("Starosta přednesl návrh návrhové komise a ověřovatelů zápisu."),
  h5("Návrh"),
  p("ZO schvaluje návrhovou komisi ve složení: Jaroslav Mixa, Jana Laboutková."),
  h5("Návrh"),
  p("ZO schvaluje ověřovatele zápisu ve složení Tomáš Kratochvíl, Petr Dub."),
  vote("PRO ( 8 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )"),

  h3("3) Schválení programu"),
  p("Starosta přečetl program."),
  ...nl([
    "Zahájení",
    "Volba návrhové komise a ověřovatelů zápisu",
    "Schválení programu",
    "Rozpočtové opatření",
    "Střednědobý výhled rozpočtu obce Krhanice na období 2024 – 2027; Rozpočet obce Krhanice na rok 2025",
    "Koupě, prodej, pronájem",
    "Různé",
    "Diskuse",
    "Závěr",
  ]),
  p("Starosta: Má někdo návrh na změnu nebo doplnění programu?"),
  h5("Návrh"),
  p("ZO schvaluje program zasedání zastupitelstva obce."),
  vote("PRO ( 8 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )"),

  h3("4) Rozpočtové opatření"),
  h4("Rozpočtové opatření č. 11/2024"),
  p("Předseda finančního výboru Petr Dub seznámil s rozpočtovým opatřením č. 11/2024."),
  h5("Rozprava"),
  p("J.Bydžovská: Dotaz na upřesnění položky – snížení částky na místní komunikaci Na Žlabech, z jakého důvodu? Starosta: Došlo k odvolání a obec nemá stavební povolení. Peníze přesuneme do dalšího roku."),
  h5("Návrh"),
  p("ZO bere na vědomí vratku 40 000,- Kč z provozního příspěvku pro rok 2024 Mateřské školy Krhanice z důvodu nevyčerpaných energií."),
  h5("Návrh"),
  p("ZO bere na vědomí vratku 500 000,- Kč z provozního příspěvku pro rok 2024 Základní školy Krhanice z důvodu nevyčerpaných energií."),
  h5("Návrh"),
  p("ZO schvaluje rozpočtové opatření č. 11/2024."),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 1 - Bc. Dušová )"),

  h3("5) Střednědobý výhled rozpočtu obce Krhanice na období 2024 – 2027; Rozpočet obce Krhanice na rok 2025"),
  h4("STŘEDNĚDOBÝ VÝHLED ROZPOČTU 2024 – 2027"),
  p("Informace starosty:"),
  p("Střednědobý výhled rozpočtu je nástrojem sloužícím pro střednědobé finanční plánování rozvoje. Sestavuje se na základě uzavřených smluvních vztahů a přijatých závazků zpravidla na 2 až 5 let následujících po roce, na který se sestavuje roční rozpočet."),
  p("Střednědobý výhled rozpočtu obsahuje souhrnné základní údaje o příjmech a výdajích, o dlouhodobých závazcích a pohledávkách, o finančních zdrojích a potřebách dlouhodobě realizovaných záměrů."),
  p("U dlouhodobých závazků se uvádí dopady na hospodaření územního samosprávného celku po celou dobu trvání závazku (v našem případě splátka zápůjčky)."),
  p("Návrh střednědobého výhledu rozpočtu byl zveřejněn dne 28.11.2024."),
  p("Starosta seznámil přítomné se Střednědobým výhledem rozpočtu na období 2024 – 2027."),

  h4("DOBROVOLNÉ-SVAZKY OBCÍ: BENE-BUS, TÝNECKO-SVAZEK OBCÍ, POSÁZAVSKÝ VODOVOD - DSO"),
  p("Informace starosty: Obec je členem následujících dobrovolných svazků obcí. Byly nám zaslány následující dokumenty a v rozpočtu obce 2025 byly vyčleněny následující finanční příspěvky."),

  h4("DSO BENE-BUS:"),
  p("Informace starosty: Byl nám předložen návrh Rozpočtu 2025 a návrh Střednědobého výhledu rozpočtu a Rozpočtové opatření č. 1."),
  p("Vyvěšeno dne 8.11.2024. Orgán určený ke schválení – valná hromada."),
  p("Návrh rozpočtu – přebytkový."),
  p("Příspěvek obce Krhanice pro rok 2025: 311 640,- Kč."),

  h4("TÝNECKO-SVAZEK OBCÍ:"),
  p("Informace starosty: Byl nám předložen návrh Rozpočtu 2025 a návrh Střednědobého výhledu rozpočtu."),
  p("Vyvěšeno dne 18.11.2024. Orgán určený ke schválení – valná hromada."),
  p("Návrh rozpočtu – vyrovnaný."),
  p("Příspěvek obce Krhanice pro rok 2025: 12 595,- Kč."),

  h4("POSÁZAVSKÝ VODOVOD – dobrovolný svazek obcí:"),
  p("Informace starosty:"),
  p("Byl nám předložen návrh Rozpočtu 2025."),
  p("Vyvěšeno dne 29.11.2024. Orgán určený ke schválení – správní rada členů."),
  p("Návrh rozpočtu – schodkový, krytý finančními prostředky minulých let."),
  p("Příspěvek obce Krhanice pro rok 2025: bez příspěvku."),

  h4("ROZPOČET 2025 - FOND OBNOVY VODOVODŮ OBCÍ KRHANICE A PROSEČNICE"),
  p("Informace starosty:"),
  p("Návrh Rozpočtu Fondu obnovy vodovodů obcí Krhanice a Prosečnice byl vyvěšen 28.11.2024."),
  p("Příjmy tvoří nájemné od VHS Benešov a 0,0025 % z celkové hodnoty majetku vodovodů k 31.12. předchozího kalendářního roku. Použití Fondu je na opravy vodovodů."),
  p("Návrh rozpočtu Fondu je vyrovnaný."),
  p("Předpoklad konečného zůstatku Fondu k 31.12.2024: 480 tisíc Kč."),

  h4("ROZPOČET OBCE KRHANICE NA ROK 2025"),
  p("Petr Dub přečetl Zápis komise pro sestavení rozpočtu 2025."),
  p("Starosta informoval o procesu sestavení návrhu rozpočtu pro rok 2025."),
  p("Starosta informoval o návrhu rozpočtu pro rok 2025."),
  p("Provozní příspěvek pro zřízené příspěvkové organizace: Základní škola Krhanice a Mateřská škola Krhanice"),
  p("Návrh Rozpočtu a Návrh Střednědobého výhledu rozpočtu příspěvkových organizací zřízených obcí Krhanice byl vyvěšen 28.11.2024."),
  p("Návrh provozního příspěvku pro příspěvkové organizace pro rok 2025:"),
  ...ul([
    "Mateřská škola Krhanice, okres Benešov: 730 950,- Kč",
    "Základní škola Krhanice, okres Benešov: 3 914 702,- Kč",
    "v tom: Středisko Základní škola: 2 935 223,- Kč",
    "Středisko Školní jídelna: 979 479,- Kč",
  ]),
  p("Starosta: Součástí Rozpočtu 2025 je Příloha."),
  p("Přílohu přečetl Tomáš Kratochvíl."),
  h5("Rozprava"),
  p("L.Maršíková: Dotaz na vybudování umělého povrchu na tréninkovém hřišti – podrobnosti. Starosta: Bude pouze zpracována dokumentace a rozpočet."),
  p("L.Maršíková: V jakém by to bylo rozsahu? Byl by umělý povrch po celé ploše současného tréninkového hřiště? Starosta: V podstatě po celé ploše."),
  p("L.Maršíková: Neuvažovalo se o vybudování hřiště v areálu Sokolky? Starosta: Zvažovalo se více možností. Ze zkušeností z Netvořic – velká hluková zátěž pro okolní zástavbu rodinnými domy – je umístění na tréninkovém hřišti před školou nejlepší varianta."),
  p("I.Dvořák: Dotaz, zda by nestačila architektonická studie, proč zpracovávat hned projektovou dokumentaci? Starosta: Nebude to projektová dokumentace pro stavební řízení. Bude to nějaká forma dokumentace a navazující vyhotovení rozpočtu."),
  p("L.Maršíková: Dotaz na částku 400 tisíc na chodník k nádrži u vrby – odkud povede? Starosta: Od Němečků dolů k nádrži."),
  p("I.Dvořák: Podle čeho se určuje, ve které části obce se bude budovat chodník? Jsou určitě i jiná důležitější místa. T.Kratochvíl: Tento chodník bude řešen v návaznosti na jednání v minulosti. Starosta: Zásadní jsou chodníky kolem hlavní silnice přes obec. Proběhla diskuse."),
  p("L.Maršíková: Dotaz na střechu spojovacího krčku mezi školou a jídelnou. Nešlo by taky zateplit jídelnu? J.Mixa: Do spojovacího krčku skrz střechu zatéká. Tím musíme začít. Chceme krček zastřešit a zateplit. Jídelna bude řešena z hlediska zastřešení a zateplení později."),
  p("L.Maršíková: Dotaz na kanalizaci. V projektu jsou 4 miliony na projekt čističky. Není to zbytečné, když nemáme vyřešeno financování? Starosta: Jsou to v rozpočtu uvolněné peníze na tento projekt. Může se a také nemusí uskutečnit."),
  p("L.Maršíková: Kolik stála zpráva Vodamu a jaké bylo zadání? Starosta: 20 tisíc. Zadání bylo zhodnocení dosavadních prací, návaznost na územní plán, … až po odhad ceny splaškové vody objemu 1 metr kubický pro občany Krhanic. Proběhla diskuse se závěrem, že starosta zjistí dotační možnosti na čistírnu a splaškové řady a zda se z dotace mohou hradit napojení nemovitostí na splaškovou kanalizaci."),
  p("L.Maršíková: Podává Kulturní komise podrobný rozpočet na kulturní akce? P.Dub: Podává."),
  p("L.Maršíková: Dotaz na financování praporu na výročí hasičského sboru? T.Kratochvíl: Sbor by si mohl zaplatit prapor sám, proto si ho objednal. Vydal by se ze všech financí, proto požádal o finanční podpory obec a sponzory."),
  h5("Návrh"),
  p("ZO schvaluje Střednědobý výhled rozpočtu obce Krhanice na období 2024 – 2027."),
  vote("PRO ( 6 ) – PROTI ( 2 – Maršíková, Bc. Dušová ) – ZDRŽEL SE ( 0 )"),
  h5("Návrh"),
  p("ZO bere na vědomí, že Rozpočet Bene-Bus dobrovolný svazek obcí na rok 2025 je přebytkový a bere na vědomí Střednědobý výhled rozpočtu Bene-Bus dobrovolný svazek obcí na období 2026-2028 a bere na vědomí Rozpočtové opatření č. 1/2024."),
  h5("Návrh"),
  p("ZO bere na vědomí, že Rozpočet 2025 Týnecko-svazek obcí je vyrovnaný a bere na vědomí Střednědobý výhled rozpočtu na období 2025-2027."),
  h5("Návrh"),
  p("ZO bere na vědomí, že Rozpočet 2025 Posázavský vodovod – dobrovolný svazek obcí je schodkový a bude kryt finančními prostředky z minulých let."),
  h5("Návrh"),
  p("ZO schvaluje Rozpočet Fondu financování obnovy vodovodů obcí Krhanice a Prosečnice pro rok 2025 jako vyrovnaný."),
  vote("PRO ( 8 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )"),
  h5("Návrh"),
  p("ZO schvaluje Přílohu Rozpočtu obce Krhanice na rok 2025."),
  vote("PRO ( 6 ) – PROTI ( 2 - Maršíková, Bc. Dušová ) – ZDRŽEL SE ( 0 )"),
  h5("Návrh"),
  p("ZO schvaluje Rozpočet obce Krhanice na rok 2025 jako schodkový. Schodek bude hrazen finančními prostředky z minulých let."),
  vote("PRO ( 6 ) – PROTI ( 2 - Maršíková, Bc. Dušová ) – ZDRŽEL SE ( 0 )"),

  h3("6) Koupě, prodej, pronájem"),
  ...ul(["pronajmout část pozemku parc. č. 59/1 k.ú. Krhanice o výměře 941,2 m² ke zřízení zahrádky za cenu 10,- Kč/1 m²/rok od 1.1.2025 do 31.12.2025."]),
  p("Informace starosty: Jedná se o žádost manželů Klapáčových. Jedná se o pozemek za hasičskou zbrojnicí."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronájem části pozemku parc. č. 59/1 k.ú. Krhanice o výměře 941,2 m² ke zřízení zahrádky za cenu 10,- Kč/1 m²/rok od 1.1.2025 do 31.12.2025 Janu a Jaroslavě Klapáčovým, Hennerova 3/2009, 150 00 Praha 5."),
  vote("PRO ( 6 ) – PROTI ( 1 – Bc. Dušová ) – ZDRŽEL SE ( 1 - Maršíková )"),
  ...ul(["pronajmout pozemek parc. č. 423/5 k.ú. Krhanice o výměře 469 m² ke zřízení zahrádky za cenu 10,- Kč/1 m²/rok od 1.1.2025 na dobu 4 let."]),
  p("Informace starosty: Jedná se o žádost Michala Caro – nový majitel objektu Krhanice č.ev.34."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronájem pozemku parc. č. 423/5 k.ú. Krhanice o výměře 469 m² ke zřízení zahrádky za cenu 10,- Kč/1 m²/rok od 1.1.2025 na dobu 4 let Ing. Michalu Caro, Ořechova č.ev. 794, 250 00 Zdiby Brnky."),
  vote("PRO ( 6 ) – PROTI ( 1 – Bc. Dušová ) – ZDRŽEL SE ( 1 - Maršíková )"),
  ...ul(["prodat stavební pozemek č. st. 474 k.ú. Krhanice o výměře 39 m², na jehož pozemku se nachází rekreační objekt č.ev. 34 za cenu stanovenou znaleckým posudkem."]),
  p("Informace starosty: Jedná se o žádost manželů Ing. Michal Caro a Ing. Blanka Caro – noví majitelé Krhanice č.ev. 34. Rádi by vyřešili historický stav – nesoulad vlastnictví objektu (soukromý majitel) a stavebního pozemku (vlastník obec). Pozemek se nachází v chatové oblasti Svatovice."),
  h5("Rozprava"),
  p("Proběhla diskuse se závěrem, že zastupitelstvo rozhodne o prodeji za cenu znaleckého posudku. To se sdělí manželům Caro a oni se vyjádří, zda s tímto postupem souhlasí."),
  h5("Návrh"),
  p("ZO schvaluje záměr budoucího prodeje stavebního pozemku č. st. 474 k.ú. Krhanice a schvaluje zadání vyhotovení znaleckého posudku pro budoucí prodej stavebního pozemku č. st. 474 k.ú. Krhanice o výměře 39 m², na jehož pozemku se nachází rekreační objekt č.ev. 34."),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 1 - Bc. Dušová )"),
  ...ul(["pronajmout část pozemku parc. č. 1972/6 k.ú. Krhanice o výměře 4,6 m² pro stávající jímku odpadních vod včetně potrubí pro přítok odpadních vod do podzemní části pod tímto pozemkem o výměře 8,74 m³ a dále pro provoz této jímky odpadních vod za cenu 100 Kč/m³/rok od 1.4.2025 na dobu 4 let."]),
  p("Informace starosty: Jedná se o žádost Roberta Novotného – pokračování smlouvy. Jedná se o pozemek pod hospodou."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronájem části pozemku parc. č. 1972/6 k.ú. Krhanice o výměře 4,6 m² pro stávající jímku odpadních vod včetně potrubí pro přítok odpadních vod do podzemní části pod tímto pozemkem o výměře 8,74 m³ a dále pro provoz této jímky odpadních vod za cenu 100 Kč/m³/rok od 1.4.2025 na dobu 4 let Robertu Novotnému, Krhanice č.p. 62, 257 42 Krhanice."),
  vote("PRO ( 6 ) – PROTI ( 1 – Bc. Dušová ) – ZDRŽEL SE ( 1 - Maršíková )"),

  h3("7) Různé"),
  h4("DSO SPOLEČNÁ VODA"),
  p("Informace starosty: Na zastupitelstvu jsme schválili záměr vstupu obce Krhanice do DSO Společná voda. Nyní budeme schvalovat usnesení, která zahajují tento proces. Schválíme Dohodu vlastníků provozně souvisejících vodovodů s městysem Davle, IČO: 002 41 156, městem Jílové u Prahy, IČO: 002 41 326, obcí Kamenný Přívoz, IČO: 002 41 351, obcí Krhanice, IČO: 002 32 025, obcí Libeř, IČO: 002 41 415, obcí Petrov, IČO: 002 41 539 a Posázavský vodovod – dobrovolný svazek obcí, IČO: 141 17 223, jehož jsme členy."),
  p("Předmětem dohody je vymezení vzájemných práv a povinností při předávce pitné vody mezi dvěma vodovody a při zajištění kvalitního a plynulého provozování provozně souvisejících vodovodů, včetně sjednaných limitů ročního množství dodávky pitné vody. Účelem dohody je upravit vztahy mezi vlastníky (Posázavský vodovod – dobrovolný svazek obcí – vlastník 1, městys Davle – vlastník 2, město Jílové u Prahy – vlastník 3, obcí Kamenný Přívoz – vlastník 4, obcí Krhanice – vlastník 5, obcí Libeř – vlastník 6 a obcí Petrov – vlastník 7). Dohoda je na dobu neurčitou. Uzavření této dohody, včetně všech povinných náležitostí ukládá jednotlivým vlastníkům provozně souvisejících vodovodů zákon o vodovodech a kanalizacích."),
  p("Informace starosty: Dále budeme schvalovat Dohodu vlastníků provozně souvisejících vodovodů s městem Týnec nad Sázavou, IČO: 002 32 904 a Posázavský vodovod – dobrovolný svazek obcí, IČO: 14117223."),
  p("Předmětem dohody je vymezení vzájemných práv a povinností při předávce pitné vody mezi dvěma vodovody a při zajištění kvalitního a plynulého provozování provozně souvisejících vodovodů, včetně sjednaných limitů ročního množství dodávky pitné vody. Účelem dohody je upravit vztahy mezi vlastníky (obcí Krhanice – vlastník 1, městem Týnec nad Sázavou – vlastník 2 a Posázavský vodovod – dobrovolný svazek obcí – vedlejší účastník). Dohoda je na dobu neurčitou. Uzavření této dohody, vč. všech povinných náležitostí ukládá jednotlivým vlastníkům provozně souvisejících vodovodů zákon o vodovodech a kanalizacích."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Dohodu vlastníků provozně souvisejících vodovodů s Posázavský vodovod – dobrovolný svazek obcí, IČO: 141 17 223, Masarykovo náměstí 194, 254 01 Jílové u Prahy, městysem Davle, IČO: 002 41 156, Na náměstí 63, 252 06 Davle, městem Jílové u Prahy, IČO: 002 41 326, Masarykovo náměstí 194, 254 01 Jílové u Prahy, obcí Kamenný Přívoz, IČO: 002 41 351, Kamenný Přívoz 285, Kamenný Přívoz 252 82, obcí Krhanice, IČO: 002 32 025, Krhanice 46, Krhanice 257 42, obcí Libeř, IČO: 002 41 415, Libeř 35, Libeř 25241 a obcí Petrov, IČO: 002 41 539, Hlavní 30, Petrov 252 81."),
  vote("PRO ( 8 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )"),
  h5("Návrh"),
  p("ZO pověřuje starostu obce podpisem Dohody vlastníků provozně souvisejících vodovodů s Posázavský vodovod – dobrovolný svazek obcí, IČO: 141 17 223, Masarykovo náměstí 194, 254 01 Jílové u Prahy, městysem Davle, IČO: 002 41 156, Na náměstí 63, 252 06 Davle, městem Jílové u Prahy, IČO: 002 41 326, Masarykovo náměstí 194, 254 01 Jílové u Prahy, obcí Kamenný Přívoz, IČO: 002 41 351, Kamenný Přívoz 285, Kamenný Přívoz 252 82, obcí Krhanice, IČO: 002 32 025, Krhanice 46, Krhanice 257 42, obcí Libeř, IČO: 002 41 415, Libeř 35, Libeř 25241 a obcí Petrov, IČO: 002 41 539, Hlavní 30, Petrov 252 81."),
  vote("PRO ( 8 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )"),
  h5("Návrh"),
  p("ZO schvaluje Dohodu vlastníků provozně souvisejících vodovodů obce Krhanice, IČO: 002 32 025 s městem Týnec nad Sázavou, IČO: 002 32 904 a Posázavský vodovod – dobrovolný svazek obcí, IČO: 141 17 223."),
  vote("PRO ( 8 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )"),
  h5("Návrh"),
  p("ZO pověřuje starostu obce podpisem Dohody vlastníků provozně souvisejících vodovodů obce Krhanice, IČO: 002 32 025 s městem Týnec nad Sázavou, IČO: 002 32 904 a Posázavský vodovod – dobrovolný svazek obcí, IČO: 141 17 223."),
  vote("PRO ( 8 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )"),

  h4("NAVÝŠENÍ VODNÉHO"),
  p("Informace starosty: Byla nám zaslána kalkulace vodného pro rok 2025."),
  p("Navýšila se cena za 1 m³ vody pro Posázavský vodovod o 8,95 Kč , takže se to promítne jako hlavní navýšení ceny vodného pro další rok. Celkově se zvedne cena 1 m³ o 8,78 Kč bez DPH. Konečná cena bude 74,10 Kč bez DPH/1 m³ pitné vody + DPH 12%."),
  h5("Rozprava"),
  p("Bc. Dušová: Dotaz, zda nelze vzít cenu vodného pouze na vědomí. Starosta: Ne."),
  h5("Návrh"),
  p("ZO schvaluje cenu vodného od 1.1.2025 ve výši 74,10 Kč bez DPH/1 m³."),
  vote("PRO ( 7 ) – PROTI ( 1 – Bc. Dušová ) – ZDRŽEL SE ( 0 )"),

  h4("DÍLČÍ PŘEZKOUMÁNÍ HOSPODAŘENÍ OBCE KRHANICE"),
  p("Informace starosty: Dne 6.12.2024 se uskutečnilo dílčí přezkoumání hospodaření obce ze strany Středočeského kraje, odboru kontroly s výsledkem – nebyly zjištěny chyby a nedostatky."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí Zápis z dílčího přezkoumání hospodaření územního celku obce Krhanice z 6.12.2024."),

  h4("OBECNÍ KNIHOVNA KRHANICE"),
  p("Informace starosty: Návrh v pokračování v roce 2025 s osvobozením od placení registračního poplatku."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Dodatek č. 15 k Příloze č. 1 Knihovního řádu Obecní knihovny Krhanice Výpůjční řád."),
  vote("PRO ( 8 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )"),

  h4("SOUHLAS SE VZNIKEM PRACOVNĚPRÁVNÍCH VZTAHŮ ZASTUPITELŮ"),
  p("Informace starosty: Podle zákona č. 128/2000 Sb., o obcích, § 84 odst. 2 písm. p) je zastupitelstvu obce vyhrazeno vyslovovat souhlas se vznikem pracovněprávního vztahu mezi obcí a členem zastupitelstva obce. Protože takové pracovně právní vztahy jsou reálné, následuje jejich výčet:"),
  ...ul(["oblast Činnosti knihovnické: Bc. Petr Dub."]),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje a souhlasí se vznikem pracovněprávních vztahů mezi obcí a členem zastupitelstva obce s platností od 1.1.2025 do 31.12.2025, a to oblast Činnosti knihovnické: Bc. Petr Dub. Dohody budou uzavírány v průběhu roku 2025 dle konkrétních potřeb obce."),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 1 - Dub )"),

  h4("ZPRÁVA KRHANICE – KANALIZACE A ČISTÍRNA ODPADNÍCH VOD"),
  p("Informace starosty: Starosta seznámil přítomné se zprávou od firmy PROJEKTY VODAM s.r.o."),
  p("Nyní budu zjišťovat informace o dotacích a o spoluúčasti občanů na budování jednotlivých kanalizačních přípojek k nemovitostem, abychom měli kompletní přehled."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí Zprávu Krhanice – kanalizace a čistírna odpadních vod vypracovanou firmou PROJEKTY VODAM s.r.o., Galašova 158, 753 01 Hranice."),

  h4("DOPLŇKOVÁ ČINNOST"),
  p("Informace starosty: Na základě minulého zastupitelstva jsem dohledal materiály k doplňkové činnosti Základní školy Krhanice. Přečtu Vám výpis ze Zřizovací listiny základní školy pro doplňkovou činnost."),
  p("Základní škola – výpis ze Zřizovací listiny příspěvkové organizace Základní škola Krhanice, okres Benešov, Krhanice 149, 257 42 Krhanice ze dne 22.10.2009 :"),
  h5("Okruhy doplňkové činnosti"),
  p("Zřizovatel povoluje níže uvedené okruhy doplňkové činnosti, které navazují na hlavní účel a předmět činnosti příspěvkové organizace:"),
  ...ul([
    "pronájem učeben, tělocvičného sálku, školní jídelny a dalších nebytových prostor, k tomuto pronájmu na dobu delší než 29 dní je nutný předchozí souhlas zřizovatele.",
    "pronájem movitého majetku souvisejícího s pronájmem uvedeným v bodě a).",
    "stravování i jiným zájemcům – osobám samostatně výdělečně činným podnikajícím v obci Krhanice, osobám pobírajícím starobní důchod, pracovníkům školských zařízení zřizovaných obcí Krhanice, popř. jiným zájemcům, ovšem pouze tehdy, dovoluje-li to kapacita školní jídelny a hygienické předpisy.",
  ]),
  p("Podmínkou doplňkové činnosti je:"),
  ...ul([
    "doplňková činnost nesmí narušovat plnění hlavního účelu a činnosti příspěvkové organizace,",
    "doplňková činnost musí být v souladu se zněním zákona č. 250/2000 Sb., o rozpočtových pravidlech územních rozpočtů, ve znění pozdějších předpisů,",
    "oddělené sledování nákladů a výnosů doplňkové činnosti a použití zisku v souladu se zněním zákona č. 250/2000 Sb., o rozpočtových pravidlech územních rozpočtů, ve znění pozdějších předpisů,",
    "dodržování podmínek stanovených směrnicí, pokynem nebo rozhodnutím vydaným zřizovatelem.",
  ]),
  p("Jako zřizovatel sdělím informaci ředitelce základní školy, stejně jako v případě příspěvkové organizace Mateřská škola Krhanice, aby došlo k sjednocení podmínek doplňkové činnosti u obou příspěvkových organizací. Ředitelka si vytvoří pravidla a kalkulaci doplňkové činnosti. A my zrušíme Pravidla pronájmu místností Základní školy Krhanice schválená zastupitelstvem obce dne 18.9.2017."),
  h5("Rozprava"),
  p("J.Bydžovská: Je tedy zcela v pravomoci ředitelek základní a mateřské školy, jaký zvolí nájem? Starosta: Ano. Každopádně doplňková činnost musí být výdělečná."),
  h5("Návrh"),
  p("ZO ruší Pravidla pronájmu místností Základní školy Krhanice schválené Zastupitelstvem obce Krhanice dne 18.9.2017."),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 1 – Bc. Dušová )"),

  h4("ODPADOVÉ HOSPODÁŘSTVÍ V ROCE 2025"),
  p("Místostarosta informoval o doplnění Obecně závazné vyhlášky obce Krhanice o stanovení obecního systému odpadového hospodářství. Doplnění se týká sběru textilu od 1.1.2025. Obec má šedý kontejner na textil na stanovišti u víceúčelového hřiště. Nově dojde k rozšíření míst pro sběr textilu do červených nádob – u víceúčelového hřiště v Krhanicích a v Prosečnici v kontejnerovém stání. Dále místostarosta informoval o sběru komunálního odpadu – známky na popelnice, týden prodeje známek v posledním týdnu měsíce února."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Obecně závaznou vyhlášku obce Krhanice o stanovení obecního systému odpadového hospodářství."),
  vote("PRO ( 6 ) – PROTI ( 0 ) – ZDRŽEL SE ( 2 – Maršíková, Bc. Dušová )"),

  h3("8) Diskuse"),
  ...ul([
    "I.Dvořák: Dotaz ke kanalizaci. V Prosečnici se platí daleko větší částka, nehrozí něco takového v Krhanicích? Starosta: V minulém roce se do ceny za m3 promítla oprava čerpadel přečerpávací stanice. V Prosečnici se nejedná o čistírnu, ale přečerpávací stanici splaškových vod.",
    "I.Dvořák: Dotaz na koncentraci CO2 ve škole? Zda si obec nechce nechat zkontrolovat tuto koncentraci? Starosta: Ředitelka školy si nechala zpracovat měření s výsledkem vyhovující.",
    "I.Dvořák: Dotaz na klubovnu víceúčelového hřiště, zda se plánuje něco udělat s akustikou? Starosta: Ne, nechceme snižovat výšku stropu. I.Dvořák: Doma jsme řešili akustiku římskými roletami. Starosta: Můžeme zkusit závěsy.",
    "I.Dvořák: Dotaz na pozemek pod fotovoltaickou elektrárnou, kdo bude zpracovávat územní studii? Starosta: Územní studie už nejsou potřeba. Návrh zastavitelnosti a vzhled nemovitostí jsme v minulosti obdrželi.",
    "J.Bydžovská: Proč obec nechce, aby ČEZ umístil kabel elektrického vedení do pozemku obce? Starosta: V této lokalitě je spousta nedořešených věcí a mimo jiné nejsou známy hranice pozemků.",
    "M.Maršík: Jakým způsobem se zjišťoval u občanů zájem o AlzaBox? T.Kratochvíl: Zájem se nezjišťoval, iniciativa vyšla z Komise pro obnovu a rozvoj obce.",
    "L.Maršíková: Upozornila na světelný smog AlzaBoxu. Alza má i jiné možnosti, box nemusí svítit nepřetržitě.",
    "I.Voytash: Dotaz na kanalizaci a vodovod v naší uličce, bude se možné připojit? Starosta: Obec osloví majitele nemovitostí, zda chtějí vodovod.",
    "I.Kratochvílová: Poděkovala obci za podporu Sboru dobrovolných hasičů Krhanice.",
  ]),
  p("Ivana Kratochvílová popřála všem k vánočním svátkům a do nového roku 2025."),

  h3("9) Závěr"),
  p("Zastupitelstvo obce bylo ukončeno v 17:45 hod."),

  p("Datum pořízení zápisu: 23.12.2024"),
  p("Ověřovatelé zápisu a starosta obce, podepsáno v listinné podobě."),
  h4("Přílohy"),
  ...nl([
    "Svolání zastupitelstva obce",
    "Prezenční listina zastupitelů",
    "Prezenční listina občanů",
  ]),
];

async function run() {
  const r = await publishZapis({
    cislo: "6",
    rok: "2024",
    isoDate: "2024-12-13",
    dateLabel: "13. 12. 2024",
    fullDateDot: "13.12.2024",
    pdfPath: "scripts/zapisy-pdf/zapis-2024-6.pdf",
    transcript,
  });
  console.log("OK", r.docId, "blocks", r.blocks);
}
run().catch((e) => { console.error(e); process.exit(1); });
