/* eslint-disable no-console */
// One-off: faithful transcript of Zápis č. 3/2022 (2.5.2022), transcribed
// VISUALLY from the official PDF (14 pages). Structure per AGENT-SPEC.md and
// the approved golden sample scripts/build-zapis-2026-1.ts.
import { h3, h4, h5, p, vote, nl, ul, publishZapis, type Block } from "../zapis-lib";

const V7 = "PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )";

const transcript: Block[] = [
  h4("Přítomni"),
  p("Aleš Papoušek, Jaroslav Mixa, Václav Zíta, Tomáš Kratochvíl, Petr Dub, Martin Jiřička, Bohuslav Kadeřábek"),
  h4("Omluveni"),
  p("Edita Jarošová, Jana Laboutková"),

  h3("1) Zahájení, přivítání přítomných, konstatování přítomnosti"),
  p("Starosta konstatoval, že zasedání bylo svoláno dne 25.4.2022 bylo vyvěšeno na úřední desce obecního úřadu, tj. tedy nejméně 7 dní před zasedáním. Bylo tedy svoláno řádně a včas v souladu se zákonem o obcích v platném znění. Starosta konstatoval, že podle prezenční listiny je přítomno 7 členů zastupitelstva, tedy nadpoloviční většina členů zastupitelstva. K předchozímu zápisu nebyly vzneseny námitky."),
  h5("Určení zapisovatele"),
  p("Zápisem zasedání zastupitelstva obce byla pověřena Ing. Alena Kratochvílová."),
  p("Starosta přečetl program."),
  ...nl([
    "Zahájení",
    "Volba návrhové komise a ověřovatelů zápisu",
    "Zpráva finančního výboru o kontrole hospodaření obce Krhanice za rok 2021; Zpráva o výsledcích veřejnosprávních kontrol hospodaření Mateřské školy Krhanice a Základní školy Krhanice za rok 2021",
    "Schválení účetní závěrky Mateřské školy Krhanice a Základní školy Krhanice za rok 2021",
    "Schválení účetní závěrky obce Krhanice za rok 2021",
    "Závěrečný účet obce Krhanice pro rok 2021",
    "Obecně závazná vyhláška obce",
    "Rozpočtové opatření",
    "Koupě, prodej, pronájem",
    "Různé",
    "Diskuse",
    "Usnesení a závěr",
  ]),
  p("Proběhlo hlasování o programu."),
  h5("Návrh"),
  p("ZO schvaluje program zasedání zastupitelstva obce."),
  vote(V7),

  h3("2) Volba návrhové komise a ověřovatelů zápisu"),
  p("Starosta přednesl návrh návrhové komise a ověřovatelů zápisu."),
  h5("Návrh"),
  p("ZO schvaluje návrhovou komisi ve složení Jaroslav Mixa, Petr Dub."),
  h5("Návrh"),
  p("ZO schvaluje ověřovatele zápisu ve složení Václav Zíta, Tomáš Kratochvíl."),
  vote(V7),

  h3("3) Zpráva finančního výboru o kontrole hospodaření obce Krhanice za rok 2021; Zpráva o výsledcích veřejnosprávních kontrol hospodaření Mateřské školy Krhanice a Základní školy Krhanice za rok 2021"),
  p("Bohuslav Kadeřábek seznámil s kontrolou hospodaření obce Krhanice za rok 2021. A dále seznámil s proběhlými veřejnosprávními kontrolami hospodaření příspěvkových organizací Mateřské školy Krhanice a Základní školy Krhanice. Kontroly proběhly dne 25.4.2022."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí zprávu finančního výboru o kontrole hospodaření obce Krhanice za rok 2021 ze dne 25.4.2022."),
  h5("Návrh"),
  p("ZO bere na vědomí protokoly o průběhu a výsledcích veřejnosprávních kontrol příspěvkových organizací Základní škola Krhanice a Mateřská škola Krhanice za rok 2021 ze dne 25.4.2022."),

  h3("4) Schválení účetní závěrky Mateřské školy Krhanice a Základní školy Krhanice za rok 2021"),
  h4("Mateřská škola Krhanice"),
  p("Starosta (zřizovatel) seznámil přítomné se Zprávou zřizovatele k podkladům pro schválení účetní závěrky příspěvkové organizace Mateřská škola Krhanice, okres Benešov za rok 2021."),
  p("Starosta (zřizovatel) doporučuje na základě této zprávy přijmout tento návrh usnesení zastupitelstva ve věci schválení účetní závěrky Mateřské školy v tomto znění:"),
  p("ZO schvaluje účetní závěrku příspěvkové organizace Mateřská škola Krhanice, okres Benešov za rok 2021; schvalovaná účetní závěrka poskytuje věrný a poctivý obraz předmětu účetnictví a finanční situace účetní jednotky."),
  p("Starosta přečetl „Protokol o schvalování účetní závěrky za rok 2021 příspěvkové organizace Mateřská škola Krhanice, okres Benešov“."),
  p("Ředitelka Mateřské školy Krhanice sdělila, že se k protokolu vyjádří písemně."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje účetní závěrku příspěvkové organizace Mateřská škola Krhanice, okres Benešov za rok 2021; schvalovaná účetní závěrka poskytuje věrný a poctivý obraz předmětu účetnictví a finanční situace účetní jednotky."),
  vote(V7),
  h5("Návrh"),
  p("ZO schvaluje rozdělení hospodářského výsledku příspěvkové organizace Základní škola Krhanice za rok 2021 ve výši 1 991,81 Kč do rezervního fondu."),
  vote(V7),
  h5("Návrh"),
  p("ZO schvaluje Protokol o schvalování účetní závěrky za rok 2021 příspěvkové organizace Mateřská škola Krhanice, okres Benešov."),
  vote(V7),

  h4("Základní škola Krhanice"),
  p("Starosta (zřizovatel) seznámil přítomné se Zprávou zřizovatele k podkladům pro schválení účetní závěrky příspěvkové organizace Základní škola Krhanice, okres Benešov za rok 2021."),
  p("Starosta (zřizovatel) doporučuje na základě této zprávy přijmout tento návrh usnesení zastupitelstva ve věci schválení účetní závěrky Základní školy v tomto znění:"),
  p("ZO schvaluje účetní závěrku příspěvkové organizace Základní škola Krhanice, okres Benešov za rok 2021; schvalovaná účetní závěrka poskytuje věrný a poctivý obraz předmětu účetnictví a finanční situace účetní jednotky."),
  p("Starosta přečetl „Protokol o schvalování účetní závěrky za rok 2021 příspěvkové organizace Základní škola Krhanice, okres Benešov“."),
  p("Ředitelka Základní školy Krhanice sdělila, že se k protokolu vyjádří písemně."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje účetní závěrku příspěvkové organizace Základní škola Krhanice, okres Benešov za rok 2021; schvalovaná účetní závěrka poskytuje věrný a poctivý obraz předmětu účetnictví a finanční situace účetní jednotky."),
  vote(V7),
  h5("Návrh"),
  p("ZO schvaluje rozdělení hospodářského výsledku příspěvkové organizace Základní škola Krhanice za rok 2021 ve výši 36 325,09 Kč do rezervního fondu."),
  vote(V7),
  h5("Návrh"),
  p("ZO schvaluje Protokol o schvalování účetní závěrky za rok 2021 příspěvkové organizace Základní škola Krhanice, okres Benešov."),
  vote(V7),

  h3("5) Schválení účetní závěrky obce Krhanice za rok 2021"),
  p("Bohuslav Kadeřábek seznámil přítomné se Zprávou Finančního výboru obce Krhanice k podkladům pro schválení účetní závěrky obce Krhanice za rok 2021."),
  p("Finanční výbor doporučuje na základě této zprávy přijmout tento návrh usnesení zastupitelstva ve věci schválení účetní závěrky obce Krhanice v tomto znění:"),
  p("ZO schvaluje účetní závěrku obce Krhanice, okres Benešov za rok 2021; schvalovaná účetní závěrka poskytuje věrný a poctivý obraz předmětu účetnictví a finanční situace účetní jednotky."),
  p("Finanční výbor dále doporučuje schválit výsledek hospodaření ve schvalovacím řízení za rok 2021 obce Krhanice v částce + 9 168 752,17 Kč a jeho převod na účet 432 výsledek hospodaření předchozích účetních období."),
  p("Starosta přečetl „Protokol o schvalování účetní závěrky za rok 2021 obce Krhanice“."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje účetní závěrku obce Krhanice za rok 2021; schvalovaná účetní závěrka poskytuje věrný a poctivý obraz předmětu účetnictví a finanční situace účetní jednotky."),
  vote(V7),
  h5("Návrh"),
  p("ZO schvaluje výsledek hospodaření ve schvalovacím řízení za rok 2021 obce Krhanice a jeho převod na účet 432 výsledek hospodaření předchozích účetních období."),
  vote(V7),
  h5("Návrh"),
  p("ZO schvaluje Protokol o schvalování účetní závěrky za rok 2021 obce Krhanice."),
  vote(V7),

  h3("6) Závěrečný účet obce Krhanice pro rok 2021"),
  p("Starosta seznámil se Závěrečným účtem obce Krhanice pro rok 2021. Návrh Závěrečného účtu včetně příloh byl vyvěšen na úřední desce a elektronické úřední desce dne 31.3.2022. Závěrečný účet obsahuje přehled hospodaření obce za rok 2021, hospodaření zřízených příspěvkových organizací za rok 2021 a Zprávu z celkového přezkoumání hospodaření obce. Do Závěrečného účtu bude vložena dodatečná informace o schválení účetní závěrky za rok 2021 za obec Krhanice, MŠ a ZŠ Krhanice zastupitelstvem obce dne 2.5.2022. Závěrečný účet za rok 2021 bude vyvěšen až do doby schválení nového Závěrečného účtu za rok 2022."),
  p("Písemné připomínky k závěrečnému účtu nebyly podány. Ústní připomínky: „Má někdo z přítomných připomínky k závěrečnému účtu obce?“"),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Závěrečný účet obce Krhanice za rok 2021 a dává souhlas s celoročním hospodařením, a to bez výhrad."),
  vote(V7),

  h3("7) Obecně závazná vyhláška obce"),
  p("Informace místostarosty: Bude se měnit vyhláška o nočním klidu – proběhlé či zrušené akce budou z vyhlášky vyňaty a budou aktualizovány termíny u tradičních akcí."),
  h5("Rozprava"),
  p("L.Maršíková: Požádala o doplnění akce Letní kino 5.8 – 6.8.2022 od 22:00 do 0:00 hod. Starosta: Místostarosta akci do vyhlášky doplní."),
  h5("Návrh"),
  p("ZO schvaluje Obecně závaznou vyhlášku obce Krhanice, o nočním klidu."),
  vote(V7),

  h3("8) Rozpočtové opatření"),
  p("Starosta seznámil s rozpočtovým opatřením č. 3/2022 ze dne 13.4.2022, kterým se reaguje na postup k zajištění jednotného zatřídění výdajů s poskytnutou pomocí Ukrajině. Příspěvek na stravné pro děti ukrajinských uprchlíků v základní škole a mateřské škole – řešeno jako navýšení provozního příspěvku základní škole v paragrafu humanitární zahraniční pomoc přímá."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí a schvaluje rozpočtové opatření č. 3/2022."),
  vote(V7),

  h4("Pomoc Ukrajině"),
  p("Informace starosty: Nová pravidla pro pomoc Ukrajině:"),
  p("Na minulém zastupitelstvu jsme schválili pravidla pro poskytování humanitární pomoci na území obce Krhanice zahraničním uprchlíkům z Ukrajiny, kteří získali víza pro azyl na území naší obce (jsou ubytováni zejména u našich občanů), termínově do 30.6.2022."),
  p("Vzhledem k vývoji situace na Ukrajině a dále k přístupu našeho státu k uprchlíkům (řešení příspěvků), nastala potřeba tato pravidla upravit. Hlavním záměrem je podpora dětí, zejména těch, které máme v základní škole a mateřské škole, a to do konce tohoto kalendářního roku."),
  p("PRAVIDLA – PLATNOST OD 3.5.2022 DO 31.12.2022"),
  p("Nová pravidla – pomoc bude určena ukrajinským dětem v mateřských a základních školách, kteří získali víza pro azyl na území naší obce (jsou ubytováni zejména u našich občanů):"),
  ...nl([
    "navýšení provozního příspěvku základní škole Krhanice v rámci humanitární zahraniční pomoci přímé na úhradu stravného (včetně svačinek) pro děti mateřské školy Krhanice a žáky základní školy Krhanice: 30.000,- Kč,",
    "školné v mateřské škole a školné v družině v základní škole,",
    "úhrada služeb za obědy pro děti mateřské školy (včetně svačinek) v jiných školních jídelnách.",
  ]),
  h5("Rozprava"),
  p("I.Dvořák: Kolik je tu dětí z Ukrajiny? Starosta: 9 dětí ve škole, 1 dítě ve školce a 1 dítě ve školce v Týnci."),
  p("I.Dvořák: Jakým způsobem se oslovovali lidi, aby ubytovali ukrajinské občany. Starosta: Oslovovali jsme ty, kteří by je mohli potencionálně ubytovat. Jinak máme seznam Ukrajinců od Ministerstva vnitra ČR."),
  h5("Návrh"),
  p("ZO schvaluje nová pravidla pro poskytování humanitární pomoci na území obce Krhanice zahraničním uprchlíkům z Ukrajiny od 3.5.2022 do 31.12.2022."),
  vote(V7),

  h4("Česká spořitelna – bankovní účty, bankovní karta"),
  p("Informace starosty:"),
  p("Spořící účet:"),
  p("Základní popis produktu:"),
  p("Jedná se o depozitní běžný účet, který není určen pro platební styk."),
  p("Spořící účet bude úročen zvýhodněnou roční úrokovou sazbou ve výši 2,50%p.a. po dobu 2 měsíců."),
  p("Minimální doba zvýhodněné roční úrokové sazby je 1 měsíc, maximální doba je 12 měsíců."),
  p("Minimální zůstatek na spořícím účtu je 5.000.000,- Kč."),
  p("Spořící účet je veden zcela zdarma."),
  p("Omezení produktu:"),
  p("Prostředky na účtu nejsou vázány."),
  p("Jsou povoleny pouze 4 odchozí platby měsíčně, příchozí platby nejsou omezeny."),
  p("Měsíční připisování úroků."),
  p("Výpisy měsíčně elektronicky nebo poštou."),
  p("Vkladový účet:"),
  p("Základní popis produktu:"),
  p("Účet určený k ukládání a zhodnocování dočasně volných finančních prostředků na předem definované období."),
  p("Vkladový účet bude veden v měně CZK."),
  p("Vkladový účet bude úročen zvýhodněnou roční úrokovou sazbou ve výši:"),
  ...ul([
    "3,85% p.a. po dobu 1 měsíce nebo 3 měsíců",
    "4% p.a. po dobu 6 měsíců",
  ]),
  p("Úroková sazba je garantována pro sjednanou částku a období."),
  p("Minimální doba zvýhodněné roční úrokové sazby je 1 měsíc, maximální doba je 12 měsíců."),
  p("Minimální zůstatek na vkladovém účtu je 5.000.000,- Kč."),
  p("Vkladový účet je veden zcela zdarma."),
  p("Omezení produktu:"),
  p("Prostředky na účtu jsou vázány."),
  p("Po dni zahájení úročení nelze na účet ukládat další peněžní prostředky."),
  p("V případě vkladového účtu s obnovováním bude banka vklad úročit roční úrokovou sazbou, na které se smluvní strany dohodnou při obnovení."),
  h5("Rozprava"),
  p("I.Dvořák: Dojde k nějakému prodražení, pokud se prodlouží doba rekonstrukce? Starosta: Zatím ne."),
  p("I.Dvořák: Na stránkách obce je, že jste poptali architekta, který by navrhl vzhled fasády školy. Starosta: Chceme oslovit 2 architekty, kteří by možná připravili 2 návrhy, ze kterých by se později vybíralo."),
  p("L.Maršíková: Můžeme vědět více, např. jména architektů. Starosta: Dáme je na web obce."),
  p("Z.Bartoňková: Finální dokončení rekonstrukce školy bude tedy 31.8.2023? Starosta: Ano."),
  p("I.Dvořák: Dotaz na přístavbu základní školy – Bude se dělat celé zateplení školy, nebo se vynechá část v místě přístavby? Starosta: Bude se dělat celé zateplení. Na přístavbu máme projekty, ale z finančních důvodů se realizovat nebude."),
  h5("Návrh"),
  p("ZO schvaluje zřízení spořícího účtu Obce Krhanice u České spořitelny, a.s. a uzavření smlouvy na zřízení spořícího účtu u České spořitelny, a.s."),
  vote(V7),
  h5("Návrh"),
  p("ZO schvaluje převod částky 10.000.000,- Kč z běžného účtu 320094309/0800 na spořící účet Obce Krhanice u České spořitelny, a.s. s možností průběžného čerpání."),
  vote(V7),
  h5("Návrh"),
  p("ZO pověřuje starostu obce zřízením spořícího účtu Obce Krhanice u České spořitelny, a.s. a uzavřením smlouvy na zřízení spořícího účtu u České spořitelny, a.s."),
  vote(V7),
  h5("Návrh"),
  p("ZO pověřuje starostu obce dispozicemi na spořícím účtu Obce Krhanice u České spořitelny, a.s."),
  vote(V7),
  h5("Návrh"),
  p("ZO schvaluje zřízení vkladového účtu Obce Krhanice u České spořitelny, a.s. a uzavření smlouvy na zřízení vkladového účtu u České spořitelny, a.s."),
  vote(V7),
  h5("Návrh"),
  p("ZO schvaluje převod částky 5.000.000,- Kč z běžného účtu 320094309/0800 na vkladový účet Obce Krhanice u České spořitelny a.s. na dobu 3 měsíců s možností automatického prodloužení o 3 měsíce."),
  vote(V7),
  h5("Návrh"),
  p("ZO pověřuje starostu obce zřízením vkladového účtu Obce Krhanice u České spořitelny, a.s. a uzavřením smlouvy na zřízení vkladového účtu u České spořitelny, a.s."),
  vote(V7),
  h5("Návrh"),
  p("ZO pověřuje starostu obce dispozicemi na vkladovém účtu Obce Krhanice u České spořitelny, a.s."),
  vote(V7),
  h5("Návrh"),
  p("ZO schvaluje pořízení platební karty k běžnému bankovnímu účtu 320094309/0800 a uzavření smlouvy na pořízení platební karty u České spořitelny, a.s."),
  vote(V7),
  h5("Návrh"),
  p("ZO pověřuje starostu obce zajištěním platební karty Obce Krhanice u České spořitelny, a.s."),
  vote(V7),
  p("Předseda finančního výboru Bohuslava Kadeřábka přednesl odůvodnění rozpočtového opatření č. 4/2022."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje rozpočtové opatření č. 4/2022."),
  vote(V7),

  h3("9) Koupě, prodej, pronájem"),
  ...ul([
    "prodej pozemků parc.č. 460 k.ú. Krhanice o výměře 2691 m² a pozemku parc.č. 496/2 k.ú. Krhanice o výměře 1040 m² za cenu 76 Kč/1 m². Kupující uhradí náklady na vyhotovení kupní smlouvy a náklady na návrh na vklad do katastru nemovitostí. V kupní smlouvě bude uvedeno předkupní právo obce Krhanice pro případný budoucí prodej pozemků.",
  ]),
  p("Informace starosty: Jedná se o žádost Evy Svěrákové a Miroslava Svěráka, Krhanice 38. Jedná se o lesní pozemky bez přístupu k nim. Již v minulosti měli o tyto pozemky manželé Svěrákovi zájem. Pro obec kvůli přístupu pozemky nejsou k udržování. A tak si dá obec k pozemkům předkupní právo a na 15 let."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje prodej pozemků parc.č. 460 k.ú. Krhanice o výměře 2691 m² a pozemku parc.č. 496/2 k.ú. Krhanice o výměře 1040 m² za cenu 76 Kč/1 m². Evě a Miroslavu Svěrákovým, Krhanice č.p. 38. Kupující uhradí náklady na vyhotovení kupní smlouvy a náklady na návrh na vklad do katastru nemovitostí. V kupní smlouvě bude uvedeno předkupní právo obce Krhanice pro případný budoucí prodej pozemků na dobu 15 let."),
  vote(V7),
  ...ul([
    "prodat pozemek parc. č. 1979/4 a části pozemků parc. č. 1981/2 a 2051/5 dle geometrického plánu č. 1038-5/2021 k. ú. Krhanice, které využívá Správa železnic, státní organizace, IČO 70994234, Dlážděná 1003/7, Praha 1 v rámci své činnosti při zajišťování provozování železniční dopravní cesty jako veřejné služby za cenu znaleckého posudku č. 5791 – 23/2022 ve výši 239.780,- Kč.",
  ]),
  p("Informace starosty: Jedná se o dokončení před dvěma lety záměru prodat části pozemků v návaznosti na železnici."),
  h5("Rozprava"),
  p("L.Maršíková: Kde se nacházejí pozemky, které chce obec prodat Správě železnic? Starosta: Vysvětlil, o jaké pozemky se jedná."),
  p("J.Bydžovská: Pokud obec prodá pozemky v místech přejezdů, budou tyto přejezdy zachovány? Starosta: Ano. A pokud Správa železnic chtěla v minulosti řešit zrušení přejezdu (za hřbitovem), žádala o souhlas obce."),
  p("I.Dvořák: Jak je zajištěn příchod na vlakové nádraží, když někdo odstranil lávku u kolejí? Starosta: Lávka není bezpečná. Obec nebude ta, co by ji vracela zpět. Pokud by se něco stalo, nesla by obec zodpovědnost. Napíši dopis na České dráhy, zda by nenašly ohledně lávky nějaké řešení."),
  h5("Návrh"),
  p("ZO schvaluje prodej pozemku parc. č. 1979/4 a části pozemků parc. č. 1981/2 a 2051/5 dle geometrického plánu č. 1038-5/2021 k. ú. Krhanice, které využívá Správa železnic, státní organizace, IČO 70994234, Dlážděná 1003/7, Praha 1 v rámci své činnosti při zajišťování provozování železniční dopravní cesty jako veřejné služby za cenu znaleckého posudku č. 5791 – 23/2022 ve výši 239.780,- Kč. Kupující uhradí náklady na návrh na vklad do katastru nemovitostí."),
  vote(V7),
  ...ul([
    "pronájem části pozemku parc. č. 312/19 o výměře 41 m² k.ú. Krhanice od 1.6.2022 do 31.5.2026 za cenu 10,- Kč/1 m²/rok za účelem ke zřízení zahrádky.",
  ]),
  p("Informace starosty: Jedná se o žádost Lucie Richtrové, Krhanice 72."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronájem části pozemku parc. č. 312/19 o výměře 41 m² k.ú. Krhanice od 1.6.2022 do 31.5.2026 za cenu 10,- Kč/1 m²/rok za účelem ke zřízení zahrádky Lucii Richtrové, Krhanice 72, 257 42 Krhanice."),
  vote(V7),
  ...ul([
    "koupě pozemků parc. č. 1942/9 o výměře 288 m² k.ú. Krhanice a parc.č. 1942/14 o výměře 524 m² k.ú. Krhanice.",
  ]),
  p("Informace starosty: Jedná se o pozemky v Prosečnici, jde o ostatní plochu – ostatní komunikaci. Manželé Skružní je prodají obci. Cena dohodou: parc. č. 1942/9 za 200,- Kč/1m², parc. č. 1942/14 za 400,- Kč/1m²."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje nákup pozemků parc. č. 1942/9 o výměře 288 m² k.ú. Krhanice za cenu 200,- Kč/1m² a parc.č. 1942/14 o výměře 524 m² k.ú. Krhanice za cenu 400,- Kč/1m² od Miroslava Skružného a Jaroslavy Skružné, Prosečnice 3, 257 42 Krhanice. Vklad do katastru nemovitostí hradí obec."),
  vote(V7),
  ...ul([
    "žádost o předběžný souhlas s pronájmem hřiště před základní školou, o předběžný souhlas s umístěním truhlíků napravo od chodníku k areálu TJ Sokol Krhanice a odsouhlasení záměru na zvelebení plochy mezi svahem a pamětní kamennou deskou napravo vedle chodníku směrem k areálu TJ Sokol Krhanice",
  ]),
  p("T.Kratochvíl přečetl dopis."),
  p("Žádost je na:"),
  ...nl([
    "Pronájem hřiště před základní školou o všech víkendech v měsíci září 2022 a prvním víkendu v měsíci říjnu 2022, tj. 3.9. - 4.9.2022, 10.9. - 11.9.2022, 17.9. - 18.9.2022, 24.9. - 25.9.2022 a 1.10. – 2.10.2022.",
    "Pronájem místa napravo vedle chodníku směrem k areálu TJ Sokol Krhanice, kde chceme umístit truhlíky se květinami a zeleninou.",
    "Odsouhlasení záměru zvelebení plochy mezi svahem a pamětní kamennou deskou napravo vedle chodníku směrem k areálu TJ Sokol Krhanice zejména keři.",
  ]),
  h5("Rozprava"),
  p("L.Maršíková: Za jakým účelem si nadace bude pronajímat hřiště každý víkend? Vždy platilo, že v žádosti byl uveden i důvod pronájmu."),
  p("Proběhla diskuse o problematice žádosti. Starosta přerušil jednání zastupitelstva v 18:53 hod."),
  p("Z místnosti odešli zastupitelé s právem hlasování."),
  p("Jednání zastupitelstva bylo obnoveno v 19:00 hod."),
  p("T.Kratochvíl: Seznámil přítomné s výsledkem dohadovacího řízení. Hlasování bude o bodu 2. a 3. Bod 1. bude projednán na příštím zastupitelstvu, s tím že spolek bude mít rezervační právo na tyto termíny."),
  h5("Návrh"),
  p("ZO schvaluje předběžný souhlas s umístěním truhlíků s květinami a zeleninou napravo vedle chodníku směrem k areálu TJ Sokol Krhanice ze strany vznikajícího spolku Naše Krhanice, z.s."),
  vote("PRO ( 5 ) – PROTI ( 0 ) – ZDRŽEL SE ( 2 – Papoušek, Mixa )"),
  h5("Návrh"),
  p("ZO schvaluje předběžný souhlas se záměrem zvelebit plochu mezi svahem a pamětní kamennou deskou napravo vedle chodníku směrem k areálu TJ Sokol Krhanice zejména keři ze strany vznikajícího spolku Naše Krhanice, z.s."),
  vote("PRO ( 5 ) – PROTI ( 0 ) – ZDRŽEL SE ( 2 – Papoušek, Mixa )"),

  h3("10) Různé"),
  h4("Poděkování hasičům"),
  p("Petr Dub přečetl Poděkování – dopis od pana Lébra."),

  h4("Počet členů zastupitelstva obce na volební období 2022 – 2026"),
  p("Informace starosty: V souvislosti s volbami do zastupitelstev obcí je třeba stanovit počet členů zastupitelstva obce na volební období 2022-2026. Pro obec Krhanice je to počet 9."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje 9 členů zastupitelstva obce pro volební období 2022 – 2026."),
  vote(V7),

  h4("Základní škola – dotace smlouva o dílo stavební práce – dodatek č. 1 prodloužení termínu realizace"),
  p("Starosta seznámil s Dodatkem č. 1 ke Smlouvě o dílo se zhotovitelem firmou Intermont."),
  p("Zhotovitel vyvolal jednání o změně Smlouvy v souvislosti se situací kolem šíření virové choroby COVID-19 v České republice, vyvolané koronavirem SARS CoV - 2 (dále „Pandemie“). Zhotovitel se odvolal i na vojenský konflikt mezi Ruskem a Ukrajinou (dále „Konflikt“) a oznámil, že Pandemie a Konflikt mají vliv na zhotovení díla a sjednanou dobu plnění."),
  p("Zhotovitel požádal o prodloužení termínu provedení díla."),
  p("Dohodnutá doba plnění se upravuje:"),
  p("Skutečné zahájení stavebních prací: 18.08.2021"),
  p("Datum ukončení plnění díla: 31.08.2023"),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Dodatku č. 1 ke Smlouvě o dílo na stavební práce „Krhanice – revitalizace a VZT budovy ZŠ“ s firmou Intermont, Opatrný, s.r.o., Vrskmaň 74, 431 15 Vrskmaň, IČO:49900854. Uzavřením Dodatku č. 1 se upravuje termín ukončení díla na 31.8.2023."),
  vote(V7),

  h4("DSO Týnecko-svazek obcí: Závěrečný účet"),
  p("Informace starosty: Byl nám předložen Závěrečný účet za rok 2021 a Zpráva o výsledku přezkoumání hospodaření za rok 2021."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Závěrečný účet DSO Týnecko-svazek obcí za rok 2021 a souhlasí s celoročním hospodařením, a to bez výhrad."),
  vote(V7),
  h5("Návrh"),
  p("ZO bere na vědomí Zprávu o výsledku přezkoumání hospodaření za rok 2021 DSO Týnecko – svazek obcí."),

  h4("Dotace na akci „Krhanice – rekonstrukce návsi a okolních chodníků“"),
  p("Informace starosty: Pro tuto dotaci bychom využili Program 2021-2024 pro poskytování dotací na rozvoj obcí do 2000 obyvatel ze Středočeského Fondu obnovy venkova ve znění Dodatku č. 1."),
  p("Dotaci dle tohoto Programu lze poskytnout na projekty, které splňují účel vymezený tímto Programem v rámci tematického zadání „Veřejná infrastruktura“. Jedná se o projekty na výstavbu, rekonstrukci, modernizaci a opravy veřejné infrastruktury (pozemků, staveb, nebo zařízení zřizovaných nebo užívaných ve veřejném zájmu) v následujících oblastech podpory:"),
  ...ul([
    "a) dopravní infrastruktura (stavby pozemních komunikací, chodníků a s nimi souvisejících zařízení a další),",
    "b) technická infrastruktura (stavby a s nimi provozně související zařízení technického vybavení, například vodovody, vodojemy, kanalizace, čistírny odpadních vod, stavby ke snižování ohrožení území živelními nebo jinými pohromami, stavby a zařízení pro nakládání s odpady a další),",
    "c) občanské vybavení (stavby sloužící například pro vzdělávání a výchovu, zdravotní služby, kulturu, sport, veřejnou správu, ochranu obyvatelstva a další),",
    "d) veřejná prostranství.",
  ]),
  p("Příklady uznatelných nákladů projektů v rámci tematického zadání Veřejná infrastruktura, na které bude poskytnuta dotace: zpracování projektové dokumentace na realizovaný projekt, geodetické zaměření, geodetický plán, revize, technický dozor investora, obsluha staveniště atd. průzkumné práce, stavební materiál, bourací a demoliční práce a stavební práce, demontáž, odvoz a likvidace stavební suti, odvodnění, výstavba, výměna a zpevnění povrchů, realizace přístupových ploch, oplocení, veřejné osvětlení a veřejný rozhlas, investiční víceúčelová zařízení nad 80 000 Kč bez DPH na údržbu zeleně, svoz odpadu, víceúčelová hasičská technika atd. elektronické zabezpečovací, požární a kamerové systémy, vestavěné vybavení (například vestavěné kuchyňské linky, vestavěné spotřebiče, vestavěné sportovní a hrací prvky atd.)."),
  p("Žadatel může podávat ve lhůtě stanovené tímto Programem žádost, resp. žádosti o dotaci následovně: obec od 200 do 2000 obyvatel na území Středočeského kraje může podat maximálně tři žádosti o dotaci do maximální souhrnné výše 1 000 Kč na obyvatele obce, minimálně však v částce 50 000 Kč."),
  p("Minimální spoluúčast žadatele je stanovena na 15 % z celkových uznatelných nákladů projektu, kterou je nutno při čerpání dotace dodržet."),
  p("Dotace se poskytuje do výše maximálního podílu 85 % z celkových uznatelných nákladů projektu."),
  p("Lhůta pro podání žádostí je stanovena od 6. dubna 2021 od 9:00 hodin do 28. června 2024 do 14:00 hodin."),
  p("Rekapitulace jednotlivých stavebních objektů:"),
  ...ul([
    "Náves a chodníky: 3 231 000 Kč bez DPH",
    "Dešťová kanalizace: 899 000 Kč bez DPH",
    "Veřejné osvětlení: 193 000 Kč bez DPH",
    "Rekonstrukce vodovodu: 270 000 Kč bez DPH",
    "Ostatní a vedlejší rozpočtové náklady: 258 000 Kč bez DPH",
    "CELKEM BEZ DPH: 4 851 000 Kč",
    "CELKEM S DPH: 5 869 710 Kč",
  ]),
  p("Výběrové řízení bude realizováno ve spolupráci s partnerem Posázaví o.p.s."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje podání žádosti o dotaci „Krhanice – rekonstrukce návsi a okolních chodníků“ v rámci Programu 2021-2024 pro poskytování dotací na rozvoj obcí do 2000 obyvatel ze Středočeského Fondu obnovy venkova ve znění Dodatku č. 1. v rámci tematického zadání „Veřejná infrastruktura“ ze Středočeského kraje a souhlasí s podmínkami dotace a finanční spoluúčastí obce."),
  vote(V7),
  h5("Návrh"),
  p("ZO schvaluje vypsání výběrového řízení na dodavatele stavby pro projekt „Krhanice – rekonstrukce návsi a okolních chodníků“."),
  vote(V7),
  h5("Návrh"),
  p("ZO pověřuje starostu obce realizací vypsání výběrového řízení na dodavatele stavby pro projekt „Krhanice – rekonstrukce návsi a okolních chodníků“."),
  vote(V7),
  h5("Návrh"),
  p("ZO schvaluje spolupráci s Posázavím o.p.s., Zámek Jemniště 1, 257 01 Postupice, IČ 27129772 při zajišťování poradenství při realizaci výběrového řízení pro projekt „Krhanice – rekonstrukce návsi a okolních chodníků“."),
  vote(V7),

  h4("Dotace veřejné osvětlení"),
  p("Informace starosty: Dotace na rekonstrukci veřejného osvětlení jsou průběžně sledovány a podklady k podání připravovány. Problém, respektive zdržení je na straně MPO, kde byla dotčená výzva zveřejněna již v prosinci 2021. Avizovaná možnost podávání žádosti o dotaci v lednu 2022 není plněna. Bohužel je podávání žádosti stále „neotevřeno“ - program má tedy zpoždění cca. 4 měsíce. Máme jen neformální avízo, že by se žádosti mohly začít podávat na začátku května 2022. Schválíme podání. Odnož firmy Siemens Yunex, s.r.o. nám dopracovává podklady k dotaci a pro rozhodnutí o podání dotace."),
  p("https://www.mpo-efekt.cz/cz/dotacni-programy/vyzvy/1-2022-rekonstrukce-verejneho-osvetleni"),
  p("Výzva č. NPO 1/2022 NÁRODNÍ PLÁN OBNOVY"),
  p("Rekonstrukce veřejného osvětlení - Komponenta 2.2.2"),
  p("Začátek podávání žádostí: 5.5.2022"),
  p("Ukončení podávání žádostí: 30.6.2023"),
  p("Celková alokace 1 725 000 000 Kč"),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje podání žádosti o dotaci „Krhanice – rekonstrukce veřejného osvětlení“ pro dotační titul na Ministerstvu práce a obchodu: Výzva č. NPO 1/2022 NÁRODNÍ PLÁN OBNOVY; Rekonstrukce veřejného osvětlení - Komponenta 2.2.2."),
  vote(V7),

  h4("Odpady"),
  p("Informace místostarosty o odpadovém hospodářství – reakce na dopis manželů Maršíkových."),
  p("Pan místostarosta zhodnotil odpadové hospodářství v obci. Z hlediska hodnocení obce v soutěži My třídíme nejlépe ze strany EKO-KOM a Středočeského kraje, v naší kategorii se obec Krhanice umístila na 62. místě z 190 hodnocených. Pochválil občany Krhanic za třídění a přístup k volbě popelnice z hlediska objemu a četnosti svozu."),
  p("Z.Bartoňková: Základní škola se také připojila do třídění odpadů. Umístila se na 87. místě z 500 hodnocených."),
  p("L.Maršíková: Dotaz, zda by nebylo možné realizovat pouze 14 denní svoz kvůli úspoře. Starosta: Budeme to řešit na podzim po vyhodnocení svozu za rok 2022."),
  p("P.Bydžovský: Jak se platí svoz odpadu? Starosta: Za známky na popelnice."),
  p("Proběhla všeobecná diskuse."),

  h4("Dotazníky - výsledky"),
  p("Proběhla dotazníková akce. Odpovědi jsme získali téměř od třetiny respondentů. Odpovědi jsou tentokrát rozmanité. Zpracování bude probíhat ještě cca 14 dní."),

  h4("Plánovací smlouva"),
  p("Informace starosty: Hana Dvořáková, Dolní Požáry 19 požádala o uzavření plánovací smlouvy na zhotovení zpevněné komunikace na pozemku parc.č. 1435/49 k.ú. Krhanice ve vlastnictví obce Krhanice. Plánovací smlouva bude uzavřena na dobu 5 let. Obec Krhanice se na realizaci zpevněné komunikace finančně nepodílí."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření plánovací smlouvy s Hanou Dvořákovou, Dolní Požáry č.p. 19 na zhotovení zpevněné komunikace na pozemku parc.č. 1435/49 k.ú. Krhanice ve vlastnictví obce Krhanice. Plánovací smlouva bude uzavřena na dobu 5 let. Obec Krhanice se na realizaci zpevněné komunikace finančně nepodílí."),
  vote(V7),

  h3("11) Diskuse"),
  ...ul([
    "R.Novotný: Nešlo by sjednotit vzhled školy, hasičské zbrojnice a obecního úřadu? Starosta: Ne.",
    "L.Maršíková: Dotaz, zda se bude řešit žádost našeho spolku na pronájem druhé návsi. Starosta: Dnes ne. Na návsi u obchodu bude probíhat rekonstrukce a na druhé návsi bude zařízení staveniště. Termíny budeme vědět do 3 týdnů, budeme se snažit dát vědět do 14 dnů.",
  ]),

  h3("12) Usnesení a závěr"),
  p("a. Návrhová komise přečetla usnesení zastupitelstva obce."),
  vote(V7),
  p("b. Závěr: Zastupitelstvo obce bylo ukončeno v 19:36 hod."),

  p("Datum pořízení zápisu: 9.5.2022"),
  p("Ověřovatelé zápisu a starosta obce, podepsáno v listinné podobě."),
  h4("Přílohy"),
  ...nl(["Svolání zastupitelstva obce", "Prezenční listina zastupitelů", "Prezenční listina občanů"]),
];

async function run() {
  const r = await publishZapis({
    cislo: "3",
    rok: "2022",
    isoDate: "2022-05-02",
    dateLabel: "2. 5. 2022",
    fullDateDot: "2.5.2022",
    pdfPath: "scripts/zapisy-pdf/zapis-2022-3.pdf",
    transcript,
  });
  console.log("OK", r.docId, "blocks", r.blocks);
}
run().catch((e) => { console.error(e); process.exit(1); });
