/* eslint-disable no-console */
import { h3, h4, h5, p, vote, nl, ul, publishZapis, type Block } from "../zapis-lib";

const V9 = "PRO ( 9 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )";

const transcript: Block[] = [
  h4("Přítomni"),
  p("Aleš Papoušek, Jaroslav Mixa, Tomáš Kratochvíl, Martin Jiřička, Jana Laboutková, Petr Dub, Aleš Kozel, Lucie Maršíková, Ivan Dvořák"),
  h4("Omluveni"),
  p("-"),

  h3("1) Zahájení, přivítání přítomných, konstatování přítomnosti"),
  p("Starosta konstatoval, že zasedání bylo svoláno dne 26. 10. 2022 bylo vyvěšeno na úřední desce obecního úřadu, tj. tedy nejméně 7 dní před zasedáním. Bylo tedy svoláno řádně a včas v souladu se zákonem o obcích v platném znění. Starosta konstatoval, že podle prezenční listiny je přítomno 9 členů zastupitelstva, tedy nadpoloviční většina členů zastupitelstva. K předchozímu zápisu nebyly vzneseny námitky."),
  h5("Určení zapisovatele"),
  p("Zápisem zasedání zastupitelstva obce byla pověřena Ing. Alena Kratochvílová."),

  h3("2) Volba návrhové komise a ověřovatelů zápisu"),
  p("Starosta přednesl návrh návrhové komise a ověřovatelů zápisu."),
  h5("Návrh"),
  p("ZO schvaluje návrhovou komisi ve složení Jaroslav Mixa, Jana Laboutková."),
  h5("Návrh"),
  p("ZO schvaluje ověřovatele zápisu ve složení Martin Jiřička, Lucie Maršíková."),
  vote(V9),

  h3("3) Schválení programu"),
  p("Starosta přečetl vyvěšený program."),
  ...nl([
    "Zahájení",
    "Volba návrhové komise a ověřovatelů zápisu",
    "Schválení programu",
    "Odměny neuvolněným členům Zastupitelstva obce Krhanice",
    "Dodatek č. 2 ke Smlouvě o dílo se společností Intermont, Opatrný, s.r.o. pro stavební práce Krhanice – revitalizace a VZT budovy ZŠ",
    "Rekonstrukce hlavního vodovodního přivaděče do obce Krhanice – oznámení o přidělení dotace",
    "Krhanice – rekonstrukce návsi a okolních chodníků – oznámení o přidělení dotace",
    "Rozpočtová opatření",
    "Koupě, prodej, pronájem",
    "Různé",
    "Diskuse",
    "Usnesení a závěr",
  ]),
  p("Starosta: Navrhl změnu v programu – zrušení bodu 5). Aktualizují se podklady pro zastupitele."),
  p("Martin Jiřička. Návrh doplnění bodu 5) Zpráva předsedy Kontrolního výboru ze dne 30. 8. 2022."),
  p("Starosta přečetl změněný program:"),
  ...nl([
    "Zahájení",
    "Volba návrhové komise a ověřovatelů zápisu",
    "Schválení programu",
    "Odměny neuvolněným členům Zastupitelstva obce Krhanice",
    "Zpráva předsedy Kontrolního výboru",
    "Rekonstrukce hlavního vodovodního přivaděče do obce Krhanice – oznámení o přidělení dotace",
    "Krhanice – rekonstrukce návsi a okolních chodníků – oznámení o přidělení dotace",
    "Rozpočtová opatření",
    "Koupě, prodej, pronájem",
    "Různé",
    "Diskuse",
    "Usnesení a závěr",
  ]),
  p("Proběhlo hlasování o změněném programu."),
  h5("Návrh"),
  p("ZO schvaluje program zasedání zastupitelstva obce."),
  vote(V9),

  h3("4) Odměny neuvolněným členům Zastupitelstva obce Krhanice"),
  p("Neuvolnění členové zastupitelstva musí mít schváleny odměny dle nařízení vlády."),
  p("Funkce neuvolněného člena zastupitelstva / Výše měsíční odměny:"),
  ...ul([
    "místostarosta obce: 27 626 Kč",
    "předseda finančního výboru: 2 167 Kč",
    "předseda kontrolního výboru: 2 167 Kč",
    "člen finančního výboru: 1 806 Kč",
    "člen kontrolního výboru: 1 806 Kč",
    "člen zastupitelstva: 1 083 Kč",
  ]),
  p("Platnost od 8. 11. 2022."),
  p("Nařízení vlády č. 338/2019 Sb."),
  p("Nařízení vlády, kterým se mění nařízení vlády č. 318/2017 Sb., o výši odměn členů zastupitelstev územních samosprávných celků, ve znění nařízení vlády č. 202/2018 Sb."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje výše odměn neuvolněným členům zastupitelstva s platností od 8. 11. 2022: místostarosta obce: 27 626 Kč, předseda finančního výboru: 2 167 Kč, předseda kontrolního výboru: 2 167 Kč, člen finančního výboru: 1 806 Kč, člen kontrolního výboru: 1 806 Kč, člen zastupitelstva: 1 083 Kč."),
  vote(V9),

  h3("5) Zpráva předsedy Kontrolního výboru"),
  p("Předseda Kontrolního výboru Martin Jiřička seznámil přítomné se Zprávou Kontrolního výboru ze dne 30. 8. 2022."),
  h5("Rozprava"),
  p("L. Maršíková: Kontrolní výbor kontroloval období od 13. 9. 2021 do 30. 8. 2022. Proč tak dlouhé období? M. Jiřička: Kontrolovali jsme pouze nedořešené věci."),
  p("I. Dvořák: Kontrolní výbor se schází 2x ročně. Není to málo? Starosta: Není."),
  p("J. Stibůrek: Dotaz na kulturní dům. M. Jiřička: Dotaz byl vznesen na zastupitelstvu a zodpovězen starostou."),
  h5("Návrh"),
  p("ZO bere na vědomí Zprávu Kontrolního výboru ze dne 30. 8. 2022."),

  h3("6) Rekonstrukce hlavního vodovodního přivaděče do obce Krhanice – oznámení o přidělení dotace"),
  p("Informace starosty: Získali jsme dotaci ve výši 1 000 000,- Kč z rozpočtu Středočeského kraje ze Středočeského Infrastrukturního fondu na rekonstrukci hlavního vodovodního přivaděče do obce Krhanice."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje přijetí dotace ve výši 1 000 000,- Kč z rozpočtu Středočeského kraje ze Středočeského Infrastrukturního fondu a uzavření veřejnoprávní smlouvy o poskytnutí dotace na realizaci projektu Rekonstrukce hlavního vodovodního přivaděče do obce Krhanice, ev. č. projektu ISF/DVP/047805/2022."),
  vote(V9),
  p("Zároveň proběhlo výběrové řízení na dodavatele. Výběrové řízení bylo realizováno s Posázavím o.p.s. Dle dotačních podmínek bylo osloveno pět firem. Výběrové řízení proběhlo ve středu 12. 9. 2022. Nabídku podala pouze jedna firma, dvě firmy se omluvily a zbývající se neozvaly. Hodnotícím kritériem byla nejnižší nabídková cena."),
  p("Výsledek:"),
  ...ul([
    "1. LAROS s.r.o., IČ 49826514, Nabídková cena vč. DPH 3 296 926,71 Kč",
  ]),
  p("Doporučení komise: Zhotovitel díla:"),
  p("obchodní firma/jméno: LAROS s.r.o."),
  p("sídlo / místo podnikání: Jana Nohy 1285, 256 01 Benešov"),
  p("IČO: 49826514"),
  p("Nabídková cena s DPH: 3 296 926,71 Kč"),
  p("Firma předložila návrh Smlouvy o dílo. Smlouvu posoudil právník a provedl v ní revize."),
  h5("Rozprava"),
  p("J. Stibůrek: Víme něco o firmě, která výběrové řízení vyhrála? Starosta: Firma působila v minulosti na Vlašimsku. Měla dobré reference a má i dobré zkušenosti."),
  p("J. Stibůrek: Kdy tato akce začne a kdy skončí? Starosta: Jaro 2023, do června 2023."),
  h5("Návrh"),
  p("ZO schvaluje uzavření smlouvy o dílo na akci Rekonstrukce hlavního vodovodního přivaděče do obce Krhanice s firmou LAROS s.r.o., Jana Nohy 1285, 256 01 Benešov, IČO: 49826514 ve výši 3 296 926,71 Kč."),
  vote(V9),
  h5("Návrh"),
  p("ZO pověřuje starostu obce uzavřením a podpisem smlouvy o dílo na akci Rekonstrukce hlavního vodovodního přivaděče do obce Krhanice s firmou LAROS s.r.o., Jana Nohy 1285, 256 01 Benešov, IČO: 49826514."),
  vote(V9),

  h3("7) Krhanice – rekonstrukce návsi a okolních chodníků – oznámení o přidělení dotací"),
  p("Informace starosty: Získali jsme dotaci ve výši 1 059 000,- Kč z rozpočtu Středočeského kraje ze Středočeského Fondu obnovy venkova na rekonstrukci návsi a okolních chodníků."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje přijetí dotace ve výši 1 059 000,- Kč z rozpočtu Středočeského kraje ze Středočeského Fondu obnovy venkova a uzavření veřejnoprávní smlouvy o poskytnutí dotace na realizaci projektu Krhanice – rekonstrukce návsi a okolních chodníků, ev. č. projektu FRV/VEI/048181/2022."),
  vote(V9),

  h3("8) Rozpočtová opatření"),
  h4("Rozpočtové opatření č. 6/2022 a č. 7/2022"),
  p("Informace starosty: Dle schválených pravidel jsem provedl rozpočtové opatření:"),
  ...ul([
    "č. 6/2022 – zahrnutí dotace UZ 13101 Aktivní politika zaměstnanosti do příjmů a výdajů",
    "č. 7/2022 – zahrnutí dotace UZ 98187 Volby do ZO do příjmů a výdajů.",
  ]),
  h5("Rozprava"),
  p("L. Maršíková: Vyjadřuje se předseda Finančního výboru k těmto opatřením? Starosta: Ne."),
  p("I. Dvořák: Kdo schvaluje přesuny mezi jednotlivými kapitolami rozpočtu? Starosta: Já dle mých pravomocí."),
  h5("Návrh"),
  p("ZO bere na vědomí a schvaluje rozpočtová opatření č. 6/2022 a 7/2022."),
  vote(V9),

  h4("Základní škola"),
  p("Informace starosty: Seznámení s obdrženými dopisy od ředitelky Základní školy Krhanice:"),
  ...ul([
    "žádost o prodloužení termínu vratky návratné finanční výpomoci",
  ]),
  p("Dle předloženého oznámení byla žádost o platbu podána dne 15. 4. 2022 a dne 23. 9. 2022 SZIF schválil dotaci ve výši 564.149,- Kč a její zaslání na účet školy. Původně měla být návratná finanční výpomoc obci Krhanice vrácena do 31. 8. 2022."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Dodatku č. 1 Smlouvy o poskytnutí návratné finanční výpomoci z rozpočtu obce Krhanice schválené Zastupitelstvem obce Krhanice č. 4/2021 dne 13. 9. 2021 – změna termínu vrácení návratné finanční výpomoci ve výši 595.979,- Kč na datum 15. 11. 2022."),
  vote(V9),
  ...ul([
    "žádost o opětovné zaslání investiční dotace na spolufinancování nákupu interaktivních tabulí v částce 172.868,- Kč",
  ]),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje investiční příspěvek ve výši 172.868,- Kč Základní škole Krhanice pro zajištění podílu školy pro dotaci z Programu rozvoje venkova pro pořízení tabulí s interaktivním systémem do kmenových učeben v roce 2022."),
  vote(V9),
  ...ul([
    "žádost o navýšení provozního příspěvku v celkové částce 41.420,- Kč, a to na: provoz plaveckého bazénu; právní zastupování školy; odpisy pro interaktivní tabule z dotace SZIF a schválení odpisových plánů",
    "provozní příspěvek na provoz plaveckého bazénu v částce 19.200,- Kč",
    "právní zastupování školy v částce 4.840,- Kč",
    "odpisy pro interaktivní tabule v částce 17.380,- Kč",
  ]),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje navýšení provozního příspěvku Základní škole Krhanice o 41.420,- Kč."),
  vote(V9),
  h5("Návrh"),
  p("ZO schvaluje předložené odpisové plány na sestavy interaktivních tabulí Triptych pořízených v rámci dotace z Programu rozvoje venkova pro pořízení tabulí s interaktivním systémem do kmenových učeben v roce 2022."),
  vote(V9),
  p("Předseda finančního výboru přednesl odůvodnění rozpočtového opatření č. 8/2022."),
  h5("Rozprava"),
  p("L. Maršíková: Co je to příjem úhrad za dobývané nerosty? Starosta: Jsou to peníze za těžbu v lomech."),
  p("L. Maršíková: Dotaz na celkovou výši úhrad. Starosta: Odhad na rok 2023 je 70 tisíc Kč."),
  p("I. Dvořák: Jsou dohodnuté další kompenzace, např. na dodávaný materiál na rekonstrukci návsi? Starosta: Materiál na náves si musí realizační firma vyjednat sama. Obec má ceny, jaké firma má (ve smyslu stejné jako kdokoli). Firma v rámci dobrých vztahů zasponzorovala loňský krhanický dětský den."),
  p("L. Maršíková: Dotaz k položce příjmů týkajících se základní školy. Starosta: Předpokládáme, že naše žádost na dotační platbu bude dle předchozích zkušeností schválena."),
  p("I. Dvořák: Do kdy musíme dotaci vyčerpat? Starosta: Do srpna 2023."),
  p("J. Stibůrek: Dotaz na částku na plavání pro ZŠ? Starosta: Plavání je povinné, ale stát to neplatí."),
  p("L. Maršíková: Dotaz k výdajům – snížení položky na úpravy drobných vodních toků. Starosta: Byla plánována rekonstrukce nádrže u hasičské zbrojnice. Byla odložena, peníze potřebujeme na základní školu a na náves."),
  p("L. Maršíková: Dotaz k výdajům – snížení položky pořízení, zachování a obnova místních kulturních památek. Starosta: Brána u vodní elektrárny (pozemek získaný od ČEZ) potřebuje opravit, nyní odloženo, protože obec potřebuje finance jinde."),
  p("L. Maršíková: Dotaz k výdajům – zvýšení položky sběr a svoz komunálních odpadů – pytle. Místostarosta: Pytle se nakupují jednou za čas. Jsou pro ty, co nemají popelnice a pro rekreanty."),
  h5("Návrh"),
  p("ZO schvaluje rozpočtové opatření č. 8/2022."),
  vote(V9),

  h3("9) Koupě, prodej, pronájem"),
  ...ul([
    "prodat pozemek par. č. 1979/4 k.ú. Krhanice, o výměře 174 m²; pozemek par. č. 1981/3 k.ú. Krhanice, o výměře 138 m², který vznikne dle geometrického plánu č. 1038-5/2021 oddělením z pozemku parc. č. 1981/2; pozemek par. č. 2051/8 k.ú. Krhanice, o výměře 80 m², který vznikne dle geometrického plánu č. 1039-6/2021 oddělením z pozemku parc. č. 2051/5 a pozemek par. č. 2051/9 k.ú. Krhanice, o výměře 88 m², který vznikne dle geometrického plánu č. 1039-6/2021 oddělením z pozemku parc. č. 2051/5, které využívá Správa železnic, státní organizace, IČO 70994234, Dlážděná 1003/7, Praha 1 v rámci své činnosti při zajišťování provozování železniční dopravní cesty jako veřejné služby za cenu znaleckého posudku č. 5791 – 23/2022 ve výši 239.780,- Kč.",
  ]),
  p("Informace starosty: Jedná se o zpřesnění prodeje SŽDC dle usnesení ZO Krhanice č. 3/2022 ze dne 2. 5. 2022. Byl nám předložen návrh Kupní smlouvy, geometrický plán, znalecký posudek."),
  h5("Rozprava"),
  p("I. Dvořák: Máme problém najít bezpečnou cestu na nádraží. Můj návrh je pozemek zatím neprodávat a vyjednat možnost vybudování chodníku podél kolejí. Starosta: Seznámil s jednáním se zástupci Českých drah a Správy železnic ohledně zprůchodnění pozemku u nádraží a zřízení chodníku."),
  p("Informace starosty: 31. 8. 2022 proběhlo jednání obce s Českými drahami (p.Pícha, p. Brumlich) a se Správou železnic, Správa tratí Praha Západ (p. Oubram). Předmětem jednání bylo zprůchodnění pozemků přes nádraží a vybudování chodníku ve vstupu:"),
  ...nl([
    "schodiště vedle viaduktu",
    "pozemkem obce směrem k silnici a travnatou plochou k viaduktu.",
  ]),
  p("Vyjádření: Správa železnic – zásadní problém jsou funkční koleje a rampy. Z mého pohledu je realizace chodníku nereálná. Pokud by hypoteticky chodník vznikl, musel by být oplocen. Tím by vznikly potíže s údržbou plochy a ramp."),
  p("České dráhy: Souhlasí s výše uvedeným."),
  p("Doplnění dne 2. 9. 2022 Správa železnic – telefonicky bylo sděleno, že rampy jsou pro armádu a musí být funkční, omezení prostoru chodníkem je nereálné."),
  h5("Rozprava"),
  p("P. Bydžovský: Jedna rampa je nefunkční, nevedou k ní ani koleje, kolem ní lze tedy dle mého chodník vést. Vedle druhé, funkční rampy je na chodník dostatek prostoru. Starosta: Pošlu oficiální dotaz na ČD a SŽ, aby se oficiálně vyjádřily k našim návrhům ohledně možnosti vybudování chodníku."),
  p("I. Dvořák: Dotaz na možnost vybudovat oficiální přechod přes koleje. Starosta: Můžeme poslat další oficiální dopis týkající se přechodového místa."),
  p("R. Novotný: Zkusil by najít železničního experta, který by navrhl způsob řešení. T. Strnad: Mohu neoficiálně získat stanovisko odborníka."),
  p("Starosta: Pošleme 2 dopisy, s 3.dopisem počkáme."),
  p("Starosta: Návrh odložit tento bod na příště."),
  ...ul([
    "prodat pozemek parc.č. 1978/15 k.ú. Krhanice o výměře 79 m², který vznikne dle geometrického plánu č. 1086-111/2022 oddělením z pozemku parc.č. 1978/13 k.ú. Krhanice za cenu 30,- Kč/1 m²",
  ]),
  p("Informace starosty: Jedná se o pozemek před nemovitostí Krhanice č.p. 11, Karla Boháčka. My od něj budeme kupovat část jeho pozemku, kde se nachází zvonička."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje prodat pozemek parc.č. 1978/15 k.ú. Krhanice o výměře 79 m², který vznikne dle geometrického plánu č. 1086-111/2022 oddělením z pozemku parc.č. 1978/13 k.ú. Krhanice za cenu 30,- Kč/1m² Karlovi Boháčkovi, Krhanice č.p. 11, 257 42 Krhanice."),
  vote(V9),
  ...ul([
    "prodat pozemek parc.č. 1978/16 k.ú. Krhanice o výměře 18 m², který vznikne dle geometrického plánu č. 1086-111/2022 oddělením z pozemku parc.č. 1978/13 k.ú. Krhanice za cenu 30,- Kč/1m²",
  ]),
  p("Informace starosty: Jedná se o část pozemku, který navazuje na nemovitost Krhanice č.p. 9, Václav Podroužek."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje prodat pozemek parc.č. 1978/16 k.ú. Krhanice o výměře 18 m², který vznikne dle geometrického plánu č. 1086-111/2022 oddělením z pozemku parc.č. 1978/13 k.ú. Krhanice za cenu 30,- Kč/1m² Václavu Podroužkovi, Krhanice č.p. 9, 257 42 Krhanice."),
  vote(V9),
  ...ul([
    "koupit pozemek parc.č. 2125 o výměře 20 m² dle geometrického plánu č. 1086-111/2022 oddělením z pozemku st.p. 28 k.ú. Krhanice za cenu 30,- Kč/1m² k.ú. Krhanice",
  ]),
  p("Starosta: jedná se o pozemek pod zvoničkou a kolem ní."),
  h5("Rozprava"),
  p("T. Strnad: Dotaz na anketu o umístění zvoničky. Starosta: Je připraveno v Různé."),
  h5("Návrh"),
  p("ZO schvaluje koupi pozemku parc.č. 2125 k.ú. Krhanice o výměře 20 m², který vznikne dle geometrického plánu č. 1086-111/2022 oddělením z pozemku st.p. 28 k.ú. Krhanice za cenu 30,- Kč/1m²."),
  vote(V9),
  ...ul([
    "prodat část pozemku parc.č. 1972/1 k.ú. Krhanice o velikosti cca 80 m² za cenu 30,- Kč/1 m²",
  ]),
  p("Informace starosty: Jedná se o žádost Hany Křemenové a Jakuba Štanglera, Krhanice č.p. 5. Po vyhotovení geometrického plánu (hradil by kupující) bychom projednali konkrétní přesnou výměru dle vyhotoveného geometrického plánu."),
  h5("Rozprava"),
  p("L. Maršíková: Majitelé si již část cesty oplotili. Starosta: Už v létě tam pouštěli ovce na spásání trávy. Informovali mě."),
  p("L. Maršíková: Bude na obecní části asfalt? Starosta: Cesta bude pouze zpevněná štěrkem a zhutněná."),
  p("M. Maršík: Dotaz na souhlas majitelů sousedních pozemků. Starosta: Špachtovi souhlasí, p. Kočí má jiný přístup na svůj pozemek."),
  p("R. Mikoláš: Je na té cestě věcné břemeno? Starosta: Ne, je to jeden pozemek (náves) patřící obci."),
  h5("Návrh"),
  p("ZO schvaluje záměr prodeje části pozemku parc.č. 1972/1 k.ú. Krhanice o velikosti cca 80 m2 za cenu 30,- Kč/1 m2. Geometrický plán na oddělení části pozemku a návrh na vklad do katastru nemovitostí by hradil budoucí kupující."),
  vote(V9),
  ...ul([
    "pronajmout část pozemku parc.č. 132/1 k.ú. Krhanice o výměře 150 m² od 1. 1. 2023 do 31. 12. 2026 za cenu 10,- Kč/1 m²/rok za účelem dočasného zřízení zahrádky.",
  ]),
  p("Informace starosty: Jedná se o pokračování stávajícího pronájmu pozemku – Josef Hýsek. Dosavadní smlouva končí dne 31. 12. 2022."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronajmout část pozemku parc.č. 132/1 k.ú. Krhanice o výměře 150 m² od 1. 1. 2023 do 31. 12. 2026 za cenu 10,- Kč/1 m²/rok za účelem dočasného zřízení zahrádky Josefovi Hýskovi, Nad úpadem 301, 149 00 Praha 11."),
  vote(V9),
  ...ul([
    "pronajmout část pozemku parc.č. 128/2 k.ú. Krhanice o výměře 36 m² od 1. 1. 2023 do 31. 12. 2026 za cenu 10,- Kč/1 m²/rok za účelem dočasného zřízení zahrádky.",
  ]),
  p("Informace starosty: Jedná se o pokračování stávajícího pronájmu pozemku – Zdeněk Bočan. Dosavadní smlouva končí dne 31. 12. 2022."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronajmout část pozemku parc.č. 128/2 k.ú. Krhanice o výměře 36 m² od 1. 1. 2023 do 31. 12. 2026 za cenu 10,- Kč/1 m²/rok za účelem dočasného zřízení zahrádky Ing. Zdeňku Bočanovi, Rytířova 776/1, 143 00 Praha 4."),
  vote(V9),
  ...ul([
    "pronajmout pozemek parc.č. 59/1 k.ú. Krhanice o výměře 1223 m² od 1. 1. 2023 do 31. 12. 2023 za cenu 10,- Kč/1 m²/rok za účelem dočasného zřízení zahrádky.",
  ]),
  p("Informace starosty: Jedná se o pokračování stávajícího pronájmu pozemku – manželé Klapáčovi. Dosavadní smlouva končí dne 31. 12. 2022."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje pronajmout pozemek parc.č. 59/1 k.ú. Krhanice o výměře 1223 m² od 1. 1. 2023 do 31. 12. 2023 za cenu 10,- Kč/1 m²/rok za účelem dočasného zřízení zahrádky Janu a Jaroslavě Klapáčovi, Hennerova 3/2009, 150 00 Praha 5."),
  vote(V9),

  h3("10) Různé"),
  h4("Komise pro sestavení rozpočtu pro rok 2023"),
  p("Informace starosty: V souladu se směrnicí č. 2/2017 Metodika sestavení rozpočtu obce Krhanice bude zřízena Komise pro sestavení rozpočtu pro rok 2023: Aleš Papoušek, Jana Laboutková, Bohuslav Kadeřábek, Petr Dub, Alena Kratochvílová a Jana Cachová."),
  p("Jednotliví žadatelé – základní škola, mateřská škola, Komise pro obnovu a rozvoj obce, Kulturní komise, SDH Krhanice, JSDHO Krhanice, TJ Sokol Krhanice, některé spolky a zájmové organizace již byly osloveni a vyzváni k předložení požadavků na rozpočet na rok 2023."),
  p("Sezení komise bude naplánováno na měsíc listopad 2022."),
  p("Komise pro sestavení rozpočtu zpracovává jednotlivé požadavky žadatelů, jedná s některými žadateli a dotazuje se na předkládané materiály. Vyhotovuje písemnou zprávu pro jednání zastupitelstva o rozpočtu pro rok 2023."),
  h5("Rozprava"),
  p("I. Dvořák: Jak by se zastupitelé mohli zapojit do přípravy rozpočtu? Starosta: Rozpočet připravuji já. Komise zpracovává žádosti a požadavky. Před schválením s rozpočtem seznamují všechny zastupitele."),
  h5("Návrh"),
  p("ZO schvaluje složení Komise pro sestavení rozpočtu pro rok 2023: Aleš Papoušek, Jana Laboutková, Bohuslav Kadeřábek, Petr Dub, Alena Kratochvílová a Jana Cachová."),
  vote(V9),

  h4("Plán inventur na rok 2022"),
  p("Informace starosty: Standardním způsobem provedeme inventarizaci. Schválíme Plán inventur na rok 2022 včetně přílohy č. 1 – Seznamu inventurních soupisů s konkrétním postupem pro provedení inventarizace majetku a závazků obce. Jsou zde uvedeny konkrétní osoby, termíny a úkoly. Pro rok 2022 se zřizuje jedna inventarizační komise pro střediska – Obecní úřad Krhanice, Knihovna, Hasičská zbrojnice ve složení: Aleš Papoušek, Jana Cachová, Lenka Termerová, Jaroslav Mixa a Petr Dub. Stav majetku a závazků bude zjišťován k datu 31. 12. 2022. Inventurní soupisy bude inventarizační komise vyhotovovat průběžně v měsíci lednu 2023. Inventarizační komise vyhotoví Inventarizační zprávu nejpozději do 6. 2. 2023."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Plán inventur 2022."),
  vote(V9),

  h4("Složení Likvidační a škodní komise"),
  p("Informace starosty: Dle „Pravidel pro jednání Likvidační a škodní komise při obci Krhanice“ se jmenují tito členové Likvidační a škodní komise: předseda – Tomáš Kratochvíl, členové – Jaroslav Mixa, Petr Dub."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Likvidační a škodní komisi ve složení předseda – Tomáš Kratochvíl, členové – Jaroslav Mixa, Petr Dub."),
  vote(V9),

  h4("Podpisová práva k účtům"),
  p("Informace starosty: V souvislosti s proběhlými volbami je potřeba aktualizovat nové podpisové vzory pro dispozici k bankovním účtům obce. Podpisový vzor pro starostu obce zůstane v platnosti. Dojde ke změně u dalších osob, v případě zastupování starosty: Jaroslav Mixa a Petr Dub. U bankovních karet pro internetové bankovnictví Business 24 budeme pokračovat v systému 2 osob: Aleš Papoušek (aktivní karta) a Jana Cachová (pasivní karta)."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje podpisová práva pro dispozici k bankovním účtům obce pro Mgr. Aleše Papouška, Jaroslava Mixu, Bc. Petra Duba."),
  vote(V9),

  h4("Oddávající a úředně stanovené místo pro svatby"),
  p("Starosta: Úředně stanovené místo pro provádění snatečních obřadů je katastrální území Krhanice, správní obvod Krhanice. Oddávat bude starosta obce Mgr. Aleš Papoušek, časově kdykoliv. Pro případ jeho nepřítomnosti je zastupující osobou pro provádění snatečních obřadů Jaroslav Mixa, místostarosta obce."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje, že úředně stanovené místo pro provádění snatečních obřadů je katastrální území Krhanice, správní obvod Krhanice a bere na vědomí, že oddávat bude starosta obce Mgr. Aleš Papoušek, časově kdykoliv. Pro případ jeho nepřítomnosti je zastupující osobou pro provádění snatečních obřadů Jaroslav Mixa, místostarosta obce."),
  vote(V9),

  h4("Výsledky ankety Zvonička na návsi"),
  p("VÝSLEDKY ANKETY"),
  p("Varianta č.1 (bez zvoničky): 46,53%"),
  p("Varianta č.2 (se zvoničkou): 53,47%"),
  p("Rozdíl v hlasování: pouze 6,94%"),
  p("Rozdíl byl nepatrný. Při takových malých rozdílech v anketě nebude provedeno přesunutí zvoničky."),
  p("Umístění zvoničky bylo ještě zkonzultováno s kameníkem a bylo doporučeno: Z důvodu náročnosti nebo spíše rizika nenávratného poškození zvoničky nedoporučuji její přemísťování. Doporučuji renovaci a ponechání na místě. Na zdi umístit žulové parapety, odstranit zábradlí kolem zvoničky, udělat drenážování kolem zvoničky, úpravu zeleně, odstranění šeříku."),
  p("Očistit zvoničku, nejlépe mechanicky, možná tlakovou vodou. Rozhodně ne pískováním."),
  p("Nasypat kačírek kolem zvoničky. V tomto opotřebeném stavu je stěhování zvoničky rizikové. Zvonička již byla opravovaná betonem, při přesunu by došlo k nevratnému poškození."),
  h5("Rozprava"),
  p("L. Maršíková: Kolik lidí hlasovalo? Starosta: Asi třetina rodin."),
  p("M. Maršík: Neřešili jste zvoničku s panem D. Anfilovem jako odborníkem? Starosta: Neřešili. Kameník T. Vrabec je pro nás dostatečný odborník."),

  h4("Obec Krhanice – DPH"),
  p("Informace starosty: Pravděpodobně v měsíci prosinci 2022 dosáhneme obratu z hlediska DPH pro registraci jako plátce DPH. Pro obec to bude znamenat od 1. 1. 2023 plátcovství DPH, zasáhne to do rozpočtu, fakturace u stavebních prací a dotací, budou nové položky pro odvod daně finančnímu úřadu, bude nutné rozšířit účetní systém, možné úpravy ceníků obce, ... Pokud bude schváleno navýšení obratu DPH na 2 milióny Kč, musíme zahájit proces, abychom nebyli plátci DPH."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),

  h4("Registrace akce a rozhodnutí o poskytnutí dotace"),
  p("Informace starosty: Bylo nám zasláno Registrace akce a Rozhodnutí o poskytnutí dotace pro rekonstrukci válečného hrobu obětí 2. světové války. Realizace by probíhala dle podmínek dotace v r. 2023, dávali bychom do rozpočtu 2023. Pak by muselo proběhnout výběrové řízení zakázky malého rozsahu."),
  h5("Rozprava"),
  p("M. Maršíková: Upozornění na nepoměrnou částku na opravu válečného hrobu (vůči zvoničce), aniž by zpochybňovala jeho podstatu. Starosta: Obec zaplatí cca 90 tisíc, většina (cca 350 tisíc) bude hrazena z dotace. Zvonička bude řešena později případně z jiné dotace."),
  p("L. Maršíková: Dotaz na množství, umístění a výšku tisů (velká částka v rozpočtu). Kdo dělal rozpočet? Starosta: Tisy se budou udržovat ve výše dle rozhodnutí zahradníka. Rozpočet udělala stavební komise."),
  p("I. Dvořák: Máme stanovený nějaký limit? Rozpočet byl zpracovaný dříve (staré ceny), možná tedy vzroste. Starosta: Je to o výběrovém řízení a rozhodnutí zastupitelstva. Dotaci lze odmítnout."),
  h5("Návrh"),
  p("ZO schvaluje Registraci akce a Rozhodnutí o poskytnutí dotace v rámci programu Ministerstva obrany č. 10729 – Zachování a obnova historických hodnot I, pro projekt Krhanice – rekonstrukce válečného hrobu obětí 2. světové války."),
  vote(V9),
  h5("Návrh"),
  p("ZO pověřuje starostu obce podpisem Registraci akce a Rozhodnutí o poskytnutí dotace v rámci programu Ministerstva obrany č. 10729 – Zachování a obnova historických hodnot I, pro projekt Krhanice – rekonstrukce válečného hrobu obětí 2.světové války."),
  vote(V9),
  h5("Návrh"),
  p("ZO pověřuje starostu obce realizací výběrového řízení na projekt Krhanice – rekonstrukce válečného hrobu obětí 2. světové války ve spolupráci s Posázavím o.p.s., Zámek Jemniště 1 257 01 Postupice, IČO 27129772."),
  vote(V9),

  h4("Zprůchodnění pozemků a vybudování chodníku přes nádraží"),
  p("Viz diskuse u bodu 9"),

  h4("Navýšení vodného od 1. 1. 2023"),
  p("Informace starosty: Ze strany VHS nám bylo zasláno oznámení o zvýšení ceny vodného o 3,- Kč bez DPH, tzn. 3,30 Kč s DPH s platností od 1. 1. 2023. Na navýšení se podílí nejvíce navýšení ceny vody předané z přivaděče PSV, zvýšení cen chemikálií (chlornan sodný), zvýšení mzdových nákladů (odečítač), zvýšení nákladů na opravy a údržbu infrastrukturního majetku, zvýšení ostatních provozních nákladů externích (zvýšené laboratorní rozbory)."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje navýšení ceny vodného na 63,70 Kč včetně DPH od 1. 1. 2023."),
  vote(V9),

  h4("Posázavský vodovod – dobrovolný svazek obcí – zastupování za obec"),
  p("Informace starosty: Přišel dopis od předsedy dobrovolného svazku obcí Posázavský vodovod – dobrovolný svazek obcí. Jde o návrh osoby zastupující obec Krhanice ve správní radě dobrovolného svazku. Návrh je pokračování Mg. Aleše Papouška, místopředsedy dobrovolného svazku. Je to funkce neplacená."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Mgr. Aleše Papouška jako osobu jednající za obec Krhanice ve správní radě dobrovolného svazku obcí „Posázavský vodovod – dobrovolný svazek obcí“."),
  vote(V9),

  h3("11) Diskuse"),
  ...ul([
    "I. Dvořák: Dotaz k registraci DPH. Pokud se zvedne limit pro povinnou registraci na 2 milióny, spadneme tam? Starosta: Ne.",
    "I. Dvořák: Upozornění na vznik petice proti zavezení lomu Doubí. Proběhla diskuse o povolení, o rozsahu zavážení, o plánu rekultivace, … Starosta: Obec o tom ví, plán rekultivace schvaluje životní prostředí. Firma Abakron má určitě povolení.",
    "I. Dvořák: Náklady na energie, jaké to bude mít dopady na obec? Starosta: Jsme dlouhodobě u ČEZ, měl by se na nás vztahovat strop, noví zákazníci mají vždy horší podmínky.",
    "I. Dvořák: Dotaz na solární elektrárny na obecních budovách. Kdo je vlastní, má z toho obec nějaký příjem? Starosta: Firma PIN292, platí za pronájem střech do roku 2035. Řešíme, zda by se vyplatila fotovoltaika na klubovně víceúčelového hřiště, na budově obecního úřadu to nevidíme reálně.",
    "I. Dvořák: Dotaz na pronájem klubovny víceúčelového hřiště. Byla by vhodná lepší propagace. Starosta: Zlepšíme. I. Dvořák: Zvážíme pronájem i na soukromé akce, když je tak velká poptávka? Starosta: Zvážíme do budoucna dle poptávky.",
    "I. Dvořák: Byla rekonstrukce sv. Josefa financována z rozpočtu obce? Starosta: Ne.",
    "L. Maršíková: Jaké máte další komise kromě Finančního a Kontrolního výboru? Starosta: Mám komise jako moje poradní. Je to Stavební komise, Kulturní komise a Komise pro obnovu a rozvoj obce. L. Maršíková: Dotaz na zveřejnění jmen členů komisí. Starosta: Pokud budou souhlasit, tak ano.",
    "L. Maršíková: Dotaz na přestupkovou komisi. Proběhla diskuse o přestupcích a složitosti problematiky přestupků.",
    "L. Maršíková: Námět na zřízení sociální poradny pro občany, kteří se ocitnou v nějaké nouzi. Starosta: Je projekt, který řeší sociální pomoc. Kontaktní osoba je Hana Kronovetrová. V minulosti byla tato pomoc již využívána. Občané se obrátí na mě a já zařídím většinou místní šetření. L. Maršíková: Návrh na zveřejnění této informace na webu obce.",
    "A. Kozel: Vyzval přítomné k používání informačního systému obecního úřadu MUNIPOLIS.",
    "J. Bartoš: Dotaz k anketě o zvoničce – procentuálnímu výsledku a konečnému rozhodnutí. Starosta Vysvětlil rozhodnutí (předchozí zkušenosti z ankety o názvech ulic a vyjádření kameníka). J. Mixa: Měli jsme otočit postup – nejdříve oslovit kameníka ohledně možnosti přesunutí zvoničky, pak případně anketa.",
    "T. Strnad: Pan Anfilov, který rekonstruoval sv. Josefa, navrhoval úpravy – sklo, podstavec, odvětrání. Proběhla diskuse, jaké úpravy jsou reálné dodělat.",
    "M. Maršíková: Seznámila přítomné s problémem, který se týká jejího pozemku u lomu – především poškození kamenné výztuže západní strany pozemku odstraněním hraničních kamenů při bagrování na obecním pozemku. Z diskuse vyplynulo, že bagrování neprováděla obec a že pokud někdo odvezl kameny bez vědomí p. Maršíkové, obrátí se poškozená na policii. Starosta ohledně cesty osloví stavební úřad v Týnci a silniční správní úřad v Benešově.",
    "S. Nebeský: Na úsek silnice k viaduktu navrhl umístit dva zpomalovací retardéry kvůli bezpečnosti chodců. Požadavek byl v minulosti již vznesen. Na místě proběhlo místní šetření za účasti policie – dopravní inspektorát, správa a údržba silnic a MěÚ Benešov – silniční úřad. Pan Nebeský byl na místní šetření písemně i telefonicky pozván, nezúčastnil se ho.",
    "S. Nebeský: Česká pošta má otevřeno pouze 20 hodin týdně. Uvažuje se o zřízení alternativy pošta Partner? Starosta: Ne.",
    "P. Bydžovský: Upozornil na stromy vysazené podle silnice u fotbalového hřiště. Hrušně jsou napadené. Starosta: Realizační firma v létě prováděla údržbu výsadby. Upozorním je na to.",
    "M. Steinhübel: Dotaz, zda by nebylo možné upravit velikost pozemku pro povolení čističky odpadních vod? Starosta: Musel by se změnit územní plán. Proběhla diskuse o možnosti spojovat pozemky více rodinných domů k vybudování společné čistírny odpadních vod. Starosta: Dám dotaz na MěÚ Benešov, Odbor životního prostředí.",
  ]),

  h3("12) Usnesení a závěr"),
  p("Starosta se zeptal návrhové komise na doplnění nebo změnu usnesení z jednání. Nebylo vzneseno žádné doplnění či změna. Proběhlo hlasování."),
  vote(V9),
  p("Závěr: Zastupitelstvo obce bylo ukončeno v 20:33 hod."),

  p("Datum pořízení zápisu: 15.11.2022"),
  p("Ověřovatelé zápisu a starosta obce, podepsáno v listinné podobě."),
  h4("Přílohy"),
  ...nl([
    "Svolání zastupitelstva obce",
    "Prezenční listina zastupitelů",
    "Prezenční listina občanů",
  ]),
];

async function run() {
  const r = await publishZapis({
    cislo: "6",
    rok: "2022",
    isoDate: "2022-11-07",
    dateLabel: "7. 11. 2022",
    fullDateDot: "7.11.2022",
    pdfPath: "scripts/zapisy-pdf/zapis-2022-6.pdf",
    transcript,
  });
  console.log("OK", r.docId, "blocks", r.blocks);
}
run().catch((e) => { console.error(e); process.exit(1); });
