/* eslint-disable no-console */
import { h3, h4, h5, p, vote, nl, ul, publishZapis, type Block } from "../zapis-lib";

const V9 = "PRO ( 9 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )";

const transcript: Block[] = [
  h4("Přítomni"),
  p("Aleš Papoušek, Jaroslav Mixa, Tomáš Kratochvíl, Jana Laboutková, Petr Dub, Aleš Kozel, Martin Jiřička, Lucie Maršíková, Šárka Dušová"),

  h3("1) Zahájení, přivítání přítomných, konstatování přítomnosti"),
  p("Starosta konstatoval, že zasedání bylo svoláno dne 4.12.2025, bylo vyvěšeno na úřední desce obecního úřadu, tj. tedy nejméně 7 dní před zasedáním. Bylo tedy svoláno řádně a včas v souladu se zákonem o obcích v platném znění. Starosta konstatoval, že podle prezenční listiny je přítomno 9 členů zastupitelstva, tedy nadpoloviční většina členů zastupitelstva. K předchozímu zápisu nebyly vzneseny námitky."),
  h5("Určení zapisovatele"),
  p("Zápisem zasedání zastupitelstva obce byla pověřena Ing. Alena Kratochvílová."),

  h3("2) Volba návrhové komise a ověřovatelů zápisu"),
  p("Starosta přednesl návrh návrhové komise a ověřovatelů zápisu."),
  h5("Návrh"),
  p("ZO schvaluje návrhovou komisi ve složení: Jaroslav Mixa, Jana Laboutková."),
  h5("Návrh"),
  p("ZO schvaluje ověřovatele zápisu ve složení Tomáš Kratochvíl, Aleš Kozel."),
  vote(V9),

  h3("3) Schválení programu"),
  p("Starosta přečetl program."),
  ...nl([
    "Zahájení",
    "Volba návrhové komise a ověřovatelů zápisu",
    "Schválení programu",
    "Rozpočtové opatření",
    "Střednědobý výhled rozpočtu obce na období 2025-2028; Rozpočet obce na rok 2026",
    "Obecně závazná vyhláška – o zákazu odpalování pyrotechnických výrobků a jejich užívání k provádění ohňostrojných prací nebo ohňostrojů",
    "Koupě, prodej, pronájem",
    "Různé",
    "Diskuse",
    "Závěr",
  ]),
  p("Starosta: Má někdo návrh na změnu nebo doplnění programu?"),
  h5("Návrh"),
  p("ZO schvaluje program zasedání zastupitelstva obce."),
  vote(V9),

  h3("4) Rozpočtové opatření"),
  h4("Rozpočtové opatření č. 7/2025"),
  p("Předseda finančního výboru Petr Dub seznámil s rozpočtovým opatřením č. 7/2025."),
  h5("Rozprava"),
  p("J.Bydžovská: Připomínka k dani z nemovitosti – poslední splátka se platí v prosinci."),
  h5("Návrh"),
  p("ZO schvaluje poskytnutí investičního příspěvku příspěvkové organizaci Základní škola Krhanice – středisko Školní jídelna na nákup 2 ks indukčních sporáků ve výši 296.000,- Kč."),
  vote(V9),
  h5("Návrh"),
  p("ZO schvaluje rozpočtové opatření č. 7/2025."),
  vote(V9),

  h3("5) Střednědobý výhled rozpočtu obce Krhanice na období 2025 – 2028; Rozpočet obce Krhanice na rok 2026"),
  p("Prvotní informace starosty: Tento bod jednání je velmi rozsáhlý. Z důvodu, že jednotlivé materiály na sebe navazují nebo jsou provázány určitými údaji, budete nejdříve seznámeni se všemi materiály."),

  h4("Střednědobý výhled rozpočtu 2025 – 2028"),
  p("Informace starosty:"),
  p("Střednědobý výhled rozpočtu je nástrojem sloužícím pro střednědobé finanční plánování rozvoje. Sestavuje se na základě uzavřených smluvních vztahů a přijatých závazků zpravidla na 2 až 5 let následujících po roce, na který se sestavuje roční rozpočet."),
  p("Střednědobý výhled rozpočtu obsahuje souhrnné základní údaje o příjmech a výdajích, o dlouhodobých závazcích a pohledávkách, o finančních zdrojích a potřebách dlouhodobě realizovaných záměrů."),
  p("U dlouhodobých závazků se uvádí dopady na hospodaření územního samosprávného celku po celou dobu trvání závazku (v našem případě splátka zápůjčky)."),
  p("Návrh střednědobého výhledu rozpočtu byl zveřejněn dne 26.11.2025."),
  p("Starosta seznámil přítomné se Střednědobým výhledem rozpočtu na období 2025 – 2028."),

  h4("Rozpočet 2026 - Fond obnovy vodovodů obcí Krhanice a Prosečnice"),
  p("Informace starosty:"),
  p("Návrh Rozpočtu Fondu obnovy vodovodů obcí Krhanice a Prosečnice byl vyvěšen 26.11.2025."),
  p("Návrh Rozpočtu Fondu je vyrovnaný."),
  p("Předpoklad konečného zůstatku Fondu k 31.12.2025: 838 tisíc Kč."),

  h4("Rozpočet obce Krhanice na rok 2026 po změně"),
  p("Petr Dub přečetl Zápis komise pro sestavení rozpočtu 2026."),
  p("Starosta informoval o procesu sestavení návrhu rozpočtu pro rok 2026."),
  p("Starosta informoval o návrhu rozpočtu pro rok 2026. Oproti vyvěšenému návrhu rozpočtu obce pro rok 2026 dojde ke změně v rozpočtu – navýšení příspěvku základní škole na plavání."),

  h4("Provozní příspěvek pro zřízené příspěvkové organizace: Základní škola Krhanice a Mateřská škola Krhanice"),
  p("Návrh Rozpočtu a Návrh Střednědobého výhledu rozpočtu příspěvkových organizací zřízených obcí Krhanice byl vyvěšen 26.11.2025."),
  p("Návrh provozního příspěvku pro příspěvkové organizace pro rok 2026 po změně byl předložen v tabulce: Mateřská škola Krhanice, okres Benešov – provozní příspěvek pro rok 2026 v Kč 831 550,- Kč, provozní příspěvek pro rok 2026 financování nepedagogických pracovníků a ostatních neinvestičních výdajů 769 188,- Kč, celkem 1 600 738,- Kč. Základní škola Krhanice, okres Benešov – 3 256 000,- Kč, 3 433 746,- Kč, celkem 6 689 746,- Kč, změna 3 613 746,- Kč, celkem po změně 6 869 746,- Kč. V tom: Středisko Základní škola – 2 337 300,- Kč, 1 590 436,- Kč, celkem 3 927 736,- Kč, změna 1 770 436,- Kč, celkem po změně 4 107 736,- Kč. Středisko Školní jídelna – 918 700,- Kč, 1 843 310,- Kč, celkem 2 762 010,- Kč."),
  p("Další zdroj finanční činnosti základní školy je Fond investic. Škola ho plánuje využít pro rok 2026 na financování oprav a údržby a vybavení do školní kuchyně. Předpokládaný stav Fondu investic bude ke dni 31.12.2025 ve výši 249 406 Kč."),
  p("Starosta: Součástí Rozpočtu 2026 je Příloha po ZMĚNĚ."),
  p("Přílohu přečetl Tomáš Kratochvíl."),
  p("Š.Dušová odešla z jednání v 16:01 hod."),
  p("Š.Dušová přišla na jednání v 16:05 hod."),
  h5("Rozprava"),
  p("L.Maršíková: Dotaz na ostrůvek na příjezdu do Krhanic, kdy bude realizován? Starosta: Práce jsou naplánovány na příští rok, ale budeme řešit pouze náhradní výsadbu zeleně. Proběhla diskuse o ostrůvku."),
  p("L.Maršíková: Dotaz, zda do námětů k rozpočtu podala námět jedna osoba nebo dvě. P.Dub: 2 osoby."),
  p("L.Maršíková: Dotaz na částku 60 tisíc na opravu zadní části Sokolky, zda to budou opravovat sami sokolové, nebo nějaká firma? Starosta: Sokolové v areálu dělají dost věcí brigádnicky. Tuto akci bude provádět firma."),
  p("L.Maršíková: Dotaz na hřiště v Hodkově. Není to hřiště veřejné, proč budeme osazovat nové prvky? T.Kratochvíl: Není to sice veřejné hřiště, ale veřejný prostor. Většina stávajících prvků nemá revizi. Nově osazené je mít budou. Prvky vybírala Komise pro obnovu a rozvoj obce s přihlédnutím k názorům maminek navštěvujících hřiště."),
  p("L.Maršíková: Dotaz na vizualizaci návsi u autobusové zastávky, zda to bude dělat nějaký odborník nebo některá z komisí? Starosta: Náves bude řešena jako celek, zpracování zadáme firmě. Stejné jako zpracovala vizualizaci prostoru před obchodem."),
  p("L.Maršíková: Dotaz k Unii rodičů, zda s nimi bude rovněž uzavřena veřejnoprávní smlouva? Starosta: Ano. Uzavírá se s nimi smlouva jako se všemi ostatními. Podávají vyúčtování stejně jako všichni, kdo dotaci obdrží."),
  p("Š.Dušová: Dotaz k rozpočtovému výhledu. Jsou v tom i peníze pro školství. Starosta: Je to nějaký odhad."),
  p("Š.Dušová: Schodek rozpočtu 14 milionů mi připadá dost vysoká částka, mají některé akce vyšší prioritu? Nešlo by některé z nich přesunout do dalšího roku? Starosta: Jsou to dlouhodobě plánované akce a dělají se průběžně."),
  p("I.Dvořák: Dotaz na dešťovou kanalizaci k Havlíkům, chtěl upřesnit na mapě odkud kam povede. Má obec představu, kde všude po obci je dešťová kanalizace? Má obec k dispozici nějaké plány? Starosta ukázal na mapě umístění kanalizace u Havlíků."),
  p("I.Dvořák: Dotaz, zda bude možnost pro jednotlivé domácnosti připojit se na dešťovou kanalizaci i domácími čističkami? Starosta: Oslovili jsme majitele nemovitostí a někteří mají zájem."),
  p("I.Dvořák: Dotaz, zda už máme zprávu o uplatňování územního plánu? Starosta: Už je vypracovaná, mám ji rozečtenou."),
  p("I.Dvořák: Dotaz na kanalizaci, kdy se rozhodne, že se bude nebo nebude budovat první etapa? Starosta: Na pracovním zastupitelstvu v lednu by se měli zastupitelé rozhodnout jakou cestou půjdeme."),
  p("J.Bydžovská: Dotaz na aktuální stav účtů obce. Starosta: Cca 30 milionů"),
  h5("Návrh"),
  p("ZO schvaluje Střednědobý výhled rozpočtu obce Krhanice na období 2025 – 2028."),
  vote("PRO ( 7 ) – PROTI ( 2 – Maršíková, Dušová ) – ZDRŽEL SE ( 0 )"),
  h5("Návrh"),
  p("ZO schvaluje pro rok 2026 použití Fondu investic příspěvkové organizace Základní škola Krhanice – středisko Školní jídelna na financování oprav a údržby a nákup vybavení do školní kuchyně."),
  vote(V9),
  h5("Návrh"),
  p("ZO schvaluje Rozpočet Fondu financování obnovy vodovodů obcí Krhanice a Prosečnice pro rok 2026 jako vyrovnaný."),
  vote(V9),
  h5("Návrh"),
  p("ZO schvaluje změny v Rozpočtu obce Krhanice na rok 2026 a v Příloze Rozpočtu obce Krhanice na rok 2026 v důsledku navýšení příspěvku pro základní školu o 180 000,- Kč a v návaznosti na toto navýšení změny v rozpočtu obce v části běžných výdajů a financování obce."),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 2 – Maršíková, Dušová )"),
  h5("Návrh"),
  p("ZO schvaluje Přílohu Rozpočtu obce Krhanice na rok 2026."),
  vote("PRO ( 7 ) – PROTI ( 2 – Maršíková, Dušová ) – ZDRŽEL SE ( 0 )"),
  h5("Návrh"),
  p("ZO schvaluje Rozpočet obce Krhanice na rok 2026 jako schodkový. Schodek bude hrazen finančními prostředky z minulých let."),
  vote("PRO ( 7 ) – PROTI ( 2 – Maršíková, Dušová ) – ZDRŽEL SE ( 0 )"),

  h3("6) Obecně závazná vyhláška - o zákazu odpalování pyrotechnických výrobků a jejich užívání k provádění ohňostrojných prací nebo ohňostrojů"),
  p("Místostarosta seznámil přítomné se změnami týkající se pyrotechniky v této republice. Od 1.12.2025 vznikla mapa, ve které jsou vyznačeny oblasti, kde nelze používat pyrotechniky kategorie F2 až F3. Mapa se vytváří podle míst 250 metrů od významných objektů nebo chovů, např. nemocnic, chovu dobytka, …"),
  p("https://agrigis.gov.cz/portal/apps/instant/basic/index.html?appid=ded81b51ac6e4ea1b071ef28122f547b"),
  p("Místa, která nejsou vyznačena barevně, musíme ošetřit obecní vyhláškou. Podstatné ve vyhlášce je, že bude celoroční zákaz používání pyrotechniky kategorie F2 až F3 kromě:"),
  p("Zákaz stanovený touto vyhláškou neplatí:"),
  ...ul([
    "a) ve dnech 31. prosince a 1. ledna,",
    "b) v místě a době konání kulturní, sportovní nebo jiné společenské akce přístupné veřejnosti.",
  ]),
  p("Název vyhlášky: Obecně závazná vyhláška obce Krhanice o regulaci zacházení s pyrotechnickými výrobky"),
  h5("Rozprava"),
  p("L.Maršíková: Kdo vypracoval tyto výjimky? Starosta: Výjimky jsme si zvolili my, vyhlášku jsme zpracovali podle předlohy na webu Ministerstva vnitra."),
  p("L.Maršíková: Navrhla, aby ve vyhlášce žádné výjimky nebyly."),
  p("Proběhla diskuse o tom, zda by nebylo lepší úplně zakázat na území celé obce používání veškeré pyrotechniky bez výjimek. Starosta navrhl posunout účinnost vyhlášky od 2.1.2026."),
  p("Jelikož se zastupitelé neshodli na znění návrhu nové vyhlášky k hlasování, bylo jednání přerušeno 16:55 – 17:08 hodin. Poté byl předložen návrh k hlasování."),
  h5("Návrh"),
  p("ZO schvaluje Obecně závaznou vyhlášku obce Krhanice o regulaci zacházení s pyrotechnickými výrobky s platností od 2.1.2026."),
  vote("PRO ( 5 ) – PROTI ( 4 – Maršíková, Dušová, Kozel, Kratochvíl ) – ZDRŽEL SE ( 0 )"),

  h3("7) Koupě, prodej, pronájem"),
  ...ul(["pronajmout část pozemku parc. č. 59/1 k.ú. Krhanice o výměře 915 m² ke zřízení zahrádky za cenu 15,- Kč/1 m²/rok od 1.1.2026 do 31.12.2026."]),
  p("Informace starosty: Jedná se o žádost pana Klapáče."),
  h5("Rozprava"),
  p("L.Maršíková: Velikost pronájmu je menší než v předchozím roce. Starosta: Vzdálenost od hasičské zbrojnice je o jeden metr větší."),
  h5("Návrh"),
  p("ZO schvaluje pronájem části pozemku parc. č. 59/1 k.ú. Krhanice o výměře 915 m² ke zřízení zahrádky za cenu 15,- Kč/1 m²/rok od 1.1.2026 do 31.12.2026 Janu Klapáčovi, Hennerova 3/2009, 150 00 Praha 5."),
  vote(V9),
  ...ul(["prodat části pozemku parc.č. 1984 k.ú. Krhanice o výměře 132 m² – díl a+c a část pozemku parc.č. 1984 k.ú. Krhanice o výměře 22 m² – díl b dle geometrického plánu č. 1233-124/2025 za cenu 28 126 Kč."]),
  p("Informace starosty: Jedná se o žádost Jaroslavy Hánové. Ta předložila dokumenty, ze kterých vyplývá, že v roce 1940 (1940) nebyla zapsána do katastru nemovitostí koupě části obecního pozemku. Stvrzenka z roku 1942 byla předložena. Zároveň byl obecním geodetem zaměřen skutečný stav pozemku. Výsledkem je, že 126 m² je historický odkup a 28 m² je připlocení do obecního pozemku."),
  p("Historické m² budou za 1 Kč – narovnání historického stavu a nové m² bylo za 1000,- Kč/1 m². Celková částka je 28 126 Kč."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje prodej části pozemku parc.č. 1984 k.ú. Krhanice o výměře 132 m² – díl a+c a část pozemku parc.č. 1984 k.ú. Krhanice o výměře 22 m² – díl b dle geometrického plánu č. 1233-124/2025 za cenu 28 126 Kč Jaroslavě Hánové, Krhanice č.p. 139, 257 42 Krhanice."),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 2 – Maršíková, Dušová )"),
  ...ul(["koupě pozemků parc.č. 148/12, 247, 264, 265, 239 a 403/3 vše k.ú. Krhanice (v rámci budování kanalizace a ČOV Krhanice)."]),
  p("Informace starosty: V rámci budování kanalizace a ČOV Krhanice budeme vykupovat pozemky. Po jednáních s paní Norkovou jsme se dohodli na odkupu pozemků souvisejících s kanalizací a dvou pozemků nesouvisejících s kanalizací."),
  p("Jedná se o pozemky 148/12; 247; 264; 265;239 a 403/3. Pozemky související s kanalizací budeme kupovat za cenu 100,- Kč/1 m² a pozemky nesouvisející s kanalizací budeme kupovat za cenu 60,- Kč/1 m²."),
  p("Pozemek parc.č. 148/12 – trvalý travní porost, velikost 360, cena za m2 60 Kč, cena za pozemek 21 600 Kč, souvislost s kanalizací NE, poznámka: vodoteče - přítoku do nádrže Gabčíkovo; obec má sousední pozemky parc.č. 128/10 a 1988. Pozemek parc.č. 247 – ostatní plocha, velikost 707, cena za m2 100 Kč, cena za pozemek 70 700 Kč, souvislost ANO, poznámka: u přítoku do Palečnického potoka pod lokalitou Na vlčím důle. Pozemek parc.č. 264 – ostatní plocha, velikost 126, cena za m2 100 Kč, cena za pozemek 12 600 Kč, souvislost ANO, poznámka: u Palečnického potoka pod lokalitou Nad Palouky. Pozemek parc.č. 265 – trvalý travní porost, velikost 486, cena za m2 100 Kč, cena za pozemek 48 600 Kč, souvislost ANO, poznámka: u Palečnického potoka pod lokalitou Nad Palouky, sousední pozemek s pozemkem parc.č. 264. Pozemek parc.č. 239 – trvalý travní porost, velikost 1133, cena za m2 100 Kč, cena za pozemek 113 300 Kč, souvislost ANO, poznámka: pod lokalitou Na vlčím důle. Pozemek parc.č. 403/3 – trvalý travní porost, velikost 2176, cena za m2 60 Kč, cena za pozemek 130 560 Kč, souvislost NE, poznámka: pozemek nad vodojemem, přístup k vodojemu není po obecním pozemku - možnost směny. CELKEM 397 360 Kč."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje koupi pozemků parc.č. 148/12, 247, 264, 265, 239 a 403/3 vše k.ú. Krhanice za cenu 397 360 Kč od Marcely Norkové, Zašová č.p. 752, 756 51 Zašová."),
  vote(V9),

  h3("8) Různé"),
  h4("Dílčí přezkoumání hospodaření obce Krhanice"),
  p("Informace starosty: Dne 26.11.2025 se uskutečnilo dílčí přezkoumání hospodaření obce ze strany Středočeského kraje, odboru kontroly s výsledkem – nebyly zjištěny chyby a nedostatky."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí Zápis z dílčího přezkoumání hospodaření územního celku obce Krhanice z 26.11.2025."),

  h4("Obecní knihovna Krhanice"),
  p("Informace starosty: Návrh v pokračování v roce 2026 s osvobozením od placení registračního poplatku."),
  p("Zároveň dojde od 1.1.2026 ke změně na pozici knihovnice. Novou knihovnicí bude Dana Kohoutová."),
  h5("Rozprava"),
  p("L.Maršíková: Jaký bude mít úvazek paní Kohoutová? Starosta: Stejný jako měla paní Dubová."),
  h5("Návrh"),
  p("ZO schvaluje Dodatek č. 16 k Příloze č. 1 Knihovního řádu Obecní knihovny Krhanice Výpůjční řád."),
  vote(V9),
  h5("Návrh"),
  p("ZO bere na vědomí, že od 1.1.2026 bude novou knihovnicí Obecní knihovny Krhanice Dana Kohoutová."),

  h4("Fotovoltaika na střeše klubovny zázemí víceúčelového hřiště v Krhanicích"),
  p("Informace starosty: Získali jsme dotaci na FVE na klubovně. Nyní musíme vypsat výběrové řízení. S výběrovým řízením budeme spolupracovat s Posázaví o.p.s. Jako odborníka si vezmeme Filipa Saturku, který nám připravoval odbornou část do dotace. Budou osloveny minimálně 3 firmy."),
  h5("Rozprava"),
  p("Š.Dušová: Jaká budou kritéria výběrového řízení? Starosta: Připravovat podklad bude pan Saturka. Předpokládám, že nejnižší cena."),
  h5("Návrh"),
  p("ZO pověřuje starostu obce vypsáním výběrového řízení na projekt Fotovoltaika na střeše klubovny zázemí víceúčelového hřiště v Krhanicích."),
  vote(V9),
  h5("Návrh"),
  p("ZO schvaluje spolupráci s Posázavím o.p.s. při realizaci výběrového řízení na projekt Fotovoltaika na střeše klubovny zázemí víceúčelového hřiště v Krhanicích."),
  vote(V9),

  h4("Školní jídelna cizí strávníci – cena oběda od 1.1.2026"),
  p("Informace starosty: Základní škola předložila zvýšení ceny stravného pro cizí strávníky od 1.1.2026. Cena se nezvyšovala od roku 2023."),
  p("Cena stravného od 2026 / od 2023: Potraviny 44,- Kč / 39,- Kč. Mzdy 29,- Kč / 29,- Kč. Věcné náklady 17,- Kč / 12,- Kč. Zisk 1,- Kč / 1,- Kč. Celkem 91,- Kč / 81,- Kč."),
  h5("Rozprava"),
  p("L.Maršíková: Kolik je cizích strávníků? Starosta: Cca 5–11 strávníků denně."),
  h5("Návrh"),
  p("ZO schvaluje cenu stravného pro cizí strávníky Školní jídelny Krhanice od 1.1.2026 ve výši 91,- Kč."),
  vote(V9),

  h4("Plán financování obnovy vodohospodářské infrastruktury"),
  p("Informace starosty: Společná voda ve spolupráci s Vodohospodářskou společností Benešov nám připravily Plán financování obnovy vodovodu Obce Krhanice pro období 2026-2035 dle příslušné legislativy."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Plán financování obnovy vodovodu Obce Krhanice pro období 2026-2035."),
  vote("PRO ( 8 ) – PROTI ( 0 ) – ZDRŽEL SE ( 1 - Dušová )"),

  h3("9) Diskuse"),
  p("Š.Dušová: Upozornila na místo u nádraží, kde se shromažďuje omladina. Není zde světlo. V poslední době je tam viděla několikrát. Starosta: Osvětlení bude řešeno spolu s chodníkem k nádraží."),
  p("M.Maršík: Upozornil na to, že v zatáčce u Josífka potkal, a ne poprvé, děti. Dotaz, zda by toto místo nešlo nějak vyřešit. Např. instalací prahů. Starosta: Už jsme to řešili, bohužel řada navrhovaných možností neprošla."),
  p("Proběhla diskuse. Padlo několik návrhů, např. osazení dopravních značek upozorňujících na pohyb chodců, osazení zpomalovacích prahů, vodorovné značení …"),
  p("P.Schiller: Poděkoval zastupitelům za velkou podporu jak zásahové jednotky, tak i sboru dobrovolných hasičů."),
  p("Starosta: Požádal Petra Schillera, aby zastoupil Ivanu Kratochvílovou s přáním k Vánocům a do nového roku. Petr Schiller popřál všem hezké vánoční svátky a vše nejlepší do nového roku 2026."),

  h3("10) Závěr"),
  p("Zastupitelstvo obce bylo ukončeno v 17:42 hod."),

  p("Datum pořízení zápisu: 18.12.2025"),
  p("Ověřovatelé zápisu a starosta obce, podepsáno v listinné podobě."),
  h4("Přílohy"),
  ...nl(["Svolání zastupitelstva obce", "Prezenční listina zastupitelů", "Prezenční listina občanů"]),
];

async function run() {
  const r = await publishZapis({
    cislo: "6",
    rok: "2025",
    isoDate: "2025-12-12",
    dateLabel: "12. 12. 2025",
    fullDateDot: "12.12.2025",
    pdfPath: "scripts/zapisy-pdf/zapis-2025-6.pdf",
    transcript,
  });
  console.log("OK", r.docId, "blocks", r.blocks);
}
run().catch((e) => { console.error(e); process.exit(1); });
