/* eslint-disable no-console */
// Faithful visual transcript of Zápis č. 2/2021 (14.6.2021), read page-by-page
// from the official PDF (13 pages). Structure per scripts/build-zapis-2026-1.ts.
import { h3, h4, h5, p, vote, nl, ul, publishZapis, type Block } from "../zapis-lib";

const V8 = "PRO ( 8 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )";

const transcript: Block[] = [
  h4("Přítomni"),
  p("Aleš Papoušek, Jaroslav Mixa, Václav Zíta, Tomáš Kratochvíl, Petr Dub, Martin Jiřička, Bohuslav Kadeřábek, Edita Jarošová"),
  h4("Omluveni"),
  p("Jana Laboutková"),

  h3("1) Zahájení, přivítání přítomných, konstatování přítomnosti"),
  p("Starosta konstatoval, že zasedání bylo svoláno dne 4.6.2021 bylo vyvěšeno na úřední desce obecního úřadu, tj. tedy nejméně 7 dní před zasedáním. Bylo tedy svoláno řádně a včas v souladu se zákonem o obcích v platném znění. Starosta konstatoval, že podle prezenční listiny je přítomno 8 členů zastupitelstva, tedy nadpoloviční většina členů zastupitelstva. K předchozímu zápisu nebyly vzneseny námitky."),
  h5("Určení zapisovatele"),
  p("Zápisem zasedání zastupitelstva obce byla pověřena Ing. Alena Kratochvílová."),
  p("Starosta přečetl program."),
  ...nl([
    "Zahájení",
    "Volba návrhové komise a ověřovatelů zápisu",
    "Zpráva finančního výboru o kontrole hospodaření obce Krhanice za rok 2020; Zpráva o výsledcích veřejnosprávních kontrol hospodaření Mateřské školy Krhanice a Základní školy Krhanice za rok 2020",
    "Schválení účetní závěrky Mateřské školy Krhanice a Základní školy Krhanice za rok 2020",
    "Schválení účetní závěrky obce Krhanice za rok 2020",
    "Závěrečný účet obce Krhanice pro rok 2020",
    "Obecně závazná vyhláška obce – o nočním klidu",
    "Koupě, prodej, pronájem",
    "Rozpočtové opatření",
    "Různé",
    "Diskuse",
    "Usnesení a závěr",
  ]),
  p("Proběhlo hlasování o programu."),
  h5("Návrh"),
  p("ZO schvaluje program zasedání zastupitelstva obce."),
  vote(V8),

  h3("2) Volba návrhové komise a ověřovatelů zápisu"),
  p("Starosta přednesl návrh návrhové komise a ověřovatelů zápisu."),
  h5("Návrh"),
  p("ZO schvaluje návrhovou komisi ve složení Jaroslav Mixa, Petr Dub."),
  h5("Návrh"),
  p("ZO schvaluje ověřovatele zápisu ve složení Václav Zíta, Bohuslav Kadeřábek."),
  vote(V8),

  h3("3) Zpráva finančního výboru o kontrole hospodaření obce Krhanice za rok 2020; Zpráva o výsledcích veřejnosprávních kontrol hospodaření Mateřské školy Krhanice a Základní školy Krhanice za rok 2020"),
  p("Bohuslav Kadeřábek seznámil s kontrolou hospodaření obce Krhanice za rok 2020. A dále seznámil s proběhlými veřejnosprávními kontrolami hospodaření příspěvkových organizací Mateřské školy Krhanice a Základní školy Krhanice. Kontroly proběhly dne 17.5.2021."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí zprávu finančního výboru o kontrole hospodaření obce Krhanice za rok 2020 ze dne 17.5.2021."),
  h5("Návrh"),
  p("ZO bere na vědomí protokoly o průběhu a výsledcích veřejnosprávních kontrol příspěvkových organizací Základní škola Krhanice a Mateřská škola Krhanice za rok 2020 ze dne 17.5.2021."),

  h3("4) Schválení účetní závěrky Mateřské školy Krhanice a Základní školy Krhanice za rok 2020"),
  h4("Mateřská škola Krhanice"),
  p("Starosta (zřizovatel) seznámil přítomné se Zprávou zřizovatele k podkladům pro schválení účetní závěrky příspěvkové organizace Mateřská škola Krhanice, okres Benešov za rok 2020."),
  p("Starosta (zřizovatel) doporučuje na základě této zprávy přijmout tento návrh usnesení zastupitelstva ve věci schválení účetní závěrky Mateřské školy v tomto znění:"),
  p("ZO schvaluje účetní závěrku příspěvkové organizace Mateřská škola Krhanice, okres Benešov za rok 2020; schvalovaná účetní závěrka poskytuje věrný a poctivý obraz předmětu účetnictví a finanční situace účetní jednotky."),
  p("Starosta přečetl „Protokol o schvalování účetní závěrky za rok 2020 příspěvkové organizace Mateřská škola Krhanice, okres Benešov“."),
  p("Ředitelka Mateřské školy Krhanice sdělila, že se k protokolu vyjádří písemně."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje účetní závěrku příspěvkové organizace Mateřská škola Krhanice, okres Benešov za rok 2020; schvalovaná účetní závěrka poskytuje věrný a poctivý obraz předmětu účetnictví a finanční situace účetní jednotky."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje Protokol o schvalování účetní závěrky za rok 2020 příspěvkové organizace Mateřská škola Krhanice, okres Benešov."),
  vote(V8),

  h4("Základní škola Krhanice"),
  p("Starosta (zřizovatel) seznámil přítomné se Zprávou zřizovatele k podkladům pro schválení účetní závěrky příspěvkové organizace Základní škola Krhanice, okres Benešov za rok 2020."),
  p("Starosta (zřizovatel) doporučuje na základě této zprávy přijmout tento návrh usnesení zastupitelstva ve věci schválení účetní závěrky Základní školy v tomto znění:"),
  p("ZO schvaluje účetní závěrku příspěvkové organizace Základní škola Krhanice, okres Benešov za rok 2020; schvalovaná účetní závěrka poskytuje věrný a poctivý obraz předmětu účetnictví a finanční situace účetní jednotky."),
  p("Starosta přečetl „Protokol o schvalování účetní závěrky za rok 2020 příspěvkové organizace Základní škola Krhanice, okres Benešov“."),
  p("Ředitelka Základní školy Krhanice sdělila, že se k protokolu vyjádří písemně."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje účetní závěrku příspěvkové organizace Základní škola Krhanice, okres Benešov za rok 2020; schvalovaná účetní závěrka poskytuje věrný a poctivý obraz předmětu účetnictví a finanční situace účetní jednotky."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje rozdělení hospodářského výsledku příspěvkové organizace Základní škola Krhanice za rok 2020 ve výši 26.035,24 Kč do rezervního fondu."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje Protokol o schvalování účetní závěrky za rok 2020 příspěvkové organizace Základní škola Krhanice, okres Benešov."),
  vote(V8),

  h3("5) Schválení účetní závěrky obce Krhanice za rok 2020"),
  h4("Zpráva o výsledku přezkoumání hospodaření obce za rok 2020"),
  p("Informace starosty: Starosta seznámil s výsledky kontroly hospodaření za rok 2020 provedené Středočeským krajem, odborem interního auditu a kontroly dne 22.4.2021. Výsledek – nebyly zjištěny chyby a nedostatky."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí Zprávu o výsledku přezkoumání hospodaření obce za rok 2020."),
  p("Bohuslav Kadeřábek seznámil přítomné se Zprávou Finančního výboru obce Krhanice k podkladům pro schválení účetní závěrky obce Krhanice za rok 2020."),
  p("Finanční výbor doporučuje na základě této zprávy přijmout tento návrh usnesení zastupitelstva ve věci schválení účetní závěrky obce Krhanice v tomto znění:"),
  p("ZO schvaluje účetní závěrku obce Krhanice, okres Benešov za rok 2020; schvalovaná účetní závěrka poskytuje věrný a poctivý obraz předmětu účetnictví a finanční situace účetní jednotky."),
  p("Finanční výbor dále doporučuje schválit výsledek hospodaření ve schvalovacím řízení za rok 2020 obce Krhanice v částce + 7.157.023,48 Kč a jeho převod na účet 432 výsledek hospodaření předchozích účetních období."),
  p("Starosta přečetl „Protokol o schvalování účetní závěrky za rok 2020 obce Krhanice“."),
  h5("Rozprava"),
  p("J.Bydžovská: Dotaz na rozdílné částky ve výsledku hospodaření obce. Starosta: Částka přes 2 milióny Kč představuje pouze rozdíl příjmů a výdajů bez uzávěrkových operací."),
  h5("Návrh"),
  p("ZO schvaluje účetní závěrku obce Krhanice za rok 2020; schvalovaná účetní závěrka poskytuje věrný a poctivý obraz předmětu účetnictví a finanční situace účetní jednotky."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje výsledek hospodaření ve schvalovacím řízení za rok 2020 obce Krhanice a jeho převod na účet 432 výsledek hospodaření předchozích účetních období."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje Protokol o schvalování účetní závěrky za rok 2020 obce Krhanice."),
  vote(V8),

  h3("6) Závěrečný účet obce Krhanice pro rok 2020"),
  p("Starosta seznámil se Závěrečným účtem obce Krhanice pro rok 2020. Návrh Závěrečného účtu včetně příloh byl vyvěšen na úřední desce a elektronické úřední desce dne 7.5.2021. Závěrečný účet obsahuje přehled hospodaření obce za rok 2020, hospodaření zřízených příspěvkových organizací za rok 2020 a Zprávu z celkového přezkoumání hospodaření obce. Do Závěrečného účtu bude vložena dodatečná informace o schválení účetní závěrky za rok 2020 za obec Krhanice, MŠ a ZŠ Krhanice zastupitelstvem obce dne 14.6.2021. Závěrečný účet za rok 2020 bude vyvěšen až do doby schválení nového Závěrečného účtu za rok 2021."),
  p("Písemné připomínky k závěrečnému účtu nebyly podány. Ústní připomínky: „Má někdo z přítomných připomínky k závěrečnému účtu obce?“"),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Závěrečný účet obce Krhanice za rok 2020 a dává souhlas s celoročním hospodařením, a to bez výhrad."),
  vote(V8),

  h3("7) Obecně závazná vyhláška obce – o nočním klidu"),
  p("Informace místostarosty: Bude se měnit vyhláška o nočním klidu – proběhlé či zrušené akce budou z vyhlášky vyňaty a budou aktualizovány termíny u tradičních akcí. Bude změna termínu u akce KRHANICE BEAT FEST: z června přesun na 11.9.2021 a přibyla akce Letní kino. Pořadatel musí sledovat aktuální protiepidemická opatření."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Obecně závaznou vyhlášku obce Krhanice č. 1/2021, o nočním klidu."),
  vote(V8),

  h3("8) Koupě, prodej, pronájem"),
  ...ul(["uzavřít Smlouvu o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby č. IV-12-6028567/VB/002, Krhanice-kNN-č.parc. 276/2 na pozemku parc. č. 1981/1 k.ú. Krhanice s ČEZ Distribuce, a.s., IČ 24729035, DIČ CZ24729035, se sídlem Děčín IV-Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 4.000,- Kč na umístění kabelového vedení NN,"]),
  p("Informace starosty: Jedná se o pozemek u komunikace k lomu pod Sádkem vedle trafostanice. Bude to elektrická přípojka pro jeden pozemek na stavbu rodinného domu."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby č. IV-12-6028567/VB/002, Krhanice-kNN-č.parc. 276/2 na pozemku parc. č. 1981/1 k.ú. Krhanice s ČEZ Distribuce, a.s., IČ 24729035, DIČ CZ24729035, se sídlem Děčín IV-Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 4.000,- Kč na umístění kabelového vedení NN."),
  vote(V8),
  ...ul(["uzavřít Smlouvu o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby č. IV-12-6028834/VB/001, Krhanice – kNN – parc. č. 336/3 na pozemcích parc. č. 318/2 a 319 k.ú. Krhanice s ČEZ Distribuce, a.s., IČ 24729035, DIČ CZ24729035, se sídlem Děčín IV-Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 6.100,- Kč na umístění kabelového vedení NN,"]),
  p("Informace starosty: Jedná se o pozemek s chatou na začátku areálu střelnice u řeky Sázavy. Elektrická přípojka bude pro tento rekreační domek."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o budoucí smlouvě o zřízení věcného břemene a dohodu o umístění stavby č. IV-12-6028834/VB/001, Krhanice – kNN – parc. č. 336/3 na pozemcích parc. č. 318/2 a 319 k.ú. Krhanice s ČEZ Distribuce, a.s., IČ 24729035, DIČ CZ24729035, se sídlem Děčín IV-Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 6.100,- Kč na umístění kabelového vedení NN."),
  vote(V8),
  ...ul(["uzavřít Smlouvu o zřízení věcného břemene – vodovodní přípojky pro pozemek parc.č. st. 310 k.ú. Krhanice na pozemku parc.č. 1435/20 k.ú. Krhanice na dobu neurčitou za cenu 3.000,- Kč,"]),
  p("Informace starosty: Jedná se o realizaci vodovodní přípojky pro Dolní Požáry č.p. 16 (manželé Skořepovi)."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvu o zřízení věcného břemene – vodovodní přípojky pro pozemek parc.č. st. 310 k.ú. Krhanice na pozemku parc.č. 1435/20 k.ú. Krhanice na dobu neurčitou za cenu 3.000,- Kč s Bc. Jaroslavem Skořepou a Kateřinou Skořepovou, 254 01 Pohoří č.p. 16."),
  vote(V8),
  ...ul(["uzavřít Smlouvu o zřízení věcného břemene – na umístění elektrické přípojky pro pozemek parc.č. 1429/2 k.ú. Krhanice na pozemku parc.č. 1435/20 k.ú. Krhanice na dobu neurčitou za cenu 3.000,- Kč,"]),
  p("Informace starosty: Jedná se o elektrickou přípojku k pozemku s ovocným sadem Roberta Novotného, za Rafandou u lesa."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o zřízení věcného břemene – na umístění elektrické přípojky pro pozemek parc.č. 1429/2 k.ú. Krhanice na pozemku parc.č. 1435/20 k.ú. Krhanice na dobu neurčitou za cenu 3.000,- Kč s Robertem Novotným, 257 42 Krhanice č.p. 62."),
  vote(V8),
  h4("Správa železnic – žádost o zajištění souhlasu s dělením pozemků"),
  p("Informace starosty: Již jsme odsouhlasili záměr prodeje částí pozemků parc.č. 2051/5 a 1981/2 k.p. Krhanice u nádraží Správě železnic. Nyní byly Správou železnic vyhotoveny geometrické plány č. 1039-6/2021 a 1038-5/2021, kdy dochází k dělení pozemků. Po schválení geometrických plánů Odborem výstavby Týnec n.S., bude jednání ohledně odprodeje pokračovat – Správa železnic vyhotoví znalecký posudek na cenu a poté budeme projednávat na zastupitelstvu."),
  h5("Geometrický plán č. 1039-6/2021"),
  ...ul([
    "p.č. 2051/5 – ost. pl./ost.komunikace – výměra: 883 m² – zůstává obci",
    "p.č. 2051/8 – ost. pl./ost.komunikace – výměra: 80 m² – výkup pro SŽ",
    "p.č. 2051/9 – ost. pl./ost.komunikace – výměra: 88 m² – výkup pro SŽ",
  ]),
  h5("Geometrický plán č. 1038-5/2021"),
  ...ul([
    "p.č. 1981/2 – ost. pl./ost.komunikace – výměra: 650 m² – zůstává obci",
    "p.č. 1981/3 – ost. pl./ost.komunikace – výměra: 138 m² – výkup pro SŽ",
  ]),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje z důvodu odprodeje budoucích oddělených částí pozemků parc. č. 2051/8 o výměře 80 m² a 2051/9 o výměře 88 m² Správě železnic, státní organizaci, IČ 70994234, Dlážděná 1003/7, 110 00 Praha 1 dělení pozemku parc.č. 2051/5 k.ú. Krhanice dle geometrického plánu č. 1039-6/2021."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje z důvodu odprodeje budoucí oddělené částí pozemku parc. č. 1981/3 o výměře 138 m² Správě železnic, státní organizaci, IČ 70994234, Dlážděná 1003/7, 110 00 Praha 1 dělení pozemku parc.č. 1981/2 k.ú. Krhanice dle geometrického plánu č. 1038-5/2021."),
  vote(V8),

  h3("9) Rozpočtové opatření"),
  h4("Pojištění členů zásahové jednotky JSDHO Krhanice"),
  p("Počet členů zásahové jednotky hasičů (JSDHO Krhanice) se navýšil o jednoho. Při revizi smlouvy navýšíme pojištění tak, aby v případě úrazu hasiče hasičem bylo dvojnásobné plnění na 500.000,- Kč. Smlouva obsahuje i vyšší limity na pojištění odpovědnosti za škodu."),
  h5("Návrh"),
  p("ZO schvaluje pojistnou smlouvu pojištění odpovědnosti za újmu a pojištění úrazu Jednotky sboru dobrovolných hasičů obce Krhanice s Hasičskou vzájemnou pojišťovnou, a.s."),
  vote(V8),
  h4("Základní škola"),
  p("Martin Jiřička přečetl dopis ředitelky Základní školy Krhanice – žádost o financování spoluúčasti školy z důvodu podání dotace na nákup tabulí s interaktivním systémem do kmenových učeben. Celková výše projektu je na částku 705.187,- Kč a spoluúčast školy na dotaci je 141.038,- Kč."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje investiční příspěvek ve výši 141.038,- Kč Základní škole Krhanice pro zajištění podílu školy pro dotaci z Programu rozvoje venkova pro pořízení tabulí s interaktivním systémem do kmenových učeben v roce 2021. V případě neobdržení této dotace z Programu rozvoje venkova bude celá částka poskytnutého příspěvku vrácena obci Krhanice v termínu do 10.12.2021."),
  vote(V8),
  p("Informace starosty byl předložen odpisový plán na elektrickou pánev zakoupenou do základní školy tento rok."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje předložený odpisový plán na elektrickou pánev pro Základní školu Krhanice."),
  vote(V8),
  p("Informace starosty – byl předložen rozpočet na dovybavení IT učebny (PC Dell a síťové prvky)."),
  h5("Návrh"),
  p("ZO schvaluje navýšení provozního příspěvku o 89.000,- Kč pro Základní školu Krhanice na navýšení odpisů a na dovybavení IT učebny."),
  vote(V8),
  h4("TAJV, z.s. – žádost o finanční příspěvek"),
  p("Starosta seznámil s žádostí TAJV, z.s. o příspěvek na sportovní den mládeže s TAJV v Krhanicích ve výši 5.000,- Kč."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO neschvaluje poskytnutí finančního příspěvku ve výši 5.000,- Kč pro TAJV, z.s., IČ 09287094, Sportovní 158, 290 01 Poděbrady na pořádání sportovního dne mládeže s TAJV v Krhanicích v roce 2021."),
  vote(V8),
  h4("Veřejně prospěšné práce"),
  p("Informace starosty: Využití dotace od Úřadu práce a zaměstnání 2 lidí z obce Krhanice v rámci veřejně prospěšných prací. Navýšení mzdových prostředků na 6 měsíců – paragraf komunální služby a rozvoj. Dotace na jedno pracovní místo je 15.000,- Kč/1 měsíc."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí účast obce Krhanice v rámci aktivní politiky zaměstnanosti (veřejně prospěšné práce)."),
  p("Předseda finančního výboru Bohuslava Kadeřábka přednesl odůvodnění rozpočtového opatření č. 3/2021."),
  h5("Rozprava"),
  p("L.Maršíková: Dotaz na 2 lidi z úřadu práce, zda to budou další dva k těm stávajícím. Co bude náplní jejich práce? Starosta: Ano. Budou mít na starosti zeleň, zalévání a úklid."),
  p("L.Maršíková: Dotaz na částku na projektovou dokumentaci a geodetické práce na návsi, čeho se to týká? Starosta: Jedná se o přechodové místo, které by mělo vést z chodníku u pítka až autobusové zastávce. Vše souvisí s žádostí o dotaci na náves a chodníky u obchodu."),
  h5("Návrh"),
  p("ZO schvaluje rozpočtové opatření č. 3/2021."),
  vote(V8),

  h3("10) Různé"),
  h4("Několika větami"),
  p("Zpráva starosty, co proběhlo, …"),
  h5("Rozprava"),
  p("J.Stibůrek: Jsou náklady na likvidaci odpadů náklady obce? Starosta: ano."),
  h4("DSO BENE-BUS: Závěrečný účet"),
  p("Informace starosty: Byl nám předložen Závěrečný účet za rok 2020 a Zpráva o výsledku přezkoumání hospodaření za rok 2020."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Závěrečný účet DSO BENE-BUS za rok 2020 a souhlasí s celoročním hospodařením, a to bez výhrad."),
  vote(V8),
  h5("Návrh"),
  p("ZO bere na vědomí Zprávu o výsledku přezkoumání hospodaření za rok 2020 DSO BENE-BUS."),
  h4("DSO TÝNECKO-SVAZEK OBCÍ: Závěrečný účet"),
  p("Informace starosty: Byl nám předložen Závěrečný účet za rok 2020 a Zpráva o výsledku přezkoumání hospodaření za rok 2020."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje Závěrečný účet DSO Týnecko-svazek obcí za rok 2020 a souhlasí s celoročním hospodařením, a to bez výhrad."),
  vote(V8),
  h5("Návrh"),
  p("ZO bere na vědomí Zprávu o výsledku přezkoumání hospodaření za rok 2020 DSO Týnecko – svazek obcí."),
  h4("Memorandum o vzájemné spolupráci – ke společnému provozu vodohospodářské infrastruktury"),
  p("Informace starosty: Města a obce na Benešovsku a také na Jílovsku vodohospodářsky spravuje firma Vodohospodářské stavby Benešov (VHS Benešov). Na jednáních bylo předběžně dohodnuto, že města a obce vstoupí do této společnosti odkupem 50% podílu, aby mohli rozhodovat o vodném, údržbách vodovodních řadů a přivaděčů, rekonstrukcích a rozvoji vodohospodářské infrastruktury. Připojením se k memorandu souhlasíme s budoucím vstupem do VHS Benešov."),
  h5("Rozprava"),
  p("P.Bydžovský: Dotaz, zda se jedná o 50% nebo 51%? Starosta: Je to 50% na 50%."),
  h5("Návrh"),
  p("ZO bere na vědomí návrh projektu budoucího zajištění společného provozu vodohospodářské infrastruktury v regionech Benešovska a Vlašimska v okresech Praha-západ a Praha-východ za účasti zastoupení skupiny SUEZ Groupe v České republice a schvaluje uzavření předloženého návrhu memoranda o vzájemné spolupráci jako podkladu pro zahájení realizace projektu."),
  vote(V8),
  h5("Návrh"),
  p("ZO pověřuje starostu obce Mgr. Aleše Papouška k podpisu předloženého návrhu memoranda o vzájemné spolupráci tak, aby se podpis uskutečnil nejpozději do 30.6.2021 a k provedení všech dalších právních jednání v rámci plnění práv a povinností vyplývajících z memoranda o vzájemné spolupráci."),
  vote(V8),
  h4("Dotace Základní škola"),
  p("Informace starosty: Výběrové řízení bylo zveřejněno na profilu zadavatele. Do výběrového řízení se přihlásily a nabídku podalo 7 firem. Jedna firma byla vyloučena, protože nesložila jistinu. Firmám byly zaslány dodatečné požadavky ze stavební části, vzduchotechniky, vytápění a měření a regulace. Firmy měli specifikovat jimi navržené výrobky a zařízení. Profesanti provedli kontrolu. Výběrové řízení bylo uzavřeno s tímto výsledkem:"),
  h5("Vítězná firma"),
  p("Název právnické nebo fyzické osoby: Intermont, Opatrný, s.r.o."),
  p("Adresa: Vrskmaň 74, 431 15 Vrskmaň"),
  p("IČO: 49900854"),
  p("Nabídková cena v Kč bez DPH: 16.987.292,00 Kč"),
  p("Nabídková cena v Kč s DPH: 20 554 623,32 Kč"),
  h5("Rozprava"),
  p("J.Stibůrek: Jedná se o vzduchotechniku v jídelně? Starosta: Pouze v základní škole."),
  p("R.Novotný: Do projektu by se mělo započítat zvýšení ceny stavebních materiálů."),
  h5("Návrh"),
  p("ZO schvaluje výběr firmy Intermont, Opatrný, s.r.o., IČO: 49900854, se sídlem: Vrskmaň 74, 431 15 Vrskmaň pro realizaci akce „Krhanice – revitalizace a VZT budovy ZŠ“."),
  vote(V8),
  p("Informace starosty: Zároveň byla udělána poptávka po stavebním dozoru na tuto akci. Nejnižší nabídkovou cenu nabídl Ing. Jaroslav Mikyna, a to 180.000,- Kč bez DPH."),
  h5("Návrh"),
  p("ZO schvaluje uzavření smlouvy o dílo na stavební dozor na akci „Krhanice – revitalizace a VZT budovy ZŠ“ s Ing. Jaroslavem Mikynou, IČO: 45128359, Vlašimská 1924, 256 01 Benešov ve výši 180.000,- Kč bez DPH."),
  vote(V8),
  h5("Návrh"),
  p("ZO pověřuje starostu obce Mgr. Aleše Papouška uzavřením a podpisem smlouvy o dílo na stavební dozor na akci „Krhanice – revitalizace a VZT budovy ZŠ“ s Ing. Jaroslavem Mikynou, IČO: 45128359, Vlašimská 1924, 256 01 Benešov."),
  vote(V8),
  h4("Mateřská škola – potvrzení ředitelky na další období"),
  p("Informace starosty: Lenka Houzarová jako ředitelka Mateřské školy Krhanice je již ředitelkou od 1.2.1998. Od 1.7.2021 jí nastává poslední čtyřleté funkční období."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí pokračování Lenky Houzarové ve funkci ředitelky Mateřské školy Krhanice na čtyřleté období od 1.7.2021."),
  h4("Doplnění školské rady Základní školy za obec"),
  p("Informace starosty: Na další funkční období pokračují stávající členové školské rady: Aleš Papoušek, Jaroslav Mixa, Jana Laboutková."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje na další funkční období do Školské rady Základní školy Krhanice tyto členy: Aleš Papoušek, Jaroslav Mixa, Jana Laboutková."),
  vote(V8),
  h4("Informace o uzavírce silnice II/106 Krhanice – Prosečnice"),
  p("Informace starosty: stavba kvůli počasí musela změnit termín základního ukončení rekonstrukce silnice od teplárny mezi Krhanicemi a Prosečnicí až k odbočení k lomu. Vyasfaltování proběhne od 21.6. do 23.6.2021. Potom v tomto úseku budou pokračovat dokončovací práce. Zahájení rekonstrukce úseku od odbočení od lomu ke křižovatce u viaduktu má předpokládané zahájení od 28.6.2021, předpokládaní frézování bude od 30.6.2021. Stavbyvedoucí mi informace o termínech zpřesňuje průběžně. Podle toho se zasílají občanům dotčených úseků informační SMS."),
  h4("Uzavření knihovny – dovolená o prázdninách"),
  p("Informace starosty: Z důvodu čerpání dovolené bude obecní knihovna uzavřena od 1.7. do 16.7.2021, od 2.8.do 13.8.2021."),

  h3("11) Diskuse"),
  ...ul([
    "B.Jerman: Dotaz, zda se počítá s kruhovým objezdem u viaduktu? Starosta: Projekt je schválený, ale zatím Středočeský kraj nemá na realizaci projektu peníze.",
    "L.Maršíková: Zajistí se nějak, aby ulicí pod lomem v období uzávěrky hlavní silnice neprojížděla auta? Starosta: Logisticky je to velmi náročné. Osobním vozidlům není možné průjezd zakázat. Zákaz platí pouze pro vozidla nad 3,5 tuny.",
    "H.Strnadová: Dotaz na incident u školy. Proč rodiče dostali informace až po 4 dnech? Starosta: Postupoval jsem podle pokynů kriminální policie, abych nenarušil jejich vyšetřování.",
    "L.Maršíková: V době, kdy končí ředitelce mateřské školy mandát, není třeba vyhlásit výběrové řízení? Starosta: Výběrové řízení se vyhlašovat nemusí. Proběhlo setkání stávající ředitelky se zastupiteli a ta předložila koncepci na další období.",
    "L.Maršíková: Je koncepce někde na internetu? Starosta: Můžete si požádat o její poskytnutí. Domluvím se s paní ředitelkou.",
    "Paní Nováková: Upozornila na větve do silnice nalevo od křižovatky směrem k nádraží. Starosta: Zeleň roste na soukromém pozemku. To bychom museli upozornit majitele.",
    "Paní Nováková: Po Krhanicích se toulá v poslední době dost psů. Starosta: Řešíme průběžně s místostarostou.",
    "Paní Nováková: Návrh na vznik muzea pana Hájka. Starosta: Není aktuální.",
    "Paní Nováková: Na internetu našla různé informace, ze kterých obcí se skládá obec Krhanice. Starosta: Obec Krhanice se skládá z obce Krhanice, obce Prosečnice a z části Dolní Požáry.",
    "Paní Nováková: Dotaz na kočky u obchodu. Nestálo by za to zajistit jejich kastraci? Starosta: Řešil jsem tyto kočky s paní veterinářkou. S kastrací by musel souhlasit majitel.",
    "Paní Nováková: Dotaz na neposekané pozemky v sousedství. Starosta: Komunikujeme s majiteli, aby pozemky sekali. Někdy je to složité.",
    "Paní Nováková: Dotaz na bleší trh. Ujala by se taková akce v Krhanicích? Starosta: Muselo by se to vyzkoušet. Pokud budete organizátorka, domluvte si se mnou schůzku.",
  ]),

  h3("12) Usnesení a závěr"),
  ...ul(["Návrhová komise přečetla usnesení zastupitelstva obce."]),
  vote(V8),
  ...ul(["Závěr: Zastupitelstvo obce bylo ukončeno v 19:10 hod."]),

  h4("Přílohy"),
  ...nl(["Svolání zastupitelstva obce", "Prezenční listina zastupitelů", "Prezenční listina občanů"]),
];

async function run() {
  const r = await publishZapis({
    cislo: "2",
    rok: "2021",
    isoDate: "2021-06-14",
    dateLabel: "14. 6. 2021",
    fullDateDot: "14.6.2021",
    pdfPath: "scripts/zapisy-pdf/zapis-2021-2.pdf",
    transcript,
  });
  console.log("OK", r.docId, "blocks", r.blocks);
}
run().catch((e) => { console.error(e); process.exit(1); });
