/* eslint-disable no-console */
// One-off: faithful transcript of Zápis č. 2/2025 (16.4.2025), transcribed
// VISUALLY from the official PDF (8 pages). Structure per the approved golden
// sample scripts/build-zapis-2026-1.ts and the contract scripts/zapisy/AGENT-SPEC.md.
import { h3, h4, h5, p, vote, nl, ul, publishZapis, type Block } from "../zapis-lib";

const V8 = "PRO ( 8 ) – PROTI ( 0 ) – ZDRŽEL SE ( 0 )";

const transcript: Block[] = [
  h4("Přítomni"),
  p("Aleš Papoušek, Jaroslav Mixa, Tomáš Kratochvíl, Aleš Kozel, Jana Laboutková, Petr Dub, Lucie Maršíková, Šárka Dušová"),
  h4("Omluveni"),
  p("Martin Jiřička"),

  h3("1) Zahájení, přivítání přítomných, konstatování přítomnosti"),
  p("Starosta konstatoval, že zasedání bylo svoláno dne 8.4.2025, bylo vyvěšeno na úřední desce obecního úřadu, tj. tedy nejméně 7 dní před zasedáním. Bylo tedy svoláno řádně a včas v souladu se zákonem o obcích v platném znění. Starosta konstatoval, že podle prezenční listiny je přítomno 8 členů zastupitelstva, tedy nadpoloviční většina členů zastupitelstva. K předchozímu zápisu nebyly vzneseny námitky."),
  h5("Určení zapisovatele"),
  p("Zápisem zasedání zastupitelstva obce byla pověřena Ing. Alena Kratochvílová."),

  h3("2) Volba návrhové komise a ověřovatelů zápisu"),
  p("Starosta přednesl návrh návrhové komise a ověřovatelů zápisu."),
  h5("Návrh"),
  p("ZO schvaluje návrhovou komisi ve složení: Jaroslav Mixa, Jana Laboutková."),
  h5("Návrh"),
  p("ZO schvaluje ověřovatele zápisu ve složení Lucie Maršíková, Tomáš Kratochvíl."),
  vote(V8),

  h3("3) Schválení programu"),
  p("Starosta přečetl program."),
  ...nl(["Zahájení", "Volba návrhové komise a ověřovatelů zápisu", "Schválení programu", "Rozpočtové opatření", "Koupě, prodej, pronájem", "Různé", "Diskuse", "Závěr"]),
  p("Starosta: Má někdo návrh na změnu nebo doplnění programu?"),
  h5("Návrh"),
  p("ZO schvaluje program zasedání zastupitelstva obce."),
  vote(V8),

  h3("4) Rozpočtové opatření"),
  p("Předseda finančního výboru Petr Dub seznámil s rozpočtovým opatřením č.2/2025."),
  h5("Rozprava"),
  p("P.Schiller: Vysvětlil podrobněji částku 110.000 Kč na dýchací techniku. Nyní máme 4 komplety a musí se buď udělat revize po 10 letech, nebo je vyměnit za jiné spolu s koupí 2 nových kompletů pro rozšíření. Zdůraznil, že dýchací technika se při zásazích používá čím dál častěji."),
  p("J.Mixa: Upřesnil položku zatrubnění potoka pod hasičskou nádrží. Týkalo by se to té části potoka, kde jsou kontejnery. Námět vznikl ze stavební komise. Cenu zjišťoval u výrobce."),
  p("L.Maršíková: Nedostala podrobné informace. Ráda by viděla vizualizaci."),
  p("Starosta: Vizualizaci neděláme. Zjišťovali jsme pouze ceny materiálů. Budeme dělat jednoduchou dokumentaci a budeme zjišťovat, zda získáme příslušná povolení."),
  p("L.Maršíková: Můžeme jako ostatní zastupitelé vidět záměry Stavební komise?"),
  p("Starosta: Komisi používám jako poradní orgán."),
  p("L.Maršíková: Dotaz k přístavbě mateřské školy ohledně vlastní podoby přístavby. Znamená to, že se do mateřské školy bude vcházet rovnou z branky?"),
  p("Starosta: V podstatě ano."),
  p("I.Dvořák: Rozpočet je na čtyři milióny. Je to v posledních letech několikátý zásah. Nedaly se už předem naplánovat lépe stavební práce?"),
  p("Starosta: Popsal historii předchozích úprav. Přistavovala se nová část kvůli zvýšení kapacity. Přístavba nové části stála 1,5mil a byla z části sponzorována darem. Na původní budově se žádné úpravy nedělaly."),
  p("Š.Dušová: Na kdy se plánuje realizace?"),
  p("Starosta: Předpokládáme v létě. Bude záležet na získání stavebního povolení."),
  p("L.Maršíková: Přístavba mateřské školy je také řešením Stavební komise?"),
  p("Starosta: V podstatě je to součinnost Stavební komise, projektantky a statika. Přístavba byla reakcí na přání nové paní ředitelky na úpravu druhého patra."),
  h5("Návrh"),
  p("ZO schvaluje rozpočtové opatření č. 2/2025."),
  vote(V8),

  h3("5) Koupě, prodej, pronájem"),
  ...ul(["prodat pozemek st. 474 k.ú. Krhanice o výměře 39 m² , na kterém se nachází rekreační objekt č.ev. 34, na základě znaleckého posudku č. 4860 I 43 I 25 za cenu obvyklou ke dni 27.3.2025 ve výši 69 459,- Kč+ cena za vyhotovení znaleckého posudku ve výši 5.000,- Kč, tedy celkem za 74 459,- Kč."]),
  p("Informace starosty: Zastupitelstvo obce č.5/2024 dne 14.12.2024 schválilo záměr budoucího prodeje stavebního pozemku č. st. 474 k.ú. Krhanice a schválilo zadání vyhotovení znaleckého posudku pro budoucí prodej stavebního pozemku č. st. 474 k.ú. Krhanice o výměře 39 m², na jehož pozemku se nachází rekreační objekt č.ev. 34. Znalecký posudek byl vyhotoven. Cena za pozemek bude navýšena o cenu za znalecký posudek."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje prodej pozemku st. 474 k.ú. Krhanice o výměře 39 m², na kterém se nachází rekreační objekt č.ev. 34, na základě znaleckého posudku č. 4860 I 43 I 25 za cenu obvyklou ke dni 27.3.2025 ve výši 69 459,- Kč+ cena za vyhotovení znaleckého posudku ve výši 5.000,- Kč, tedy celkem za 74 459,- Kč Ing. Michalovi Caro a Ing. Blance Caro, Ořechová č. ev. 794, Brnky, 250 66 Zdiby."),
  vote(V8),
  ...ul(["pronajmout část pozemku parc. č. 59/1 k.ú. Krhanice o výměře 264,8 m² na dobu 4 let, a to za účelem spolkové činnosti za cenu 1,- Kč/1 m²/rok."]),
  p("Informace starosty: Sbor dobrovolných hasičů Krhanice požádal o pronájem části pozemku parc. č. 59/1 k.ú. Krhanice o výměře 264,8 m² za účelem využití pro hasičský kroužek mladých hasičů a při pořádání venkovních zavedených společenských akcí (např. Čarodějnice, stavění máje, výročí, kácení máje, ples pod hvězdami a jiné podobné akce). Daná část pozemku přímo navazuje na hasičskou zbrojnici. Obec má naplánovanou akci „Stavební úpravy a přístavba objektu č. p. 69, Krhanice“. Dojde ke zhotovení přístavby hasičské zbrojnice, kdy obec může počítat s aktivní účastí hasičů při realizaci přístavby."),
  h5("Rozprava"),
  p("L.Maršíková: Dotaz, zda TJ Sokol Krhanice platí za hřiště?"),
  p("Starosta: Ne, Sokol platí pouze pojištění budovy."),
  p("L.Maršíková: Na pozemku za zbrojnicí se bude stavět, tudíž se hasičům pronajatý pozemek bude zmenšovat."),
  p("Starosta: Hasiči o stavbě vědí."),
  p("T. Kratochvíl: Za sbor jsme seznámeni se stavbou i o tom, že je na pozemku jímka."),
  p("P.Schiller: Potvrdil stanovisko."),
  p("L.Maršíková: Protinávrh pronajmout hasičům pozemek bezúplatně. Proběhla diskuse."),
  p("T.Kratochvíl: Hasiči počítali s cenou 10 Kč/m². Výsledkem diskuse bylo, že protinávrh usnesení byl stažen."),
  p("Š.Dušová: Jsou hasiči nakloněni tomu, aby pozemek využívaly i jiné spolky?"),
  p("Starosta: Spolek nesmí pronajatý pozemek dále pronajímat ostatním. Musela by to být akce v součinnosti s hasiči. Základem je respektovat podmínky pronájmu."),
  p("T. Kratochvíl: V minulosti už společné akce proběhly (příklad: Masopust, Krhanice Jinak) je to na rozhodnutí výboru hasičů."),
  p("P. Schiller: Potvrdil, že o případném pořádání společných akcí by rozhodoval výbor hasičů."),
  h5("Návrh"),
  p("ZO schvaluje pronajmout část pozemku parc. č.59/1 k.ú. Krhanice o výměře 264,8 m² na dobu 4 let za účelem spolkové činnosti za cenu 1,- Kč/1 m²/rok Sboru dobrovolných hasičů Krhanice, 257 42 Krhanice, IČO 66134234 od 17.4.2025."),
  vote("PRO ( 6 ) – PROTI ( 0 ) – ZDRŽEL SE ( 2 – Š.Dušová, T.Kratochvíl )"),
  ...ul(["uzavřít Smlouvu o smlouvě budoucí o zřízení služebnosti inženýrské sítě č. IE-12-6011442NB SIS/02 na pozemku 317/1 k.ú. Krhanice s ČEZ Distribuce, a.s., IČO 24729035, DIČ CZ24729035, se sídlem Děčín IV Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 2 000,- Kč na umístění inženýrské sítě kanalizační přípojky - uliční vpusť+ dešťová kanalizace."]),
  p("Informace starosty: Jedná se o pozemek navazující na rozvodnu ČEZu vedle vodní elektrárny."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje uzavření Smlouvy o smlouvě budoucí o zřízení služebnosti inženýrské sítě č. IE-12-6011442NB SIS/02 na pozemku 317/1 k.ú. Krhanice s ČEZ Distribuce, a.s., IČO 24729035, DIČ CZ24729035, se sídlem Děčín IV Podmokly, Teplická 874/8, 405 02 Děčín na dobu neurčitou za cenu 2 000,- Kč na umístění inženýrské sítě kanalizační přípojky - uliční vpusť+ dešťová kanalizace."),
  vote(V8),
  ...ul([
    "prodat automobil Volkswagen Multivan s registrační značkou 8A5 7153 obálkovou metodou s minimální požadovanou cenou 100 000,- Kč.",
    "prodat automobil Volkswagen Transporter s registrační značkou 2SB 9433 obálkovou metodou s minimální požadovanou cenou 1 000,- Kč.",
    "prodat dopravní automobil Avia A30 K s registrační značkou BNA 0541 obálkovou metodou s minimální požadovanou cenou 1,- Kč.",
  ]),
  p("Informace starosty: Zastupitelstvo č.5/2024 dne 24.10.2024 pověřilo starostu obce zajištěním prodeje automobilu Volkswagen Multivan s registrační značkou 8A5 7153 obálkovou metodou s minimální požadovanou cenou 100 000,- Kč, zajištěním prodeje automobilu Volkswagen Transporter s registrační značkou 2SB 9433 obálkovou metodou s minimální požadovanou cenou 1 000,- Kč a zajištěním prodeje dopravního automobilu Avia A30 K s registrační značkou BNA 0541 obálkovou metodou s minimální požadovanou cenou 1,- Kč. Záměry prodejů byly zveřejněny 27.2. a 28.2.2025 na úřední desce a dále byly inzerovány na webu pozary.cz a bazos.cz. Došlé nabídky dne 31.3.2025 byly posouzeny a vyhodnoceny."),
  h4("Volkswagen Multivan s registrační značkou 8A5 7153"),
  p("Bylo doručeno 9 obálek – nabídek."),
  p("Pořadí:"),
  ...nl([
    "Pořadové číslo 3. – Ondřej Šíba, Vratislavova 27/14, 128 00 Praha 2 – 196.150,- Kč",
    "Pořadové číslo 5. – SLUŽBY – MECHANIZACE ZEMNÍ PRÁCE, Radek Šimsa, Bezděkovice 120, 38801 Blatná – 171.500,-. Kč",
    "Pořadové číslo 7. – Lukáš Troníček, Pecerady 2, 257 41 Týnec nad Sázavou – 167.000,- Kč",
  ]),
  h4("Volkswagen Transporter s registrační značkou 2SB 9433"),
  p("Bylo doručeno 12 obálek – nabídek. Komise do hodnocení nabídek zařadila nabídku č.13, která byla v obálce č.5 pro prodej Avia A30K. Bylo posuzováno 13 nabídek."),
  p("Pořadí:"),
  ...nl([
    "Pořadové číslo 2. – Sbor dobrovolných hasičů Dolany u Kladna, Dolany 71, 273 51 Unhošť – 27.500,- Kč",
    "2.–3.: Pořadové číslo 4. – Sbor dobrovolných hasičů Maletín, Starý Maletín 21, 789 01 Maletín – 27.000,- Kč",
    "2.–3.: Pořadové číslo 7. – František Laňka, Krkonošská 64, 468 61 Desná – 27.000,- Kč",
  ]),
  h4("Dopravní automobil Avia A30 K s registrační značkou BNA 0541"),
  p("Bylo doručeno 12 obálek – nabídek. U nabídky č.3 komise vznesla dotaz na adresu jak formou SMS, tak e-mailem a také pomocí WhatsApp. E-mail se vrátil jako nedoručitelný. U nabídky č.4 byl komisí byl vznesen dotaz na doplnění adresy. Dotyčný doplnil potřebné údaje."),
  p("Pořadí:"),
  ...nl([
    "nekontaktní: Pořadové číslo 3. – Jan Král, 728720775 – 25.000,- Kč",
    "Pořadové číslo 4. – Jakub Kratochvíl, Malé lipky 282, 664 07 Pozořice – 21.000,- Kč",
    "Pořadové číslo 11. – Václav Viktora, Na Zlaté stoce 8, 370 05 České Budějovice – 17.300,- Kč",
    "Pořadové číslo 12. – Petr Absolon, Baba č.2, 256 01 Benešov – 15.000,- Kč",
  ]),
  p("V souladu s obálkovou metodou budeme schvalovat nejvýhodnější nabídku z předložených nabídek."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO schvaluje prodej automobilu Volkswagen Multivan s registrační značkou 8A5 7153 Ondřeji Šíbovi, Vratislavova 27/14, 128 00 Praha 2 za cenu 196 150,- Kč."),
  vote(V8),
  h5("Návrh"),
  p("ZO pověřuje starostu uzavřením smlouvy na prodej automobilu Volkswagen Multivan s registrační značkou 8A5 7153 a zajištěním převodu automobilu na nového vlastníka."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje prodej automobilu Volkswagen Transporter s registrační značkou 2SB 9433 Sboru dobrovolných hasičů Dolany u Kladna, Dolany 71, 273 51 Unhošť za cenu 27 500,- Kč."),
  vote(V8),
  h5("Návrh"),
  p("ZO pověřuje starostu uzavřením smlouvy na prodej automobilu Volkswagen Transporter s registrační značkou 2SB 9433 a zajištěním převodu automobilu na nového vlastníka."),
  vote(V8),
  h5("Návrh"),
  p("ZO schvaluje prodej dopravního automobilu Avia A30 K s registrační značkou BNA 0541 Jakobovi Kratochvílovi, Malé lipky 282, 664 07 Pozořice za cenu 21 000,- Kč."),
  vote(V8),
  h5("Návrh"),
  p("ZO pověřuje starostu uzavřením smlouvy na prodej dopravního automobilu Avia A30 K s registrační značkou BNA 0541 a zajištěním převodu automobilu na nového vlastníka."),
  vote(V8),

  h3("6) Různé"),
  h4("Závěrečné účty svazku obcí"),
  h5("Týnecko-svazek obcí; Posázavský vodovod – dobrovolný svazek obcí"),
  p("Informace starosty:"),
  p("Týnecko-svazek obcí: Byl nám předložen návrh Závěrečného účtu za rok 2024 a Zpráva o výsledku přezkoumání hospodaření za rok 2024. Vyvěšeno dne 31.3.2025. Schvalující orgán – valná hromada svazku."),
  p("Posázavský vodovod – dobrovolný svazek obcí: Byl nám předložen návrh Závěrečného účtu za rok 2024 a Zpráva o výsledku přezkoumání hospodaření za rok 2024. Vyvěšeno dne 26.3.2025. Schvalující orgán – správní rada členů."),
  h5("Rozprava"),
  p("Do rozpravy se nikdo nepřihlásil."),
  h5("Návrh"),
  p("ZO bere na vědomí Závěrečný účet Týnecko-svazek obcí za rok 2024 a Zprávu o výsledku přezkoumání hospodaření za rok 2024 Týnecko – svazek obcí."),
  h5("Návrh"),
  p("ZO bere na vědomí Závěrečný účet Posázavský vodovod – dobrovolný svazek obcí za rok 2024 a Zprávu o výsledku přezkoumání hospodaření za rok 2024 Posázavský vodovod – dobrovolný svazek obcí."),

  h4("Přístavba hasičské zbrojnice"),
  p("Informace starosty: Byla dokončena projektová dokumentace na přístavbu hasičské zbrojnice vypracovaná projektantem Ing. Romanem Moravcem, IČO: 68571887. Zadal jsem zhotovení rozpočtu. Nyní probíhá získání vyjádření dotčených orgánů a správců sítí k projektové dokumentaci. Následovat bude žádost o stavební povolení. Začátek realizace přístavby předpokládáme nejpozději v září 2025. Realizaci bude provádět místní firma BFJ stav, s.r.o. Otty Fischera. Cena bude maximální a předpokládáme snížení ceny díla aktivní účastí hasičů. Tímto postupem bylo zvoleno řešení, které povede k realizaci přístavby hasičské zbrojnice, kdy budou náklady na výstavbu ještě sníženy oproti rozpočtu stavby a to o brigádnickou spoluúčast členů Sboru dobrovolných hasičů Krhanice."),
  h5("Rozprava"),
  p("L.Maršíková: Přestavba bude trvat 17 měsíců. Jak zajistíte běžnou činnost?"),
  p("P.Schiller: Běžných činností se stavba nedotkne. Starosta: Doufáme, že získáme stavební povolení do konce prázdnin a začne se stavět v září. Termín realizace předpokládáme kratší maximálně do června následujícího roku."),
  p("L.Maršíková: Na jakém základě jste oslovil jen dvě místní firmy? Myslím si, že jsme měli oslovit více firem než jen dvě místní."),
  p("Starosta: Cizí firma by nemusela akceptovat pomoc hasičů. Díky tomu, že se hasiči dobrovolně zapojí, sníží se náklady na výstavbu. Se sídlem máme místní stavební firmy v podstatě pouze dvě. Proběhla diskuse, proč byla vybrána právě tato firma. Obec bude mít stavební dozor. Na stavbu bude docházet starosta, ale i pan Sommer ze Stavební komise. Pan Michálek bude zajišťovat bezpečnost."),
  p("J.Mixa: Nemám s firmou BFJ stav, s.r.o., nic společného. Pro tuto firmu občas dělám. Nejsem zaměstnanec ani ve vedení firmy. Z diskuse nevyplynuly žádné závěry."),
  p("I. Dvořák: očekávají se další dostavby hasičské zbrojnice?"),
  p("T. Kratochvíl: Stavba je navrhnuta tak, aby splnila požadavky i na novou cisternu do budoucna. Nově navržená garáž plní veškeré požadavky."),
  p("Š. Dušová: Dotaz ohledně výběrového řízení."),
  p("Starosta: Záleží na okolnostech a žádnou limitní částku nemáme."),
  h5("Návrh"),
  p("ZO schvaluje uzavření smlouvy o dílo na akci „Stavební úpravy a přístavba objektu č. p. 69, Krhanice“ s firmou BFJ stav, s.r.o., IČO: 26686406, Krhanice 255, 257 42 Krhanice na celkovou částku 3 552 633,06 Kč s DPH."),
  vote("PRO ( 6 ) – PROTI ( 2 – L.Maršíková, Š.Dušová ) – ZDRŽEL SE ( 0 )"),
  h5("Návrh"),
  p("ZO pověřuje starostu obce uzavřením a podpisem smlouvy o dílo na akci „Stavební úpravy a přístavba objektu č. p. 69, Krhanice“ s firmou BFJ stav, s.r.o., IČO: 26686406, Krhanice 255, 257 42 Krhanice."),
  vote("PRO ( 6 ) – PROTI ( 2 – L.Maršíková, Š.Dušová ) – ZDRŽEL SE ( 0 )"),

  h4("Rekonstrukce komunikace v Prosečnici"),
  p("Informace starosty: Na letošní rok je naplánována rekonstrukce místní komunikace od hlavní silnice k nemovitosti Prosečnice č.p. 20. Rekonstrukci bude provádět firma BES s.r.o., která dlouhodobě v obci rekonstruuje místní komunikace. Po rekonstrukci bude komunikace zaměřena a proveden zápis do katastru nemovitostí."),
  h5("Rozprava"),
  p("J.Mixa: Vysvětlil stav komunikace."),
  p("L.Maršíková: Dotaz, zda se bude po této komunikaci jezdit na pozemky pana Moulíka?"),
  p("Starosta: Je to možné."),
  p("D.Krotil: Dříve nám bylo řečeno, že při nové výstavbě by se mělo jezdit přímo z hlavní silnice."),
  p("Starosta: Obec neplánuje na pozemcích v dané lokalitě stavět. Máme jiné priority."),
  h5("Návrh"),
  p("ZO schvaluje objednávku u firmy BES s.r.o., IČO: 43792553, Sukova 625, 256 17 Benešov na realizaci akce „Prosečnice MK na pozemku p.č. 1595675 - obnova povrchu na celkovou částku 1 393 683,59 Kč bez DPH."),
  vote("PRO ( 7 ) – PROTI ( 0 ) – ZDRŽEL SE ( 1 – Š.Dušová )"),

  h4("Doplňující dotazy k ČOV Krhanice a kanalizace"),
  p("Informace starosty: Přečetl odpovědi na dotazy a doplňující informace."),
  p("Je třeba udělat rozvahu, zda nezávisle na nevypsané dotaci na ČOV a kanalizaci na SFŽP a nevypsané dotaci na Středočeském kraji začneme realizovat projektovou dokumentaci. To bude na projednání na pracovním sezení zastupitelů."),

  h3("7) Diskuse"),
  ...ul([
    "M.Maršík: Upozornil na to, že na víceúčelovém hřišti jsou uvolněné sítě. Starosta: Víme o tom. Již jsme nakoupili silnější provázky. Oprava bude provedena jinak – zapůjčíme si plošinu.",
    "M. Maršík: Kraj hřiště zarůstá trávou a zvedá se. Bude se to nějak řešit? Starosta: Jednou ročně provádíme údržbu. Zvažujeme rekonstrukci.",
    "Š.Dušová: Dotaz ke Společné vodě na právníka obce. Starosta: Všechny obce v Posázavský vodovod – dobrovolný svazek obcí máme stejnou právničku. Řeší transformaci, hlídá právní věci transformace.",
    "Š.Dušová: Jak jsme k právničce přišli? Starosta: Přes VHS Benešov.",
    "I.Dvořák: Dotaz ke kanalizaci. Co teď bude následovat? Starosta: Bude pracovní sezení zastupitelů. Výsledek bude sdělen na navazujícím zastupitelstvu obce.",
    "I.Dvořák: Dotaz na stávající územní plán. Dojde k úpravě ve prospěch domácích čistíren odpadních vod? Starosta: S touto úpravou počítáme v další změně územního plánu.",
    "Starosta: Přeji všem hezké a sluníčkové velikonoční svátky.",
  ]),

  h3("8) Závěr"),
  p("Zastupitelstvo obce bylo ukončeno v 19:40 hod."),

  p("Datum pořízení zápisu: 22.4.2025"),
  p("Ověřovatelé zápisu a starosta obce, podepsáno v listinné podobě."),
  h4("Přílohy"),
  ...nl(["Svolání zastupitelstva obce", "Prezenční listina zastupitelů", "Prezenční listina občanů"]),
];

async function run() {
  const r = await publishZapis({
    cislo: "2",
    rok: "2025",
    isoDate: "2025-04-16",
    dateLabel: "16. 4. 2025",
    fullDateDot: "16.4.2025",
    pdfPath: "scripts/zapisy-pdf/zapis-2025-2.pdf",
    transcript,
  });
  console.log("OK", r.docId, "blocks", r.blocks);
}
run().catch((e) => { console.error(e); process.exit(1); });
